### ISSUE TITLE
stable release

### ISSUE THREAD

**Issue by vip32** [sshnet/SSH.NET#1]
when can we expect a stable release? been using this for ages and seems pretty stable. most of us need a stable nuget release so our consuming packages can get out of beta too.

**Comment by drieseng** [comment]
I'm currently refactoring our code to introduce support for UWP/UAP10 (see issue #4).
Once this is done, I'll likely release a new beta/rc.
Lack of hardware is blocking me from finishing that issue though.

**Comment by vip32** [comment]
great to hear you are still working on the project. isn't it a possibility to release a stable without the new UWP feature? based on the current beta.

**Comment by drieseng** [comment]
I've released a new beta today.
You help us advance this release to stable by testing and providing feedback.

**Comment by gordonwatts** [comment]
I just wanted to say that I've been running the new beta to copy down large files (>2 GB) and it has worked without problems on both a slow connection and a decently fast one. Thanks for the work! And looking forward to a non-beta release! :-)

**Comment by vip32** [comment]
i also upgraded to beta1 and all is running smooth. great to see there is progress again :) and hopefully soon a final

**Comment by drieseng** [comment]
I just released version **2016.0.0-beta2** of **SSH.NET**.
If no new issues / regressions are reported, I'll release a new stable version next week.

**Comment by gordonwatts** [comment]
It looked good to me. :-)

**Comment by vip32** [comment]
beta 2 runs fine here

**Comment by vip32** [comment]
thanks for releasing stable :)
