### ISSUE TITLE
Terminal Name

### ISSUE THREAD

**Issue by codelabexpert** [sshnet/SSH.NET#10]
Hi, 
the constructor of CreateShellStream expects a parameter "terminal name". What is the impact\consequence of this parameter? Is there a valid enumeration I should use?

**Comment by drieseng** [comment]
I added some more information in this commit: https://github.com/sshnet/SSH.NET/commit/14e26081af6e7f07c1503c8011f504a08f20caef

**Comment by drieseng** [comment]
Please confirm this issue is fixed in version **2016.0.0-beta2** of **SSH.NET**.
