### ISSUE TITLE
sftpClient.DownloadFile appending data to copied file

### ISSUE THREAD

**Issue by richstan** [sshnet/SSH.NET#1001]
When using sftpClient.DownloadFile to copy a CSV file. The file is copied across to the local destination but with a few rows of data appended to the file causing data issues. 

"AA","Current","","2022-08-24","2024-08-23","2022-08-24"
"BB","Current","","2022-08-26","2024-08-25","2022-08-26"
"CC","Current","","2022-08-26","2024-08-25","2022-08-26"
"DD","Current","","2022-08-29","2024-08-28","2022-08-29"
"EE","Current","","2022-08-29","2024-08-28","2022-08-29"**22-08-24","2024-08-23","2022-08-24"
"BB","Current","","2022-08-26","2024-08-25","2022-08-26"
"CC","Current","","2022-08-26","2024-08-25","2022-08-26"
"DD","Current","","2022-08-29","2024-08-28","2022-08-29"
"EE","Current","","2022-08-29","2024-08-28","2022-08-29"22-08-26"**

**Comment by JamesMcWhinney42** [comment]
We have running into the same issue.  Somehow it seems to work fine in our test environment, but then we end up with appended characters in our prod environment.

**Comment by JamesMcWhinney42** [comment]
We figured it out.  The issue is in the way we were writing the file using the below code:

```
Using Sftp As New SftpClient(ConnInfo)
            Dim fs As System.IO.Stream = File.OpenWrite(LocalFilePath)
            Sftp.Connect()
            Sftp.DownloadFile(RemoteFilePath, fs)
            Sftp.Disconnect()
            fs.Close()
        End Using
```

The issue is that File.OpenWrite opens an existing file if there is already one present.
It seems that if the existing file is overwritten character by character, so if the old file was longer than the new one, the original characters remain at the end of the file.

**Comment by WojciechNagorski** [comment]
Does the problem still occur? If so don't hesitate to reopen an issue.
