### ISSUE TITLE
openssh-9.0sp1

### ISSUE THREAD

**Issue by YuGhost** [sshnet/SSH.NET#1004]
when linux server update openssh to 9.0 ,  Renci.SshNet can't connect to server , Please Help!

**Comment by drieseng** [comment]
@YuGhost Do you have access to the server logs? Please check if you can find more information.
There's not much actionable in the issue you reported.

**Comment by YuGhost** [comment]
@drieseng The server response does not contain an SSH identification string.  This is the error . I use Sshclient ( ip , port, user, pwd) in my C# Program . when openssh update , I get the error info. Please help !

**Comment by littlefreak3000** [comment]
I believe openssh 9.0 drops support for RSA keys. I recently dealt with this.

**Comment by YuGhost** [comment]
> I believe openssh 9.0 drops support for RSA keys. I recently dealt with this.

Are you using SshClient to connect ssh ? When i use SshClient to connect ssh, the error info is "The server response does not contain an SSH identification string". I look the log in ssh servers，that the sshclient didn't connect ths sshserver. @littlefreak3000

**Comment by WojciechNagorski** [comment]
The changes has been implemented on develop branch
