### ISSUE TITLE
Is it possible to know when a file is still uploading?

### ISSUE THREAD

**Issue by Alexinio97** [sshnet/SSH.NET#1008]
While listing the files in a directory using **ListDirectory** I noticed that it also returns the files that are currently being uploaded from external tools ( e.g: from Winscp or directly from the sftp command line ). Is it possible to know when a file is available for processing, such as download for example, with the current implementation?
Right now I'm trying to find a way to filter those files that are not fully uploaded.
Thank you!

**Comment by kirides** [comment]
It's the same with files on the local filesystem, you need to make sure you only process complete files by yourself.
somthing like, upload the file as `file.zip.part` and on successful upload, rename it to `file.zip` or delete on error.
(this is what a lot of other software does)
