### ISSUE TITLE
Disposing client without disconnecting on v2013.4.7

### ISSUE THREAD

**Issue by eaglehail** [sshnet/SSH.NET#101]
What is the best practice between these two examples? Does it make sense to put the Disconnect() in a finally block to ensure it is always called or is it acceptable to simply allow dispose to close the channel? I haven't found many examples on the best way to use this library. What is the correct way to handle exceptions after connecting to the SFTP server?
- When the client is disposed it sends a command to close the channel and hides some internal exceptions.
- Disconnect() closes the channel and then sends a command to disconnect.

Example 1:

```
using (var client= new SftpClient(connectionInfo))
{
    client.Connect();
    // There is a possibility that an exception could occur here.
    client.ListDirectory("");
    client.Disconnect();
}
```

Example 2:

```
using (var client= new SftpClient(connectionInfo))
{
    try
    {
        client.Connect();
        // There is a possibility that an exception could occur here.
        client.ListDirectory("");
    }
    catch(Exception exception)
    {
        // handle the exception
    }
    finally
    {
        client.Disconnect();
    }
}
```

**Comment by drieseng** [comment]
If you do not intend to reconnect, you never need to explicitly disconnect.
Disposing the client is all you need:

``` cs
using (var client= new SftpClient(connectionInfo))
{
    client.Connect();
    // There is a possibility that an exception could occur here.
    client.ListDirectory("");
}
```

Let me know if I can close this issue.

Update:
I just now noticed that you're using v2013.4.7.
In that version, you need to disconnect if you want a clean close of the channel.
In which I would go for example 1.

**Comment by eaglehail** [comment]
Thanks for responding so quickly.

Would you please explain your reasoning for choosing example 1? In that example the disconnect is never called if there is an exception running ListDirectory(). Example 2 would call disconnect even if an exception occured.

**Comment by drieseng** [comment]
I'm (always) a bit short on time, and a little too fast to respond.

For version 2016.0.0 (and higher) of SSH.NET, you should use this:

``` cs
using (var client= new SftpClient(connectionInfo))
{
    client.Connect();
    // There is a possibility that an exception could occur here.
    client.ListDirectory("");
}
```

For earlier versions of SSH.NET, you _may_ want to use the approach you proposed in example 2.

**Comment by eaglehail** [comment]
Thanks for the response and all your work on this library. It has worked great so far.
