### ISSUE TITLE
Add Methods to ISftpClient to make Moq Testable

### ISSUE THREAD

**Issue by Pieeer1** [sshnet/SSH.NET#1015]
It would be great if there were more methods from SFTP client in ISftp Client (such as connect) so that in dependency injecting Moq unit tests, you can setup and verify the expressions.

**Comment by Pieeer1** [comment]
Found a couple posts related to this that are closed, however it is still an issue. Current workaround found was:

```
                if (_sftpClient is SftpClient client)
                {
                    client.Connect();
                }
```

Where _sftpClient is the interface and your dependency injection looks like:

```
 builder.Services.AddSingleton<ISftpClient,SftpClient>(
                    (s) => {
                        return new SftpClient("ip", "user", "password");
                    }
                );
```

Fix found here: https://github.com/sshnet/SSH.NET/pull/975

**Comment by Pieeer1** [comment]
Additionally, There needs to be an interface for SftpFile, or the class needs to have a more accessible constructor.

**Comment by WojciechNagorski** [comment]
ISftpClient has been implemented
