### ISSUE TITLE
The server response does not contain an SSH identification string

### ISSUE THREAD

**Issue by rajkumars82** [sshnet/SSH.NET#1016]
Hi,

I'm trying to connect from AWS Lambda .NET 6.0 function to SFTP using (SSH.NET 2020.0.2). Facing an exception "The server response does not contain an SSH identification string. The connection to the remote server was closed before any data was received. More information on the Protocol Version Exchange is available here: https://tools.ietf.org/html/rfc4253#section-4.2" not sure how to handle and resolve this exception.

**Comment by banditmsu** [comment]
Did you ever figure this out?

**Comment by rajkumars82** [comment]
Yes. There was an issue with my sftp configuration. I'm closing the ticket.

**Comment by banditmsu** [comment]
What was the issue? I'm trying to diagnose something similar.

**Comment by rajkumars82** [comment]
SFTP endpoint was not available - The folder in the remote server.

**Comment by banditmsu** [comment]
This keeps happening randomly and we can't figure out why. Same credentials every time.
