### ISSUE TITLE
Add IDisposable to ISftpClient, as well as Connect and Disconnect

### ISSUE THREAD

**Issue by fjmorel** [sshnet/SSH.NET#1019]
SftpClient implements IDisposable, but ISftpClient doesn't. So I can't dispose of clients if I pass one around by interface.

The same thing applies to the Connect and Disconnect methods as well.

**Comment by S-Jindal** [comment]
@fjmorel  would you take that up? If possible, please open a PR for this.

I think there are too many open issues which are quite trivial to address and seems like the primary author of this project @drieseng is not taking up fixes actively.

**Comment by JonAnders** [comment]
I believe this was fixed in #975, but not released yet.
