### ISSUE TITLE
Using FTP client object provided in Renci.SSHNet.dll 2016.0.0.0 to download/upload files frequently result in memory leak

### ISSUE THREAD

**Issue by goodjob0711** [sshnet/SSH.NET#104]
Our application service is using the FTP client object in Renci.SSHNet.dll 2016.0.0.0 to frequently upload/download files from FTP server.  We found the memory used by the service increase  incredibly 
If we change back to previous version .Renci.SSHNet.dll 2014.4.6.0 for example. We don't face this issue.
Anybody is experiencing the same issue?  What is the root cause?

**Comment by drieseng** [comment]
Please provide the minimal code and scenario that allows me to reproduce this?
Thanks!

**Comment by goodjob0711** [comment]
Here are some codes used for the FTP file download. The service will download all the files from the FTP server .Frequency is about 1 Min.  Let the service run a couple of hours. We can see the memory usage will increase from original 30-40M to about 1G . This issue was not found in previous beta 2 version. 

```
        If strHost.Length = 0 Or user.Length = 0 Or passOrKey.Length = 0 Then Return False

        If intPort = 0 Then intPort = SFTP_PORT 'use default as 22     
          sftp = New SftpClient(_Host, user, passOrKey)
        sftp.Connect()
```

'Get file list and put those valid files in an array
  lstFile = sftpConn.GetFileList(strRemotePath)
            If lstFile Is Nothing Then Return False

```
        For Each strDBTmp As String In lstFile
            If Right(strDBTmp, 4).ToUpper = ".MDB" Then
                strPostalSplit = strDBTmp.Split("_")
                If strPostalSplit(0).ToUpper = "BP" And strPostalSplit(1).ToUpper = "RU" And strPostalSplit(2).Length = 8 And strPostalSplit(3).Length = 12 Then
                    DBlstFile.Add(strDBTmp)
                End If
            End If
        Next
        For intI As Integer = 1 To DBlstFile.Count
            strFile = strRemotePath & "/" & DBlstFile.Item(intI - 1).ToString
            strCTR = strFile.Replace(strFile.Substring(strFile.LastIndexOf(".")), ".CTR")
            Dim correctCtr As String = strCTR.Replace("//", "/")
            If sftpConn.FileExists(strRemotePath, correctCtr) Then
                If sftpConn Is Nothing Then Return False

        'download file           
            sftpFile = sftp.Get(remoteFile)
            strLocalFile = localPath + "\" + sftpFile.Name
            buffer = New FileStream(strLocalFile, FileMode.Create, FileAccess.ReadWrite)
            sftp.DownloadFile(remoteFile, buffer)
            buffer.Close()                  

        'Remove files on FTP server after download them
                      File.Copy(strLocalPath & "\" & DBlstFile.Item(intI - 1).ToString, Param.Get_FleesPool_Path & "\" & DBlstFile.Item(intI - 1).ToString, True)
                    File.Copy(strLocalPath & "\" & DBlstFile.Item(intI - 1).ToString, strLocalPath & "Archived\" & DBlstFile.Item(intI - 1).ToString, True)
                    sftpConn.DeleteFileOrDirectory(strFile)
                    sftpConn.DeleteFileOrDirectory(strCTR)


                             End If
        Next
```

**Comment by drieseng** [comment]
Please submit a small - but complete - repro.
Preferrably a repro that first creates the necessary files and/or directories (on the SSH server or locally) that are needed to reproduce the issue.

I know I may be asking a lot from you, but I'm currently doing 80+ hours a week.
I don't have much cycles to spend on this ...
