### ISSUE TITLE
When is a version with async support going to be released to NuGet?

### ISSUE THREAD

**Issue by IanKemp** [sshnet/SSH.NET#1040]
TAP code has been in the `develop` branch for nearly a year and the last actual feature release was nearly 2 years ago... all of the open issues in the vNext milestone are old and the linked PRs that some of them have, have been waiting since March... I appreciate that this project may not be a priority due to time pressures, but publishing a version with TAP support would go a long way towards easing the use of this library.

**Comment by drieseng** [comment]
I'm really sorry about the lack of activity. I'm gonna try to get more people involved soon, and will try to free more time for this project myself.

**Comment by dca00** [comment]
The existing works perfectly fine when wrapped in a Task: a 2-liner. Awaiting would be nice but not a real change in function.

**Comment by IanKemp** [comment]
> I'm really sorry about the lack of activity. I'm gonna try to get more people involved soon, and will try to free more time for this project myself.

I understand completely, and it's good to know you haven't abandoned the project!

> The existing works perfectly fine when wrapped in a Task: a 2-liner. Awaiting would be nice but not a real change in function.

The whole point of a library is so I don't have to write that sort of code.

**Comment by dca00** [comment]
> The whole point of a library is so I don't have to write that sort of code.

In ideal world, all code will be written for us by someone else. In less than ideal world, we have to write it. When the effort is so minimal it is not reasonable to demand it, while there are more serious issues with the library than this. A long list of issues to go through exists, and I had to write tons more boilerplate code, to work around some of them, than this.

**Comment by wertzui** [comment]
@dca00 wrapping a sync method in `Task.Run` wil actually use a `Thread` instead of being really asynchronous.
To be rally asynchronous you have to use `Task` all the way down to the IO level which will then result not in a `Thread`, but in an hardware interrupt.
For SSH.NET this means using the `...Async` methods of the underlying `Socket` which is what you can see in the current async branch.

**Comment by dca00** [comment]
Which is only important if you are a hacker who hacks into thousands if not tens of thousands of victim hosts at the same time.

**Comment by darkoperator** [comment]
Or a network admin with thousands of devices, cyber security profesional auditing thousands of devices .. etc

**Comment by dca00** [comment]
If this is what you want to prioritize, power to you! I've walked away a long time ago.

**Comment by IanKemp** [comment]
> Which is only important if you are a hacker who hacks into thousands if not tens of thousands of victim hosts at the same time.

This is the most ridiculous non-argument I've ever heard against releasing a feature that makes code simpler and more performant. Especially when said feature is **already written**.

**Comment by darkoperator** [comment]
+1

**Comment by wertzui** [comment]
> Which is only important if you are a hacker who hacks into thousands if not tens of thousands of victim hosts at the same time.

Which is the difference between a reasonable software developer and a script kiddy.

**Comment by superware** [comment]
Thank you for the great work! When is a version with async support going to be released to NuGet?

**Comment by SuperJMN** [comment]
I'm eagerly waiting for async version, too. Thanks for the good work you're doing!
