### ISSUE TITLE
Server HMAC algorithm not found

### ISSUE THREAD

**Issue by SylvainSorlin** [sshnet/SSH.NET#1050]
I have a problem connecting to my linux server.

When I try to connect, I get a "Server HMAC algorithm not found" message.
I check the log and I find that lib cannot use the hmac-sha2-256-etm algorithm.

My server only accepts these 3 algorithms:
- hmac-sha2-256-etm@openssh.com
- hmac-sha2-512-etm@openssh.com
- umac-128-etm@openssh.com

[#825](https://github.com/sshnet/SSH.NET/issues/825) does not work

**Comment by Jedrzej94** [comment]
Same here. We just faced this issue.

edit://
We had to rollback to the ones without `-etm`

**Comment by SylvainSorlin** [comment]
I can't, I did an ssh-audit.
I'm trying to add the etm in the project.

**Comment by alef75** [comment]
Same here

Server side is hardened via tool like ssh-audit  and for security reason only the following hmac should be enabled
hmac-sha2-256-etm@openssh.com
hmac-sha2-512-etm@openssh.com
umac-128-etm@openssh.com

**Comment by SylvainSorlin** [comment]
Personally, I have given up on this library and I have compiled my own C++ DLL using libssh. 
I then imported it into my C# project.

**Comment by robert-scheck** [comment]
[OpenSSH upstream](https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/usr.bin/ssh/PROTOCOL?rev=1.55&content-type=text/plain) writes regarding Encrypt-then-MAC MAC algorithms:

> 1.5 transport: Protocol 2 Encrypt-then-MAC MAC algorithms
> 
> OpenSSH supports MAC algorithms, whose names contain "-etm", that perform the calculations in a different order to that defined in RFC 4253. These variants use the so-called "encrypt then MAC" ordering, calculating the MAC over the packet ciphertext rather than the plaintext. This ordering closes a security flaw in the SSH transport protocol, where decryption of unauthenticated ciphertext provided a "decryption oracle" that could, in conjunction with cipher flaws, reveal session plaintext.
> Specifically, the "-etm" MAC algorithms modify the transport protocol to calculate the MAC over the packet ciphertext and to send the packet length unencrypted. This is necessary for the transport to obtain the length of the packet and location of the MAC tag so that it may be verified without decrypting unauthenticated data.

Based on this, it would make sense to me to support Encrypt-then-MAC MAC algorithms in SSH.NET.

**Comment by WojciechNagorski** [comment]
The fastest option to achieve this is to prepare a PR with changes and unit or integration tests.

**Comment by SkymaX86** [comment]
Same issue here, on hardened systems only the -etm MAC algorithms allowed. Please add support for
hmac-sha2-512-etm@openssh.com
hmac-sha2-256-etm@openssh.com

**Comment by PashCracken** [comment]
Hi. We are facing the same issue also. I really like this library and would like to continue to use it. But we will soon be forced to look for alternatives if this is not resolved. Hoping for a fix 😊

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
