### ISSUE TITLE
Bug in read pre-condition check in blocking PipeStream helper class

### ISSUE THREAD

**Issue by doctorseus** [sshnet/SSH.NET#1053]
Hi, I borrowed your PipeStream class in another project and I ran into an suprising issue. As I use the stream for byte exact manipulations I ran into a issue where Read() was blocked although enough bytes were already in the buffer to fullfill the request.

If you look at this line:
https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/Common/PipeStream.cs#L233

It says: ```(length >= (count + 1) || !BlockLastReadBuffer)```

This results in blocking if length is not bigger then the count asked to read. I think the correct way would also to allow reading if length is just equals to count. It should only block if not enough data is available. I fixed this for my case, but maybe this would also help here.

**Comment by WojciechNagorski** [comment]
The [PipeStream.cs#L233](https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/Common/PipeStream.cs#L233) has been changed. 
If you would like to make PR for this problem I would appreciate it.
