### ISSUE TITLE
Ubuntu 22.04 SFTP  An established connection was aborted by the server.

### ISSUE THREAD

**Issue by okarpov** [sshnet/SSH.NET#1056]
SFTP Works well with Ubuntu 20.04 (fresh install)

but does not work at all with Ubuntu 22.04 (fresh install)

Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server.

```
var SFTP=new SftpClient(psslog.Node.IP, psslog.Node.SSHPort, psslog.Node.UserName, psslog.Node.Password);

SFTP.Connect(); <--- throws exception: Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server.
```

however i can access it with FileZilla

**Comment by okarpov** [comment]
same for SSH connection

**Comment by WojciechNagorski** [comment]
Does the problem still occur? If so don't hesitate to reopen an issue.
