### ISSUE TITLE
ErrorCode:10054,Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server

### ISSUE THREAD

**Issue by leechialyn2022** [sshnet/SSH.NET#1057]
I am using ssh.net.2016.0.0-beta2 to development a tool with VB.net of visual studio 2012 sp5 in localhost( windows10)  to connect to the windows server2016.the code is:
          Sub Main()    
              Dim host As String = "IPAdress"
              Dim userName As String = "user"
              Dim passPhrase As String = ""
              Dim portNum As Integer = 22
              Dim objKeyFile As New Renci.SshNet.PrivateKeyFile(keyFilePath, passPhrase)
              Dim sshconn As New PrivateKeyConnectionInfo(host, portNum, userName, objKeyFile)
              Dim sshClient As New SshClient(sshconn)
              Dim cmd As SshCommand          
              Try
                  Using sshClient
                      sshClient.ConnectionInfo.Timeout = TimeSpan.FromSeconds(60)          
                      sshClient.Connect()
                      If sshClient.IsConnected = False Then
                          MsgBox("SSH Connect is Failure")
                          Exit Sub
                      End If
                      cmd = sshClient.RunCommand("touch abc.txt")
                      cmd.Result.Split(New Char() {Chr(10)}, StringSplitOptions.RemoveEmptyEntries)
                      sshClient.Disconnect()
                  End Using             
              Catch ex As Exception
                  MsgBox(ex.Message)
                  Throw ex
                  Exit Sub
              End Try    
           End Sub

When the step "sshClient.Connect()" is excuted,an error is occured.
The error code is 10054,the error stacktrace is:
   Renci.SshNet.Common.SshConnectionException: An established connection was aborted by the server.

    System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
    Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
    Renci.SshNet.Session.SocketRead(Int32 length, Byte[] buffer)
    Renci.SshNet.Session.Read(Int32 length)
    Renci.SshNet.Session.ReceiveMessage()
    Renci.SshNet.Session.MessageListener()

And in the server I found the OPENSSH event log is:
    "sshd: Unable to negotiate with XXX.XXX.XXX.XXX port XXXX: no matching host key type found. Their offer: ssh-rsa,ssh-dss [preauth]"

The OPENSSH's version in the local machine is OpenSSH_for_Windows_8.1p1, LibreSSL 3.0.2.
The OPENSSH's version in the server is OpenSSH_for_Windows_8.9p1, LibreSSL 3.4.3.
I searched this log in the internet ,and found some ways to resolve the error,like this:add a config file to the folder "Users/user/.ssh" of the local machine,write these to the config file:
      HOST localhostIP
      Hostname localhostIP
      IdentityFile /.ssh/id_rsa
      IdentitiesOnly yes
      HostKeyAlgorithms ssh-dss,ssh-rsa
      PubkeyAcceptedKeyTypes ssh-dss,ssh-rsa
Though I can connect the server by the OPENSSH command in the PowerShell of the local machine, when excuting the source code,the error  is always occured.why ? 
The SSH.NET can't be updated,I found ssh.net.2016.1.0 and other the newer version,but in the NuGet can't update it and give this message  'SSH.NET' already has a defined dependency on 'SshNet.Security.Cryptography'. 
How can I resolve this error?

**Comment by RPJack** [comment]
Is there have any solution? i just got the same error with you @leechialyn2022 .

**Comment by WojciechNagorski** [comment]
Does the problem still occur? If so don't hesitate to reopen an issue.
