### ISSUE TITLE
port forwarding not allowed

### ISSUE THREAD

**Issue by maxmontgmx** [sshnet/SSH.NET#1058]
Hi all,

When we make local port forwarding, doe it exit a way to know if the port forwarding is allow by the remote host?
In my case I case port forwarding without error although port forwarding is prohibited on the remote host.

Thanks for your help

**Comment by maxmontgmx** [comment]
Hi all,
No response, no help.
Please
Thanks in advance...

**Comment by WojciechNagorski** [comment]
I am closing the issue due to lack of time and the report does not contain enough information to reproduce the bug.

**Comment by WojciechNagorski** [comment]
@maxmontgmx This is an open source project and we spend our free time solving the issue.
