### ISSUE TITLE
Uploading files asynchronously with BeginUploadFile() never writes any data.

### ISSUE THREAD

**Issue by TheGuitarleader** [sshnet/SSH.NET#1063]
When attempting to upload a file using:
```
var task = Task.Factory.FromAsync(tempClient.BeginUploadFile(memStr, serverPath), tempClient.EndUploadFile);
await task;
```
no data is ever actually written. I have confirm that `BeginDownloadFile()` works completely fine and as it should. I've ran the same thing using `UploadFile()` and it writes data correctly.

With my testing this seems to be the only way to get it to run asynchronously.
```
async Task UploadFileAsync(SftpClient tempClient, Stream memStr, string serverPath)
{
    tempClient.UploadFile(memStr, serverPath, true);
    await Task.CompletedTask;
}
```

**Comment by TheGuitarleader** [comment]
I restarted the OpenSSH on the server and Visual Studio and I have gotten it to transfer data but now the problem is it seems to never continue any code. It just halts the application.

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
