### ISSUE TITLE
Local port forwarding "ForwardedPortLocal" does not work

### ISSUE THREAD

**Issue by isential-gmbh** [sshnet/SSH.NET#1066]
Hello,

I have several applications that use SSH.NET to access MySQL and MariaDB databases respectively. For a new application that also accesses a MariaDB database, "ForwardedPortLocal" does not work.

The SSH connection is established successfully and I can issue any shell commands. So far, so good. However, I want to access the database, so I set up local port forwarding with "ForwardedPortLocal". However, "ForwardedPortLocal" is not working properly, although everything appears correct in the debugger.

Now a little code before I explain further:

```
ConnectionInfo ConnNfo = new ConnectionInfo("domäne.tld", 22, "ssh-user",
	new AuthenticationMethod[]
	{
		new PrivateKeyAuthenticationMethod("ssh-user", new PrivateKeyFile[]
			{
				new PrivateKeyFile(@"C:\Daten\Visual Studio\Projects\Z-Tests\sshtest2\.ssh\private.key", "PassPhrase")
			}
		),
	}
);

using var sshclient = new SshClient(ConnNfo);

sshclient.Connect();

var portfwd = new ForwardedPortLocal(IPAddress.Loopback.ToString(), 3306, "localhost", 3306);
sshclient.AddForwardedPort(portfwd);
portfwd.Start();

using MySqlConnection MySqlCon = new ("server=127.0.0.1; user id=benutzer; password=kennwort; database=datenbank; Allow Zero Datetime=True; persistsecurityinfo=False");

/*
 * Unbehandelte Ausnahme
 *
 * MySql.Data.MySqlClient.MySqlException: "Reading from the stream has failed."
 *
 * Innere Ausnahme
 * EndOfStreamException: Attempted to read past the end of the stream.
 *
 */
MySqlCon.Open();			// <--- Ausnahme

MySqlCon.Close();
sshclient.Disconnect();

```

In the debugger I see that the local port forwarding is set up and started correctly:

```
-	portfwd	{Renci.SshNet.ForwardedPortLocal}	Renci.SshNet.ForwardedPortLocal
		BoundHost		"127.0.0.1"		string
		BoundPort		3306			uint
		Host			"localhost"		string
		IsStarted		true			bool
		Port			3306			uint

```

The SSH client is also set up correctly and I can, among other things, execute shell commands such as

`
Console.WriteLine(sshclient.CreateCommand("ls -lah ~/.ssh").Execute());
`

successfully.

Now I stop the program before MySqlCon.Open() and look at the ports used in the system with

`
netstat -bano -p TCP
`

and look at the ports used in the system. Thereby I notice the following:

```
Aktive Verbindungen

  Proto  Lokale Adresse         Remoteadresse          Status           PID

  TCP    10.0.70.5:59619        192.168.70.204:49172   WARTEND         0
  TCP    10.0.70.5:59620        192.168.70.204:49172   WARTEND         0
  TCP    10.0.70.5:59773        192.168.70.204:135     HERGESTELLT     5732
 [spoolsv.exe]
  TCP    10.0.70.5:59774        192.168.70.204:135     HERGESTELLT     5732
 [spoolsv.exe]
  TCP    10.0.70.5:59775        192.168.70.204:135     HERGESTELLT     5732
 [spoolsv.exe]
  TCP    10.0.70.5:59776        192.168.70.204:49172   SYN_GESENDET    5732
 [spoolsv.exe]
  TCP    10.0.70.5:59777        192.168.70.204:49172   HERGESTELLT     5732
 [spoolsv.exe]
  TCP    127.0.0.1:3306         0.0.0.0:0              ABHÖREN         42608
 [sshtest2.exe]
  TCP    127.0.0.1:8884         0.0.0.0:0              ABHÖREN         4
 Es konnten keine Besitzerinformationen abgerufen werden.
  TCP    127.0.0.1:9395         127.0.0.1:56791        HERGESTELLT     6704
```

At line
`
TCP 127.0.0.1:3306 0.0.0.0:0 LISTEN 42608
`

I see the port and the PID = 42608, which my test program sshtest2.exe got.

How is this to be interpreted? I would have expected the following:

`
TCP 127.0.0.1:3306 127.0.0.1:3306 LISTEN TO 42608.
`

I just don't understand this, because other programs that work the same way work flawlessly.

Thanks already and many greetings

René

**Comment by isential-gmbh** [comment]
**UPDATE**

I ran the same test program but with different connection and access data. Essentially, it is other Internet providers. Here I find that the other providers do not cause any problems and everything runs as it should. Thereby I noticed something: The error is not made by the **ForwardedPortLocal** method, as I wrongly suspected. When I stop after port forwarding, I see the following in all cases:

`TCP    127.0.0.1:3306         0.0.0.0:0                ABHÖREN         42608`

So that is correct and I was wrong.

Now I stopped at the error-free program runs directly after MySqlConnection.Open and lo and behold, the following picture presented itself to me:
```
Proto    Lokale Adresse         Remoteadresse          Status           PID

  TCP    127.0.0.1:3306         0.0.0.0:0              ABHÖREN         51156
 [sshtest2.exe]
  TCP    127.0.0.1:3306         127.0.0.1:62024        HERGESTELLT     51156
 [sshtest2.exe]
  TCP    127.0.0.1:62024        127.0.0.1:3306         HERGESTELLT     51156
 [sshtest2.exe]
```
Here you can see that two connections are established and that port 62024 is used as an "intermediate port".

Now I'm starting to think that the provider (all-inkl.com) is causing the problem and stopping the negotiation of the "intermediate port".

I will therefore open a ticket with them to be sure that they stop it.

**Comment by isential-gmbh** [comment]
Sorry, there is no error. Our Internet service provider no longer supports SSH tunneling. We did not know that.

**Comment by drieseng** [comment]
@isential-gmbh, thanks for the update.
