### ISSUE TITLE
SSH.NET support for .NET 7

### ISSUE THREAD

**Issue by dewanymca** [sshnet/SSH.NET#1069]
We have been using SSH.NET In .NET CORE 3.1 app and looking to upgrade app to .NET 7. Wanted to check what's the compatibility of SSH current version with .NET 7.

Any help will be appreciated.

**Comment by dewanymca** [comment]
Bumping this up.

**Comment by darkoperator** [comment]
I dont belive it has been tested in that version of .NetSent from my iPhoneOn Jan 30, 2023, at 12:00 AM, dewanymca ***@***.***> wrote:﻿
Bumping this up.

**Comment by durranitech** [comment]
I'm using it with dotnet 7 works flawlessly

**Comment by BenvdStouwe** [comment]
I can confirm, SSH.NET works well in dotnet 7.

**Comment by WojciechNagorski** [comment]
We're really close to merging #1109 PR which will provide native support for .NET 6 and 7. But as you say, SSH.NET works very well on the new .NET even now.
