### ISSUE TITLE
Feature request: ssh-keygen support 

### ISSUE THREAD

**Issue by finsj** [sshnet/SSH.NET#107]
The ability to do ssh-keygen into a Stream for each key would be an awesome feature for the library.  BouncyCastle currently supports a similar feature--albeit for PGP.  Chilkat also has the ability to do this--but I'm not a big fan of Chilkat.  

Is this on the roadmap?

**Comment by drieseng** [comment]
Nope, sorry.
Feel free to raise awareness in the SSH.NET community or contribute this yourself.
Personally, I don't expect to have time for this soon.
