### ISSUE TITLE
SSH Server

### ISSUE THREAD

**Issue by AngeloBestetti** [sshnet/SSH.NET#1074]
Correct if I´m wrong, this project it´s just a Client Version? Is there any implementation for SSH Server?

**Comment by darkoperator** [comment]
Correct only client. Do not know of anyone has implemented a server version in .NetSent from my iPhoneOn Jan 28, 2023, at 12:06 PM, Angelo Bestetti ***@***.***> wrote:﻿
Correct if I´m wrong, this project it´s just a Client Version? Is there any implementation for SSH Server?

**Comment by fchamieh** [comment]
Same here, looking for SSH Server implementation, found only commercial solutions

**Comment by notofug** [comment]
Checkout https://github.com/Aimeast/FxSsh

**Comment by canine-afficionado** [comment]
https://github.com/microsoft/dev-tunnels-ssh/blob/main/src/cs/Ssh/README.md

**Comment by darkoperator** [comment]
This is one to definitely keep and eye on. If they add support to shell, scp and SFTP I would migrate my project to this one if development and improvements are consistent

**Comment by canine-afficionado** [comment]
@darkoperator there is a SCP implementation based on that library here: https://github.com/aliasadidev/ssh-scp
