### ISSUE TITLE
SftpClient Connect Exception - No such file

### ISSUE THREAD

**Issue by rutzelt** [sshnet/SSH.NET#1079]
Hello.  We've been using Renci.SshNet for some time now.  We came across an error today which we have been unable to resolve.  We have used thick clients that seem to be able to get around the issue.  When issuing the connect statement, we are immediately presented with an exception and a "No such file" error.  I've done some extensive research and do not see that anyone has had the exact issue.  Using FileZilla, the connect succeeds but throws and error after the connection:

Status: Connected to xxx.xxx.com
Error:	Warning: failed to resolve home directory: no such file or directory
Status:	Retrieving directory listing of "/Distribution/CWx/KC/CERN_HIE/UMAA/TEST_ADT"...

Using WinSCP, we need to suppress the Preserve TimeStamp option.  

Interestingly, we get the error immediately on the connect call.  We do not get past it.  Therefore, we don't even have the ability to issue a change directory command or similar.

Here is a code snippet:
 try
            {
                using (var client = new SftpClient(host, username, password))
                {
                    client.Connect();
                    //var listing = client.ListDirectory(remoteDirectory);
                    client.Disconnect();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
            }

   at Renci.SshNet.Sftp.SftpSession.RequestRealPath(String path, Boolean nullOnError)
   at Renci.SshNet.Sftp.SftpSession.OnChannelOpen()
   at Renci.SshNet.SubsystemSession.Connect()
   at Renci.SshNet.SftpClient.CreateAndConnectToSftpSession()
   at Renci.SshNet.SftpClient.OnConnected()
   at Renci.SshNet.BaseClient.Connect()
   at RenciSftpClient.TransferClient.ConnectTestFromOpenAi() in 

Is there anything we can do to make the library behave more like FileZilla (i.e. don't throw an exception on the Connect call)?  We assume it has a little something to do with the the server side where our login might have a default directory associated that isn't available.

Any help would be much appreciated.  Thanks in advance,
Tom

**Comment by mtsalt** [comment]
In my development, when I got "No such file" error, the remote directory path was wrong, mostly. Another reason was permission.

In your code snippet, there is ListDirectory (but commented out already...) method. this method also occurs "No such file" error, when the remote directory path is wrong.
