### ISSUE TITLE
Getting Renci.SshNet.Common.SshException: Failed to open local file

### ISSUE THREAD

**Issue by saurabh919** [sshnet/SSH.NET#1082]
Hello,

We had an implementation where we made a connection with remote sftp and used sftp.ReadAllBytes to read the file. We recently made some changes to underlying infra of sftp server. 

After which we are getting this exception, Can someone please explain what this error really means ? i couldn't find any reference to this online. We already tried to login to SFTP via same creds and are able to download and open the files manually but it is not working via renci sshnet. Note for 10% of files its working fine but for 90% of the calls its failing with below ex. Any leads will be appreciated. Thanks

Renci.SshNet.Common.SshException: Failed to open local file
   at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)
   at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)
   at Renci.SshNet.SftpClient.ReadAllBytes(String path)

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information. What changes did you make to underlying infra?
