### ISSUE TITLE
Renci.SshNet.Common.SshAuthenticationException: Permission denied (password).

### ISSUE THREAD

**Issue by danammeansbear** [sshnet/SSH.NET#1083]
Hi All,
I am getting the following error in my code. 
Renci.SshNet.Common.SshAuthenticationException: Permission denied (password).
   at Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session)
   at Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

But I have verified the Username, Password and Address are correct by logging into the SFTP using CyberDuck. 

I have seen issues open and closed where the passwords contain a special character like the @ symbol causing problems? 
Currently the passwords are randomly generated by a customer and @ symbols have worked in the past but our prod password doesn't contain the @ symbol. Because the passwords are randomly generated by the customer, we have no control or ability to request new passwords omitting any certain character. What could be causing this issue? What can I do to correct this? 
Thank you all who come across this.

**Comment by danammeansbear** [comment]
To add, I am using version 2016.0.0

**Comment by slee-virtuscorp** [comment]
Having the same issue.  This has brought our implementation to a dead stop.  I cannot figure it out.

**Comment by danammeansbear** [comment]
@slee-virtuscorp So eventually I realized in our implementation, we have a test, dev and prod server. All the files have an address to show where the file is coming from or going to as a pointer. All the dev and Test data had a prod link. The problem was it was trying to log into dev/Test when the link for the file was pointed to prod which is a different username and password. This caused the code to produce this error. in your implementation, make sure you aren't doing something similar .... I felt like an idiot.

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information
