### ISSUE TITLE
Which one if faster to upload file WriteAllBytes Vs UploadFile

### ISSUE THREAD

**Issue by paritoshnagar2016** [sshnet/SSH.NET#1085]
I am working on project using SSH.Net nuget and I am using WriteAllBytes that usually takes time to upload the file even if it's less than 2-5 mb. I wanted to know if there any way to improve performance or what I am doing wrong here. Thank You

**Comment by A9G-Data-Droid** [comment]
If you read the source you will find that both methods result in the same pathway at [SftpSession.RequestWrite](https://github.com/sshnet/SSH.NET/blob/3ecbd1071d653bbf04254c08d14d7ce75d60688b/src/Renci.SshNet/Sftp/SftpSession.cs#L833)

So I think the performance should be the same.

The main difference is the preamble. You could test both methods side by side and tell us what your results are. YMMV.
