### ISSUE TITLE
Ignore Permission Errors

### ISSUE THREAD

**Issue by robinhalabicki** [sshnet/SSH.NET#1091]
Is there a way to ignore permission errors or not preserve timestamp of the file on upload?

`
Permission denied.
Error code: 3
Error message from server: This server does not support operations to modify file attributes. File attributes for [/Inbox/myfile.txt] were not modified.`

**Comment by robinhalabicki** [comment]
bump

**Comment by WojciechNagorski** [comment]
This is a message from the server. Unfortunately, this cannot be ignored. You need more permissions for this file/directory.
