### ISSUE TITLE
Unable to connect to AWS SFTP Server

### ISSUE THREAD

**Issue by danpetitt** [sshnet/SSH.NET#1092]
I was hoping someone might be able to give some guidance on configuration of server or this library as we cannot connect to a customers SFTP Server they setup on AWS.

I have tried various formats of private key from PuttyGen; nothing really help.

When attempting a connection using a private key I get error:
`An established connection was aborted by the server.`

Server: `SSH-2.0-AWS_SFTP_1.1`

Connection Info:
![image](https://user-images.githubusercontent.com/1733292/222543946-ee582625-d2fc-48cb-ac1e-5a8082a5ad3c.png)

**Comment by danpetitt** [comment]
I managed to resolve this by ensuring the AWS SFTP setup is downgraded to the `TransferSecurityPolicy-2020-06` policy

**Comment by Rob-Hague** [comment]
I'm assuming this is either already fixed by version 2023.0.0, or if not then by #1316. It would be great to get an update there if possible
