### ISSUE TITLE
Corefx support

### ISSUE THREAD

**Issue by smbecker** [sshnet/SSH.NET#11]
I see that you are starting to use the new corefx libraries but only target UWP at the moment. Have you considered adding additional "netstandard" targets?

**Comment by drieseng** [comment]
Yes, of course. I actually started working on .NET Core support, but both the runtime and tooling support was too flaky at that time.
Once the UWP "port" is complete, adding further target framework support should be pretty easy.

**Comment by drieseng** [comment]
.NET Core support is available in 2016.0.0-beta3.
Get it [here](https://www.nuget.org/packages/SSH.NET/2016.0.0-beta3)!
