### ISSUE TITLE
The server response contains a null character at position 0x0000000B

### ISSUE THREAD

**Issue by dsuesstr** [sshnet/SSH.NET#1112]
I get the following error using version 2020.0.2 with username/password. Connection works with winscp and other clients.

The server response contains a null character at position 0x0000000B: 00000000 53 53 48 2D 32 2E 30 2D 0D 0A 00 SSH-2.0-... A server must not send a null character before the Protocol Version Exchange is complete. More information is available here: https://tools.ietf.org/html/rfc4253#section-4.2 --->

Is there anything i can do except contacting the server provider?

**Comment by Rob-Hague** [comment]
Fixed by #1441
