### ISSUE TITLE
sftp.UploadFile - fails on 1st try ("An existing connection was forcibly closed by the remote host."), succeeds on 2nd.

### ISSUE THREAD

**Issue by jugghayd** [sshnet/SSH.NET#1120]
We've been noticing a pattern with an Azure function that runs up to 5 times depending on failures. We're noticing that this step to upload a stream via SFTP has a pattern of failing the first time, but succeeding the 2nd.
Error message is "An existing connection was forcibly closed by the remote host. "

Stack trace:
    at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan readTimeout)
   at Renci.SshNet.Connection.ProtocolVersionExchange.SocketReadLine(Socket socket, TimeSpan timeout, List`1 buffer)
   at Renci.SshNet.Connection.ProtocolVersionExchange.Start(String clientVersion, Socket socket, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
   at LPLDataflow.Helpers.SFTPService.SendStream(MemoryStream stream)

My code:
``` lang-csharp
        public void SendStream(MemoryStream stream)
        {
            AuthenticationMethod[] auths = { new PrivateKeyAuthenticationMethod(Username, privateKeyFile) };
            var connectionInfo = new ConnectionInfo(ServerLocation,
                                        Username,
                                        auths);
            using (var sftpClient = new SftpClient(connectionInfo))
            {
                try
                {
                    sftpClient.Connect();                    
                    if (sftpClient.IsConnected)
                    {
                        sftpClient.BufferSize = 4 * 1024; // bypass Payload error large files
                        sftpClient.ChangeDirectory(DestinationDirectory);
                        sftpClient.UploadFile(stream, DestinationFileName);
                        sftpClient.Disconnect();
                    }
                }
                finally
                {
                    if (sftpClient != null)
                    {
                        if (sftpClient.IsConnected)
                        {
                            sftpClient.Disconnect();
                        }
                        sftpClient.Dispose();
                    }
                }
            }
        }
```

**Comment by A9G-Data-Droid** [comment]
The `finally` will run on success and failure so you don't need two `Disconnect` statements. Your `using` block will automatically dispose so your `finally... Dispose` is also redundant.

Keep it DRY (Don't Repeat Yourself)

That's not your problem. The error you are seeing is clearly server side. You will need to get answers from server logs or Microsoft as to why they are forcibly closing the connection before we can determine if this library behavior could change to prevent it. Without that server side information the answer is "works on my machine".
