### ISSUE TITLE
How How to read the contents of a file, send it via sssh for processing and return it back?

### ISSUE THREAD

**Issue by arpsyapathy** [sshnet/SSH.NET#1121]
Hello!

How to read the contents of a file, send it via sssh for processing and return it back with SSH.NET?

I have a signature server. I execute a command on my computer and get a signature file
Command (cmd):
```
more file.txt | ssh sign@signserver sign.sh > file.txt.signed
```
(Read the content, send the content via ssh for signing and return the signature file)

How can I do the same using the SSH.NET library? Can you suggest an example please?
How to do stdin, stdout?

Thank you in advance

**Comment by A9G-Data-Droid** [comment]
The documentation is a bit lacking. The advice is to read the unit tests. This gives some examples of [uploading](https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet.Tests/Classes/Sftp/SftpFileTest.cs) and this gives some examples of [downloading](https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet.Tests/Classes/Sftp/SftpDownloadAsyncResultTest.cs).

C# is not bash and doesn't have a concept of pipelines. This library is not feature complete to the Linux SSH command. It merely communicates using the same protocol.

The big questions are: "How will you know when the server is done signing the file? Will you know the name?"

You could monitor the server location where the signed file is being written for the expected file name. Copy back and then delete. You will have to write this code to fit your needs. This is not really an "issue" with this library and this issue should be closed.

If you want to request better documentation or the addition of a feature you need, those would be issues.

**Comment by WojciechNagorski** [comment]
You can use SftpClient which allows you to make the operation of files like uploading and downloading files.
