### ISSUE TITLE
Inquiry about the absence of RenameFileAsync method in SftpClient class

### ISSUE THREAD

**Issue by Enriquess** [sshnet/SSH.NET#1124]
During my development process, I noticed that there is no asynchronous method available for renaming files in the SftpClient class.
I would like to kindly inquire about the reason for the absence of the RenameFileAsync method in the SftpClient class. Is there a specific technical limitation or design decision behind this omission? It would be greatly appreciated if you could provide some insights into the rationale behind this decision.

Additionally, if there are any plans to introduce an asynchronous rename file functionality in future releases, I would love to know more about the timeline or any potential workarounds that could be considered in the meantime.

**Comment by WojciechNagorski** [comment]
This is already implemented on develop branch `public async Task RenameFileAsync(string oldPath, string newPath, CancellationToken cancellationToken)` It waits for a release.
