### ISSUE TITLE
Error not load file or assmble Renci.SShNet, Version=2020.0.2.0" .net 7

### ISSUE THREAD

**Issue by iruizeguilaz** [sshnet/SSH.NET#1127]
I created a new project in .net 7 where I want to use a sftp call. I have different project, dependy injection and this is a infraestrcutre project

I installed last version by nuget visual studio 2022

when I call firts time the method fom my application prject to use a method to copy some files the app launch me Error not load file or assmble Renci.SShNet, Version=2020.0.2.0 ...."

The dll is well imported, there are not erros in visual and compiling the app

I have read some users in other topics that they use this dll with .net despite the fact you are preparing a new version for net 7  I have read

mybe i have to install another version?

**Comment by iruizeguilaz** [comment]
Great news, I have change the version to 2020.0.0 and now works

**Comment by WojciechNagorski** [comment]
In the next version, SSH.NET will natively support .NET 6 and above.

**Comment by drieseng** [comment]
@iruizeguilaz, it should work just fine for version 2020.0.2 as well. Are you sure you're not mixing versions in your projects?

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
