### ISSUE TITLE
Minor redesign and optimization of (Private)Key classes

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#1128]
* Remove **_privateKey** field from **Key** base class.
* Remove `ctor(byte[] data)` from **Key**, and move current implementation to **RsaKey** and **DsaKey** classes.
* The `ctor(byte[] data` of **RsaKey** and **DsaKey** can be optimized to remove intermediate **List\<BigInteger>**.
* Remove initial assignment of **_publicKey** from `ED25519Key(byte[] pk, byte[] sk)`ctor.
* Rename **privateKey** field in **ED25519Key** to **_privateKey** and remove disable of **IDE1006** for this field.

**Comment by drieseng** [comment]
cc: @WojciechNagorski

**Comment by WojciechNagorski** [comment]
I don't mind. It looks like a great idea. IDE1006 is also a good role.

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
