### ISSUE TITLE
ForwardedPortDynamic should implement IDisposable

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#1133]
**ForwardedPortDynamic** defines a public `Dispose()` method, but does not implement **IDisposable**.
Its base class, **ForwardedPort**, defines a protected `Dispose(bool disposing)` method.
We should update **ForwardedPort** to implement **IDisposable**.

**Comment by TechInterMezzo** [comment]
@drieseng I just found this issue while looking for something else. It seems this is fixed by now and can be closed?
