### ISSUE TITLE
The connection was closed by the server: Failed to read binary packet data! (ProtocolError)

### ISSUE THREAD

**Issue by nngochue** [sshnet/SSH.NET#1150]
I am getting the error "The connection was closed by the server: Failed to read binary packet data! (ProtocolError)" when try to connect my application to SFTP Server.

Here is my code:
```
            var methods = new List<AuthenticationMethod>();
            methods.Add(new PasswordAuthenticationMethod(userName, password));
            var con = new ConnectionInfo(hostName, port, userName, methods.ToArray());
            var sftpClient = new SftpClient(hostName, userName, password);           
            sftpClient.Connect();
```

 I can connect to the SFTP using FileZilla 3.62.2

Version: 2020.0.2
.Net Framework 4.5.2

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
