### ISSUE TITLE
Digest Access Authentication not supported?

### ISSUE THREAD

**Issue by serhat359** [sshnet/SSH.NET#1152]
I'm trying to connect to an FTP server through SSH.NET and currently the connections go through a proxy. Unfortunately the proxy I'm using uses Digest for authentication and maybe this library only supports Basic authentication. Can you please add support for this? I did download your library and made some local changes (but not created a pull request) and I confirmed that it was working for my needs. I only needed to modify Renci.SshNet.Connection.HttpConnector.cs for this change and it didn't take long. Please add support for Digest, I really need it.

Thank you for your hard work.

**Comment by WojciechNagorski** [comment]
I am closing the issue due to lack of time and other priorities for the near future. If you care about time and you need it, I encourage you to prepare a PR.
