### ISSUE TITLE
`ShellStream` copies from output stream back to input stream when `Task.Delay` is used

### ISSUE THREAD

**Issue by Kemsekov** [sshnet/SSH.NET#1168]
# Problem
Shell copies output stream back to input stream when `Task.Delay` is called.
# How to reproduce
```cs
using var client = new Renci.SshNet.SshClient("ip","root","password");

client.Connect();

var file = File.Open("output.txt",FileMode.Append);
using var shellStream = client.CreateShellStream("shell1",0,0,0,0,10000000);
using var shell = client.CreateShell(shellStream,file,null);

shell.Start();

shellStream.WriteLine("echo \"touch very_dangerous_command.txt\" > file.txt");
Task.Delay(1000).Wait();

shellStream.WriteLine("cat file.txt");
Task.Delay(1000).Wait();

shellStream.WriteLine("rm file.txt");
Task.Delay(1000).Wait();

shellStream.WriteLine("history");
Task.Delay(1000).Wait();

shell.Stop();
```

# What effects it have:

It does create `file.txt` with content `touch very_dangerous_command.txt`

It prints to output buffer `touch very_dangerous_command.txt`

It does remove `file.txt`.

But when `history` is called it repeats everything back inside of itself and in the end on my remote machine I have both files 'file.txt' and 'very_dangerous_command.txt' which is nuts. =/

interestingly, without `Task.Delay()` calls it works just fine.

# Results
Files in the `/root` on server before program execution and after.
![image](https://github.com/sshnet/SSH.NET/assets/57869319/1892b985-2da8-494c-8009-8daefe809677) 

Text file that shows what is happening to shell. There is a lot of repeated/misplaced commands, which leads to chaos.
[output.txt](https://github.com/sshnet/SSH.NET/files/12503738/output.txt)

# Setup
dotnet 7.0.105
"SSH.NET" Version="2020.0.2

Linux myhostname 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux

**Comment by Rob-Hague** [comment]
I could be wrong, but I don't think `Shell` and `ShellStream` are meant to be used together: they both create a "session" channel and a shell independently. I think you might try passing a standard `MemoryStream` to the `input` parameter of `CreateShell` which you can wrap in a `StreamWriter`.

Or alternatively, use the `ShellStream` as you are doing but without the `Shell`.

As to why these two types both exist, I have no idea.
