### ISSUE TITLE
Support for Netconf 1.1?

### ISSUE THREAD

**Issue by kgovind12** [sshnet/SSH.NET#1172]
Does this library offer support for Netconf 1.1? If so, which version of the library supports it? So far I have only seen Netconf 1.0.

**Comment by WojciechNagorski** [comment]
We support 1.1 https://github.com/sshnet/SSH.NET/blob/cd1151decac9f5672411eebb12d939cedc53b317/src/Renci.SshNet/Netconf/NetConfSession.cs#L138
If you have a problem please report it.
