### ISSUE TITLE
Strange behavior of ShellStream.Read

### ISSUE THREAD

**Issue by ilya-loskutov** [sshnet/SSH.NET#118]
Hi,
I use the following pattern code for the shell session with my Ubuntu server:

```
SshClient client = new SshClient(ip, login, psw); 
client.Connect();
ShellStream mainStream = client.CreateShellStream("xterm", 80, 24, 800, 600, 1024); //as global var

void SendCommand(string command)
{
mainStream.WriteLine(command); //sendData to server
}

//timer's callback, get server's response
async Task<string> GetResponse(CancellationToken ct)
{
StringBuilder sb = new StringBuilder();
byte[] buffer = new byte[256];
int i = 0;
while (!cts.IsCancellationRequested)
{            
   if ((i = await mainStream.ReadAsync(buffer, 0, buffer.Length))!= 0) //read data from the stream
    {
    sb.Append(client.ConnectionInfo.Encoding.GetString(buffer, 0, i));                                  
    }                   
}
return sb.ToString(); 

```
Since a succesfull authentication GetResponse() returns correct data, e.g. hello from server, however when I try to send some command (through  mainStream.WriteLine) it returns **my inputed command**!
As I understood under the hood ShellStream.WriteLine just sends data through current session's class. The Read method uses `Queue <byte> _incoming` instance. It's strange for me how my command could turn up there.
Please, help

**Comment by drieseng** [comment]
The commands that you write are actually written to the shell so it's normal that they show up on the output.
You could first write the ```stty -echo``` command to disable echo of commands you "type".
