### ISSUE TITLE
ShellStream.DataReceived Adds Unexpected Byte (0x0D) After 0x0A - Binary Data

### ISSUE THREAD

**Issue by RuvimPiholyuk** [sshnet/SSH.NET#1188]
#### Problem
When using SSH.NET's `ShellStream.DataReceived` to read binary data continuously, I've noticed an unexpected behavior. It seems that an extra byte (0x0D) is added after a valid 0x0A, which is not expected behavior for binary data reading. This issue does not occur when asynchronously reading `SshCommand.OutputStream` continuously.

#### Steps to Reproduce

1. Create a new SSH.NET session and establish a connection.
2. Open a shell stream using `CreateShellStream` or a similar method.
3. Register a `ShellDataReceived` event handler to read binary data.
4. Continuously read binary data using the `ShellStream.DataReceived` event.
5. Observe that an extra 0x0D byte is added after 0x0A in the received binary data.

#### Expected Behavior

When reading binary data from `ShellStream.DataReceived`, I expect the received data to be identical to what is sent over the SSH session, without any additional bytes (such as 0x0D) being inserted.

#### Actual Behavior

The `ShellStream.DataReceived` event adds an unexpected byte (0x0D) after a valid 0x0A in the received binary data, which is not consistent with the expected behavior for binary data reading.

#### SshCommand Comparison

It's worth noting that when continually reading from `SshCommand.OutputStream`, this issue does not occur. The behavior is consistent with the expected behavior for binary data reading. This comparison suggests that the issue may be specific to `ShellStream.DataReceived`.

#### Environment

- .NET version: 4.7.2
- Operating System: Windows 11

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
