### ISSUE TITLE
Request for a Method to Clear Incoming Queue in ShellStream - Efficient Memory Management

### ISSUE THREAD

**Issue by RuvimPiholyuk** [sshnet/SSH.NET#1192]
#### Request
I kindly request the addition of a method to `ShellStream` that allows users to clear the incoming data queue without the need to read data via the `DataReceived` event. This feature is essential for efficient memory management and provides an alternative way to clear the incoming buffer.

#### Use Case
One common use case for this feature is when managing long-lived SSH sessions that receive a continuous stream of data via the `DataReceived` event. While the `Read()` method is available to read and discard data, having a dedicated method to clear the incoming buffer offers an efficient, non-reading option.

#### Proposed Method
I propose adding a method, such as `ClearIncomingQueue()`, to the `ShellStream` class that users can call to clear the incoming data queue without the need to explicitly read data.

#### Example Usage
```csharp
// Clear the incoming data queue without reading data.
shellStream.ClearIncomingQueue();

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
