### ISSUE TITLE
Issue with ED2559 ssh connection

### ISSUE THREAD

**Issue by dominikamann** [sshnet/SSH.NET#1196]
Hi,

iam not able to connect over ssh to one of my machines.

![grafik](https://github.com/sshnet/SSH.NET/assets/29973737/8bbbf278-1dd1-4534-a8ea-d1a5cf1c5293)

Over windows console (ssh root@IP) it works fine.
I first thought it is related to https://github.com/sshnet/SSH.NET/pull/1177. See comments. I was asked by @Rob-Hague to open a new issue.

**Code:**

![271530656-8c653494-fbde-43d7-adf5-e99c833dd5e9](https://github.com/sshnet/SSH.NET/assets/29973737/a56e1626-6f4a-428a-bead-d24360cdfe59)

**Issue:**

![grafik](https://github.com/sshnet/SSH.NET/assets/29973737/80b73dba-3bed-4f3f-aaab-e1ef81d5c089)

![grafik](https://github.com/sshnet/SSH.NET/assets/29973737/bdfa141c-bd63-43f9-a8d7-0b5aab642013)

![grafik](https://github.com/sshnet/SSH.NET/assets/29973737/faddc394-90bf-4f1d-9450-e71c0e24c087)

**Console output** 

![grafik](https://user-images.githubusercontent.com/29973737/271560685-cc47047a-387b-4448-bf7d-9ab9a3378fd8.png)

_Originally posted by @dominikamann in https://github.com/sshnet/SSH.NET/issues/1177#issuecomment-1740744830_

**Comment by WojciechNagorski** [comment]
@dominikamann I have to wait a few days for the release, so if we fix your issue by then, it will be included in the next release.

**Comment by Rob-Hague** [comment]
I am not certain, but I think your connection is performing certificate-based authentication, which unfortunately is not currently implemented 

https://github.com/sshnet/SSH.NET/blob/5803ada7cf8e373016d673c7c1922c8154b6e22a/src/Renci.SshNet/Security/CertificateHostAlgorithm.cs

Does that sound right?

**Comment by WojciechNagorski** [comment]
If so we have #595 and there are forks that are mentioned in #479.

**Comment by WojciechNagorski** [comment]
@Rob-Hague Do you want to handle this issue?

**Comment by Rob-Hague** [comment]
I will look into it
