### ISSUE TITLE
what is difference ssh.net vs ssh.net-netconf

### ISSUE THREAD

**Issue by peter2145** [sshnet/SSH.NET#1197]
1. My program is doing netconf communication.  (me is netconf client)
1-1. When I use 'ssh.net-netconf', all of them(connect/sendreceieve ) success.
1-2. When I use 'ssh.net', only connect success. 
what difference?

2. I need host key algorithm "ecdsa-sha2-nistp256". But netconf package has just rsa, dss.
How can I add "ecdsa-sha2-nistp256" algorithm without ssh.net package?

**Comment by Rob-Hague** [comment]
The SSH.NET-NETCONF package is a fork of this one, with (only) the following changes:

https://github.com/sshnet/SSH.NET/compare/develop...declspec:SSH.NET:develop

That could explain why it works.

**Comment by WojciechNagorski** [comment]
@Rob-Hague I'm not familiar with netconf at all. I see what was change in this fork, but for now, I don't know what it does. I need more time to get to know this. Unless @Rob-Hague you know what this is about.
```c#
                var xpath = "/nc:hello/nc:capabilities/nc:capability[text()='urn:ietf:params:netconf:base:1.1']";

                _usingFramingProtocol = ServerCapabilities.SelectSingleNode(xpath, nsMgr) != null
                    && ClientCapabilities.SelectSingleNode(xpath, nsMgr) != null;
```

**Comment by Rob-Hague** [comment]
I am also unfamiliar with netconf

@peter2145 you may try the above change with the latest code here (which has ecdsa) and see if it works

**Comment by peter2145** [comment]
I using nuget Pkg 'SSH.NET-netconf'.
How Can I Use the latest PKG?

**Comment by peter2145** [comment]
Also, Is there anything for adding file "ecdsa-sha2-nistp256" algorithm?
I don't want to use nuget PKG 'SSH.NET'.

**Comment by Rob-Hague** [comment]
@peter2145 you should download the code, make the changes to NetConfSession.cs and build it. Then you can add a project reference and see if it works
 
![image](https://github.com/sshnet/SSH.NET/assets/5132141/8cfd0b25-9ad6-4ac9-a415-8b8655db5484)

**Comment by peter2145** [comment]
@Rob-Hague 
I confirmed that it is operating normally.
The parameters of SendReceiveRPC() change depending on the _usingFramingProtocol variable.
I think parameter is problem. 

Please reflect the above code in the SSH.NET package.

**Comment by Rob-Hague** [comment]
Thanks for checking. There is actually a similar change in PR #946 which seems to also fix the issue.
