### ISSUE TITLE
add interface to SftpFile

### ISSUE THREAD

**Issue by jayhilden** [sshnet/SSH.NET#120]
It would be really nice if you put an interface in front of `SftpFile`, this would make mocking for unit testing much, much easier.

Thank you.

**Comment by TrevorPilley** [comment]
+1, also an `ISftpClient` interface would also help with this

**Comment by CasperWSchmidt** [comment]
This should be implemented! Since SftpFile has no public constructor, no virtual properties/methods and no interface unit testing is actually nearly impossible!
Besides that, using interfaces is always best practice :)

**Comment by jayserdny** [comment]
+1

**Comment by CraigHead** [comment]
+1 ... 4 years later. Can this be added please? It's difficult to build unit tests for project that implement SSH.NET without this interface!

**Comment by CasperWSchmidt** [comment]
I decided to solve the issue by simply writing my own interface and implementation as a wrapper/adapter.

**Comment by drieseng** [comment]
This is available in the 2020.0.0 release.

**Comment by MartijnSchoemaker** [comment]
I still don't see an interface on SftpFile. Or do I miss something?

**Comment by drieseng** [comment]
Let me check later, it may be an oversight on my part.

**Comment by drieseng** [comment]
I was a bit too fast. I read this issue as a request to add an **ISftpClient** interface.
Can (one of) you submit a PR for adding an **ISftpFile** interface?

**Comment by wxtsxt** [comment]
This is still hard to mock ISftpClient when ISftpFile is not there.

**Comment by CasperWSchmidt** [comment]
@wxtsxt see above^^ You are more than welcome to submit a PR adding the interface :)

Unfortunately I don't have the time myself, and as noted above, we simply created a wrapper as a workaround.

**Comment by wxtsxt** [comment]
With merge request !812 SftpClient (and ISftpClient) returns interface ISftpFile instead of SftpFile.
Such change allows to create unit tests with mocks (sample using NSubstitude):
```
            var file = Substitute.For<ISftpFile>();
            file.FullName.Returns("my file name");

            var sftpClient = Substitute.For<ISftpClient>();
            sftpClient.ListDirectory(myPath).Returns(new List<ISftpFile> { file });
```
Please review the MR.

**Comment by CasperWSchmidt** [comment]
Still no review?

**Comment by IgorMilavec** [comment]
I see this was merged. Can we close this issue?

**Comment by Deathgar** [comment]
> I see this was merged. Can we close this issue?

Definitely not. The changes are in the repository, but not in the Nuget releases. In the last 3 for sure.

**Comment by U002883** [comment]
What is missing for the changes to be available in Nuget releases?

**Comment by CasperWSchmidt** [comment]
> What is missing for the changes to be available in Nuget releases?

A release I would say :)

**Comment by sga-solita** [comment]
I can see the last release was almost 2 years ago, so aren't this project ripe for a new release? :) I really miss the latest changes for ISftpClient and ISftpFile, to be able to create proper tests.

**Comment by drieseng** [comment]
Before we publish a new release, we first have to complete tests for some async methods that were introduced.
I hope to have more time in the coming weeks. You should understand that we also have a job and a family.

**Comment by sga-solita** [comment]
You are of course right, forgive me (us) for being pushy, and thank you for finding time to maintain this project, which is much appreciated

**Comment by drieseng** [comment]
@sgacommentor, no problem. I'm on the receiving end for other OSS projects, so I understand your "pain".

**Comment by brainwipe** [comment]
Just hit the same unit test roadblock. Would very much appreciate the release!

**Comment by drieseng** [comment]
@brainwipe, we're working on it.

**Comment by HackPoint** [comment]
> I decided to solve the issue by simply writing my own interface and implementation as a wrapper/adapter.

Can you show how you solved to mock SftpFile?

**Comment by CasperWSchmidt** [comment]
@HackPoint sorry for the late reply. I wrapped that as well 😊 so all types returned to my application logic is wrappers I control

**Comment by CodersaurusRex** [comment]
Any update on when this might be released?

**Comment by WojciechNagorski** [comment]
I'm waiting for the last permissions from @drieseng
All changes for release are ready.

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
