### ISSUE TITLE
Request the latest Nuget PKG

### ISSUE THREAD

**Issue by peter2145** [sshnet/SSH.NET#1200]
![image](https://github.com/sshnet/SSH.NET/assets/80012797/8b056a4b-8b93-44a5-a241-876cb5c53043)

Please release with the attached file details in mind.

or

Please Add algorithm(ecdsa) to ssh.net-netconf PKG.

**Comment by peter2145** [comment]
FileName is "NetConfSession.cs".

**Comment by A9G-Data-Droid** [comment]
You can add the file yourself in a pull request. That is much more likely to be addressed in a timely fashion. This also allows you to test the change on your end.

Also, posting a picture of code is much less useful than just posting the code itself. We can't copy and paste text from the picture...

Finally, you already asked this question in Issue #1197. Please don't open multiple issues.
