### ISSUE TITLE
SCPClient and Port Forwarding

### ISSUE THREAD

**Issue by boukenka** [sshnet/SSH.NET#121]
Hello,

Thanks first for that component. It is really great and it is very useful for me.
I have a question for the usage of SCP. Is it possible to define a Forwarded Local Port?
I have tried via the coding. But I couldn't succeed. Is it possible with the SCP Client and the SSH.NET library?
Or is there another way to use SCP with port forwarding? Or with SCP, it is not possible (and in that case my question has no meaning)?

Thanks

**Comment by drieseng** [comment]
You can enable port forwarding using SshClient.
Let me know if you need any help.

**Comment by boukenka** [comment]
Thanks for the answer. Yes I would appreciate a bit of coding where there is SCP configured with port forwarding.
