### ISSUE TITLE
Fix typo in SftpFileSytemInformation class name

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#1225]
Notice that we have a typo in the name of this class.

@WojciechNagorski @Rob-Hague: Do we fix this?

**Comment by Rob-Hague** [comment]
Seems sensible

**Comment by drieseng** [comment]
@Rob-Hague, this is of course a breaking change. I'm ok with this though.

If we fix this, the [SA1649 ](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1649.md) suppression - which I'll add in my next PR - can be removed from this type.

**Comment by Rob-Hague** [comment]
Sounds good to me
