### ISSUE TITLE
Does this library offer cross-platform-support via Mono?

### ISSUE THREAD

**Issue by fhaag** [sshnet/SSH.NET#123]
This is a general question about the library - **is SSH.NET supposed to be runnable on Mono, and by that, on different OSes where Mono runs?**

Based upon the "SSH.NET supports the following target frameworks:" enumeration from the readme file, it would seem that Mono is *not* supported, as only .NET versions, Silverlight, Windows Phone, and UWP are listed.

On the other hand, there is at least one pull request (#86) whose author seems to be using SSH.NET with Mono on Linux, and in the ensuing discussion, there is not a single indication that this might be an unsupported scenario.

**Comment by drieseng** [comment]
We do not explicitly support Mono, as in I don't perform any tests on Mono.
But - when time permits - I'll gadly take a look at any Mono-related issues.
