### ISSUE TITLE
Add Support .NET Framework 4.8 Documentation 

### ISSUE THREAD

**Issue by andrewrady** [sshnet/SSH.NET#1244]
Good evening,

I've recently used the newest version 2023.0.0 on a project of .NET Framework 4.8 without issues. Is there any tests or documentation I can provide to be able to update the documentation on Nuget to show support for that version?

**Comment by WojciechNagorski** [comment]
From readme:
![image](https://github.com/sshnet/SSH.NET/assets/17333903/83d3c976-e9ca-443f-80f1-2dd2d23e6f98)

From Nuget:
![image](https://github.com/sshnet/SSH.NET/assets/17333903/44030020-c034-4ff7-bd00-db44b54b8543)

We have run our tests on multiple frameworks: 
https://github.com/sshnet/SSH.NET/blob/f9f2b0e5f40eb6982ba98b696e1850eb81fe06a3/test/Renci.SshNet.Tests/Renci.SshNet.Tests.csproj#L3

**Comment by andrewrady** [comment]
My apologies, I didn't see the "and higher" in the documentation.

Thanks!
