### ISSUE TITLE
CHM file not in Asset list on lastest release.

### ISSUE THREAD

**Issue by noguiol** [sshnet/SSH.NET#1249]
Hello.

I notice that the readme refers to the CHM being part of the release assets and want to point out that they are not there for release 2023.0.0

https://github.com/sshnet/SSH.NET/releases/tag/2023.0.0

Thank you!

**Comment by scott-xu** [comment]
Fixed by https://github.com/sshnet/SSH.NET/releases/tag/2023.0.1
