### ISSUE TITLE
2023.0.1 requires exact Microsoft.Bcl.AsyncInterfaces version

### ISSUE THREAD

**Issue by mus65** [sshnet/SSH.NET#1287]
I noticed that #1268 introduced a dependency to an exact version of Microsoft.Bcl.AsyncInterfaces (8.0.0) . I assume this was a copy&paste mistake from the SshNet.Security.Cryptography dependency. Please changes this to a minimum version (>= 8.0.0), otherwise projects using SSH.NET will run into issues when trying to upgrade to a newer Microsoft.Bcl.AsyncInterfaces release.

**Comment by darkoperator** [comment]
seems I hit an issue with this in Posh-SSH

**Comment by mus65** [comment]
@darkoperator doesn't look like the same issue. This issue is about the too strict version constraint which would cause nuget restore failures if other projects depend on another Microsoft.Bcl.AsyncInterfaces version. Your issue seems to be about the dependency itself missing.

**Comment by darkoperator** [comment]
ok, sadly my module is broken because of this dependency on PS 7, it is one weird bug I can not figure out so sticking with the previous nugget for now

**Comment by mus65** [comment]
Fixed by #1288

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.

**Comment by ThatBrianK** [comment]
Hi, I just wanted to chime in and say that this fix actually broke the library I had built. I now get an error:

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or 
one of its dependencies. The system cannot find the file specified.

I do not get this error with 2023.0.1 but with any higher version I do. I tried 2 tricks I could find online but neither of them worked.
1. check "auto-generate binding redirects
2. adding an App.config file containing the following:
`		<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
			<dependentAssembly>
				<assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" />
				<bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" />
			</dependentAssembly>
		</assemblyBinding>`

I'm not really sure where to go for help. Thanks!

**Comment by mus65** [comment]
This does indeed look like missing binding redirects. There is no text on 2. , did you forget to paste it?

 The fix depends on your application. For modern .NET, the binding redirects should always be automatically generated unless you explicitly disable them. For legacy .NET framework it can be more complicated.

**Comment by ThatBrianK** [comment]
thanks, I forgot to enclose it as Code.
I'm using .NET Framework 4.8. 
`<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"> <dependentAssembly> <assemblyIdentity name="Microsoft.Bcl.AsyncInterfaces" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" /> <bindingRedirect oldVersion="0.0.0.0-8.0.0.0" newVersion="8.0.0.0" /> </dependentAssembly> </assemblyBinding>`

**Comment by mus65** [comment]
Looks correct in general. Are you using a web application? In that case this must be in web.config, not app.config IIRC. Other than that, hard to tell without a minimal repro...

**Comment by ThatBrianK** [comment]
Thanks for responding! It's not a web application. The only thing of note is that it's a class library used as a plugin with another application. I've tried both including and omitting the Microsoft.Bcl.AsyncInterfaces.dll file alongside the Renci.SshNet.dll file in the same directory as my dll but it did not make a difference

**Comment by mus65** [comment]
The binding redirect needs to be on the application using the library, not the library itself.
