### ISSUE TITLE
Update version in client string for new releases

### ISSUE THREAD

**Issue by pra-olo** [sshnet/SSH.NET#1292]
The client string set [here](https://github.com/sshnet/SSH.NET/blob/13a6b5df0e8ebd37fbd7cefff4a491ed82ea3c9f/src/Renci.SshNet/Session.cs#L565) is static and hasn't been updated in eight years.

Updating this to reflect the released version would assist SSH service operators in auditing their clients' capabilities before updating supported ciphers and key-exchange algorithms.

**Comment by Rob-Hague** [comment]
After #1256, it might be possible to achieve this by using the MSBuild [WriteLinesToFile](https://learn.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task) task to write out the Version property as a constant in the source. It might already be possible with [WriteCodeFragment](https://learn.microsoft.com/en-us/visualstudio/msbuild/writecodefragment-task) to get the AssemblyVersion attribute
