### ISSUE TITLE
Crypto implementation

### ISSUE THREAD

**Issue by AtLeastITry** [sshnet/SSH.NET#1294]
I see that this package is dependent on https://github.com/sshnet/Cryptography/. Is that still actively in use within the codebase? If so is there any plans to migrate to the built in hash providers rather than the ones from that package? It seems like that package is no longer maintained with the last changes being 7-8 years old?

**Comment by Rob-Hague** [comment]
It is only used for HMACRIPEMD160, which is probably not used by anyone

**Comment by AtLeastITry** [comment]
> It is only used for HMACRIPEMD160, which is probably not used by anyone

Ah ok I see, thanks for the swift response!

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
