### ISSUE TITLE
Timeout not followed when connecting via SOCKS

### ISSUE THREAD

**Issue by BoronBGP** [sshnet/SSH.NET#1335]
Currently whenever an SSH connection is made via socks and the server cannot be reached there is a long delay until a "Destination Unreachable" error is thrown and ConnectionInfo.timeout seems to make no difference to this. It would be very useful to make these connections to throw the exception once the length of the timeout has passed.

**Comment by WojciechNagorski** [comment]
Thanks for reporting the problem!

The fastest method to solve this problem will be to prepare an appropriate PR yourself, preferably with the preparation of an appropriate unit or integration test.

At the moment, the project is being developed entirely as a hobby without any support.

**Comment by BoronBGP** [comment]
I'll have a go at creating an MR sometime this weekend, would it be best for me to base it on the timeout parameter or use a seperate parameter for socks timeout?

**Comment by Rob-Hague** [comment]
Completed by #1342
