### ISSUE TITLE
can we make a SSH DLL

### ISSUE THREAD

**Issue by the-french-rooki** [sshnet/SSH.NET#1346]
Hello evrybody, 
not really an issue , but i need a favor if possible , 
I would need a dll to use the SSH  library in other windows development platform ( Labview) 
 
is that possible that someone build it for me ?
do you have any remarks or advice about using it ?

thank you 
Emmanuel

**Comment by Rob-Hague** [comment]
Download the .nupkg file from https://www.nuget.org/packages/SSH.NET

Unzip it (it is a zip file)

The dlls are in the lib/ directory

**Comment by the-french-rooki** [comment]
**Thank you very much ** , i did not know it was a zip...
 I will try now
so far i have difficulties ' an error occured trying to load the assembly"  ; i will figure this out

**Comment by the-french-rooki** [comment]
ok , thank you , in my Labview Configuration , i can open/load any dll untill the version 2023.0.0 , but not the dll of the version after that.

![image](https://github.com/sshnet/SSH.NET/assets/162574473/bf1cedc9-660a-467b-a70c-2c2a3942cb28)

**Comment by Rob-Hague** [comment]
I'm just guessing, but 2023.0.1 introduced a dependency on the Microsoft.Bcl.AsyncInterfaces package

You might need the dll from that as well (as well as the dlls of its own dependencies)

https://www.nuget.org/packages/SSH.NET#dependencies-body-tab

**Comment by the-french-rooki** [comment]
hello,
THANK YOU AGAIN.
i put all the dependencies in the same folder 

![image](https://github.com/sshnet/SSH.NET/assets/162574473/0cea0b9f-f6b5-4c44-bb6f-0aa7d10512eb)
I can load the 3 "dependencies" for Net 4.6.2 ( 4.6.1 sometimes)  , but not the renci.SSH.net 2024.

also i can load the 2023 version for .Net 7 , but not the 2024 for NET 7 ; when both should not have dependencies.
 i continue to investigate.

thank you
emmanuel
