### ISSUE TITLE
Renci.SshNet.Common.SshAuthenticationException: Permission denied

### ISSUE THREAD

**Issue by utkutkan** [sshnet/SSH.NET#1347]
Hi all,
I have developed a basic app whis downloads files from sftp. It works fine on my dev PC (windows 10 pro) but when I depoly to prod environment (win10 Home Edition Single Language), I get the error Renci.SshNet.Common.SshAuthenticationException: Permission denied.

Any suggestions, the operating system limitation about Renchi or something else ?
Regards.

**Comment by Rob-Hague** [comment]
If the authentication details are correct, perhaps the remote server only allows certain IP addresses for your login, which doesn't include the prod environment?

I think it is unlikely to be an OS limitation

Can you connect with e.g. WinSCP from the prod environment?
