### ISSUE TITLE
State of SSH.NET Extension

### ISSUE THREAD

**Issue by darinkes** [sshnet/SSH.NET#1348]
Hi,

I've been working quite a while now on some extensions and I think they are ready to leave the beta status.

But I don't want to rush forward without syncing with the core devs of the library.
Especially if there are any hints for further improvements.

Currently I'm working on the 2024.0.0 Update.
With this update I also want to sync the versioning, so it's clear what SSH.NET Version is required.

- https://github.com/darinkes/SshNet.Agent
- https://github.com/darinkes/SshNet.Keygen
- https://github.com/darinkes/SshNet.PuttyKeyFile

Thanks in advance
Stefan

**Comment by Rob-Hague** [comment]
Hi Stefan

I don't think there are any plans to implement what you already have, if that's what you mean? And I can't imagine there would be any changes which hamper the extensions. So I think you are good to go.

"plan" is quite a strong word but you can see a few todo list items in #1269 for reference. There will probably be some focus on async in the "near" future

**Comment by darinkes** [comment]
> Hi Stefan
> 
> I don't think there are any plans to implement what you already have, if that's what you mean? And I can't imagine there would be any changes which hamper the extensions. So I think you are good to go.

Exactly. Thats good to know, thanks.

> "plan" is quite a strong word but you can see a few todo list items in #1269 for reference. There will probably be some focus on async in the "near" future

Ok, not really worried. If somethings break, I'm sure we can figure it out :)
