### ISSUE TITLE
Session operation has timed out

### ISSUE THREAD

**Issue by AkshayDeeti123** [sshnet/SSH.NET#1350]
We are currently using 2016.1.0 version to make SSH connection to the Cisco switches and execute some commands. And never faced any issue. 

Due to security concern, we have upgraded it to 2020.0.2. But it is leading to issues. i.e. Out of 50 SSH connections made to the switch and execute a command, only 27 are successful. Rest 23 failed with below error "Session operation has timed out".

We are unable to use the latest stable version 2024.0.0 because we are limited to use .Net Framework 4.5.2 now.

Any help please to use 2020.0.2 ?

**Comment by Rob-Hague** [comment]
Discussion in #1349

**Comment by WojciechNagorski** [comment]
I've added comment https://github.com/sshnet/SSH.NET/discussions/1349#discussioncomment-8718787
