### ISSUE TITLE
we have a requirement to enable the following ciphers (aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com)

### ISSUE THREAD

**Issue by Abishek-dev-github** [sshnet/SSH.NET#1356]
we have a requirement to enable the following ciphers (aes128-gcm@openssh.com, aes256-gcm@openssh.com, chacha20-poly1305@openssh.com). Let me know how we can accommodate this request.

**Comment by safeerk** [comment]
@Abishek-dev-github you are able to get this done?
