### ISSUE TITLE
How to use command line option

### ISSUE THREAD

**Issue by sw-atparagon** [sshnet/SSH.NET#1359]
In the sftp command line client I am able to add -o HostKeyAlgorithms=+ssh-rsa  -o "PubkeyAcceptedAlgorithms=+ssh-rsa".
Can I do something similar using the c# ssh.net library?  Without it the connection
does not work either because there no mutual signature algorithm without "PubkeyAcceptedAlgorithms=+ssh-rsa" or no matching host key type found. Their offer: ssh-rsa without the -o HostKeyAlgorithms=+ssh-rsa  -o "PubkeyAcceptedAlgorithms=+ssh-rsa"  option.

**Comment by Rob-Hague** [comment]
The library already supports ssh-rsa by default. Could you please clarify the error you receive?

**Comment by sw-atparagon** [comment]
It seems I was using an older version of ssh.net It seems to work now Thank you
