### ISSUE TITLE
Support for RSA 4096-bit modulus?

### ISSUE THREAD

**Issue by cciprianobas** [sshnet/SSH.NET#1381]
### Discussed in https://github.com/sshnet/SSH.NET/discussions/1379

<div type='discussions-op-text'>

<sup>Originally posted by **cciprianobas** April 19, 2024</sup>
My vendor informed us that they will replace their RSA key with a new key using 4096-bit modulus in June 2024. I have Renci SSH.NET 2024 latest version for .NET 4.6.2. Does this support RSA 4096? Thank you.</div>

**Comment by Rob-Hague** [comment]
Yes, there is nothing specific to the key length

**Comment by cciprianobas** [comment]
Thank you!
