### ISSUE TITLE
CHM file not in Asset list on latest release. (2024.0.0)

### ISSUE THREAD

**Issue by DavidJFowler** [sshnet/SSH.NET#1387]
This appears to be a regression of https://github.com/sshnet/SSH.NET/issues/1249

**Comment by Rob-Hague** [comment]
Does https://sshnet.github.io/SSH.NET/index.html fulfil your needs?

**Comment by DavidJFowler** [comment]
Got it. Thanks. 

The foreword page: https://sshnet.github.io/SSH.NET/docs/foreword.html is a bit confusing. It still says to download the CHM file from the latest release.

**Comment by Rob-Hague** [comment]
Yeah, it needs tidying up

**Comment by Rob-Hague** [comment]
Some tidying was done in #1395
