### ISSUE TITLE
Support private key file formats other than PEM.

### ISSUE THREAD

**Issue by allisterb** [sshnet/SSH.NET#139]
Trying to open a new ssh-keygen generated ED25519 private key file throws the exception "Key 'OPENSSH' is not supported."

Looking at the detection code in PrivateKeyFile.cs it seems only PEM format keys with a particular header are supported. The new OpenSSH format for keys is supposed to be more secure than the older format so supporting the new format would be great. I'll try to have a go at it by following the existing code but I don't know what the full requirements are for supporting a new key file format.

**Comment by AndrewBragdon** [comment]
+1 for this issue, it doesn't support PPK files either

**Comment by apretth** [comment]
+1 for this feature.

**Comment by drieseng** [comment]
As of [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1), SSH.NET supports the following private key formats:

* RSA in OpenSSL PEM and ssh.com format
* DSA in OpenSSL PEM and ssh.com format
* ECDSA 256/384/521 in OpenSSL PEM format
* ED25519 in OpenSSH key format

**Comment by lcheng526** [comment]
what is ssh.com format? how do I tell a key is in ssh.com format
