### ISSUE TITLE
Wait for linefeed with ShellStream.Expect

### ISSUE THREAD

**Issue by rhegner** [sshnet/SSH.NET#140]
I noticed that `ShellStream.ReadLine()` is not implemented using `ShellStream.Expect()`. I was wondering how I would wait for a linefeed using `ShellStream.Expect()`?

The reason for this is that I want to read from the shell line-by-line. And the end of a line can be a linefeed or a command promt.

So for reading a single line I tried this:

    ShellStream.Expect(new Regex("\n|>"));

But it returns everything up to the next command promt and not just the first line. What am I doing wrong?

**Comment by IgorMilavec** [comment]
@rhegner Expect has a known bug, that we will try to fix as soon as possible. However, this fix might break some applications, that is why I'm trying to better understand usage patterns related to Expect API. Can you please explain how you use it and if possible provide a proto code for it?

**Comment by jscarle** [comment]
@IgorMilavec @WojciechNagorski This was fixed by #1207 and #1319.
