### ISSUE TITLE
SSH.Net 2024.0.0 works for UWP but does not work for Android and iOS

### ISSUE THREAD

**Issue by Karteeka18** [sshnet/SSH.NET#1406]
### Discussed in https://github.com/sshnet/SSH.NET/discussions/1405

<div type='discussions-op-text'>

<sup>Originally posted by **Karteeka18** May 17, 2024</sup>
We have integrated SSH.Net 2024.0.0 from Nuget for Xamarin UWP, Xamarin. IOS and Mono Android.  UWP works fine. BUT iOS and Android are throwing exceptions. Any ideas or suggestions would be helpful.
Visual Studio 2022 C#

              using (SftpClient sftp = new SftpClient(host, port, user, pass))
                {
                    sftp.Connect();

                    if (!sftp.Exists(path))
                        ok = false;
                    sftp.Disconnect();
                }

Throws an Exception on sftp.Connect().

**iOS Exception** 
{System.NotImplementedException: The method or operation is not implemented.   at System.Security.Cryptography.ECDsa.Create (System.Security.Cryptography.ECParameters parameters) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamari…} </div>

**Comment by Rob-Hague** [comment]
It's not clear to me which runtime version your app is using and which target platform for the library.

You would get a definitive answer by including that in an issue in the https://github.com/dotnet/runtime repository, although I'm afraid the answer might simply be that ECDsa is not supported on your chosen version/platform.
