### ISSUE TITLE
Help for referencing the project in .NET Core from Linux?

### ISSUE THREAD

**Issue by ChuckHeatherly** [sshnet/SSH.NET#146]
Could someone explain how I could reference this project for .NET Core from Linux? It doesn't look like NuGet works with .NET Core on Linux. It sort of works with Mono, but that's not .NET Core. If I download the binary .dll for the netstandard1.3 platform, I don't know how to actually reference that in the project.json file. Any help would be appreciated!

**Comment by It4lik** [comment]
.NET Core recently move on a .csproj instead of project.json (to provide retrocompatibility with existing .NET projects). 

You can add these lines to your .csproj : 
```
  <ItemGroup>
    <PackageReference Include="SSH.NET" Version="2016.0.0" />
  </ItemGroup>
```

Regards, it4.

**Comment by drieseng** [comment]
@ChuckHeatherly Can we close this issue?

**Comment by ChuckHeatherly** [comment]
Sure.
