### ISSUE TITLE
ED25519 key - Client encryption algorithm not found

### ISSUE THREAD

**Issue by michaloro** [sshnet/SSH.NET#1464]
SSH connect using ED25519 key fails because of "Client encryption algorithm not found" exception thrown by SshClient.connect method.

SSH device configuration as reported by nmap:
```
PORT    STATE SERVICE   VERSION
22/tcp  open  ssh       (protocol 2.0)
| fingerprint-strings: 
|   NULL: 
|     SSH-2.0-ssh
|     YD=Pq
|     curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group14-sha256,kexguess2@matt.ucc.asn.au,kex-strict-s-v00@openssh.com
|     ssh-ed25519
|     chacha20-poly1305@openssh.com
|     chacha20-poly1305@openssh.com
|     hmac-sha2-256
|     hmac-sha2-256
|     none
|_    none
```

C# code:
```
var key = "-----BEGIN OPENSSH PRIVATE KEY-----\r\nb3BlbnNzaC1rZX...wQFBgcICQoL\r\n-----END OPENSSH PRIVATE KEY-----\r\n";
var stream = new MemoryStream(Encoding.UTF8.GetBytes(key));
var auth = new PrivateKeyAuthenticationMethod("root", new PrivateKeyFile(stream));
var connectionInfo = new ConnectionInfo("192.168.3.215", "root", auth);
SshClient client = new SshClient(connectionInfo);

client.Connect();
```

Version of Renci.SshNet: 2024.1.0
SSH connection using PuTTy with same private key works.

How to resolve this issue?

**Comment by Rob-Hague** [comment]
`chacha20-poly1305@openssh.com` is supported on the latest develop branch but not on version 2024.1.0. You can try a prerelease package from the CI feed @ https://ci.appveyor.com/nuget/ssh-net e.g. 2024.1.1-prerelease.3 or download the binaries from https://ci.appveyor.com/project/drieseng/ssh-net/builds/50334579/job/egl9wbf039u6v2ya/artifacts

**Comment by michaloro** [comment]
Yes, problem solved, thank you.
