### ISSUE TITLE
Stuck in infinite loop

### ISSUE THREAD

**Issue by fcisler** [sshnet/SSH.NET#147]
Not sure if I'm doing something wrong here....

  Dim pkf As New Renci.SshNet.PrivateKeyFile("c:\path\to\private.key")
  Dim sc As New Renci.SshNet.SshClient("192.168.1.66", "username", pkf)
  sc.Connect()

And I just get an infinite loop in RsaCipher.cs, specifically

       while (random <= BigInteger.One || random >= max)
                {
                    random = BigInteger.Random(bitLength);
                }

Using a linux host, ssh -i private.key username@192.168.1.66 works without issue. Unfortunately I must use private key authentication and do not have the option to test other methods with this host. Putty from the same windows machine also works.

**Comment by drieseng** [comment]
This should be fixed.
Please confirm that you were building SSH.NET from the **develop** branch.
