### ISSUE TITLE
Any plan for key exchange RSA-based?

### ISSUE THREAD

**Issue by valben-melair** [sshnet/SSH.NET#1472]
Hi,

From the list of Key Exchange Method, it only supports the following:

curve25519-sha256
curve25519-sha256@libssh.org
ecdh-sha2-nistp256
ecdh-sha2-nistp384
ecdh-sha2-nistp521
diffie-hellman-group-exchange-sha256
diffie-hellman-group-exchange-sha1
diffie-hellman-group16-sha512
diffie-hellman-group14-sha256
diffie-hellman-group14-sha1
diffie-hellman-group1-sha1

Do you have any plan for RSA? 

Thanks

**Comment by Rob-Hague** [comment]
Specifically which key exchange algorithms do you refer to? RSA is typically not used for key exchange. The library already supports RSA for host and client authentication.

**Comment by vpgalon16** [comment]
Thanks Rob.

We get this error below:

The connection was closed by the server: FlowSshTransport: no mutually supported host key algorithm. Local list: RSA/sha2-512,RSA/sha2-256. Remote list: RSA,DSA,Ed25519,ECDSA/nistp256,ECDSA/nistp384,ECDSA/nistp521. (KeyExchangeFailed).\r\nclientRequestId: 7627ab80-c3bc-4b94-9a69-870d99bada27

Can you explain the meaning of this error?

**Comment by Rob-Hague** [comment]
I'm guessing you are on a version before 2023.0.0? 2023.0.0 added support for the RSA/sha2 host key algorithms which appear to be missing based on the message

**Comment by vpgalon16** [comment]
Thanks for a quick response.

Btw, i'm getting this error via logic apps (see screenshot below), do you know how to align my logic app sftp connector to the latest version of connector?

<img width="224" alt="image" src="https://github.com/user-attachments/assets/35458c2a-fffd-4692-898c-1e43b3b1b716">

**Comment by Rob-Hague** [comment]
Sorry, I've not used logic apps before
