### ISSUE TITLE
.Net Framework support for newer encryption algortihms.

### ISSUE THREAD

**Issue by ericpanorel** [sshnet/SSH.NET#1478]
Are there any plans to support these algorithms?
aes256-gcm@openssh.com
aes128-gcm@openssh.com

for .Net Framework target?

These are present in .Net Core 6

```
      var connectionInfo = new ConnectionInfo(hostname, port, username,
             new PasswordAuthenticationMethod(username, password),
             new KeyboardInteractiveAuthenticationMethod(username));


      Console.WriteLine("Encryption algorithms:"); //aes256-gcm@openssh.com
      foreach (var cipherInfo in connectionInfo.Encryptions)
      {
        Console.WriteLine($"- {cipherInfo.Key}");
      }
```

**Comment by Rob-Hague** [comment]
Yes, support exists on the current develop branch and will be in the next release. You can try a prerelease package from the CI feed @ https://ci.appveyor.com/nuget/ssh-net e.g. 2024.1.1-prerelease.10 or download the binaries from https://ci.appveyor.com/project/drieseng/ssh-net/builds/50466645/job/h8ykcifwq22wic79/artifacts

**Comment by ericpanorel** [comment]
Thanks. I tried it in my minimal application/code. It (pre-release) works!

**Comment by scott-xu** [comment]
Fixed by https://github.com/sshnet/SSH.NET/pull/1450
