### ISSUE TITLE
Improvement suggestion: Group Permission scp

### ISSUE THREAD

**Issue by Psilax** [sshnet/SSH.NET#148]
We are using this library to copy files from desktop to an custom embedded linux build with Yocto.
Because of our strict security settings on the target we where having problems with group permissions.
It turns out that SSH.net restricted the group permissions to files severely.
After discussing this with our linux expert who analysed and figured out the problem we made locally the change to set the rights as followed, giving the same permissions to the group as to the users:

For the UploadDirectory & InternalUpload function in ScpClient.NET.cs:
SendData(channel, string.Format("D0775 0 {0}\n", "."));

For the InternalUpload in ScpClient.cs:
SendData(channel, string.Format("C0664 {0} {1}\n", length, Path.GetFileName(filename)));

The idea is that it is easier to downgrade permission inside the SSH server through the right settings, while it is not possible to upgrade permission in the SSH server.

**Comment by drieseng** [comment]
The permissions that we set match those of other popular scp clients.
I don't see any reason we should change this.
