### ISSUE TITLE
Exception when initializing PrivateKeyFile with type aes256-gcm@openssh.com

### ISSUE THREAD

**Issue by Tawmy** [sshnet/SSH.NET#1483]
Hey there, I am trying to connect to an SFTP server using an OpenSSH key. This OpenSSH key uses the cipher aes256-gcm@openssh.com. When initializing a new instance of PrivateKeyFile with the path to the private key and private key passphrase, the library throws an exception: `Cipher 'aes256-gcm@openssh.com' is not supported for an OpenSSH key.`

I was under the impression 2024.1 added support for this specific cipher. Does the key need to be initialized differently?

I am using .NET 8 on macOS 14.6.1.

**Comment by scott-xu** [comment]
The cipher is added for packet encryption/decryption only but not for private key decryption.

I'm going to spend some time refactoring the code to make it easy for private key decryption.

**Comment by Tawmy** [comment]
That is much appreciated, thank you!
