### ISSUE TITLE
`ScpClient.Upload(Stream, string)` Overload Doesn't Work

### ISSUE THREAD

**Issue by dsimunic** [sshnet/SSH.NET#15]
The scp `Upload` method overload using the file stream does not work correctly. The idiom 

```
using (Stream stm = ...) {
    scpClient.Upload(stm, fileName);
}
```

always fails with a timeout exception. 

Stepping through the source, it appears that the channel never gets correctly set up, and it times out while waiting for server's window adjustment message that never arrives.

The `ScpClient.Upload(FileInfo, string)` overload, on the other hand, works correctly. (As witnessed by the unit test).

**Comment by drieseng** [comment]
@dsimunic I haven't been able to reproduce this issue. Please try using the new stable release ([2016.0.0](https://www.nuget.org/packages/SSH.NET/2016.0.0)) and report back.

**Comment by dsimunic** [comment]
My apologies, won't be able to do that as am no longer using SSH.NET. The other overload was just good enough to finish the project I was working on. Thanks for the great tool, made my life easier.

**Comment by AntonStein** [comment]
I have the same problem... is there still no solution for that?!
The File is getting created on the remote host, but always with 0 kb..
