### ISSUE TITLE
Move file in another folder on remote-machine

### ISSUE THREAD

**Issue by anionDev** [sshnet/SSH.NET#1511]
I want to move the file `file.txt` from the folder `/foo` to the folder `/bar` using SSH.NET. Both folders are on the remote-machine. (So the folder `/bar` already exists.)

I have tried the following things:

- `_Connection.Get("/foo/file.txt").MoveTo("/bar");` (resulted in an `SshException`.)
- `_Connection.Get("/foo/file.txt").MoveTo("/bar/file.txt");` (results in file will be renamed to `file (1).txt` but remains in `/foo`.)

I see the same behavior when I use `_Connection.RenameFile(...)`.

So: Is it somehow possible to move a file to another folder on the remote machine using SSH.NET without downloading and uploading the file again?

Side note for the case that it is important: The remote-OS is Android 14.

**Comment by Rob-Hague** [comment]
Strange, do you have a small sample? This integration test passes for me:

```c#
        [TestMethod]
        public void Test_Sftp_SftpFile_MoveTo2()
        {
            using (var sftp = new SftpClient(SshServerHostName, SshServerPort, User.UserName, User.Password))
            {
                sftp.Connect();

                string uploadedFileName = Path.GetTempFileName();
                string remoteFileName = "/foo/file.txt";
                string newFileName = "/bar/file.txt";

                CreateTestFile(uploadedFileName, 1);

                using (var file = File.OpenRead(uploadedFileName))
                {
                    sftp.UploadFile(file, remoteFileName);
                }

                var sftpFile = sftp.Get(remoteFileName);

                sftpFile.MoveTo(newFileName);

                Assert.IsTrue(sftp.Exists(newFileName));
                Assert.IsFalse(sftp.Exists(remoteFileName));
            }
        }
```

(with some tweaks to the dockerfile to add the directories)

**Comment by anionDev** [comment]
thank you for your response! ok it is nice to know that it _should_ work. then i really guess the issue in my case is that android (or my ssh-server-app) does not allow all ssh-operations. so probably not a SSH.NET-issue.
