### ISSUE TITLE
2024.1.0 SSH Client Connect() never exits with wrong credentials

### ISSUE THREAD

**Issue by marino-gnss** [sshnet/SSH.NET#1528]
Hi,

When I use the Connect() method where the password used is wrong, the function call does not seem to exit or throw any errors. 

Is this expected? 

        `public bool Connect()
        {
            bool ok = false;

            try
            {
                if (_SSHClient == null)
                {
                    _SSHClient = new SshClient(_ConnectionInfo);
                }

                if (_SSHClient.IsConnected != true)
                {
                    _SSHClient.Connect();
                    ok = _SSHClient.IsConnected;
                }

            }
            catch(SystemException ex)
            {
                Logger.Error(ex);
            }
            return ok;
        }`

**Comment by marino-gnss** [comment]
Adding a catch statement for: Renci.SshNet.Common.SshAuthenticationException, resolved this issue.

sorry false alarm.

**Comment by Rob-Hague** [comment]
Thanks for reporting back and sorry for no response
