### ISSUE TITLE
SftpFileStream also sends SSH_FXP_FSTAT upon init when mode is not Append

### ISSUE THREAD

**Issue by waynebrantley** [sshnet/SSH.NET#154]
Using your library I cannot connect to a particular SFTP server. 
I attempted to connect to this server using WinSCP and it fails also, unless I set the SFTP protocol to version 3 or 4 (instead of the default version 6).

How can I set the version of the SFTP protocol that SSH.NET uses?

**Comment by drieseng** [comment]
We're using version 3.
Can you share more information on the the server and the error that you get?

**Comment by waynebrantley** [comment]
Here is the code I am using
``
using (var stfp = new SftpClient(_hostName.Option, port, _userName.Option, _password.Option))
{
    stfp.Connect();
    stfp.WriteAllBytes(fileName, ms.ToArray());
    stfp.Disconnect();
}
``
Here is the error where I call WriteAllBytes.
```
Renci.SshNet.Common.SshException: Cannot find message [/testfile3343.01232017]
   at Renci.SshNet.Sftp.SftpSession.RequestFStat(Byte[] handle)
   at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize, Boolean useAsync)
   at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)
   at Renci.SshNet.SftpClient.WriteAllBytes(String path, Byte[] bytes)
```

I found a similar issue here:  http://sshnet3.rssing.com/chan-6841276/all_p70.html
This person said 
> It seems my customer has disabled the shell to let only the sftp with SSH2 1024 key connection.

I found a reference to this issue about an IBM Proxy Server not supporting anything but protocol 3.  That is what led me to try that.   I then contacted the vendor and in fact they WERE using an IBM proxy server and indicated it must be version 3 or 4.

Potentially there is another way to send the data other than ``WriteAllBytes`` that would result in different protocol commands that might work?

**Comment by waynebrantley** [comment]
@drieseng Sent you an email to your github email profile.  I can give you access to the server where you can reproduce this issue if interested.

**Comment by waynebrantley** [comment]
@drieseng So I figured out what this issue is.  The issue is permissions are denied to set the attributes of files on the SFTP server.   So, I commented out the following line and everything worked fine:

https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/Sftp/SftpFileStream.cs#L272

- It occurs to me this code is getting the attributes of a file even when the ``FileMode`` is not append.  So if this code only tried to get the attributes when mode was ``Append`` that would solve this bug.
- Additionally, it appears it is possible that anytime you are dealing with attributes you may be denied permission - so that should probably be accounted for somehow.

Any chance the suggested change above can be implemented and a new package pushed?

If it helps, for example when uploading with WinSCP, the UI shows this error.
```
Permission denied.
Error code: 3
Error message from server: This server does not support operations to modify file attributes.
```

**Comment by drieseng** [comment]
Wayne, in this case we're not **setting** attributes but **getting** the attributes.
If possible, I'd still like to be able to reproduce this issue myself.
Can you get me the correct credentials?

**Comment by waynebrantley** [comment]
I agree with your premise!   I will attempt to get credentials for you to reproduce it.

**Comment by waynebrantley** [comment]
I sent  you credentials to reproduce the error.

**Comment by drieseng** [comment]
I was able to reproduce the error. There are actually a few strange things I noticed with that SSH server:

- It reports a generate failure when you use **SSH_FXP_FSTAT** to obtain the file attributes for a **SSH_FXF_WRITE** handle of a file that did not exist when the handle was created.  If a failure is to be reported, I would at least expect a **SSH_FX_NO_SUCH_FILE**.   Note that OpenSSH does not report a failure in this case, but - as always - the SSH specification is not clear on this.
- A given filename can exist multiple times (at one point, I had at least five distinct files with the same absolute file name).

I agree with your conclusion that we should only obtain the file attributes if we want to append.
I'll fix this asap.

**Comment by waynebrantley** [comment]
Thanks for doing this.
Do you have a timeframe for this milestone to be completed?  It is the 2016.1 milestone, so a little worried.  
😄 

(I already forked it, it builds except one test fails - so I can always run off my own clone if it is going to be several months - but rather wait if just a few weeks)
