### ISSUE TITLE
Cannot establish ssh connection

### ISSUE THREAD

**Issue by made1990** [sshnet/SSH.NET#157]
Hi I am using the follwoing code to run a ssh command on a remote server:

            ```
using (var client = new SshClient("IP-Adress", "user", "password"))
            {
                client.Connect();
                client.RunCommand("uptime");
                client.Disconnect();
            }

```

Running the code gives me the following error message:

System.Net.Sockets.SocketException
  HResult=-2147467259
  Message=no suitable authentication method found to complete authentication
  NativeErrorCode=10013
  Source=Renci.SshNet
  StackTrace:
       at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
       at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
       at Renci.SshNet.Session.Connect()
       at Renci.SshNet.BaseClient.Connect()
       at App2.MainPage.button_Click(Object sender, RoutedEventArgs e)
  InnerException: 

Any ideas on that?

On remote server site there is no log in the messages that even somebody tried to login via ssh.
SSH to the server works fine with putty and user and password give above.

**Comment by made1990** [comment]
Ok,
I saw on server site an entry in /var/log/messages:

sshd[6581]: reverse mapping checking getaddrinfo for desktop-xxxxxx [_IP-Address_] failed - POSSIBLE BREAK-IN ATTEMPT!
Connection closed by _IP-Address_ [preauth]

Any thoughts on that?

**Comment by made1990** [comment]
I added the hostname in /etc/hosts , so the error messages is gone, still no conneciton and this message remains:
Connection closed by IP-Address [preauth]

**Comment by made1990** [comment]
Ok - solved it by setting the following in /etc/ssh/sshd_config on the server

PasswordAuthentication yes

It was set to "no" originally.
My understanding ist, that this has to be set when using clear test passwords.
Is putty using encrypted passwords? What is using ssh.net?

**Comment by made1990** [comment]
Anyone an idea what to change in my code so the ssh connection works out of the box?
I don't want to change the ssh settings on all my remote servers?...Actually I cannot do that on all servers?

**Comment by drieseng** [comment]
The **PasswordAuthentication** setting has nothing to do with plain text passwords.
It just configures whether to allow authentication using password or not.

The general recommendation is to use SSH keys instead of passwords.

**Comment by drieseng** [comment]
@made1990 Please close this issue if you have no further questions on this topic.
