### ISSUE TITLE
ESXi connection issues

### ISSUE THREAD

**Issue by KennyMacCormik** [sshnet/SSH.NET#158]
Greetings,

I've run into issues while using your module

`[Reflection.Assembly]::LoadFile('C:\PSM\Renci.SshNet.dll');

$KeyboardInteractive = New-Object Renci.SshNet.KeyboardInteractiveAuthenticationMethod("root");
$ConnectionInfo = New-Object Renci.SshNet.ConnectionInfo("some ip here", "root", ($KeyboardInteractive));

$SshClient = New-Object Renci.SshNet.SshClient($ConnectionInfo);`

And I get the following exception when trying to connect()

`Exception calling "Connect" with "0" argument(s): "String reference not set to an instance of a String.
Parameter name: s"
At line:1 char:1
+ $SshClient.Connect()
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentNullException`

I can't find any information about this error in documentation. Can you please help me with this?

**Comment by darkoperator** [comment]
You need to register a job that will handle the event when keyboard interactive is executed. In PS alone I have mixed results do to timing so for Posh-SSH I simply wrote the cmdlet for creating session in C#/

**Comment by drieseng** [comment]
No feedback since initial report.
Reopen this issue if you need more help.
