### ISSUE TITLE
Launch background job

### ISSUE THREAD

**Issue by pelhu** [sshnet/SSH.NET#16]
Hi dear Gert.

I can not run a background task with "&" at the end of the command line. My symbol "&" is simply ignored. Could you help me please?

Cordially Khamzat

**Comment by YuryAlkevich** [comment]
I have the same problem with SshClient. Neither 'command &' nor 'nohup command &' doesn't keep alive launched command in background after end of execution of RunCommand method

**Comment by darkoperator** [comment]
That is because no shell is created with that API call so there is no state. You will need to use a ShellStream for that. It will create a shell and you can write and read from the stream and it maintains state

**Comment by YuryAlkevich** [comment]
Thank you @darkoperator. Everything works fine via ShellStream

**Comment by sdlmw** [comment]
Hello @YuryAlkevich 

I have the same a problem with you, Could you  tell me how to use ShellStream?  Thank you!

**Comment by dustinkerstein** [comment]
Just wanted to see if it was possible to post a working example of a background command working. I am running into the same issue and no matter how I call my command (sh, nohup, &, etc.) it still blocks execution. Is there a simple example of ShellStream posted somewhere? Thanks!

**Comment by dustinkerstein** [comment]
Looks like this works:

```
var command = clientStart.CreateCommand("mycommand &");
var asyncExecute = command.BeginExecute();
```

**Comment by dustinkerstein** [comment]
I managed to get the below using ShellStream working:

```
var stream = clientStart.CreateShellStream("input", 0, 0, 0, 0, 1000000);
Thread.Sleep(100); // Ugly but needed to wait a little or else shell isn't ready
stream.WriteLine("nohup sh -c '( ( command &>/dev/null ) & )'");
```

**Comment by gavin1970** [comment]
I have shellstream working.  Maybe you can steal some ideas from here. 

https://github.com/gavin1970/Linux-Commander/blob/master/Linux-Commander/common/Ssh.cs

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
