### ISSUE TITLE
Upload Inconsistent

### ISSUE THREAD

**Issue by dgozzy** [sshnet/SSH.NET#160]
I'm using the following code to upload files. I've rerun the same file multiple times and about half of the time the file doesn't appear when I use Filezilla. Any suggestions?

using (var sftp = new SftpClient(host, username, password))
            {
                sftp.Connect();

                //Stream fs = File.OpenRead(completeXML);
                using (var fileStream = new FileStream(completeXML, FileMode.Open))
                {
                    sftp.UploadFile(fileStream, finalPath, null);
                }

                sftp.Disconnect();
                sftp.Dispose();
            }

**Comment by drieseng** [comment]
What version of SSH.NET are you using?

**Comment by dgozzy** [comment]
according to VS, 2016.0.0.0:
![image](https://cloud.githubusercontent.com/assets/17993137/22706343/c073e2f4-ed23-11e6-9e07-c8a5e61fe01f.png)

**Comment by dgozzy** [comment]
Also, thank you for the help!

**Comment by drieseng** [comment]
Just did a quick review of our code, and I don't immediately see how this could happen.
What server (and version) are you using?
Can you easily reproduce this, and if so - would it be possible for me to run some tests against this (test) server?

**Comment by dgozzy** [comment]
After seeing your confidence I went to double check if I might be the problem. My code going into the snippet above looked good. I then checked if maybe Filezilla was the problem and it turns out Filezilla is the issue. When using Putty to verify, the code consistently works. Sorry for the hassle but a win for SSH.net

**Comment by drieseng** [comment]
No problem.
Let me know if you have any further questions.
