### ISSUE TITLE
Is SDCTR supported?

### ISSUE THREAD

**Issue by jhunolt** [sshnet/SSH.NET#166]
We are having an issue connecting to one particular SFTP site.  Other SFTP clients like WinSCP, and psftp.exe are working.

One thing I noticed is that the site appears to be using stateful-decryption counter mode, is this supported with SSH.Net?

Here is part of the working WinSCP debug log.

 . 2017-02-08 14:30:57.288 Initialised AES-256 SDCTR client->server encryption
. 2017-02-08 14:30:57.288 Initialised HMAC-SHA1 client->server MAC algorithm
. 2017-02-08 14:30:57.319 Initialised AES-256 SDCTR server->client encryption
. 2017-02-08 14:30:57.319 Initialised HMAC-SHA1 server->client MAC algorithm

**Comment by drieseng** [comment]
This should work just fine.
Is this a public site?

**Comment by jhunolt** [comment]
Hi Gert,

It is a commercial site at 202.45.14.85 port 4022.  I can't give you the login info as it is not our site, but I believe if you connect and accept the host key you can see the cipher issue prior to being prompted to log in.

This is the connection in WinSCP prior to our SSH key being sent for authentication.  This was the first time I connected via WinSCP so I had to cache the host key.

. 2017-02-08 14:15:03.704 Looking up host "202.45.14.85" for SSH connection
. 2017-02-08 14:15:03.704 Connecting to 202.45.14.85 port 4022
. 2017-02-08 14:15:03.938 Selecting events 63 for socket 1064
. 2017-02-08 14:15:03.938 We claim version: SSH-2.0-WinSCP_release_5.9
. 2017-02-08 14:15:03.954 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:03.954 Looking for incoming data
. 2017-02-08 14:15:03.954 Looking for network events
. 2017-02-08 14:15:03.954 Detected network event
. 2017-02-08 14:15:03.954 Enumerating network events for socket 1064
. 2017-02-08 14:15:03.954 Enumerated 18 network events making 18 cumulative events for socket 1064
. 2017-02-08 14:15:03.954 Handling network write event on socket 1064 with error 0
. 2017-02-08 14:15:03.954 Handling network connect event on socket 1064 with error 0
. 2017-02-08 14:15:03.954 Looking for network events
. 2017-02-08 14:15:04.172 Detected network event
. 2017-02-08 14:15:04.172 Enumerating network events for socket 1064
. 2017-02-08 14:15:04.172 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:04.172 Handling network read event on socket 1064 with error 0
. 2017-02-08 14:15:04.172 Server version: SSH-2.0-SSHD
. 2017-02-08 14:15:04.172 We believe remote version has SSH-2 channel request bug
. 2017-02-08 14:15:04.172 Using SSH protocol version 2
. 2017-02-08 14:15:04.188 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:04.188 Looking for incoming data
. 2017-02-08 14:15:04.188 Looking for network events
. 2017-02-08 14:15:04.406 Detected network event
. 2017-02-08 14:15:04.406 Enumerating network events for socket 1064
. 2017-02-08 14:15:04.406 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:04.406 Handling network read event on socket 1064 with error 0
. 2017-02-08 14:15:04.422 Doing Diffie-Hellman group exchange
. 2017-02-08 14:15:04.422 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:04.422 Looking for incoming data
. 2017-02-08 14:15:04.422 Looking for network events
. 2017-02-08 14:15:04.858 Detected network event
. 2017-02-08 14:15:04.858 Enumerating network events for socket 1064
. 2017-02-08 14:15:04.858 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:04.858 Handling network read event on socket 1064 with error 0
. 2017-02-08 14:15:04.858 Doing Diffie-Hellman key exchange with hash SHA-256
. 2017-02-08 14:15:05.217 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:05.217 Looking for incoming data
. 2017-02-08 14:15:05.233 Looking for network events
. 2017-02-08 14:15:05.685 Detected network event
. 2017-02-08 14:15:05.685 Enumerating network events for socket 1064
. 2017-02-08 14:15:05.685 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:05.685 Handling network read event on socket 1064 with error 0
. 2017-02-08 14:15:06.075 Host key fingerprint is:
. 2017-02-08 14:15:06.075 ssh-rsa 2048 3f:57:92:6d:60:96:8d:f5:5a:30:70:4d:80:d2:14:a5
. 2017-02-08 14:15:06.075 Verifying host key rsa2 0x10001,0xcbcb4ba975ce2fdc 5376338f75ad91f1 f265ede7dd84d7cc a668b0cc97dbdcd1 5b0ba1c1b222503b 5f087c4375b5178d a4267a64e9c928a9 ceac2287bb38b26e 3243392dcc7f5e5c e2ca784487a340b8 1c1e029e8da0755d 30d0a00094427cdf 12b31b56e223e5ff d4b1964342c484f2 bb86e11a0f090548 22044c3d4de3a965 32476c64108654f6 781c71e637c7c0b4 f50fef22d5e47872 49c178c0f8a595f2 f8cd067b9184c487 ca1d7f84e033665d 6cb7349fe267201f 0aadccc10a2c689d 56c6ae7edd6abe5a da09229ab008609e 10f78e4be8da7df7 6b5d6e1c57351f0a b1af24f4c6768c4b 2179a40c0e38da44 74c8c9b8acd3a64e 94d83ccc6b58a12f  with fingerprint ssh-rsa 2048 3f:57:92:6d:60:96:8d:f5:5a:30:70:4d:80:d2:14:a5
. 2017-02-08 14:15:06.138 Asking user:
. 2017-02-08 14:15:06.138 **Continue connecting to an unknown server and add its host key to a cache?**
. 2017-02-08 14:15:06.138 
. 2017-02-08 14:15:06.138 The server's host key was not found in the cache. You have no guarantee that the server is the computer you think it is.
. 2017-02-08 14:15:06.138 
. 2017-02-08 14:15:06.138 The server's rsa2 key fingerprint is:
. 2017-02-08 14:15:06.138 ssh-rsa 2048 3f:57:92:6d:60:96:8d:f5:5a:30:70:4d:80:d2:14:a5
. 2017-02-08 14:15:06.138 
. 2017-02-08 14:15:06.138 If you trust this host, press Yes. To connect without adding host key to the cache, press No. To abandon the connection press Cancel. ()
. 2017-02-08 14:15:10.818 Selecting events 63 for socket 1064
. 2017-02-08 14:15:10.818 Initialised AES-256 SDCTR client->server encryption
. 2017-02-08 14:15:10.833 Initialised HMAC-SHA1 client->server MAC algorithm
. 2017-02-08 14:15:10.833 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:10.833 Looking for incoming data
. 2017-02-08 14:15:10.833 Looking for network events
. 2017-02-08 14:15:10.833 Detected network event
. 2017-02-08 14:15:10.833 Enumerating network events for socket 1064
. 2017-02-08 14:15:10.849 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:10.849 Handling network read event on socket 1064 with error 0
. 2017-02-08 14:15:10.864 Initialised AES-256 SDCTR server->client encryption
. 2017-02-08 14:15:10.864 Initialised HMAC-SHA1 server->client MAC algorithm
. 2017-02-08 14:15:10.864 Waiting for the server to continue with the initialization
. 2017-02-08 14:15:10.864 Looking for incoming data
. 2017-02-08 14:15:10.864 Looking for network events
. 2017-02-08 14:15:11.379 Detected network event
. 2017-02-08 14:15:11.379 Enumerating network events for socket 1064
. 2017-02-08 14:15:11.379 Enumerated 1 network events making 1 cumulative events for socket 1064
. 2017-02-08 14:15:11.379 Handling network read event on socket 1064 with error 0

Also is there a way to run a VB script or bat and call the SSH.Net components to make a test connection?  One of the issues I face is the component is being called by code I don't have access to, so I can enable any debug logs or generate any logs to speak of, 

Thanks for your response.

Jon

**Comment by drieseng** [comment]
I cannot reproduce this issue.
I got an authentication error, which is to be expected.
What exact exception do you get, or do you know what error is reported server-side?

**Comment by jhunolt** [comment]
I think we were seeing a “Credential is Invalid.” message in our end user application, but I believe that can be cause by any of the following.

The Session is disposed.
The SSH_MSG_DISCONNECT message - which is used to disconnect from the server - has been sent.
The client has not been authenticated successfully.
The listener thread - which is used to receive messages from the server - has stopped.
The socket used to communicate with the server is no longer connected. 

The company on the server side has been unhelpful, simply saying the issue is not on their side, and unwilling to provide any logs.

On our side I also have the issue that the messages I see are filtered through our code, and only very high level compared to what I can get with psftp or WinSCP.

I am checking with the person that originally reported the issue on our side, it started months ago, want to make sure it is still current.

In the meantime is there a simple command prompt or script driven way I can connect with more detailed logging to check?

**Comment by drieseng** [comment]
You can always create a small console app.

For now, you'll need to compile **SSH.NET** from source in **debug** configuration and configure tracing listeners to get detailed tracing.

Example configuration file:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.diagnostics>
    <trace autoflush="true"/>
    <sources>
      <source name="SshNet.Logging" switchName="SshNetSwitch" switchType="System.Diagnostics.SourceSwitch">
        <listeners>
          <add name="SshNetTraceFile" />
          <add name="Console" />
        </listeners>
      </source>
    </sources>
    <switches>
      <add name="SshNetSwitch" value="Verbose"/>
    </switches>
    <sharedListeners>
      <add name="SshNetTraceFile" type="System.Diagnostics.TextWriterTraceListener" initializeData="SshNetTrace.log" />
      <add name="Console" type="System.Diagnostics.ConsoleTraceListener" traceOutputOptions="DateTime,Timestamp,ThreadId" />
    </sharedListeners>
  </system.diagnostics>
</configuration>
````

In a future update, I'll see if I can update **SSH.NET** to support tracing in **release** configuration  without (all too much) impact on performance.

**Comment by jhunolt** [comment]
I tested the version of our app that was failing before and now it appears to be connecting fine too.  We have an actual production test happening tomorrow with the latest version of everything and transferring live files that will confirm.

My guess is that the institution on the other end finally changed something on their side that is letting things work now.  I will let you know how the test tomorrow goes.

I think creating a small console app is beyond what I can do, but it sure would be handy for debugging.

**Comment by jhunolt** [comment]
We have confirmed that the production version of our app using the SSH.Net component is now working fine with this SFTP host.  Not sure what the issue was, but apparently something was changed on the target SFTP server that resolved it.
