### ISSUE TITLE
SSH_FXP_OPENDIR fails against PowerShell OpenSSH

### ISSUE THREAD

**Issue by n0h** [sshnet/SSH.NET#171]
Please see PowerShell/Win32-OpenSSH#521.

We are using SSH.NET against PowerShell OpenSSH SFTP in one of our test environments. This combination used to work as of release v0.0.4.0 of that project, but it is broken in subsequent releases. We initially thought they introduced a bug in their code but they investigated and found that they actually made a fix. The fix revealed a problem with SSH.NET, in that it assumes all directories should start with "/" which is not the case for Windows. See the linked ticket for further details. Here is a comment from their developer:

> Its appending the current working directory to the path passed based on the assumption that the full path always starts with the "/". In windows the paths doesn't start with "/" so their code is appending the current working directory to the path passed. This is working earlier because of a bug in our code which is now fixed.

This may also be related to #83 (which links back to PowerShell/Win32-OpenSSH#310).

**Comment by drieseng** [comment]
I'm not sure if we should consider this an issue in **SSH.NET**.
The Win32 port of OpenSSH itself actually returns paths with forward slashes (eg. /C:/Users/Gert Driesen), so the client should probably do this as well.

I assume you were passing a directory with backslahes?

**Comment by drieseng** [comment]
The only examples that I found on their site use forward slashes:

https://github.com/PowerShell/Win32-OpenSSH/wiki/sftp.exe-examples

**Comment by n0h** [comment]
Yes, we were using backslashes. Switching our code and settings to use forward slashes resolved our problem.

However, wondering what is the optimal way for SSH.NET to handle this. We have tested other SFTP clients, including the aforementioned PowerShell OpenSSH's included sftp.exe. When it provides output, it returns paths with forward slashes as you say. But for input it seems to accept both slashes and backslashes, and treat them the same.

**Comment by drieseng** [comment]
I just tested this with putty:

```
psftp> pwd
Remote directory is /C:/Users/Gert Driesen
psftp> cd c:\
Directory /C:/Users/Gert Driesen/c:/: bad message
```

Based on this, I'm very much inclined to close this issue.
Agree?

**Comment by n0h** [comment]
I did some additional testing with putty as well as PowerShell OpenSSH's included sftp.exe. Initially I thought that it would make sense to match PowerShell's behavior, which has more affordances for working with windows paths, and seems to simply treat backslashes as if they were slashes.

But upon further thought it is not that simple. Backslashes are sometimes used as escape characters in sftp so you can't just globally treat them as slashes. Still, I question the assumption that putty behavior should be considered to be correct. Perhaps they have room to improve their interoperation with windows?

I'm no sftp expert so I thought it would make sense to look at the RFC to see what the specs say to do. Apparently it never made it out of draft status but here are the relevant sections:

[File Names](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-6)
```
   This protocol represents file names as strings.  File names are
   assumed to use the slash ('/') character as a directory separator.

   File names starting with a slash are "absolute", and are relative to
   the root of the file system.  Names starting with any other character
   are relative to the user's default directory (home directory).  Note
   that identifying the user is assumed to take place outside of this
   protocol.
```

This lends support to your position, and to closing this issue.

[Best Practice for Dealing with Paths](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-8.9.1)
```
   The client SHOULD treat the results of SSH_FXP_REALPATH as a
   canonical absolute path, even if the path does not appear to be
   absolute.  A client that uses REALPATH(".", "") and treats the result
   as absolute, even if there is no leading slash, will continue to
   function correctly, even when talking to a Windows NT or VMS style
   system, where absolute paths may not begin with a slash.

   The client SHOULD also use SSH_FXP_REALPATH call to compose paths so
   that it does not need to know when a path is absolute or relative.

   For example, if the client wishes to change directory up, and the
   server has returned "c:/x/y/z" from REALPATH, the client SHOULD use
   REALPATH("c:/x/y/z", "..", SSH_FXP_REALPATH_STAT_ALWAYS)

   As a second example, if the client wishes transfer local file "a" to
   remote file "/b/d/e", and server has returned "dka100:/x/y/z" as the
   canonical path of the current directory, the client SHOULD send
   REALPATH("dka100:/x/y/z", "/b/d/e", SSH_FXP_REALPATH_STAT_IF).  This
   call will determine the correct path to use for the open request and
   whether the /b/d/e represents a directory.
```

This demonstrates more consideration for non-unixy systems, and to me it seems in a way contradictory to the earlier section.

Anyway, you are in a better position to determine what the "right" thing to do here is. As I said, we have our system working properly now that we know what was causing our issue, so we are not impacted if you decide to leave the behavior as is.

Thanks for your work on this project.

**Comment by drieseng** [comment]
No thanks (but appreciated!).
