### ISSUE TITLE
DownloadFile > InternalDownloadFile Infinite Loop

### ISSUE THREAD

**Issue by ghost** [sshnet/SSH.NET#175]
I've been using this library for uploads and it works great! Today I needed to use the download method and I could not figure out why that method runs and runs and never completes. No errors. I dug into the project and noticed that this method doesn't appear complete...

`while (true)
            {
                // TODO: cancel read ahead when download is canceled by user

                //  Cancel download
                if (asyncResult != null && asyncResult.IsDownloadCanceled)
                    break;

                var data = fileReader.Read();
                if (data.Length == 0)
                    break;

                output.Write(data, 0, data.Length);

                totalBytesRead += (ulong) data.Length;

                if (downloadCallback != null)
                    downloadCallback(totalBytesRead);
            }`

There's an infinite loop here and at least for me the break is never hit. Is there another version I can use? I know this method works if you have the correct version as all the examples on the web work according to their writers. Also previous employees at my company have used this library in the past the exact same way I am with no issues.

Thanks for any input.

**Comment by drieseng** [comment]
You're using a new implementation for **DownloadFile** that is currently only available in the **develop** branch, and as such I wouldn't yet consider it stable.

That said, it _should_ work just fine. Can you consistently reproduce the "hang"?
What SSH server (and version) are you using?

I hope you can find some time to work with me on finding the cause for this issue.

**Comment by ghost** [comment]
Thanks for you response. I managed to locate an old version of the dll which does what I need it to do.

As your question yes it does consistently hang indefinitely. I left it running for a solid hour and it was still going. Oddly with my code it does create the empty file in the location I defined. Sometimes* when I force the application to stop the file does come across correctly and other times it's a blank file. I can't share details of my environment but I can share my code implementing the library if that helps.

`    fileList.ForEach(f =>
                {
                    try
                    {
                        var smtpPath = directory + f;

                        using (var memoryStream = new MemoryStream())
                        {
                            sftpClient.DownloadFile(smtpPath, memoryStream);

                            var fileInfo = new FileInfo(f);

                            var outputFile = destination + fileInfo.Name;
                            var fileStream = new FileStream(outputFile, FileMode.Create, FileAccess.Write);

                            memoryStream.WriteTo(fileStream);
                            memoryStream.Close();

                            fileStream.Close();
    }}});`

**Comment by drieseng** [comment]
I'll try some potential fix later today.
If that doesn't work out, I'll add some extra tracing.

**Comment by ghost** [comment]
I appreciate the effort.

**Comment by drieseng** [comment]
Can you rebuild from the **develop** branch and check if you can still reproduce this issue?
I don't have high hopes, but I'd appreciate it if you'd try it .
The next step is adding some extra tracing.

Isn't it possible for you to provide the name and version of the SSH server software that you're using, so I can try to reproduce it myself?

**Comment by drieseng** [comment]
@BabyMickers Do you have an update for me? Thx!

**Comment by ghost** [comment]
@drieseng I haven't tried rebuilding the dev branch again yet. I contacted my administrator and all he could tell me was that it wasn't a SSH server but a Unix box. I hope that helps. Thanks!

**Comment by drieseng** [comment]
Please try to rebuild from the **develop** branch as this issue is blocking the release of a new beta.
You can use [this](https://github.com/sshnet/SSH.NET/wiki/How-to-obtain-remote-server-info) to obtain the name and version of the remote SSH server software.

**Comment by ghost** [comment]
Server/Version: SSH-2.0-OpenSSH_5.3
I rebuilt the development branch and ran a test. Did not experience any hanging. File downloaded properly almost instantaneously.

`
	using (var sftpClient = new SftpClient("host", "user", "pass"))
	{
		sftpClient.Connect();

		using (var memoryStream = new MemoryStream())
		{
			sftpClient.DownloadFile(@"/Test/test.txt", memoryStream);

			var fileStream = new FileStream(@"C:\Test\test.txt", FileMode.Create, FileAccess.Write);

			memoryStream.WriteTo(fileStream);
			memoryStream.Close();

			fileStream.Close();
		}
	}`
I can't seem to get the code to display properly. I apologize.
Thanks again!

**Comment by drieseng** [comment]
Thanks for the update.
I'll consider this issue fixed.
