### ISSUE TITLE
Please make proper Readme with examples

### ISSUE THREAD

**Issue by d668** [sshnet/SSH.NET#176]
Can you kindly follow github common practice - make a readme with guide and code samples. I am looking  and not sure where to start

**Comment by drieseng** [comment]
I gadly accept you offer, and await your PR (another GitHub common practice).
Honestly, I can't do everything myself ...

**Comment by rickerj135** [comment]
Oh, Mr. Driesen. Since you're not busy, I left some clothing in Stuttgart to be cleaned. Be a good fellow and ride the train to pick it up for me?

[😊]


Jim Ricker




________________________________

**Comment by drieseng** [comment]
@rickerj135 I'm on my way :p
