### ISSUE TITLE
Support for FTP 

### ISSUE THREAD

**Issue by meghabhamare** [sshnet/SSH.NET#181]
Hello, 

Please let me know if this will also support for a simple FTP. 
Also, for a simple FTP client and server with SFTP or vice versa , what will be the changes that one needs to do ? 

Thanks in advance.

**Comment by Kvasi** [comment]
The .NET Framework provides comprehensive support for the FTP protocol with the FtpWebRequest and FtpWebResponse classes.

**Comment by drieseng** [comment]
Our focus is on SSH-related protocols, and - as @Kvasi mentions - the .NET Framework already provides support for this.
