### ISSUE TITLE
Is your library supported on the top of .Net Core 

### ISSUE THREAD

**Issue by JPBlanc** [sshnet/SSH.NET#192]
Not a bug, but just a question :

Does you library work on .Net Core, in fact, can it be uable with PowerShell on the top of Linux ?

Thanks for you attention.

**Comment by drieseng** [comment]
Yes, it should work just fine on .NET Core.
I haven't recently tested it on Linux, but i works just fine with .NET Core on Windows.
Don't hesitate to open an issue if you run into any problem on Linux.
