### ISSUE TITLE
Fatal Error in SftpFileStream.cs

### ISSUE THREAD

**Issue by hzsong123** [sshnet/SSH.NET#196]
Fatal Error in SftpFileStream.cs
 in function: public override int ReadByte()
_bufferLen = data.Length;
[Error]: Buffer.BlockCopy(data, 0, _readBuffer, 0, _readBufferSize);
[Must be]: Buffer.BlockCopy(data, 0, _readBuffer, 0, _bufferLen);
by hzsong123, 2017-03-15
e-mail: hzsong123@126.com

**Comment by drieseng** [comment]
I recently fixed this as part of issue #173.
