### ISSUE TITLE
Build failure of developer branch

### ISSUE THREAD

**Issue by imapangolin** [sshnet/SSH.NET#198]
Trying to see if dev build will resolve "no suitable authentication" exception.

Getting the errors in the attachment.  VS2015.

![screen shot 2017-03-17 at 10 43 26 am](https://cloud.githubusercontent.com/assets/3413937/24048477/68e3c276-0aff-11e7-9bc1-623fdf5c279d.png)

**Comment by imapangolin** [comment]
The specific issue I am trying to resolve is the exception "No suitable authentication method found to complete authentication".  The server is Firefox SFTP - not under my control.  Any idea what I could use to make this work?  

Connect code is:

         using (var client = new SftpClient(ServerName, Convert.ToInt32(Port), UserID, Password))
            {
                client.Connect();

             //   client.BufferSize = 4 * 1024;
                using (Stream file1 = File.OpenWrite(ClientFileName))
                {
                    client.DownloadFile(ServerFileName, file1);
                }
            }

**Comment by darkoperator** [comment]
Could it uses keyboard interactive, do not see any code for handling the event in your snippet

**Comment by imapangolin** [comment]
What’s keyboard interactive?

**Comment by imapangolin** [comment]
I do doubt this - as this is for an unattended process.

**Comment by darkoperator** [comment]
It is an auth method where credentials are handled by a PAM on the host. I got the same error when that method is enabled on the server. You can see how I handle that auth method in Posh-SSH https://github.com/darkoperator/Posh-SSH/blob/master/PoshSSH/PoshSSH/NewSessionBase.cs

**Comment by darkoperator** [comment]
It is an auth method on the server it does not affect if  you are doing it interactively or unattended

**Comment by imapangolin** [comment]
I clearly didn’t know what I was talking about as far as the keyboard interactive.  Coding for that does indeed cure my connection problem and I thank you.

The issue of the developer build failing, however, does remain.

Thanks again

**Comment by darkoperator** [comment]
No clue on the build, I tend to stick with release versions. Happy it helped

**Comment by drieseng** [comment]
The build failure is due to recent changes by @olegkap, which we will probably (at least temporarily) revert.

**Comment by imapangolin** [comment]
Thanks  - can you let me know please when the dev build is buildable?

**Comment by drieseng** [comment]
Build is now fixed.
