### ISSUE TITLE
Try to use it in VS2017 console app, getting error

### ISSUE THREAD

**Issue by KernowCode** [sshnet/SSH.NET#200]
Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified

**Comment by drieseng** [comment]
Can you attach the source to that console app?
What framework are you targeting?

**Comment by SuperJMN** [comment]
It doesn't happen with my VS 2017 install. No problem at all.

**Comment by drieseng** [comment]
No feedback since initial report.
Reopen this issue if you have more info.
