### ISSUE TITLE
Firewall issue port 443 with renci ssh.net

### ISSUE THREAD

**Issue by nfmt** [sshnet/SSH.NET#202]
When i use port 443 behind firewall , i have only "timeout" when i use client.connect() (c#) 
The same configuration works in my home.
Behind this firewall , Bitvise client and putty work with the same port : 443. 

I  can't use port 22 in my job site.
Could somebody help me ?

**Comment by darkoperator** [comment]
Can you post a snippet of the code you are using to make the connection?

**Comment by nfmt** [comment]
First, thank your help.
this is the snippet. Nothing special to note. i am always ended with client.connect(). Always "time out" behind the firewall but work in my home. With port 22, the code works but i can't use it.

public static bool testVpn(CloudObject currentCloudParameter)
        {
            bool validConnect = false;
            ConnectionInfo vpnConnection = VpnConnect.makeSSHConnection(currentCloudParameter.cloudIPServer,
                443, currentCloudParameter.cloudUser, currentCloudParameter.cloudPassword);
            using (var client = new SshClient(vpnConnection))
            {
                try
                {
                    client.ErrorOccurred += delegate (object sender, ExceptionEventArgs e)
                    {
                        Console.WriteLine("Client error: " + e.Exception.Message);
                    };
                    client.HostKeyReceived += delegate (object sender, Renci.SshNet.Common.HostKeyEventArgs e)
                    {
                        e.CanTrust = true;
                        Console.WriteLine("Connected to server");
                        Console.WriteLine("Key Exchanged");
                    };
                    client.Connect();
                    Console.WriteLine(client.ConnectionInfo.ServerVersion);
                    if (client.IsConnected)
                    {
                        ...
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine(ex.Message);
					....
		}
}

thank

**Comment by nfmt** [comment]
Error, i close it. Sorry

**Comment by kasbst** [comment]
@nfmt What's your configuration? Do you have port 443 set in sshd config or are you using ssh tunnel?
