### ISSUE TITLE
Nuget Package vs Latest Build

### ISSUE THREAD

**Issue by LukB4ULeap** [sshnet/SSH.NET#203]
When was the last Nuget update made? 
Can you tell me which build is the latest as our project is in a crucial stage and I wonder if introducing a new build will help me in tiding over the problem faced.

**Comment by kasbst** [comment]
@LukB4ULeap https://www.nuget.org/packages/SSH.NET

SSH.NET 2016.1.0-beta1 	           Wednesday, December 14, 2016

For further testing you have to probably use the version from develop branch for now. @drieseng must confirm however ;)

**Comment by drieseng** [comment]
I've released version **2016.1.0-beta2** just a few days ago.
It's available from [GitHub](https://github.com/sshnet/SSH.NET/releases/tag/2016.1.0-beta2) and [NuGet](https://www.nuget.org/packages/SSH.NET/2016.1.0-beta2).
