### ISSUE TITLE
SshClient connection not possible with privat keyfile

### ISSUE THREAD

**Issue by Luzzifer** [sshnet/SSH.NET#210]
Hi,

I have problems with the new 2016.1.0-beta1 version with the sshclient connection with a private key file.

I use the same code with the 2014.4.6-beta6 and it work. I have checked the new help file for correct use / function call and I think is all correct but in the new version have I this error at the Connect of the SshClient object:

>The value can not be NULL.
>Parameter name: All lists are NULL or empty.

I use this code lines for the connection:

```
string strRSAPath = CAssemblyHelper.GetAssemblyPathByFileName("id_rsa_" + USERNAME);

                System.IO.Stream KEYFILE = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream(strRSAPath);

                Renci.SshNet.PrivateKeyFile KEYFILESTREAM = new Renci.SshNet.PrivateKeyFile(KEYFILE, KEYFILEPASSPHRASE);

                var ci = new Renci.SshNet.PrivateKeyConnectionInfo(SSHSERVER, SSHPORT, USERNAME2, KEYFILESTREAM);
                Renci.SshNet.SshClient client = new Renci.SshNet.SshClient(ci);
                client.Connect();
```

Can you check this please. Is this a bug or have I anything do wrong.

Thanks for help. Sorry for my english, it is not so well.

Best regards,
Michael

**Comment by kasbst** [comment]
@Luzzifer I think your issue is that GetManifestResourceStream() returns NULL.

Make sure that:
1) Your referenced assembly (in your case private key) has Build Action set to "Embedded Resource"
2) The path for GetManifestResourceStream is NAMESPACE.FOLDER.FILE

Example:
```C#
System.IO.Stream KEYFILE = System.Reflection.Assembly.GetExecutingAssembly().GetManifestResourceStream("NAMESPACE.privatekeyfile");
PrivateKeyFile KEYFILESTREAM = new PrivateKeyFile(KEYFILE, "pkpassword");

var ci = new PrivateKeyConnectionInfo(server, 22, username, KEYFILESTREAM);
using (var client = new SshClient(ci))
{
       client.Connect();

       SshCommand terminal = client.RunCommand("hostname");
       Console.WriteLine("Connected to " + terminal.Result);

       client.Disconnect();
 }
```
