### ISSUE TITLE
SFTP Binary Mode?

### ISSUE THREAD

**Issue by QuantumRevenger** [sshnet/SSH.NET#212]
I'm having an issue with checksum after uploading a .zip file over SSH.NET and am told I must use Binary Mode - albeit no clear option to define this.

Is Binary Mode default, or how do I enforce this?

**Comment by kasbst** [comment]
@QuantumRevenger the binary mode is the default for SFTP protocol and you have to explicitly force the text/ascii mode, if desired. However, the ascii/text mode is supported by an SFTP version 4 and newer only. And many SFTP servers/clients (including the most widespread one, the OpenSSH) support an SFTP version 3 only. So they will not even let you use the text/ascii mode.

Moreover, as SftpSession.cs states:
```C#
private const int MaximumSupportedVersion = 3;
private const int MinimumSupportedVersion = 0;
```
Please share your code, so we can reproduce in case you have still an issue with that.

**Comment by LadyR123** [comment]
Hello, I have the same problem with sourceforge.net
Local sha256 is diff with server sha256


```
private static void HandleKeyEvent(object sender, AuthenticationPromptEventArgs e)
        {
            foreach (AuthenticationPrompt prompt in e.Prompts)
            {
                if (prompt.Request.IndexOf("Password:", StringComparison.InvariantCultureIgnoreCase) != -1)
                {
                    prompt.Response = "anypass";
                }
            }
        }
  KeyboardInteractiveAuthenticationMethod keybAuth = new KeyboardInteractiveAuthenticationMethod("jjjj");
            keybAuth.AuthenticationPrompt += new EventHandler<AuthenticationPromptEventArgs>(HandleKeyEvent);
            ConnectionInfo conInfo = new ConnectionInfo("frs.sourceforge.net", 22, "iikk", keybAuth);
            using (var sftp = new SftpClient(conInfo))
            {
                sftp.Connect();
 using (FileStream fs = new FileStream(zip_path, FileMode.Open))
                {
                          sftp.UploadFile(fs, "file.zip");
                }
}
```
