### ISSUE TITLE
"quote site" 

### ISSUE THREAD

**Issue by imapangolin** [sshnet/SSH.NET#214]
I have an ftp process that they want us to switch over to sftp - and part of the process is sending a 
"quote site wait_for_files"

And then we get *.* 

so with sftp - how do we send a "quote site wait_for_files" - maintain the connection the get everything?

Thanks

**Comment by imapangolin** [comment]
Am I just ignorant - or is there a better place to ask this question?

**Comment by darkoperator** [comment]
To be honest I think SFTP even when the name says FTP is compleatly different and this would not translate to it.

**Comment by imapangolin** [comment]
Thanks - thats what I suspected but the vendor says "change to the sftp server" and everything else is the same - but there is a QUOTE SITE command that is required to trigger creation of the files we are to download so I'll just try to get in touch with someone there because it just doesn't make sense.

**Comment by kasbst** [comment]
@imapangolin , as @darkoperator mentioned, FTP has nothing to do with SFTP; SFTP is a binary, packet based protocol, based on SSH. It doesn't use text based commands
and responses like FTP, so there are no textual commands like QUOTE SITE in SFTP protocol. You have to use remote shell commands for any additional interaction with the remote server if various SFTP clients built-in commands (including SFTP client in SSH.NET) are not enough for your needs.
