### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by mcpat-it** [sshnet/SSH.NET#216]
Hi,

I know it was discussed [here](https://github.com/sshnet/SSH.NET/issues/181), but is it possible to implement ftp? I have to use a socks proxy, and your lib is perfect (but I have to use sFtp) for this matter. I have to use FTP over socks, not sFTP...

It would be great if you could implement this feature!

Thx
Patrick

**Comment by darinkes** [comment]
Why should FTP be part of an SSH Library? As in the question before the reasoning is missing.

Besides its already part of .NET:
https://msdn.microsoft.com/en-us/library/system.net.ftpwebrequest(v=vs.110).aspx

**Comment by mcpat-it** [comment]
because I have to use a socks5 proxy, and the ftpwebrequest cannot do it and it is not as good as your solution!

**Comment by Rondom** [comment]
FTP is a completely different protocol from SSH/SFTP. Despite its name SFTP (I guess that's where your confusion comes from), does not really have much in common with FTP, it's completely different.

Thus, this is almost definitely the wrong project to look into if you want to deal with FTP.

**Comment by mcpat-it** [comment]
Thx for answer. Yes this was my confusion. Therefore I close the issue...
