### ISSUE TITLE
Difference in file permissions in a folder when a file is created through ssh.net vs putty 

### ISSUE THREAD

**Issue by madhav4043** [sshnet/SSH.NET#219]
I tried to create a file in a linux box through SSH.NET and I am able to create it successfully. The file permissions are -rw------ but when I create the same file through putty the file permissions are -rw-r--r--. I am using same username and server in the .net code and putty. When I try this operation in a different linux box the permissions of a file created through .net code and putty are same in that server. What could be the reason for this discrepancy?

string strShellCommand = "echo 'test textttt' > test_file.txt";
ExecuteCommand(strShellCommand);
public void ExecuteCommand(string strCommand)
        {
            ConnectionInfo ConnNfo = new ConnectionInfo("testserver.intra.com", 22, "adm",
            new AuthenticationMethod[]{

                // Pasword based Authentication
                new PasswordAuthenticationMethod("adm","password2017"),
                }
            );
            // Execute (SHELL) Commands
            using (var sshclient = new SshClient(ConnNfo))
            {
                sshclient.Connect();                          
                string str = sshclient.CreateCommand(strCommand).Execute();                
                sshclient.Disconnect();
            }
        }

**Comment by darkoperator** [comment]
Coult it that putty is a full terminal and uses the mask for the configured shell and execute() does exec on the binary outside of a terminal?

**Comment by madhav4043** [comment]
Thanks for replying. I have executed the umask command in putty and through C# code and I get same result 022 in both. Also the C# script is working as expected in another instance of UNIX server with same code. Is there any other way of executing a command using this DLL?

**Comment by darkoperator** [comment]
Using a ShellStream, after connecting create one and write your commands to it 

Sshclient.Connect(); using (ShellStream shell = Sshclient.CreateShellStream("dumb", 80, 24, 800, 600, 1024))

Use writeline and read to write and read from the shell. It should use the mask of the shell for the permissions

**Comment by WojciechNagorski** [comment]
SSH.NET has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
