### ISSUE TITLE
SetLastWriteTime and SetLastWriteTimeUtc not implemented

### ISSUE THREAD

**Issue by ygoe** [sshnet/SSH.NET#228]
This is documented in the code, these methods throw a NotImplementedException. I'd rather have them do what they're supposed to do. Is this a complicated feature to implement?

Or, put it another way, can I upload a local file and keep its last write time?

**Comment by ygoe** [comment]
This code seems to be the workaround:

	var sftpFile = client.Get("path/to/file");
	sftpFile.LastWriteTimeUtc = someTime;
	sftpFile.UpdateStatus();

**Comment by Rondom** [comment]
See #217

**Comment by ygoe** [comment]
That doesn't help for the *Utc methods because the attributes don't have that information.

**Comment by drieseng** [comment]
Duplicate of #217.

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
