### ISSUE TITLE
How to use the Shell object?

### ISSUE THREAD

**Issue by SuperJMN** [sshnet/SSH.NET#232]
Hello! I'm trying to make a SSH Client for UWP.

I'm playing a bit with the library and did this as a test to learn, since there is a big lack of documentation online.

```
var input = new MemoryStream();
var output = new MemoryStream();
var exOtput= new MemoryStream();

var client = new SshClient("host", "user", "pass");
client.Connect();
shell = client.CreateShell(input , output , exOtput);
shell.Start();
```

I have managed to read by polling the output stream and using the `Seek` method. However, regarding the input it seems that **writing to the input stream doesn't have any effect**. In other words, I don't know if I'm writing to the input stream correctly, because I don't receive any response back in the output.

I'm also trying to understand what's happening and created a classic Console application. The problem is the same: I cannot send anything to the Shell using a MemoryStream.

This is the exact code I'm testing with:

```
using System;
using System.IO;
using Renci.SshNet;

namespace SSHTest
{
    class Program
    {
        static void Main(string[] args)
        {

            var ssh = new SshClient("raspberrypi", 22, "pi", "raspberry");
            ssh.Connect();
            
            var memoryStream = new MemoryStream();
            var streamWriter = new StreamWriter(memoryStream) { AutoFlush = true };

            var shell = ssh.CreateShell(memoryStream, Console.OpenStandardOutput(), new MemoryStream());
            shell.Start();

            streamWriter.WriteLine("ls");
            
            while (true)
            {               
            }
        }
    }
}
```

Thanks in advance :)

**Comment by LightCC** [comment]
The Shell object seems to be the least developed of the interfaces in SSH.NET (between using SshCommand, ShellStream, and Shell).  Take a look through the tests and look at the implemented methods in the code and you may see what I mean.  I'm struggling to get Shell or ShellStream working, but there are some people that have gotten the basics working.  

Here is an app using SSH.NET on Github that uses Shell:  [Universal SSH](https://github.com/SuperJMN/UniversalSSH) that you may be able to use as an example.  These StackOverflow Q&A's may help:

* <https://stackoverflow.com/questions/46847304/is-it-possible-to-execute-multiple-ssh-commands-from-a-single-login-session-with>
* <https://stackoverflow.com/questions/44528158/ssh-net-doesnt-process-my-shell-input-commands?noredirect=1&lq=1>

**Comment by MaLiN2223** [comment]
For anyone looking for answer, I think OP found one on [stackoverflow](https://stackoverflow.com/a/44542531/3809977)
