### ISSUE TITLE
Connecting to Reflections SSH server causes SshAuthentication Failure

### ISSUE THREAD

**Issue by haimiko** [sshnet/SSH.NET#240]
When I try to connect with password to a Reflections SSH server i get the following error:
+		$exception	{"No suitable authentication method found to complete authentication (publickey,keyboard-interactive)."}	Renci.SshNet.Common.SshAuthenticationException

Other OpenSSH2 servers work just fine.

**Comment by haimiko** [comment]
Fixed by using kauth.AuthenticationPrompt += new EventHandler<AuthenticationPromptEventArgs>(HandleKeyEvent);

**Comment by TrueGandalf** [comment]
Hello! What is kauth?
