### ISSUE TITLE
Cannot execute command for oracle

### ISSUE THREAD

**Issue by makaraset** [sshnet/SSH.NET#247]
Dear all,

I cannot execute Linux command for Oracle via ssh.net such as expdp, impdp, tnsping
`using (var client = new SshClient("192.168.1.5", "oracle", "123456"))
{
client.Connect();
var cmd = client.CreateCommand("expdp uat/uatdbsys@uatdb DUMPFILE=test.dmp SCHEMAS=uat");
 cmd.Execute();
 Console.WriteLine("Command 1: " + cmd.Result);
 client.Disconnect();
 Console.ReadLine();
 }`

After I executed I got error 
`Error = "bash: expdp: command not found\n"`.

Anyone please help me!
Thanks in advance!

**Comment by drieseng** [comment]
Specify the full path to the commands that you want to execute.
Let me know if that worked for you.

**Comment by IgorMilavec** [comment]
Closed due to inactivity
