### ISSUE TITLE
Bad length exception on cat command

### ISSUE THREAD

**Issue by udulukovkodron** [sshnet/SSH.NET#257]
Hello,
I have a router, I want to read a file content from the router with **cat** command (without downloading the file).
I found that in some conditions I got an "Bad length exception".
I have tried to set all combinations of hmac algorithms and cipher algorithms in ConnectionInfo.
I got the cipher and hmac lists on the router with **ssh -c help**/**ssh -m help** commands. But it didnt help.
Router have Dropbear_2014-63-1 installed.
SSH.NET is the last from develop branch.

I did a test with infinite loop to read the file contents, and Exception is thrown after some successfuly executed commands.

My first idea was the encoding, but I set connInfo.Encodig to UTF8Encoding.ASCII. It also didnt help.
Later I found that if I remove some strings from the file, Exception is not thrown. Then, playing with file length I discovered that Exception is thrown only when file length is between 462b and 479b (463b...478b).

Here is the log I have:
Execute "cat <file_name>" 
SshNet.Logging Verbose: 1 : SendMessage to server 'ChannelOpenMessage': 'SSH_MSG_CHANNEL_OPEN'.
SshNet.Logging Verbose: 1 : First block: 0000001c0a5b00000017000000000000 **decrypted first block read by the Message.ReceiveMessage() method**
SshNet.Logging Verbose: 1 : ReceiveMessage from server: 'ChannelOpenConfirmationMessage': 'SSH_MSG_CHANNEL_OPEN_CONFIRMATION : #23'.
SshNet.Logging Verbose: 1 : SendMessage to server 'ChannelRequestMessage': 'SSH_MSG_CHANNEL_REQUEST : #0'.
SshNet.Logging Verbose: 1 : First block: 0000000c0663000000170e7aae82f565 **decrypted first block read by the Message.ReceiveMessage() method**
SshNet.Logging Verbose: 1 : ReceiveMessage from server: 'ChannelSuccessMessage': 'SSH_MSG_CHANNEL_SUCCESS : #23'.
SshNet.Logging Verbose: 1 : First block: 000001ec0b5e00000017000001d7636f **decrypted first block read by the Message.ReceiveMessage() method**
SshNet.Logging Verbose: 1 : Data received: **<here I put the whole data array that processed by the Message.LoadData method()>**
SshNet.Logging Verbose: 1 : < file contents in text veiew >
SshNet.Logging Verbose: 1 : ReceiveMessage from server: 'ChannelDataMessage': 'SSH_MSG_CHANNEL_DATA : #23'.
SshNet.Logging Verbose: 1 : First block: 77cfa6f64ec991321a70a3ea512b89c3 **here is the error - this is decrypted block, and the packet len is greater than SSH max packet size.**

**Comment by drieseng** [comment]
Can you provide a self-contained test case?
With this I mean a small app (source) that:
* configures SSH.NET accordingly (hmac, cipher) 
* creates the file that you want to read (with content that allows you to reproduce the issue)
* executes **cat**

**Comment by udulukovkodron** [comment]
Sorry, Forgot to close the issue.
I think the issue was somewhere in dropbear package.
I updated the package, and now it is all OK.
thank you
