### ISSUE TITLE
Download Range Bytes to Stream with SftpClient

### ISSUE THREAD

**Issue by fabriziomorello** [sshnet/SSH.NET#259]
Is there any way to download a range of bytes and not entire file?  I read from FTP's RFC 959 that it supports REST (RESTART):

> RESTART (REST) The argument field represents the server marker at which file transfer is to be restarted. This command does not cause file transfer but skips over the file to the specified data checkpoint. This command shall be immediately followed by the appropriate FTP service command which shall cause file transfer to resume.

Is there any implementations of this?

**Comment by drieseng** [comment]
*SftpClient* implement the SFTP protocol, not plain FTP.
