### ISSUE TITLE
Only works in debug mode

### ISSUE THREAD

**Issue by made1990** [sshnet/SSH.NET#261]
Hi there,

I am using Visual Studio 2017 creating a windows 10 uwp app.

When trying my app in Debug mode, my ssh.net module works just fine. But when I try in Release mode its not working anymore (no connection to my ssh server can be established).

The difference I see is, that in Release mode it usese .Net Native compiling and Code optimization. Non of those is used in debug mode.
Unfortunately when I would upload the app to the windows store, it would use .Net Nativ compiling which would result in a non-working app :(

Any idea why is that?

**Comment by drieseng** [comment]
What error do you get, and which version of **SSH.NET** are you using?

**Comment by made1990** [comment]
I am using SSH.NET 2016.0.0, also tried the latest beta 2016.1.0-beta1 but that made no difference

Well at that point in my code in hangs:

`try
{
          sshclient.Connect();
}
catch
{
         // some error handling
}`

In Debug mode the Connect works fine and the code goes on, but in Releaes Mode it always goes to the catch part.

Let me check what happens, if I comment out the try-catch-phase....

**Comment by drieseng** [comment]
Please provide the stack trace of the exception that you get.

**Comment by made1990** [comment]
Strangely it's wokring now.
I downgraded Microsoft.NETCore.UniversalWindowsPlatform to 5.2.2 and it seems to work now..
With version 5.3.x it did not work

**Comment by drieseng** [comment]
Don't hesitate to reopen the issue if you can provide more details.
