### ISSUE TITLE
Question on .net Core use

### ISSUE THREAD

**Issue by craigxgibbons** [sshnet/SSH.NET#263]
I am trying to use SSH.NET version 2016.0.0 in a ,net Core project. I've attempted to run the following simple block of code to get started and I am seeing some errors;

```
            var connectionInfo = new ConnectionInfo("sftp.foo.com",
                                        "guest",
                                        new PasswordAuthenticationMethod("guest", "pwd"),
                                        new PrivateKeyAuthenticationMethod("rsa.key"));

            using (var client = new SftpClient(connectionInfo))
            {
                client.Connect();
            }
```

1.) 'SftpClient' does not contain a constructor that takes 1 arguments
2.) 'SftpClient': type used in a using statement must be implicitly convertible to 'System.IDisposable'
3.) 'SftpClient' does not contain a definition for 'Connect' and no extension method 'Connect' accepting a first argument of type 'SftpClient' could be found (are you missing a using directive or an assembly reference?)

I have a using statement for using Renci.SshNet;

Is this a .net Core problem or am I missing something here?

Thanks

**Comment by drieseng** [comment]
What version of Visual Studio are you using?

**Comment by craigxgibbons** [comment]
I'm on Visual Studio Community 2015 Update 3

**Comment by jasonfwi** [comment]
This works for me in .net Core.
```
ConnectionInfo conn = new ConnectionInfo(sshHost, 22, sshUser,
                new AuthenticationMethod[]
                {
                    
                    new PasswordAuthenticationMethod(sshUser, sshPass),
			new PrivateKeyAuthenticationMethod(rsaKey)
                });
```

**Comment by IgorMilavec** [comment]
@craigxgibbons was the question answered, can we close the issue?
