### ISSUE TITLE
AuthenticationConnection limitation

### ISSUE THREAD

**Issue by pelhu** [sshnet/SSH.NET#264]
Hi,
Could you do parametric the number of "AuthenticationConnection initialCount".
Because I have applications that connect up to hundreds of machines simultaneously.

cordially

**Comment by lifeincha0s** [comment]
> Hi, Could you do parametric the number of "AuthenticationConnection initialCount". Because I have applications that connect up to hundreds of machines simultaneously.
> 
> cordially

Wouldn't it be easier to handle the threads outside of the library? You could use a thread pool and put each connection on its own thread. That way the library only manages the individual connection and the kernel handles the threading. I have a single program that I've had success connecting to upwards of 50 server at a time. However, I could have misunderstood what you asked.

**Comment by Rob-Hague** [comment]
The AuthenticationConnection semaphore has been removed in #1304

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
