### ISSUE TITLE
Session operation has timed out occurring after Windows update

### ISSUE THREAD

**Issue by PieterStoffelen** [sshnet/SSH.NET#265]
On two different sites we have an application checking the time of Linux servers using ssh.net. This is the code:

```
try
{
	SshClient ssh = new SshClient(ServerName, sUsername, sAppPassword);
	ssh.Connect();

	SshCommand sshCommand = ssh.CreateCommand("date");

	sResult = sshCommand.Execute();

	ssh.Disconnect();
}
catch (Exception ex)
{
	Console.Error.WriteLine("An error occurred in CheckServerTime while checking " + ServerName + ": " + ex.Message);
}

```

This worked fine on both sites until a few weeks ago. Then we suddenly got exceptions Session operation has timed out. So I changed the code with extended timeouts:

```
try
{
	SshClient ssh = new SshClient(ServerName, sUsername, sAppPassword);
	ssh.ConnectionInfo.Timeout = new TimeSpan(0,0,60);
	ssh.Connect();

	SshCommand sshCommand = ssh.CreateCommand("date");

	sshCommand.CommandTimeout = new TimeSpan(0, 0, 60);
	sResult = sshCommand.Execute();

	ssh.Disconnect();
}
catch (Exception ex)
{
	Console.Error.WriteLine("An error occurred in CheckServerTime while checking " + ServerName + ": " + ex.Message);
}

```

and now everything is running again, but dead slow. The servers do not cause the slowness, manually everything runs smooth. 

I think a recent Windows patch has caused this slowness. Code used is version 2016.1.0-beta1 from this site. This is the stacktrace of the exception:

```
An error occurred in CheckServerTime while checking Server134: Session operation has timed out
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at CheckServerTime.Program.CheckServerTime (String ServerName, String sUsername, String sAppPassword)

```
This timeout did not occur earlier on at both sites this code is running. Increasing the timeout to 60 seconds helps, but is a very bad fix.

Any help would be appreciated.

**Comment by IgorMilavec** [comment]
I this issue still relevant or can we close the issue?
