### ISSUE TITLE
Data longer than 2147483647 is not supported

### ISSUE THREAD

**Issue by thegalah** [sshnet/SSH.NET#269]
Getting this message

**Comment by drieseng** [comment]
What version of **SSH.NET** are you using?
Can you provide the full stacktrace?

**Comment by thegalah** [comment]
I'm using version 2016.0.0
I'm not sure exactly what's causing it, no exception is being thrown it is just being output to console ~2min 10 s after a tunnel is created

**Comment by drieseng** [comment]
Can you try using version **2016.1.0-beta2** (available through [NuGet](https://www.nuget.org/packages/SSH.NET/2016.1.0-beta2) and [GitHub](https://github.com/sshnet/SSH.NET/releases/tag/2016.1.0-beta2))?
This may be duplicate of #58.

**Comment by thegalah** [comment]
The beta versions seem to break I will need to check the breaking changes

**Comment by drieseng** [comment]
These are generally "harmless" breaking changes.

**Comment by drieseng** [comment]
@thegalah Any update on this? What "breaking changes" trouble you?

**Comment by dinehs** [comment]
Still I am getting this issues "Data longer than xxx is not supported".

What should I do?

Thanks,
