### ISSUE TITLE
x64 build is a lot slower than x86

### ISSUE THREAD

**Issue by xlixinxli** [sshnet/SSH.NET#271]
First of all, I'd like to thank you for the continued effort on improving the quality of this library. I synced to your latest changes in the developer branch and noticed a great performance gain in SFTP downloading speed comparing to the official Nuget release 2016.1.0. Great job on this! 

Then I noticed a huge performance difference between the 32-bit and 64-bit build. If I build my application in x64 then the downloading speed is nearly half of when I build in x86. I did a search and don't see any report on this issue. Could you share some light?

Thank you!

**Comment by drieseng** [comment]
What exact scenario are you testing?
Please share a minimal code fragment.
Are you building both x86 and x64 in release mode?

**Comment by xlixinxli** [comment]
I'm simply using a console program to test the SftpClient.DownloadFile() function. You'll see the code fragment below. I build AnyCPU in release mode of Renci.SshNet project and let my program point to the release dll. If I build my program in x86 then the download speed is 32 MB/s, in x64 then the speed is 17 MB/s. The result is the same if I build the release version of Renci.SshNet in x86 and x64 specifically.

    class Program
    {
        static void Main(string[] args)
        {
            using (var sftp = new SftpClient("hostname", 22, "username", "password"))
            {
                sftp.Connect();

                string remoteFileName = "remotefile.name";
                FileStream fs = new FileStream(Path.Combine("D:\\Download", remoteFileName), FileMode.Create);
                sftp.DownloadFile(remoteFileName, fs);
                fs.Close();
                fs.Dispose();

                sftp.Disconnect();
            }
        }
    }

**Comment by drieseng** [comment]
I get no noticable difference between x86 and x64.
For **2016.0.0**, I get around 40 MB/s (both x86 and x64), while for the **develop** branch I get about 57 MB/s (again both x86 and x64).

What size is the file you're downloading?

PS. You can safely remove the `Disconnect()`.

**Comment by xlixinxli** [comment]
Well, this is what I'm afraid of the most that we don't see the same thing. The file size I test is 245MB and I catch the time before and after the DownloadFile() call. 

x64
2016: time = 23.57s, speed = 10.39MB/s
Dev: time = 15.77s, speed = 15.53MB/s

x86
2016: time = 16.89s, speed = 14.50MB/s
Dev: time = 8.91s, speed = 27.48MB/s

I test with Bitvise SSH Server(https://www.bitvise.com/winsshd-download) using a virtual account on my PC but it's about the same if I download from a real network device. Apparently SSH.net doesn't have special treatment for 64 bit system. Then what could be causing this huge difference on my machine?

**Comment by xlixinxli** [comment]
OK, I just had an interesting discovery. The slow download speed of x64 build only occurs when I launch my test app in visual studio. If I launch the executable directly from the bin folder then it's as fast as 38 MB/s! It looks like VS is the culprit here. I still don't know why, though.

**Comment by drieseng** [comment]
OK, thanks for the update.
Don't hesitate to reopen this issue if you have more info.

**Comment by xlixinxli** [comment]
Sure and thanks for bearing with me on this. Just one last question. When will I be expecting a new release? The dev branch is indeed about twice as fast as 2016 Nuget package. And I believe the performance gain comes from the read ahead  optimization.

**Comment by drieseng** [comment]
I'm trying to get a new beta out this week (or even today).
There have also been optimizations in other areas as part of the 2016.1.0 release cycle.

**Comment by drieseng** [comment]
I just released 2016.1.0-beta2.
Have fun!
