### ISSUE TITLE
SftpClient.Connect throwing SshConnectionException

### ISSUE THREAD

**Issue by willwolfram18** [sshnet/SSH.NET#278]
I'm working with the Renci.SshNet library (v2016.0.0) in a C# application, which is scheduled to upload a file to an FTP server on a daily basis. When testing on my machine the code behaves as expected uploading the file to the SFTP server. However, after deploying to production we are seeing the following exception, even though the application is connecting to the same SFTP host address:

    System.AggregateException: One or more errors occurred. ---> Renci.SshNet.Common.SshConnectionException: Server response does not contain SSH protocol identification.
        at Renci.SshNet.Session.Connect()
        at Renci.SshNet.BaseClient.Connect()

The corresponding code that is throwing the exception is as follows:

    using (FileStream fileToUpload = new FileStream(exportFilePath, FileMode.Open))
	{
		using (var sftpClient = new SftpClient(SftpHost, 22, SftpUserName, new PrivateKeyFile(privateKeyFileName)))
		{
			sftpClient.ErrorOccurred += SftpErrorHandler;

			sftpClient.Connect(); // Line throwing the exception

			if (!sftpClient.IsConnected)
			{
				throw new InvalidOperationException($"An error occurred while connecting to the SFTP server {SftpHost}");
			}

			sftpClient.UploadFile(fileToUpload, fileName);
			sftpClient.Disconnect();
			sftpClient.ErrorOccurred -= SftpErrorHandler;
		}
	}

Does anyone have any suggestions on how to approach this issue? From my perspective, this seems to be a very nondescript error. I'm wondering if this is a firewall configuration on the machine running the application? Or perhaps it's a configuration issue on the SFTP server that the application is connecting to?

**Comment by darinkes** [comment]
Did you checked there is an ssh server on the remote side?
e.g.:
```
$ telnet host 22
Trying 1.2.3.4...
Connected to host.
Escape character is '^]'.
SSH-2.0-OpenSSH_7.5
```
(yeah! I have seen Admins configuring SFTP on Port 22, cause they mixed SFTP and FTPS)

According to:
https://github.com/sshnet/SSH.NET/blob/master/src/Renci.SshNet/Session.cs#L610
It might also be an Timeout, cause of slow connection | Firewall blocking | something else...

**Comment by willwolfram18** [comment]
TelNet from my machine returns `SSH-2.0-VShell_4_0_2_519 VShell`, so I think it is configured properly? But I will attempt to verify this from the server that is experiencing the error as well.

I don't think this is the result of a timeout/slow connection, since the [`SocketReadLine()`](https://github.com/sshnet/SSH.NET/blob/bc080e8c1ba2487728e208d6ab37be58191f0bbf/src/Renci.SshNet/Session.cs#L1756) method says it will throw an `SshOperationTimeoutException` if the read exceeds the provided timeout. I'm seeing an [`SshConnectionException`](https://github.com/sshnet/SSH.NET/blob/bc080e8c1ba2487728e208d6ab37be58191f0bbf/src/Renci.SshNet/Session.cs#L612) which is thrown after calling the `SocketReadLine()` method. Which makes me think it's some type of Firewall rule preventing the read of the SSH info?

**Comment by darkoperator** [comment]
Make sure the server supports SFTP with another client, had that happened to me with a bunch of CentOS minimal installs where SSH was there just that it needed another package to enable SFTP.

**Comment by darinkes** [comment]
Indeed, the version string looks fine.
IMHO a firewall should already block the TCP-Handshake, not just data on the connection.
Maybe the ssh server doesn't want to talk with your production server. Whitelist? Blacklist?
Don't know much about VShell.

**Comment by drieseng** [comment]
@Bwolfing Do you have an update for us?

**Comment by willwolfram18** [comment]
Based on feed back from everyone, it looks like it was some type of configuration issue within our staging environment. What specifically, I can't be sure as our Application Operation engineers handled the investigation and fix. But this was an issue external to SSH.Net, As such, I will close the issue.

**Comment by jlareo** [comment]
I also have the same problem in some machines. Changing from Release mode to Debug mode seems to solve the problem.

**Comment by SethRogers7420** [comment]
Just an FYI for anyone getting this in the future, check your FTP blacklist.
I just saw this happen on a server and it was caused by the application somehow being automatically blacklisted by our FTP software after running for over a year without a problem.
It's not the most helpful error message when that happens.

**Comment by Mintesnotg** [comment]
error on this 

The server response does not contain an SSH identification string.
The connection to the remote server was closed before any data was received.
