### ISSUE TITLE
Multiple IP addresses for a host leads to inconsistent behaviour

### ISSUE THREAD

**Issue by matthewvukomanovic** [sshnet/SSH.NET#28]
The existing host resolve will always take the first IPAddress which is returned.

We have the situation where the ip address needs to be a IPv4 address since the SFTP server is only bound to the 4 address, however the server also has a IPv6 address.

In some cases there may be times when there will be two addresses of the same type that also need to be decided against.

**Comment by olegkap** [comment]
Added ability to specify client ip. Its same as #130.

**Comment by IgorMilavec** [comment]
Issue #132 seems to provide more information, closing this one
