### ISSUE TITLE
Permission denied (password)

### ISSUE THREAD

**Issue by ijason** [sshnet/SSH.NET#282]
I'm getting Permission denied (password) when i try to connect.  I know the username and password are correct because I can log in via a web transfer client.  Any idea as to what is doing wrong?  Is it maybe a setting that isn't set correctly? 

`Using ftp = New Renci.SshNet.SftpClient("host", "username", "password")`
`            ftp.Connect()`
`End Using`

**Comment by darkoperator** [comment]
How is authentication setup on the SSH server? could be using Keboard-Interactive mode.

**Comment by drieseng** [comment]
What version of **SSH.NET** are you using?

**Comment by ijason** [comment]
Version 2016.0.0  
Let me find out about the authentication setup on the SSH server.

**Comment by ijason** [comment]
The issue was on our end and has been resolved.  Thanks for the responses.

**Comment by pd-xpediator** [comment]
Hi, I am facing same issue. How can I resolve it? I am using port 22, which is default. With Filezilla I am able to connect easily, but from code, it throws error 'Permission Denied(Password)'.
How to solve this?
Thanks in advance!
