### ISSUE TITLE
why the max sftp download rate is 4Mbs?

### ISSUE THREAD

**Issue by zou1003** [sshnet/SSH.NET#283]
using sftp download the max download rate is 4MB/s,when i user filezilla it is 10MB/s.

**Comment by drieseng** [comment]
Are you using `SftpClient.DownloadFile(...)` ?
If yes, try using **2016.1.0-beta2**.
Please provide feedback.

**Comment by zou1003** [comment]
I used SftpClient.ReadAllBytes. if not set BufferSize the speed is 2MB/s, when i set BufferSize >1024*64, the speed is 4MB/s. I had try 2016.1.0-beta2 too.

**Comment by drieseng** [comment]
If you really want to download a full file, then you should use `DownLoadFile(...)` with the latest beta as that will perform async read aheads.

I'll submit an issue to get some other methods in **SftpClient** use the same mechanism.

**Comment by drieseng** [comment]
I've submitted #284 to implement the read-ahead mechanism for other methods in **SftpClient**.

What SSH server are you using (name and version)?
In general, I do not recommend using a buffer size of more than 64 KB.

**Comment by zou1003** [comment]
I do not have the sever info, only konw it's a unix server.
I'm using this lib to build an application to modify files on the server,i don't want to save file to disk. modify files on memory and then upload to the server again.yesterday I find out the filezilla's speed is 10M/s, and my app. only 2M/s.

**Comment by zou1003** [comment]
yeah,using DownLoadFile(...) the speed is 10M/s.

**Comment by drieseng** [comment]
Why would you have to save the file to disk?
You can just use a **MemoryStream** with `DownloadFile(...)`.

**Comment by zou1003** [comment]
get it,thank you !

**Comment by drieseng** [comment]
No problem.
Let me know if I can close this issue.

**Comment by drieseng** [comment]
Don't hesitate to open a new issue if you have any further questions.
