### ISSUE TITLE
Remote files deleted after download

### ISSUE THREAD

**Issue by jonslo** [sshnet/SSH.NET#285]
When executing: 

`client.DownloadFile(fileName, new FileStream(destinationPath + "\\" + fileName, FileMode.Create));`

the remote file on the SFTP has been deleted.  Is this expected?

**Comment by jonslo** [comment]
Same occurs when my FileStream is disposed:

```
using (var fs = new FileStream(destinationPath + "\\" + fileName, FileMode.Create))
                {
                    client.DownloadFile(fileName, fs);
                }
```

**Comment by drieseng** [comment]
That is of course not the expected behavior.
This surely must be a bug in the SSH server software.
What SSH server (and version) are you using?
What version of **SSH.NET** are you using?

**Comment by jonslo** [comment]
Thanks for the quick reply...

NuGet - SSH.NET - v2016.0.0   

ClientVersion from debugger watch - "SSH-2.0-Renci.SshNet.SshClient.0.0.1"
ServerVersion from debugger watch - "SSH-2.0-SFTP Server"

**Comment by darkoperator** [comment]
This is so weird, I have not seen this behavior ever with SSH.NET

**Comment by jonslo** [comment]
looks like the remote server is running some cleanup script after a download has completed - not an SSH.NET issue.  Thanks again...
