### ISSUE TITLE
#<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.

### ISSUE THREAD

**Issue by ghost** [sshnet/SSH.NET#295]
This error appeared during vagrant up using vagrant-aws. Tried a number of Vagrantfile changes nothing solved the issue.

DEBUG ssh: == Net-SSH connection debug-level log END ==
 INFO ssh: SSH not up: #<Vagrant::Errors::NetSSHException: An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

**Comment by drieseng** [comment]
I doubt Vragent uses SSH.NET.
I found a similar issue [here](https://github.com/mitchellh/vagrant/issues/8136).
