### ISSUE TITLE
Server Host Key Validation

### ISSUE THREAD

**Issue by ghost** [sshnet/SSH.NET#296]
How do we use this library to validate the server's host key? Isn't this. . .you know, a thing with security?

**Comment by drieseng** [comment]
You'll now find an example [here](https://github.com/sshnet/SSH.NET/blob/develop/README.md).

I hope you'll be kinda ... you know, glad that I helped you out with this.

**Comment by InteXX** [comment]
@drieseng 

> I hope you'll be kinda ... you know, glad that I helped you out with this

Well, I sure am  :-)

I can't help but wonder, though...  isn't it a bit dangerous to send credentials across the wire before we've validated the target server?

Or maybe I'm misunderstanding. Maybe those credentials aren't sent at all. Maybe they're just stored locally in preparation for the `Connect()` method call.

Am I correct with the former or the latter? Or incorrect with both?

A dig through the source hasn't revealed it for me. I end up chasing rabbits down holes. Perhaps you might point it out, if you've got a moment?
