### ISSUE TITLE
Corrupted data with SftpClient.WriteAllBytes when byte array is "big"

### ISSUE THREAD

**Issue by zecodeur** [sshnet/SSH.NET#298]
Is it safe to call SftpClient.WriteAllBytes() with a byte array bigger than the buffer size?

I am able to repro issue by writing a "big" file with some pattern in it, and then immediately downloading it and checking things bytes for bytes. Things differ at byte #32695, which is suspiciously close to some internal buffer size i think.

I wonder if this is not similar to what was seen in https://github.com/sshnet/SSH.NET/issues/293

**Comment by drieseng** [comment]
This is probably a duplicate of #70.
This is fixed in **2016.1.0-beta1**.
What version of **SSH.NET** are you using?

**Comment by zecodeur** [comment]
I'm using version 2016.0.0 which appears to be the latest available on NuGet servers. So, indeed, it looks like I hit this same issue.

**Comment by drieseng** [comment]
**2016.0.0** is the latest stable release, but there are 2 newer pre-release versions available on the NuGet servers.

**Comment by drieseng** [comment]
Beta 4 of **SSH.NET** version **2016.1.0** is now available on [GitHub](https://github.com/sshnet/SSH.NET/releases/tag/2016.1.0-beta4) and via [NuGet](https://www.nuget.org/packages/SSH.NET/2016.1.0-beta4).

Reopen this issue if you can still reproduce the problem with beta 4.
