### ISSUE TITLE
RunCommand hangs when run agains a cisco SX20

### ISSUE THREAD

**Issue by greysun75** [sshnet/SSH.NET#307]
I am trying to use SSH.Net to run a command on a cisco SX20. I am able to connect to the endpoint but when it hits the RunCommand line the app freezes. I am able to use PuTTy to run the same command without issue. Any idea where I might be going wrong?

I have been at this for days trying different variations of code but they all seem to hang at the same place,  either on RunCommand or .Execute.  Here is what I currently have

`private void btnCheck_Click(object sender, EventArgs e)
    {
        var pass = Encoding.ASCII.GetBytes("mypassword");

        KeyboardInteractiveAuthenticationMethod kauth = new KeyboardInteractiveAuthenticationMethod("myuser");
        kauth.AuthenticationPrompt += new EventHandler<Renci.SshNet.Common.AuthenticationPromptEventArgs>(HandleKeyEvent);

        ConnectionInfo conInfo = new ConnectionInfo("myip", 22, "myuser", kauth);
        using (var client = new SshClient(conInfo))
        {
            try
            {
                client.Connect();
                if (client.IsConnected)
                {
                    SshCommand sshCommand = client.RunCommand("xStatus SystemUnit Uptime");
                    lblUptime.Text = sshCommand.Result;
                    client.Disconnect();
                }
            }
            catch (Exception error)
            {
                string Error = error.Message.ToString();
            }
        }
    }`

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
