### ISSUE TITLE
Sftp cancel download 

### ISSUE THREAD

**Issue by sergeushenecz** [sshnet/SSH.NET#309]
Hellow everyone.How can I cancel download current file?

**Comment by mjanulaitis** [comment]
I do not see any way to cancel an upload or download.  Is that still the case?

**Comment by zybexXL** [comment]
You can use the `BeginDownloadFile()` which returns an `SftpDownloadAsyncResult` object. This object has a property `IsDownloadCanceled` which you can set to true to cancel the download. `BeginUploadFile` works in a similar way.
