### ISSUE TITLE
mtime.sec not present

### ISSUE THREAD

**Issue by BenjaminReed** [sshnet/SSH.NET#310]
Whenever I am attempting to scp files, I always get the following error; "scp: protocol error: mtime.sec not present". Nothing I have seen online has solved this issue, any ideas? I know there is a connection established and that everything works directly up to this point. If there are any questions I can answer or screenshots to provide let me know. Thanks in advanced!

**Comment by drieseng** [comment]
As far I can know this is either because no shell is assigned to the user, or because scp is not allowed.
