### ISSUE TITLE
Getting ANSI escape code for SshCommand

### ISSUE THREAD

**Issue by MonRoyals** [sshnet/SSH.NET#314]
I need the ANSI escape codes from the response for colouring the ssh command output. Using a  ShellStream with xterm as terminal name I got the escape codes back from the SSH server. Using the SshCommand I didn't receive that additional information.

Is there any way to get the ANSI escape codes from the response (accessing the streams directly with a BinaryReader) or is it possible in a ShellStream to get the response code from a command send via the write method.

Thanks

**Comment by WojciechNagorski** [comment]
SSH.NET has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
