### ISSUE TITLE
Message type 80 is not valid

### ISSUE THREAD

**Issue by aldinei-sampaio** [sshnet/SSH.NET#32]
Hello. We are using version 2014.4.6.0 of SSH.NET and ocasionally we receive the error "Message type 80 is not valid". The code 80 really not seems to be a valid SFTP return code, but we are having throuble trying to figure out what may be causing the issue.

It occurs only occasionally, so its very dificult to reproduce it.

Any info that could point us to the right direction is appreciated.

**Comment by pver** [comment]
This looks related to https://github.com/sshnet/SSH.NET/issues/8 which should be fixed in the newest release (see https://github.com/sshnet/SSH.NET/releases/tag/2016.0.0-beta1 )

**Comment by aldinei-sampaio** [comment]
Thanks, we will try to upgrade.
