### ISSUE TITLE
Configure port

### ISSUE THREAD

**Issue by sewarts** [sshnet/SSH.NET#324]
I need to configure the SftpClient to use port 21 but, whilst this is an option in previous releases, cannot see how to do this in the latest version.

**Comment by drieseng** [comment]
You can for example use this ctor:

```cs
using (var client = new SftpClient("HOST", 21, "USER", "PWD"))
{
  client.Connect();
  ...
}
```

**Comment by drieseng** [comment]
Do you actually have code that compiled against an older version of **SSH.NET**, but not against **2016.1.0**?

**Comment by sewarts** [comment]
Thanks - this worked (can't see this in wiki though?)
using (var client = new SftpClient("HOST", 21, "USER", "PWD"))
{
  client.Connect();
  ...
}
