### ISSUE TITLE
Keep-alives are not activated if connection is already opened

### ISSUE THREAD

**Issue by gordonwatts** [sshnet/SSH.NET#334]
It looks to me like the following sequence of operations has a silent ignore in it:

1. Create a connection and open it
2. Set the KeepAliveInterval
3. Monitor for a keepalive.

It looks like you start the keep alive timer in BaseClient only when the connection is opened. And in that code you only create the timer if the user has requested a keepalive time. By default, that isn't the case. When you change the KeepAliveInterval, it notices there is no timer, and so does nothing. Hence, the timer isn't set.

**Comment by drieseng** [comment]
Fixed in **develop** branch, and in upcoming **2017.0.0-beta1** release.
Thanks for reporting the issue!

**Comment by gordonwatts** [comment]
Thanks!!!
