### ISSUE TITLE
outputstream() and extendedoutputstream() usability?

### ISSUE THREAD

**Issue by smarrocco** [sshnet/SSH.NET#347]
What is the difference between
Client.CreateCommand.OutputStream()
and
Client.CreateCommand.ExtendedOutputStream()

I'm trying to get the stdout and stderr by sending asynchronous ssh commands. The documentation suggests nothing, but online users suggest that ExtendedOutputStream() returns *both* stdout *and* stderr combined.

**Comment by drieseng** [comment]
in general stderr is sent via **SSH_MSG_CHANNEL_EXTENDED_DATA** messages, and as such ends up in **ExtendedOutputStream**.

**Comment by smarrocco** [comment]
I'm curious what is meant by "in general"?
Does Only stdout go to .OutputStream
and
Only stderr to to .ExtendedOutputStream?

or

Does .ExtendedOutputStream receive BOTH STDOUT and STDERR?

**Comment by Charles-Isaac** [comment]
> I'm curious what is meant by "in general"?
> Does Only stdout go to .OutputStream
> and
> Only stderr to to .ExtendedOutputStream?
> 
> or
> 
> Does .ExtendedOutputStream receive BOTH STDOUT and STDERR?

I just tried it and only stdout go to .OutputStream and only stderr go to .ExtendedOutputStream

**Comment by drieseng** [comment]
In general means "it depends on the SSH server". But most - if not all - implementation send stderr via **SSH_MSG_CHANNEL_EXTENDED_DATA** messages, and as such it ends up in **ExtendedOutputStream**.
