### ISSUE TITLE
Urgent - Cannot authenticate using private key when using SSH tunnel

### ISSUE THREAD

**Issue by zubingirglani** [sshnet/SSH.NET#348]
Hi,

I am trying to connect from Client X to Server Y via SFTP using a private key. My company requires me to go via an SSH Tunnel running on Server Z which requires authentication using a (different) private key.

How can I achieve this using SSH.NET? I have tried using ForwardedPortLocal but the authentication does seem to support key based authentication.

Thanks,

Zubin

**Comment by drieseng** [comment]
@zubingirglani confirmed via an offline conversation that this issue is resolved. The server required multi-factor authentication.
