### ISSUE TITLE
SshNet.Security.Cryptography assembly is missing from zip distribution

### ISSUE THREAD

**Issue by sneevand** [sshnet/SSH.NET#350]
Hi Guys,

I am using Renci.SshNet in [Lib net4.0] dll in SSIS script task; I installed the dll using gacutil; when  build  script task no errors; but when i run the package i got below error.

System.IO.FileLoadException:Could not load file or assembly 'SshNet.Security.Cryptography, Version=1.2.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4' or one of its dependencies. The system cannot find the file specified.":"SshNet.Security.Cryptography, Version=1.2.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4

any thoughts on how to use it in SSIS?

Regards,
Navin

**Comment by sneevand** [comment]
got it resolved; download src build and generate dll on your desktop; And add thee dll to windows assembly folder using gacutil -i "dll path"

**Comment by drieseng** [comment]
@sneevand Did you use the zip distribution? It may indeed be better to include the **SshNet.Security.Cryptography** assembly as well (where needed).

**Comment by Abhinavsingh993** [comment]
Hi I am facing the same issue but I don't know how to generate DLL file, could you please help me out?

**Comment by Abhinavsingh993** [comment]
I have included sshnet.security.cryptography explicitly, my application is working well when using as an console application but when I am installing renci and cryptography in GAC for my SSIS Application it's not working
