### ISSUE TITLE
Provide explicit ns2.0 binaries

### ISSUE THREAD

**Issue by damageboy** [sshnet/SSH.NET#357]
I understand this might sound like an odd request to say the least, but I'm encountering an extremely annoying issue when trying to restore my own project(s) which are dependent on both external ns1.x and ns2.0 nuget packages... (for example dapper + ssh.net).

Here are a couple of previous issues reporting similar errors with other nugets:
dotnet/core#907
dotnet/sdk#1792

Here's a sample repro repo from the last issue:
https://github.com/ogreenz/rid-netstandard2-repro

Basically, the gist of this is that nugets that require a ns1.x dependency while a ns2.0 dependency is also required are "forcing" a downgrade of the stdlib nugets like for example System.IO.FileSystem.Primitives

The only solution I could find is to forcefully request a version >= 4.3.0 in my OWN project or face the cryptic NU1605 warning which is treated by default as an error since sometime during the netcore 2.0.0 preview period...

It would be great if users are not forced to individually deal with this cryptic error by providing a ns2.0 binary as part of the official nugets.

**Comment by drieseng** [comment]
Pfew, time flies :(
This landed long time ago on the **develop** branch, but until now I haven't gotten around to pushing a new release.
I'm trying to pick up speed again (and putting other OSS work on hold).

**Comment by drieseng** [comment]
This will be part of the upcoming beta.
