### ISSUE TITLE
SSH.NET Connection with PrivateKey Error

### ISSUE THREAD

**Issue by rido111** [sshnet/SSH.NET#364]
Hi,

We want to connect SFTP Server with Private Key and PassPhrase file but we get an error like that:

**No suitable authentication method found to complete authentication (password,keyboard-interactive).**

Why this error occurs?

The code written is below;

       ConnectionInfo m_ConnectionInfo = new ConnectionInfo(m_FTPAddress, 22, m_FTPUserName,
            new AuthenticationMethod[]{
                // Key Based Authentication (using keys in OpenSSH Format)
                new PrivateKeyAuthenticationMethod(m_FTPUserName,new PrivateKeyFile[]{ 
                    new PrivateKeyFile(m_PrivateKeyFileName, m_PassPhrase)
                }),
            }
        );

            using (var sftp = new Renci.SshNet.SftpClient(m_ConnectionInfo))
            //using (var sftp = new Renci.SshNet.SftpClient(m_FTPAddress, m_FTPUserName, new PrivateKeyFile[] { new PrivateKeyFile(m_PrivateKeyFileName, m_PassPhrase) }))
            {
                sftp.Connect();
                using (var file = File.OpenRead(pLocalFilePath))
                {
                    sftp.UploadFile(file, "/" + pRemoteFilePath);
                }
                sftp.Disconnect();
            }

**Comment by drieseng** [comment]
The SSH server only accepts password or keyboard-interactive authentication, and you're providing publickey authentication.

Let me know if that resolved the issue for you.

**Comment by rido111** [comment]
Hi,

We checked SSH Server response by using WinFTP application. When we connect with username/password, the server refuses this connection and gives an error.  

![screenshot](https://user-images.githubusercontent.com/5902623/34380047-b9ffb368-eb0f-11e7-933a-3f939f502ca7.jpg)

So, i think that this result tells me that SSH Server only accepts **public key authentication**, is that right?
If it is right, why we get this error still?
Thanks.

**Comment by drieseng** [comment]
No, the SSH server may require multi-factor authentication. You may need to first authenticate using username/password (with either **password** or **keyboard-interactive** authentication), and subsequently authenticate using **publickey** authentication.

Check the **Multi-factor authentication** sample code [here](https://github.com/sshnet/SSH.NET/blob/develop/README.md).

**Comment by rido111** [comment]
Hi,

We did your advice and the error has changed. Errror changed like that:

**Renci.SshNet.Common.SftpPathNotFoundException: File not found**

Could you please tell me what is the problem for that?

Code:

            ConnectionInfo m_ConnectionInfo = new ConnectionInfo(m_FTPAddress, 22, m_FTPUserName,
            new AuthenticationMethod[]{
                new PasswordAuthenticationMethod(m_FTPUserName, m_FTPPassword),
                // Key Based Authentication (using keys in OpenSSH Format)
                new PrivateKeyAuthenticationMethod(m_FTPUserName,new PrivateKeyFile[]{ 
                    new PrivateKeyFile(m_PrivateKeyFileName, m_PassPhrase)
                }),
            }
        );
            using (var sftp = new Renci.SshNet.SftpClient(m_ConnectionInfo))
            //using (var sftp = new Renci.SshNet.SftpClient(m_FTPAddress, m_FTPUserName, new PrivateKeyFile[] { new PrivateKeyFile(m_PrivateKeyFileName, m_PassPhrase) }))
            {
                sftp.Connect();
                using (var file = File.OpenRead(pLocalFilePath))
                {
                    sftp.UploadFile(file, "/" + pRemoteFilePath);
                }
                sftp.Disconnect();
            }
        }

**Comment by drieseng** [comment]
Are you sure the remote (directory) path exists?
The error messages returned by the SSH server aren't always clear ("File not found" may mean that the directory does not exist).

**Comment by rido111** [comment]
ok, i will check that. But is this error telling us that we could connect with privatekey authentication?

**Comment by drieseng** [comment]
This error means that the connection was established, but the upload failed (because part of the remote path does not exist).

**Comment by rido111** [comment]
Up to now thanks for your all effort. 
If any case occurs, i will contact you again, thank you very much again.
