### ISSUE TITLE
Unable to switch off echo for root

### ISSUE THREAD

**Issue by senokosny** [sshnet/SSH.NET#366]
Hello,

There is an issue with echo management while using ShellStream.

To disable echoing I specify dictionary of terminal modes with values: (TerminalModes.ECHO, 0) in SshClient.CreateShellStream method.

But it works only for non-root accounts. For root accounts echo is always enabled (tested on RHEL 6), i.e.  DataReceived handler always get sent data.

Is there any way to make it right for root user? Or is it a bug?

 Code snippet:
```
ConnectionInfo connInfo = new ConnectionInfo("ip", 22, "root",
	new AuthenticationMethod[] {                    
	new PasswordAuthenticationMethod("root","root_pwd")});

using (var sshclient = new SshClient(connInfo))
{
	sshclient.Connect();

	IDictionary<TerminalModes, uint> dict = new Dictionary<TerminalModes, uint>();
	dict.Add(TerminalModes.ECHO, 0);
	using (ShellStream shell = sshclient.CreateShellStream("vt100", 80, 24, 800, 600, 1024, dict))
	{
		shell.Expect(new Regex(@"[$#>]"), TimeSpan.FromSeconds(60));                        
		shell.DataReceived += shell_DataReceived;                                             
		shell.WriteLine("whoami");
		Thread.Sleep(6000);                        
		shell.Close();
	}
	sshclient.Disconnect();
}

static void shell_DataReceived(object sender, Renci.SshNet.Common.ShellDataEventArgs e)
{            
	// this always writes sent data to console
	Console.Write(Encoding.UTF8.GetString(e.Data));
}
```

**Comment by DenisSa** [comment]
I'm experiencing the same issue on CentOS 6.7 minimal, however I don't think it's related to being a root account or not. It appears to be dependent on the shell that's running on the remote system. CentOS 8 provisioned in the same way, using root account works fine.
My approach will be to explicitly disable echo through a stty command, which appears to be working fine on both systems.

**Comment by WojciechNagorski** [comment]
SSH.NET has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
