### ISSUE TITLE
Failled Connect leaves threads in Socket.Select forever

### ISSUE THREAD

**Issue by gordonwatts** [sshnet/SSH.NET#371]
I've got some multi-threaded code that is exhibiting strange behavior, so I setup a stress test that basically uses SSH.NET to connect to a server and run the "ls" command. 100 simultaneous connections. As you might imagine, not all of them go through the first time. My basic approach is:

1. Setup connection
2. Call Connect() method
3. If Connect method throws, then wait a few 100 miliseconds, and go back to step 2.

First - is it ok to call connect twice if there has been a throw the first time? Or should I dispose of the whole connection and start from scratch?

It looks like, when this happens, a thread in Socket.Select is left behind, managed by the MessageListener method in SSH.NET's Connection class. I see this even after my code has reconnected, successfully run the "ls" command, disconnected, and I've forced a run of the GC and waited for all finalizers.

Here is the dump for one of these Socket.Select threads:

 	[Managed to Native Transition]		Annotated Frame
 	System.dll!System.Net.Sockets.Socket.Select(System.Collections.IList checkRead = Count = 1, System.Collections.IList checkWrite = null, System.Collections.IList checkError = null, int microSeconds)	Unknown	No symbols loaded.
 	Renci.SshNet.dll!Renci.SshNet.Session.MessageListener()	Unknown	No symbols loaded.
 	Renci.SshNet.dll!Renci.SshNet.Abstractions.ThreadAbstraction.ExecuteThread.AnonymousMethod__0(object o)	Unknown	No symbols loaded.
 	mscorlib.dll!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(object state)	Unknown	No symbols loaded.
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown	No symbols loaded.
	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown	No symbols loaded.
 	mscorlib.dll!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown	No symbols loaded.
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown	No symbols loaded.
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown	No symbols loaded.
 	[Native to Managed Transition]		Annotated Frame

While my actual production code will never make 100 connections at once, it is expected to run for a day and make numerous connections - enough that it isn't unlikely an error will happen. And I've seem many of these threads in some previous crashes. Now that I've chased them down, I suspect the aren't actually causing problems, other than consuming resources they should not be.

**Comment by gordonwatts** [comment]
After trying to put together some standalone code to prove this (which, really, I should have done before submitting this)... and I couldn't. Which lead to the discovery that I wasn't calling the Dispose method on connections properly when there was a connection from SSH.NET. :( Sorry!

**Comment by drieseng** [comment]
No problem. Glad you found the cause.
