### ISSUE TITLE
SshClient Connect

### ISSUE THREAD

**Issue by lucastvieira** [sshnet/SSH.NET#38]
Hello, 

I don't know if its issue or I'm doing something wrong, I starting using older versions of Ssh.net and everything work fine but when I update to the last version I can't connect at server.

`System.Net.Sockets.SocketException (0x80004005): Operation Not Supported
   em System.Net.Sockets.Socket.ConnectAsync(SocketAsyncEventArgs e)
   em Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   em Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   em Renci.SshNet.Session.Connect()
   em Renci.SshNet.BaseClient.Connect()`

Code is simple
`client = new SshClient("192.168.1.141", "user", "123456");
client.KeepAliveInterval = TimeSpan.FromSeconds(120);
client.ConnectionInfo.Timeout = TimeSpan.FromSeconds(150);
client.Connect();`

I can't find any solution over the web and I don't know what do to.

Anyone can help me?

Thanks!

**Comment by drieseng** [comment]
What version of .NET are you using, and on what type of device ?

**Comment by lucastvieira** [comment]
.NET 4.5 / Visual Studio 2012

Wha do you mean about device?

**Comment by drieseng** [comment]
I thought you might have been using Silverlight or Windows Phone.
I'll try to reproduce this issue tomorrow.
I'll reach out to you if I need more info.

**Comment by drieseng** [comment]
I failed to reproduce this issue (using .NET 4.0, .NET 4.5, .NET Core).
Did you use the 2016.0.0-beta2 nuget package ?
Try to provide as much info as possible, as this is the only issue blocking the next (final) beta.

**Comment by drieseng** [comment]
No further feedback.
