### ISSUE TITLE
Login to Cisco and Huawei's routers and switches.

### ISSUE THREAD

**Issue by ml8363** [sshnet/SSH.NET#393]
Landing Huawei's routers and switches，And record the process of operation and display，Ask who is the expert，Thank you very much。

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
