### ISSUE TITLE
netconf capability wrong

### ISSUE THREAD

**Issue by harveechen** [sshnet/SSH.NET#405]
The client advise the base 1.0, however the flag to decide whether data framing mechanism to use is depended on the server response. When base 1.1 is advise by the server, the netconf gets wrong, since the client only advises 1.0 but the flag sets to use data framing mechanism.

Suggest that: in  "NetConfSession.cs" add in line 44

`"<capability>" +
                                                            "urn:ietf:params:netconf:base:1.1" +
                                                        "</capability>" +`

**Comment by declspec** [comment]
Just ran into this as well, makes the whole `NetConfClient` unusable

EDIT: Side-note, this library is very difficult to work with; virtually everything useful is marked as `internal` so the chances of implementing any workarounds seems to be virtually zero. 

The entire `Subsytem` implementation is internal, the base `ISession` is internal, the `IServiceFactory` is internal. anything that's public seems extremely high-level and doesn't allow you to work with the underlying SSH session.

I thought I might be able to workaround it by modifying the `ClientCapabilities` XML before connecting, however the `INetConfSession` is only instantiated when calling `Connect()` and immediately uses them before you can change them.
