### ISSUE TITLE
Send client key exchange init first

### ISSUE THREAD

**Issue by lzwierko** [sshnet/SSH.NET#407]
In rare case, SSH server waits for client key exchange init before sending it's own message. On the other hand SSH.NET waits for server to send key exchange init before sending client key exchange init. Typical stalemate ending with connection establish timeout.
Not to brak existing functionality, an option needs to be added that allows to send client key exchange init message up-front, right after versions exchange.

**Comment by Rob-Hague** [comment]
Fixed by #1274
