### ISSUE TITLE
How to send Y or N using SshClient.CreateCommand?

### ISSUE THREAD

**Issue by neo0000** [sshnet/SSH.NET#410]
Hi, 

I would like to automate SSH, but I'm having a problem to send the syntax or command for (**Y or N**) if the previous command need a response input for example(**sudo apt-get install git**). This would return from the SSH console: 
"**Do you want to continue? [Y/n]**"

**What I've tried so far:**
CreateCommand("Y") = but it return: bash: Y: command not found
CreateCommand("y") = but it return: bash: y: command not found
CreateCommand("yes") = here I don't know what happened, it didn't give any response from outputstream for quite a while.

Here is the sample code what I have:
**variable ssh is SshClient**

using (var command = ssh.CreateCommand("sudo apt-get install git"))
                        {
                            Console.WriteLine("Output:");
                            var asyncExecute = command.BeginExecute();
                            using (var reader = new StreamReader(command.OutputStream, Encoding.UTF8, true, 1024))
                            {
                                while (!asyncExecute.IsCompleted || !reader.EndOfStream)
                                {
                                    string line = reader.ReadLine();
                                    if (line != null)
                                    {
                                        Console.WriteLine(line);
                                        if (line.ToLower().Contains("do you want to continue"))
                                        {
                                            var command2 = ssh.CreateCommand("y");
                                            var a2 = command2.BeginExecute();
                                            command2.ExtendedOutputStream.CopyTo(Console.OpenStandardOutput());
                                            command2.EndExecute(a2);
                                        }
                                    }
                                }
                            }
                        }

Thanks in advance.

**Comment by darkoperator** [comment]
You will need a shellstream since the execute method does not maintain state.

**Comment by ccreeves** [comment]
Use ssh.CreateCommand("yes | sudo apt-get install git")

https://en.wikipedia.org/wiki/Yes_%28Unix%29

**Comment by neo0000** [comment]
Hi @darkoperator , 

Yeah by using shellstream it just bypass or probably send as default(Y), thanks.

Hi @ccreeves  , 

I tried also your solution and it didn't give me the right output, but thanks anyway.
