### ISSUE TITLE
SCP File Upload hangs if SCP is unavailable

### ISSUE THREAD

**Issue by garrethjeremiah** [sshnet/SSH.NET#414]
I am using this via Posh-SSH and originally filed this as

https://github.com/darkoperator/Posh-SSH/issues/200

but this looks to be an issue with SSH.NET.

When scp is missing from the endpoint, no failure is detected and a hang occurs

**Comment by drieseng** [comment]
This has been fixed as part of #308, and will be available in the next beta.
