### ISSUE TITLE
Can this library be used to stream data to an ssh command

### ISSUE THREAD

**Issue by Mark-Pfeifer** [sshnet/SSH.NET#416]
I've started working with this library and have successfully executed simple commands on my ssh server.

What I'd like to do, but haven't found a way yet, is to send information my program over an ssh connection that serves as the input to the command executing on the host.

For example, one could send a .tar file as the input to a tar extraction command running on the host.  The Linux equivalent would be cat somefile.tar | ssh user@host tar xz -C /destination.

At this point, it doesn't look like any of your command execution allows input.  Please correct me if I've missed something.

**Comment by WalkerNA** [comment]
I don'to believe so.  The closest discussion was in PR #141 which has not been resolved.  I have yet to find a proper solution for this as well.

**Comment by Mark-Pfeifer** [comment]
Thanks for getting back to me.  Sorry to hear that there’s no support for streaming input.

Mark Pfeifer

**Comment by Rob-Hague** [comment]
Added in #1293 (version 2024.0.0)
