### ISSUE TITLE
Can I change the user after I'm connected with sftp client?

### ISSUE THREAD

**Issue by ddalic** [sshnet/SSH.NET#421]
I've successfully changed the user after connecting on ssh server with SshClient and trough ShellStream. 
Is there any way to do that with SftpClient?
Main problem is that I can't connect directly with root user, only to change user to root after connecting to server.

**Comment by drieseng** [comment]
No, this not possible using SFTP.

**Comment by mjanulaitis** [comment]
@drieseng do you know how to change the user to root after the connection is made?
