### ISSUE TITLE
We has can public _isDisposed?

### ISSUE THREAD

**Issue by VAllens** [sshnet/SSH.NET#424]
I want to get the `Dispose` state of the `SftpClient` instance outside.
This state allows me to decide when to reinitialize it.
Do you have any better advice?
Here's my sample code:
``` CSharp
private SftpClient _ftpClient;

private SftpClient FtpClient
{
	get
	{
		if (_ftpClient == null || IsDisposed)
		{
			_ftpClient = new SftpClient(Config.Host, Config.Port, Config.UserName, Config.Password);
		}

		return _ftpClient;
	}
}

public virtual bool IsConnected
{
	get
	{
		try
		{
			return FtpClient.IsConnected;
		}
		catch (Exception ex)
		{
			Log("FtpClient is disposed!", ex);
			return false;
		}
	}
}

public virtual bool IsDisposed
{
	get
	{
		try
		{
			return !FtpClient.IsConnected;
		}
		catch (Exception ex)
		{
			Log("FtpClient is disposed!", ex);
			return true;
		}
	}
}
```

**Comment by keithallenjackson** [comment]
See PL #458

**Comment by VAllens** [comment]
This is great, thank you.

**Comment by drieseng** [comment]
A SSH.NET client (SFTP, SSH, …) is only ever disposed when `Dispose()` is invoked by user code. I don't see why you'd need to have a `(Is)Disposed` property.

**Comment by keithallenjackson** [comment]
> drieseng commented 2 hours ago
> A SSH.NET client (SFTP, SSH, …) is only ever disposed when Dispose() is invoked by user code. I don't see why you'd need to have a (Is)Disposed property.

Actually, Dispose is also called when the channel closes abruptly. See my issue #453. This is one of the main issues PL #458 tries to address. This causes the ShellStream to Dispose without the user explicitly doing so.

I can continue to discuss ways forward to address this issue in the actual PL. I'm not hard-set on the current PL implementation and completely understand if it appears a bit 'hackish.' Let's make work and make it 'right' 😃

**Comment by IgorMilavec** [comment]
I have created a discussion #926 for all ShellStream related issues.

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
