### ISSUE TITLE
Connecting via a SOCK5 proxy throws an exception

### ISSUE THREAD

**Issue by sindizzy** [sshnet/SSH.NET#427]
Looking at this bug here https://github.com/sshnet/SSH.NET/pull/174 it says it was fixed and committed on Feb 16, 2017. Not sure how to read this but when I pull down the a clone of the package I still see the old code. How would I download a version with this fix?

AGP

**Comment by drieseng** [comment]
This is fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
