### ISSUE TITLE
Send cursor keys to shellstream

### ISSUE THREAD

**Issue by bigpjo** [sshnet/SSH.NET#433]
I am writing a web based terminal, everything is working fine with the exception of sending left/right/up/down cursor keys to shellstream.

Any pointers much appreciated

**Comment by darkoperator** [comment]
I have been trying to figure this also all week

**Comment by bigpjo** [comment]
Sorted it, send bytes 27, 91 then one of 68 (left) or 65 (up) or 39 (right) or 66 (down)

**Comment by darkoperator** [comment]
Do you have an example you can share?

**Comment by bigpjo** [comment]
A crude example but

var shellStream = sshClient.CreateShellStream("xterm",90,24,640,480,1024);
var leftCursor = new [] { (byte)27, (byte)91, (byte)68}; //:Left cursor
shellStream.Write(leftCursor,0,leftCursor.Length);
shellStream.Flush();

Tested on Ubuntu.
