### ISSUE TITLE
.Net Core 2.0 Support?

### ISSUE THREAD

**Issue by Dawandevo** [sshnet/SSH.NET#436]
When will the project get support for .net core 2.0?

currently the project is unusable with other up to date libraries.

**Comment by ScottRFrost** [comment]
Duplicate of #377 and #413

**Comment by drieseng** [comment]
.NET Core 2.0 is supported through our .NET Standard 2.0 assembly.
I'll be releasing a new beta for it soon.

**Comment by mrtylerzhou** [comment]
@drieseng any news on the beta with .Net Standard 2.0 support?

**Comment by krugertech** [comment]
> .NET Core 2.0 is supported through our .NET Standard 2.0 assembly.
> I'll be releasing a new beta for it soon.

Hi @drieseng 

Have you released the new beta yet ?

**Comment by Mgamerz** [comment]
I would much appreciate a new beta. I am using .net core 3 and this has many extra dependencies that are not present if using .net standard 2.
