### ISSUE TITLE
Channel_Closed in ShellStream

### ISSUE THREAD

**Issue by trebor-salim** [sshnet/SSH.NET#44]
Are you planning to add an event "Closed" in the class "ShellStream"?

Something like this:

public event EventHandler<EventArgs> Closed;

public override void Close()
{
    if (_channel != null)
        _channel.Close();
    base.Close();
}

private void Channel_Closed(object sender, ChannelEventArgs e)
{
    if (Closed != null)
    {
        //  Handle event on different thread
        ExecuteThread(() => Closed(this, new EventArgs()));
    }
}

instead of this:

private void Channel_Closed(object sender, ChannelEventArgs e)
{
    //  TODO:   Do we need to call dispose here ??
    Dispose();
}

**Comment by glenkleidon** [comment]
OK, I have done this work for my own project.

https://github.com/glenkleidon/SSH.NET/tree/bugfix/ShellStream_stopping_event_on_chanell_close  

It is pull request #1024
