### ISSUE TITLE
PipeStream not supporting Read offsets > 0

### ISSUE THREAD

**Issue by Noggog** [sshnet/SSH.NET#440]
PipeStream seems to throw an exception when Read(byte[] buffer, int offset, int count) is called, with an offset above zero. 
https://github.com/sshnet/SSH.NET/blob/master/src/Renci.SshNet/Common/PipeStream.cs#L183

Is there a reason it cannot support this?  Seems like it would be easy enough to modify the for loop to start at the desired offset, and still calculate the amount read properly.

If it's just something that hasn't been done yet, I can perhaps do the work, but I wanted to check first to see if there's some edge case that makes this feature N/A that I'm not seeing.

Thanks!

**Comment by KSebion** [comment]
I am wondering the same thing.
Ran into this exception while using System.IO.Pipelines.PipeReader.
Then rewrote my code to use the raw stream and encountered it again.

Thanks.
