### ISSUE TITLE
[.net core 2.1] SshClient.Disconnect() silently ending call stack?

### ISSUE THREAD

**Issue by 35359595** [sshnet/SSH.NET#446]
When Disconnect method is called no following code is beeng executed.

Two samples:
`using (var client = new SshClient(connectionInfo)){
    client.Connect();
    var result = client.RunCommand("ls").Result;
                return Ok(result); //this never executes/returns
            }`

`var client = new SshClient(connectionInfo);
                client.Connect();
                var result = client.RunCommand("ls").Result;
                client.Disconnect();
                return Ok(result);//this never executes/returns`

This runs just fine:
`client.Connect();
                var result = client.RunCommand("ls").Result;
                return Ok(result);//returns as expected`

**Comment by cravall** [comment]
Duplicate of #355

**Comment by drieseng** [comment]
@35359595 On what OS are you seeing this issue, and with which version of **SSH.NET**?

**Comment by drieseng** [comment]
Reopen this issue if you can reproduce it on Windows.
If you encounter this issue on Linux, then it's indeed a duplicate of #355.

**Comment by 35359595** [comment]
@drieseng MacOS HS. Latest version from NuGet (2016.1.0). Cant confirm on Mojave as update killed my VPN =)

**Comment by drieseng** [comment]
This is fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
