### ISSUE TITLE
Logging Support

### ISSUE THREAD

**Issue by MrAdam** [sshnet/SSH.NET#449]
Is there any plans to add propert logging support to this library?
It looks like the trace logging is only being used in development, and there is no way to hook in and log requests/responses in production.

**Comment by drieseng** [comment]
This is something I'd love to get to.
Requirements:
* Minimal runtime overhead when logging is disabled
* Do not force users to use a specific logging framework

**Comment by PerfectlyNormal** [comment]
LibLog (https://github.com/damianh/LibLog) should be what you need. I too would like to get this added. I'm not familiar with the code base, but I could give it a go if you don't have the time

**Comment by kemmis** [comment]
I'd love to have some logging as well. Just log to the now standard [ILogger ](https://www.nuget.org/packages/Microsoft.Extensions.Logging.Abstractions)abstraction. From there devs can direct logging to their desired sink/framework.

@drieseng are you taking contributions?
