### ISSUE TITLE
Permission denied (password)

### ISSUE THREAD

**Issue by ImJustAnotherUser** [sshnet/SSH.NET#450]
Hi,
i have create a simple program to connect to an SFTP server:

```
using (SftpClient sftp = new SftpClient(host, userName, password))
            {
                try
                {
                    sftp.Connect();
                    Console.WriteLine("Connected");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"{ex.Message} {ex.StackTrace}");
                }
                finally
                {
                    sftp.Disconnect();
                    Console.WriteLine("Disconnected");
                }
            }
```

Actually the program is throwing the following error:
```
Permission denied (password).    in Renci.SshNet.ClientAuthentication.Authenticate(IConnectionInfoInternal connectionInfo, ISession session)
   in Renci.SshNet.ConnectionInfo.Authenticate(ISession session, IServiceFactory serviceFactory)
   in Renci.SshNet.Session.Connect()
   in Renci.SshNet.BaseClient.Connect()
```

With the same credentials that i'm using in the program i can easy connect with FileZilla.
I need help for understand why i can easy connect with FileZilla but there is an authentication problem using Renci.SshNet.SshNet.
Tnx

**Comment by drieseng** [comment]
I see no reason why it would work with FileZilla, and not with SSH.NET.
What version of SSH.NET are you using?

**Comment by ImJustAnotherUser** [comment]
Sorry was a my mistake, i was using the standard SFTP port but the server requires a custom port.
Can close and delete this issue.
Tnx for the fast answer btw.

**Comment by pd-xpediator** [comment]
Hi, I am facing same issue. How can I resolve it? I am using port 22, which is default. With Filezilla I am able to connect easily, but from code, it throws error 'Permission Denied(Password)'. 
How to solve this?

**Comment by SaebAmini** [comment]
This one was doing my head in. It turned out some servers do not support `PasswordAuthenticationMethod`, so you'll have to use `KeyboardInteractiveAuthenticationMethod`, and then handle the `AuthenticationPrompt` event to provide the password:

```C#
var authMethod = new KeyboardInteractiveAuthenticationMethod("Username");
authMethod.AuthenticationPrompt += (sender, e) =>
{
    e.Prompts.Single().Response = "Password";
};
var connectionInfo = new ConnectionInfo("host", 22, "Username", authMethod);

using (var client = new SftpClient(connectionInfo))
{
    client.Connect();
    // ...
}
```

**Comment by salmankaludi** [comment]
> Hi, I am facing same issue. How can I resolve it? I am using port 22, which is default. With Filezilla I am able to connect easily, but from code, it throws error 'Permission Denied(Password)'.
> How to solve this?

Have you found any solution?

**Comment by darkoperator** [comment]
Anything on the server side logs? Is the SSH server configured for keyboard interactive login?

**Comment by salmankaludi** [comment]
No, I am just trying to connect with below code
 **var client = new SshClient(Host, UserName,Password);
client.Connect();**

And it throw me permission denied (password) exception.

I am able to connect through terminal.

**Comment by darkoperator** [comment]
Could be the server requires keyboard interactive, that is handled in the library via a event. The permission denied message is from the server message it sends back

**Comment by salmankaludi** [comment]
If I have use "KeyboardInteractiveAuthenticationMethod" then the exception is  "**permission denied (KeyboardInteractive)**"

**Comment by pd-xpediator** [comment]
D

> Hi, I am facing same issue. How can I resolve it? I am using port 22, which is default. With Filezilla I am able to connect easily, but from code, it throws error 'Permission Denied(Password)'.
> How to solve this?
> 
> Have you found any solution?

Hi, check if your password contains any special characters? If yes, you need to escape them. In my case, it was the accessibility issue. They did not provided access to the IPs. So it was not working. Can you check if you can connect to SFTP with WinSCP? [https://winscp.net/eng/download.php](https://winscp.net/eng/download.php)

**Comment by pd-xpediator** [comment]
> No, I am just trying to connect with below code
> var client = new SshClient(Host, UserName,Password);
> client.Connect();
> And it throw me permission denied (password) exception.
> I am able to connect through terminal.
Can you try another constructor which takes port also as a parameter?
SftpClient(string host, int port, string username, string password);

**Comment by salmankaludi** [comment]
When I tried to connect through terminal then it is working.

**Comment by ValalSidur** [comment]
This error ocurried when in the FTP Server doesn´t configured the correct form
