### ISSUE TITLE
Create a background thread using the & command

### ISSUE THREAD

**Issue by sdlmw** [sshnet/SSH.NET#452]
Hi developer，

I meet a problem.   When I need to use the & command to run the foreground thread in the background. The thread terminates as the disconnect () or Dispose () command runs. So, do you have the right way to help me solve this problem?

thanks

**Comment by keithallenjackson** [comment]
Please paste some of your code or a code snippet that reproduces your issue. Are you using SshClient.SendCommand? Or are you creating a ShellStream?

**Comment by sdlmw** [comment]
Hello  @keithallenjackson 

I created a ShellStream.

             ```
                PipeStream input = new PipeStream();
                var streamWriter = new StreamWriter(input) { AutoFlush = true };

                var output = new MemoryStream();
                var exOtput = new MemoryStream();
                Shell shell = SSH.CreateShell(input, output, exOtput);
                shell.Start(); 

                streamWriter.WriteLine(command);
                while(true)
                {
                     ......
                }
```

**Comment by keithallenjackson** [comment]
In your code snippet, you are creating a Shell and not a ShellStream. The shell will run your code in the input stream and pull output from output stream without waiting for the prompt to continue. 

in order to do what you want, look into ShellStream in order to write commands and then expect output.

**Comment by sdlmw** [comment]
HI @keithallenjackson 

‘ ShellStream shellStream = SSH.CreateShellStream("dumb" + random.Next(5000), 80, 24, 800, 600, 2048);
                var reader = new StreamReader(shellStream);
                Thread.Sleep(2000);
                reader.ReadToEnd();
                
                // create screen
                shellStream.WriteLine(command);
                shellStream.ReadLine(new TimeSpan(0, 0, 30));
                Thread.Sleep(10000);
                StringBuilder strBuild = new StringBuilder();
                while (true)
                {
                    ProgressValue = reader.ReadLine();
                    if (!string.IsNullOrWhiteSpace(ProgressValue))
                    {
                        if (Regex.IsMatch(ProgressValue, port.ToString(), RegexOptions.IgnoreCase))
                        {
                            break;
                        }
                        strBuild.AppendLine(ProgressValue);
                    }
                }
               // shellStream.Close();
’
I've tried this function CreateShellStream , too.  But I executed this command（shellStream.Close()）, and the task process will be killed.  The command I execute is an API written in the LUA language. This command has to be hold.

SSH.CreateShell(input, output, exOtput); The same will be done by the command（SSH.Disconnect()） to be closed.

Do you have a suitable solution?

Thanks

**Comment by keithallenjackson** [comment]
If what I am understanding, you want to:
- Create Shell/ShellStream
- SendCommand that create background work using the '&' symbol (like Linux)
- while the background work is being accomplished, close the session/connection with the intention of the background work continuing

is that right?

**Comment by sdlmw** [comment]
@keithallenjackson 

Yes， You are right.

**Comment by sdlmw** [comment]
@keithallenjackson 

ok， I'm going to try this way. Thanks

**Comment by keithallenjackson** [comment]
There are other alternatives to cron that have the same type of behavior. here is another
[https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session](https://askubuntu.com/questions/8653/how-to-keep-processes-running-after-ending-ssh-session)

**Comment by sdlmw** [comment]
Hello @keithallenjackson 

Sorry， The link unavailable

**Comment by keithallenjackson** [comment]
@sdlmw 
Fixed. The link was set to nothing, but the text was correct.
