### ISSUE TITLE
Feature Req: Add 25519 for Keys/Exchange etc

### ISSUE THREAD

**Issue by Kim-SSi** [sshnet/SSH.NET#455]
This is a placeholder for looking into adding support for EC 25519 support into the library.

The most useful code I have found is a C# library that is in the Public Domain.
https://github.com/CodesInChaos/Chaos.NaCl

It looks like it should be reasonably straight forward to add this. I have only done a preliminary test. I don't have any working code yet.

**Comment by Rondom** [comment]
See also issue #20.

**Comment by drieseng** [comment]
@darinkes' changes have landed in the **develop** branch, and will be part of the next release.
