### ISSUE TITLE
Disposing a ShellStream instance shouldn't disconnect the SshClient instance which created it

### ISSUE THREAD

**Issue by ahelwer** [sshnet/SSH.NET#459]
```
using (SshClient ssh = new SshClient(address, username, password) {
    ssh.Connect()
    using (ShellStream shell = ssh.CreateShellStream("xterm", 80, 80, 80, 80, 1024)) {
        // Do stuff
    }

    // I expect to be able to use the SshClient instance here but in fact it is disconnected
}
```

**Comment by keithallenjackson** [comment]
@ahelwer Looking at ShellStream.Dispose, there is no code that actually calls a disconnect. Are you sure it is not the end-device closing the connection? ShellStream creates a Channel that sends the ShellStream data back and forth. During the ShellStream Dispose, the Channel is closed (not the full SshClient).

**Comment by ahelwer** [comment]
@keithallenjackson you are correct, this only happens on some devices and not others. For example, I can confirm it occurs on the Cisco 4431 router running IOS-XE v16, but not the Cisco Nexus 3064 running NXOS v6.

**Comment by ahelwer** [comment]
Actually, it's even worse - I have to reconnect the SshClient instance after every single command execution (or shell instance closure) on the Cisco 4431!

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
