### ISSUE TITLE
Proxy through socks5

### ISSUE THREAD

**Issue by r-matias** [sshnet/SSH.NET#46]
Hello,

After connection with SSH.NET, i can pass all packages from any .exe (ex: chrome.exe, csgo.exe etc) through proxy socks5? Or any have a idea how make this? (Something equal Proxifier)

Sorry for bad english.

Thanks a lot.

**Comment by drieseng** [comment]
Something like this ought to do it:

``` cs
            using (var client = new SshClient("myserver", 22, "user", "pwd"))
            {
                client.Connect();

                var forwardedPort = new ForwardedPortDynamic(1080);
                client.AddForwardedPort(forwardedPort);
                forwardedPort.Start();
            }
```

**Comment by drieseng** [comment]
@soarde: Did that work out for you? Let me know if I can close this issue.

**Comment by drieseng** [comment]
Closing due to lack of feedback.
