### ISSUE TITLE
Failed to negotiate key exchange algorithm

### ISSUE THREAD

**Issue by AtosNicoS** [sshnet/SSH.NET#461]
Hi, I am using 2016.1.0 (from nuget) and I am trying to connect to a TeltonikaRUT955 Modem via SSH. I just updated the firmware to a newer version which has "Improved SSH security" in its changelog. I can no longer login via SSH.NET, only via Putty.

It seems that SSH.NET does not support newer cipher algorithms. Do you know more about this?
Putty logs the following:
```
2018-08-27 12:59:28	We claim version: SSH-2.0-PuTTY_Release_0.70
[...]
2018-08-27 12:59:28	Doing ECDH key exchange with curve Curve25519 and hash SHA-256
[...]
2018-08-27 12:59:30	Initialised AES-256 SDCTR client->server encryption
2018-08-27 12:59:30	Initialised HMAC-SHA-256 client->server MAC algorithm
2018-08-27 12:59:30	Initialised AES-256 SDCTR server->client encryption
2018-08-27 12:59:30	Initialised HMAC-SHA-256 server->client MAC algorithm
[...]
```

The router uses `Dropbear v2018.76` as ssh client.

Downgrading the firmware is not an option in case of the SSH and overall system security.

**Comment by darkoperator** [comment]
That cipher is not supported by the library, I to have ran in to issues do to it :(

**Comment by kv9y** [comment]
Is there any update on this?  We needed to upgrade some hardware and it only supports the following algorithms:  aes128-ctr; aes192-ctr; and aes256-ctr.  If I can't get SSH.NET to work, I will likely need to move to a different SSH lib.  I just don't have the time to fork this project and implement these ciphers.

**Comment by A20oz** [comment]
https://github.com/sshnet/SSH.NET/issues/461#issue-354278405

**Comment by drieseng** [comment]
In the **develop** branch, we now support **curve25519-sha256** and 
**curve25519-sha256<span></span>@libssh.org**.
