### ISSUE TITLE
Support new openssh format

### ISSUE THREAD

**Issue by Pectojin** [sshnet/SSH.NET#465]
[Duplicati](https://www.duplicati.com/) relies on this superb library but some of our users have started seeing issues with a new RSA keyfile format in `openssh client 7.8p1-1` and newer (starting to show up in Arch derivatives). 

It appears the format has changed entirely causing the library to fail when parsing.

A key generated with `ssh-keygen` will have the new look
```
-----BEGIN OPENSSH PRIVATE KEY-----  
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAA...  
-----END OPENSSH PRIVATE KEY-----
``` 
Which will cause the error 
```
Key 'OPENSSH' is not supported
```

It has turned out to not just be cosmetic i.e. changing "OPENSSH" to "RSA" just brings up the next error:
```
Invalid data type, INTEGER(02) is expected
```
For reference, we're tracking the issue here https://github.com/duplicati/duplicati/issues/3360

**Comment by Rondom** [comment]
The new format is the default in OpenSSH 7.8
https://www.openssh.com/releasenotes.html

> * ssh-keygen(1): write OpenSSH format private keys by default
>   instead of using OpenSSL's PEM format. The OpenSSH format,
>   supported in OpenSSH releases since 2014 and described in the
>   PROTOCOL.key file in the source distribution, offers substantially
>   better protection against offline password guessing and supports
>   key comments in private keys. If necessary, it is possible to write
>   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
>   when generating or updating a key.

**Comment by drieseng** [comment]
Support for OpenSSH private keys has landed in the *develop* branch, and will be part of the next release.
