### ISSUE TITLE
SSH.net Cisco Router Initial connection failed

### ISSUE THREAD

**Issue by nabamb** [sshnet/SSH.NET#469]
I am hobbyist programmer. I am getting error using Renci.SshNet. It gives me following error at statement sshclient.Connect();

    System.Net.Sockets.SocketException:'The attempted operation is not supported for the type of object referenced'

My code is

private void Rstbutton_Click(object sender, RoutedEventArgs e)
{
    s_ipaddr = IPAddr.Text;

    s_username = UsernameBox.Text;
    s_password = PassBox.Password.ToString();
    SecureString myPass = PassBox.SecurePassword;

    using (var sshclient = new SshClient(s_ipaddr, s_username, s_password)) 
    {
        sshclient.Connect();
    }
}

I am using Renci.SshNet.dll directly in the reference no installation from Nuget.

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
