### ISSUE TITLE
Could we have a .NET Core 2.1 version of this release?

### ISSUE THREAD

**Issue by rajwilkhu** [sshnet/SSH.NET#474]
Is anyone working on this? If now, I could create a PR.

**Comment by WhiteKarma** [comment]
Yes, we are interested too, it would be amazing to have a .NET Core 2.1 or 2.2 version!!!
very cool!!!

**Comment by Tom-Dunstan** [comment]
Perhaps I'm confused about what you're asking for, but I seems to target both .Net standard 1.3 and 2.0. Both of which can be used with .Net Core 2.1 and above

**Comment by drieseng** [comment]
We have .NET Standard 2.0 support in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
