### ISSUE TITLE
Building SSH.NET on .net core & Linux

### ISSUE THREAD

**Issue by Weboholics** [sshnet/SSH.NET#48]
We are using the develop branch of your code.
We are using SSH.NET in a command line application.  It works fine on windows but when we build it on linux with .net core we get this error message:
SSH.NET-develop/src/Renci.SshNet.NETCore/error CS0041: Unexpected error writing debug information -- 'Windows PDB writer is not available                -- could not find Microsoft.DiaSymReader.Native.amd64.dll'

**Comment by drieseng** [comment]
I'll see if I can get this to work tomorrow.
