### ISSUE TITLE
System.NotSupportedException: Key 'OPENSSH' is not supported.

### ISSUE THREAD

**Issue by mauroa** [sshnet/SSH.NET#485]
A NotSupportedException is thrown when generating SSH keys with the "ssh-keygen" command on a Mac with macOS Mojave 10.14.1. With lower versions it's working fine.

Exception:

System.NotSupportedException: Key 'OPENSSH' is not supported.
   at Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, String passPhrase)
   at Renci.SshNet.PrivateKeyFile..ctor(String fileName, String passPhrase)

Inspecting the generated private key I can see that the header starts with:

"-----BEGIN OPENSSH PRIVATE KEY-----"

Also, If I inspect a private key generated in a Mac with a lower macOS version, I can see something like:

"-----BEGIN RSA PRIVATE KEY-----"

The following code in this repo tries to match a Regex to detect they key name and act based on it. For this reason, It doesn't recognize "OPENSSH" as a valid private key name and it fails:

https://github.com/sshnet/SSH.NET/blob/bd01d971790a7c1fa73bad35b79ada90bf69e62d/src/Renci.SshNet/PrivateKeyFile.cs#L190-L273

Thanks.

**Comment by darinkes** [comment]
Please see https://github.com/sshnet/SSH.NET/pull/496, which adds OPENSSH-Format for ed25519 Keys.
What kind of key you used? Can't find on a quick search what MacOS ssh-keygen generates by default.

The usual default is: `If invoked without any arguments, ssh-keygen will generate an RSA key.`
(https://man.openbsd.org/ssh-keygen)

**Comment by darinkes** [comment]
Ah! I see now. Yeah, the default format was changed. Will see if my PR can be updated to support more than just ed25519 Keys.

**Comment by drieseng** [comment]
@darinkes Please submit a separate PR for this.

**Comment by darinkes** [comment]
@drieseng sure! first finish the big one.

@mauroa If you want to give it a shot: https://github.com/darinkes/SSH.NET-1/tree/openssh_format_rsa

**Comment by gojimmypi** [comment]
@darinkes - cool you are working on openssh; wondering about the status of your changes? will it include Message Authentication Code (HMAC)? perhaps I can help?

**Comment by darinkes** [comment]
@gojimmypi I'm waiting for upstream to catch up with current PRs, before creating new ones.

**Comment by ssougnez** [comment]
Is there any advancement on this one ? 
I really need to be able to connect through SFTP via OpenSSH key :-)

**Comment by nukadelic** [comment]
Same here, failed to support generated ssh via `ssh-keygen -t rsa` 

Edit: Using puttygen and exporting under different format fixed my issue, here is a neat article:
https://lluisfranco.com/2017/11/29/how-to-connect-via-sftp-using-ssh-net/

**Comment by watsonsong** [comment]
The same problem. Is there any plan to support OPENSSH keyname?

**Comment by darinkes** [comment]
> The same problem. Is there any plan to support OPENSSH keyname?

Yes, the diff is ready for an PR. But @drieseng is currently busy with other projects.
You can check out and test the diff from here: https://github.com/sshnet/SSH.NET/issues/485#issuecomment-462634112

**Comment by drieseng** [comment]
@darinkes Please submit a PR for this. If you make sure there's sufficient test coverage, I'll do my best to review it :p

**Comment by drieseng** [comment]
@darinkes ... and thx!

**Comment by darinkes** [comment]
@drieseng The diff is based on the Elliptic Curves Branch, cause OPENSSH format was needed there already partially.

**Comment by michael-andreev** [comment]
Having the same problem. Could you tell the current status of this issue?

**Comment by yhjhoo** [comment]
for me, this lib works in mac but no in windows 2012R2

**Comment by gojimmypi** [comment]
fwiw I ended up using [SSH.NET](https://github.com/sshnet/SSH.NET)

**Comment by drieseng** [comment]
This is now supported in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).

**Comment by agirardg2** [comment]
> This is now supported in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).

Is there any planned date for a stable Release soon ?

**Comment by aibars** [comment]
I added 2020.0.0-beta1 but now the error is `openssh key type: ssh-rsa is not supported`

**Comment by Arhisan** [comment]
the same for me `Renci.SshNet.Common.SshException: openssh key type: ssh-rsa is not supported`

**Comment by darkoperator** [comment]
The new OpenSSH RSA key format is not supported by the library

**Comment by ramondeklein** [comment]
Same here... The new-style OpenSSH key format is not supported. This issue is closed, but it should be open.

@darinkes I saw your fork from 31-1-2021. Does it support the new key format and will you create a PR for this library?

**Comment by darinkes** [comment]
@ramondeklein already there https://github.com/sshnet/SSH.NET/pull/614

**Comment by h0wXD** [comment]
@ramondeklein Have you tried checking out develop, building it locally, and adding the netstandard2.0 dll as reference to your project? This works for me. I am getting the same error "Renci.SshNet.Common.SshException: 'openssh key type: ssh-rsa is not supported'" when using the latest nuget package 2020.0.1.

**Comment by jkmyklebust** [comment]
I'm also having this problem (nuget package 2020.0.1).

**Comment by ghost** [comment]
I'm also having this problem (nuget package 2020.0.1).

Key generated via `ssh-keygen -t rsa`

**Comment by stevenxi** [comment]
hi @h0wXD , @jkmyklebust ,

I've got the same error, but found the quick solution.

Just need to convert the key's format from --OPENSSH to --RSA:

ssh-keygen -p -P "" -N "" -m pem -f \path\to\key\file

This will convert your current key.

**Comment by Mansimar30** [comment]
Hey, I am getting the same  issue : Renci.SshNet.Common.SshException: openssh key type: ssh-rsa is not supported.

Here's how key was generated : ssh-keygen -t rsa -b 4096

Did anybody resolve it?

**Comment by stevenxi** [comment]
@Mansimar30 ,

Please see my reply above, use ssh-keygen to convert your key.

**Comment by dbrennand** [comment]
Hi all, I hit this issue when using POSH-SSH. Documented in issue: https://github.com/darkoperator/Posh-SSH/issues/388

I worked around this issue by creating my SSH key with the `-m PEM` option.

Example: `ssh-keygen -f ~/.ssh/id_rsa -m PEM -t rsa`
