### ISSUE TITLE
Renci.SshNet.snk gets identified as Malware

### ISSUE THREAD

**Issue by darinkes** [sshnet/SSH.NET#490]
During building Renci.SshNet.Tests-Project Windows Defender pops up and warns me about:
"Malware detected: -Ramson:MSIL/Hasdcrypt.A".

In Visual Studio 2017 I get an error telling me that an error occured during signing and the process was canceled cause the file may contain a Virus or unwanted software.

I suspect it's an false-positive.

Current workaround is to disable Real-Time-Protection if I want to build the Project.

**Comment by catfood** [comment]
Still happening in latest repo, commit e449130.

**Comment by darkoperator** [comment]
I would say it is a FP, did you open a ticket with the AV vendor?

**Comment by drieseng** [comment]
This is out of our hands.
