### ISSUE TITLE
Getting below error when loading file on ftp server

### ISSUE THREAD

**Issue by ghost** [sshnet/SSH.NET#491]
Getting below error when loading file on ftp server 

An established connection was aborted by the software in your host machine.

And seems this error related to key exchange algorithm in library so would like to know which algorithm this library using default.

**Comment by drieseng** [comment]
@ghost You should check the server log to find out why the connection was aborted.
There's no default KEX algorithm in SSH.NET. You can find the list of supported algorithms [here](https://github.com/sshnet/SSH.NET/blob/develop/README.md)
