### ISSUE TITLE
Failed to negotiate key exchange algorithm

### ISSUE THREAD

**Issue by sartosim** [sshnet/SSH.NET#499]
I have an issue connecting to an FTP server using SftpClient ("SSH.NET" version="2016.1.0") the issue is raised when connect method is invoked. Let me know if you need further info.

**Comment by darkoperator** [comment]
FTP? The library is for SSH and SFTP under SSH. Is it for SSH? Subject say key negotiation failure so I assume it is for one :) if it is key negotiation what algorithm is ser for the server key? I know this library does not work with the latest elliptical curve algorithms that some system generate by default

**Comment by sartosim** [comment]
It's for SFTP I'm using the SftpClient object. The server looks updated with a new certificate 
Public key algorithm: RSA with 2048 bits
Signature algorithm: RSA-SHA256
Protocol: TLS 1.2
Key exchange: ECDHE-RSA
Cipher: AES-256-GCM
MAC: AEAD

**Comment by darinkes** [comment]
> Protocol: TLS 1.2

This reads like FTPS (FTP over SSL). This Library is for SFTP.
