### ISSUE TITLE
Strange issue with password (denied)

### ISSUE THREAD

**Issue by SrgjanX** [sshnet/SSH.NET#502]
The thing is I have a production server for work, for private use, and multiple private computers.
Ive made a really simple test connection app:

`private static void Main(string[] args)
        {
            connect();
            Console.ReadKey();
        }

        private static void connect()
        {
            try
            {
                log("Connecting");
                using (SftpClient sftp = new SftpClient("someserver", 22, "root", "pas*"))
                {
                    sftp.Connect();
                }
                log("Connected");
            }
            catch (Exception ex)
            {
                log(ex.Message + ((ex.InnerException == null) ? "" : ex.InnerException.Message));
            }
        }`

And this thing works on every machine except the production server for work,
Exception thrown is: "Permission denied (password)".
Any ideas?!

**Comment by darinkes** [comment]
I would suggest to check the sshd_config of your ssh server in production.
Especially the PermitRootLogin (https://linux.die.net/man/5/sshd_config).

But keep in mind allowing auth of root via Password is never a good idea and your application should not use it anyway. Key-Authentication is much better or add an special user for SFTP operations.
(Just mentioned since I dont know if your server is accessible from the internet.)

**Comment by SrgjanX** [comment]
> I would suggest to check the sshd_config of your ssh server in production.
> Especially the PermitRootLogin (https://linux.die.net/man/5/sshd_config).
> 
> But keep in mind allowing auth of root via Password is never a good idea and your application should not use it anyway. Key-Authentication is much better or add an special user for SFTP operations.
> (Just mentioned since I dont know if your server is accesable from the internet.)

All machines are windows 10 except the servers, those are windows server 2012.
Thanks for the tip but I only need this to work for now.
-Yes the work server, we use it to show-off public data. So its accessible.
