### ISSUE TITLE
Server HMAC algorithm not found

### ISSUE THREAD

**Issue by gargml** [sshnet/SSH.NET#503]
Hi,
I am using the latest release SSH.Net, 
and encountering issues when trying to connect to a Ubuntu machine.
I get the following error : 
Renci.SshNet.Common.SshConnectionException: Server HMAC algorithm not found. 

when calling the very straight forward method SSH.Connect(..,..,..),
this code works fine on 30 different flavors of UNIX, just that specific Ubuntu machine is giving me troubles.

Now, i am aware of the supported capabilities of the library, and made sure our sshd_config does contain at least one of the supported ciphers, KeyExchng, and Mac.
this is the sshd_config :

- Ciphers

 aes128-ctr,aes256-ctr,arcfour256,arcfour128

- MACs

 hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512

- KexAlgorithms

 curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1

The machine is Ubontu, see:
root@10-125-195-35:/etc/ssh# uname -a 
Linux 10-125-195-35 4.4.0-111-generic #134~14.04.1-Ubuntu SMP Mon Jan 15 15:39:56 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Please advise, or ask more questions that i will supply the required missing information.
Many thanks !
Gargml

**Comment by gojimmypi** [comment]
@gargml  I'm seeing this error today & curious why this issue closed without resolution? 

Any tips would be appreciated :)

**Comment by darkoperator** [comment]
The library has a limited number of HMAC supported more than likely the server is using a more  modern one.

**Comment by gojimmypi** [comment]
@darkoperator you are correct. Thank you. Indeed the problem I was having was with an old server for a vendor that apparently winscp also does not like:

![image](https://user-images.githubusercontent.com/13059545/52445612-6eb66980-2ae0-11e9-8a23-896e572aadd2.png)

Oddly, Filezilla connects without complaint.

The good thing for me is that the target is not a production server. Bad thing is I don't have a non-production server to test with.
