### ISSUE TITLE
Failed to negotiate key exchange algorithm

### ISSUE THREAD

**Issue by hamster81** [sshnet/SSH.NET#504]
I have an issue when a i try to use sshclient.connect.
the following exception appears "Failed to negotiate key exchange algorithm"

this issue exists with serveur version SSH-2.0-dropbear_2016.74 or SSH-2.0-CISCO_WLC
All is ok with server SSH-2.0-gRALQ

do you have an idea to avoid this exception?

thank's for your answer

**Comment by drieseng** [comment]
In the next beta, we'll add support for the following key exchange algorithms:
* curve25519-sha256
* curve25519-sha256<span>@</span>libssh.org
* ecdh-sha2-nistp256
* ecdh-sha2-nistp384
* ecdh-sha2-nistp521
* diffie-hellman-group14-sha256
* diffie-hellman-group16-sha512

**Comment by harmandeol** [comment]
any idea, when are we planning release 2020.0.0-beta1 ?

**Comment by drieseng** [comment]
I hope to find time this weekend, but no promises.

**Comment by drieseng** [comment]
[2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) is now available.

**Comment by harmandeol** [comment]
Thanks
