### ISSUE TITLE
Identification string should be sent before waiting for server identification string

### ISSUE THREAD

**Issue by martinprikryl** [sshnet/SSH.NET#505]
According to [RFC 4253 Section 4.2. Protocol Version Exchange](https://tools.ietf.org/html/rfc4253#section-4.2):

> When the connection has been established, both sides **MUST send an identification string.**

SSH.NET sends its identification string only after waiting for server's identification string. Amazon Managed SFTP server has the same issue. So you cannot connect to that SFTP server with SSH.NET. Both sides first wait for the other side to send the identification string before sending its own.

Spotted thanks to: https://stackoverflow.com/q/54014749/850848

**Comment by BrainBacon** [comment]
Wow, this is exactly the same problem we are having. Going to report a bug to Amazon myself too.

**Comment by psaffrey-origami** [comment]
We are also experiencing this issue. @BrainBacon - did you file a bug with Amazon? Can you link it?

**Comment by denispakizh** [comment]
The same issue is with KEY EXCHANGE INIT message, library waits for the server's KEY EXCHANGE INIT message while it should not:
>Key exchange (kex) begins by each side sending name-lists of supported algorithms.

https://tools.ietf.org/html/rfc4253#section-7

**Comment by drieseng** [comment]
This is fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
