### ISSUE TITLE
is it possible to connect SFTP using PUTTY KEY string?

### ISSUE THREAD

**Issue by vsplcDJ25** [sshnet/SSH.NET#510]
I am trying to connect SFTP using with PUTTY Key string through C# but could not able to connect to the server. received an exception while connecting to SFTP and the exception is **"Invalid Private key file".**
Please let me know with possible solution about using with SSH.NET.

**Comment by ghost** [comment]
Convert the key to OpenSSH format using PuTTYGen. PPK files are (as far as I can tell) not supported.

**Comment by mgamache** [comment]
PPK files are *not* supported. Usually PPK files are derived from PEM or other files that are supported.
