### ISSUE TITLE
Appending a file misses final bytes

### ISSUE THREAD

**Issue by OregonGhost** [sshnet/SSH.NET#514]
I've run into a strange problem with resuming transfers. We're doing transfers of file sizes of about 40MB, which will go over really slow and unreliable connections (think GSM). Because the transfer might be interrupted due to network issues, I've implemented resuming, which basically works as follows (not actual code, I omitted error and cancel handling):

    var existingSize = sftp.Get(path).Length;
    if (existingSize > 0 && existingSize < expectedSize) {
        var file = sftp.Open(targetpath, FileMode.Append, FileAccess.Write);
        source.Seek(existingSize, SeekOrigin.Begin);
        while (!cancelled) {
            int read = source.Read(buffer, 0, BufferSize);
            if (read == 0) {
                // Here file.Close() is missing
                existingSize = sftp.GetFileSize(targetpath);
                if (existingSize != source.Length) {
                    // Something went wrong.
                }
                return true;
            }

             var result = file.BeginWrite(buffer, 0, read, null, null);
             if (result.CompletedSynchronously) {
                  continue;
             }
             // Cancel handling here, omitted
             file.EndWrite(result);
        }
        return false;
    }

When there are already bytes on the target system, we seek that position in the source stream, open the remote file with append and start writing in a loop. This is done with file.BeginWrite and file.EndWrite just to allow checking a CancellationToken inbetween, because those older APIs do not support that directly.
However, whenever this happened (after network disconnect and reconnect, and finally also when I changed the first check to `existingSize >= 0` to force this code, the file ended up being to short. I tried with two files:

File 1 has 37951896 bytes, but the target file has 37934070 => 17826 bytes missing
File 2 has 37976472 bytes, but the target file has 37966800 => 9672 bytes missing

No matter where I interrupted the transfer (i.e. after 10MB, 20MB or anywhere else), for the same file it was always the same number of bytes missing. The buffer size and therefore write size didn't make any difference as well. Note that it is actually bytes missing at the end, i.e. up to the written file size, the bytes were correct.

After some trying, I discovered that inserting a `file.Close()` immediately before checking the size will make this work. While this is certainly a mistake on my side, I did not expect that this would not work. In other words, when I think writing is finished, a Close call seems to be required to actually finish. Without this, even when I retry writing the last few bytes will not work.

However, I expected `file.EndWrite()`, which should only return after the asynchronous transfer completed, to be an appropriate end point for this. It seems some caching is still going on, but the file will really never be finished, no matter how long or how often I retry rewriting the last few bytes.

Is this behaviour as intended? Shouldn't `file.EndWrite()` only return after it has actually finished writing the bytes? Because of the resume logic, I expected querying the file size to be fine, which it apparently is not.

Note that my actual problem is now solved with the Close call, but I'm still curious as to whether this is intended behaviour.

**Comment by drieseng** [comment]
@OregonGhost I can confirm that this indeed works a designed. You can use **SftpFileStream.Flush()** to force any buffered data to be written to the destination.
