### ISSUE TITLE
scp error unexpected filename

### ISSUE THREAD

**Issue by ccic** [sshnet/SSH.NET#516]
I want to copy some *.tgz from one Ubuntu 16.04 to another Ubuntu 16.05 with the following code. But it does not work and complains "scp: error: unexpected filename:"

MasterScpClient = new ScpClient(masterHostname, username, password);
Console.WriteLine($"copy {masterExecutable.FullName} to {argsOption.MasterTargetPath}");
MasterScpClient.Upload(masterExecutable, argsOption.MasterTargetPath);

The output is:
copy /home/xxx/CodeTest/C#/ScpTest/ScpTest/master/publish.tgz to /home/xxx/master.tgz
Fail to upload master executable: scp: error: unexpected filename:

**Comment by ccic** [comment]
see https://github.com/sshnet/SSH.NET/pull/515

**Comment by drieseng** [comment]
I've fixed this issue locally. Still working on revamping our integration tests.

**Comment by RudolfHenning** [comment]
I've also hit this issue using .Net Framework 4.7.2 connecting to CentOS8.

**Comment by mauroa** [comment]
Hi @drieseng, should we build this locally in order to get a new version with this fix included? Or is it planned to push a new version to nuget.org? Thanks

**Comment by drieseng** [comment]
@mauroa I'm planning on creating a new release soon(ish).
