### ISSUE TITLE
SftpClient.Connect() throwing ThreadAbortException 

### ISSUE THREAD

**Issue by lystormenvoy** [sshnet/SSH.NET#519]
` public bool Connect()
{
if (!Connected)
                {
sftp.Connect(); //Line throw exception
}
return true;
}`
Code like this, and it thrown a ThreadAbortException 
Exception.TargetSite.Name is WaitMultiple

**Comment by drieseng** [comment]
Please provide more information:
* What version of **SSH.NET** are you using?
* Can you reproduce this issue consistently?

**Comment by drieseng** [comment]
No feedback.

**Comment by lystormenvoy** [comment]
> Please provide more information:
> 
> * What version of **SSH.NET** are you using?
> * Can you reproduce this issue consistently?

Sorry for the late reply
I use nuget to install ssh.net and that is 2016.1.0
Sometimes I can reproduce.
My Code:
```
public bool Connect()
        {
            try
            {
                if (!Connected)
                {
                    sftp.Connect();
                }
                return true;
            }
            catch (System.Threading.ThreadAbortException ex)
            {
                throw new Exception(string.Format("ThreadAbortException：{0}" + ex.TargetSite.Name, ex.Message));
            }
            catch (Exception ex)
            {
                throw new Exception(string.Format("Connect failed：{0}", ex.Message));
            }
            
        }
```
