### ISSUE TITLE
Support newer SSH Ciphers and MACs

### ISSUE THREAD

**Issue by ypid** [sshnet/SSH.NET#53]
Would it be possible to support more crypto algorithms which recent versions of OpenSSH support?

From `man ssh_config` on Debian Jessie.
- MACs
  
  umac-64-etm@openssh.com,umac-128-etm@openssh.com,
  hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,
  umac-64@openssh.com,umac-128@openssh.com,
  hmac-sha2-256,hmac-sha2-512,
  hmac-md5-etm@openssh.com,hmac-sha1-etm@openssh.com,
  hmac-ripemd160-etm@openssh.com,
  hmac-sha1-96-etm@openssh.com,hmac-md5-96-etm@openssh.com,
  hmac-md5,hmac-sha1,hmac-ripemd160,
  hmac-sha1-96,hmac-md5-96
- Ciphers
  
  aes128-ctr,aes192-ctr,aes256-ctr,
  aes128-gcm@openssh.com,aes256-gcm@openssh.com,
  chacha20-poly1305@openssh.com,
  arcfour256,arcfour128,
  aes128-cbc,3des-cbc,blowfish-cbc,cast128-cbc,
  aes192-cbc,aes256-cbc,arcfour
- KexAlgorithms
  
  curve25519-sha256@libssh.org,
  ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,
  diffie-hellman-group-exchange-sha256,
  diffie-hellman-group14-sha1,
  diffie-hellman-group-exchange-sha1,
  diffie-hellman-group1-sha1

Related to: https://github.com/darkoperator/Posh-SSH/issues/103
Partly related to: #20

**Comment by Cronus89** [comment]
Any plan for this? I'm having the issue in software that uses your ssh lib. https://github.com/ShareX/ShareX/issues/3599

**Comment by Kim-SSi** [comment]
It might be useful to look at the following repos for 25519 related code, licensed as public domain or MIT:
https://github.com/CodesInChaos/Chaos.NaCl
Some additional code & tests to the above:
https://github.com/CryptoManiac/Ed25519

**Comment by AtosNicoS** [comment]
I recently also ran into this issue, I am unable to acces a Teltonika router anymore:
https://github.com/sshnet/SSH.NET/issues/461

Please implement some of the newer ciphers.

**Comment by stijnbrouwers** [comment]
+1

**Comment by marcob73** [comment]
It seems aes128-ctr, aes192-ctr and aes256-ctr are currently supported.
Is it there any schedule to add support also to the following?

- Ciphers
aes128-gcm@openssh.com,aes256-gcm@openssh.com,
chacha20-poly1305@openssh.com

Thank and Best Regards,
Marco

**Comment by drieseng** [comment]
In the next beta, we'll add support for the following key exchange algorithms:

* curve25519-sha256
* curve25519-sha256<span>@</span>libssh.org
* ecdh-sha2-nistp256
* ecdh-sha2-nistp384
* ecdh-sha2-nistp521
* diffie-hellman-group14-sha256
* diffie-hellman-group16-sha512

and we've added support for the following host key algorithms:

* ssh-ed25519
* ecdsa-sha2-nistp256
* ecdsa-sha2-nistp384
* ecdsa-sha2-nistp521

**Comment by mdzeko** [comment]
Do we have a release available anywhere with these host keys? I see the milestone, but the latest release is in the 2016 mark.

**Comment by drieseng** [comment]
[2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) is now available.
