### ISSUE TITLE
ambiguous in the namespace 'Renci.SshNet'

### ISSUE THREAD

**Issue by threeeye** [sshnet/SSH.NET#533]
Hi guys,
I have a project connecting to ssh, everything is good,
but when I copy the code to a new project:
`Dim sshconn As New PasswordConnectionInfo("SERVER-IP", "USER", "PASS")`
 I get:
> 'PasswordConnectionInfo' is ambiguous in the namespace 'Renci.SshNet'.

Thanks

**Comment by threeeye** [comment]
BTW, this only happens if I have OzekiSDK referenced

**Comment by IgorMilavec** [comment]
Please see https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/language-specification/namespaces
