### ISSUE TITLE
ShellStream stops reading?

### ISSUE THREAD

**Issue by Patrick92x** [sshnet/SSH.NET#534]
Hi Guys,

I'm a network administrator who has been using SSH.NET within the Posh-SSH module for PowerShell. It enables me to do great things network wise, but i've stumbled across an issue is just can not solve.

**Background:**
I use SSH to connect to (mainly Cisco) network devices. Those devices require a ShellStream to work interactively. When communicating with the devices i use the "write()" or "writeline()" to send commands to the device. And use "read()" whenever i want to see the output.

**Problem:**
The write / read method against the stream works just fine when the output of the command i available shortly after the execution. 

However, some commands that i use on a device can take a quite a while (30 seconds / 1 minute). During that timeperiod the devices keep providing some output to show the progression of the command that is running (most likely in the form of dots or exclamation marks). In this situation, the "read()" on the stream isn't behaving as i would expect.

After a random period of time, performing the "read()" on the stream won't give me any data about the progression. Besides that, the stream object shows that the "DataAvailable" is False.

As soon as i send another "write()" or "writeline()" the stream has DataAvailable again. I "read()" the stream again, but the output is only a very small part of the older progression output (like 3 dots out of a 100). So for some reason i only get some old output data back, and the stream doesn't seem interactive anymore.

I can repeat this step a lot of times untill eventually, after going through all the old output data from the first command, it catches up, and shows me all the output of the other "write()" commands i've used so far, and so the session is interactive again.

**Question:**
Can you guys help me out and give me some suggestions as to why this behavior is occuring?

I've been trying to find the root cause of this behavior for weeks now, but i'm unable to find it.

**Example Expected output (1 or multiple reads)**
ping 127.0.0.1 repeat 20
Type escape sequence to abort.
Sending 20, 100-byte ICMP Echos to 127.0.0.1, timeout is 2 seconds:
....................
Success rate is 0 percent (0/20)

**Example Unexpected output (1st read)**
ping 127.0.0.1 repeat 20
Type escape sequence to abort.
Sending 20, 100-byte ICMP Echos to 127.0.0.1, timeout is 2 seconds:
.....

**Example Unexpected output (after 1 or more writes)**
.

..

.

**Comment by mircast** [comment]
Same issue here

**Comment by Patrick92x** [comment]
Cisco has provided a new Recommended Release. We've upgraded to this new release, and tested SSH before and after the upgrade on switches were the problem occured. I wasn't able to recreate the problem after the upgrade.

It looks like the upgrade has fixed the issue, en thus it was indeed a Cisco problem in certain IOS releases / devices. It's weird, because not all the hardware (same type) with the same release was effected by it.
