### ISSUE TITLE
Getting server fingerprint?

### ISSUE THREAD

**Issue by TechLoom** [sshnet/SSH.NET#538]
I'm looking for a way to get the server's fingerprint so it can be saved to a config file. Then use that config each time going forward when connecting to make sure there isn't any man in the middle.

From what I can find looks like HostKeyReceived has FingerPrint byte array.

But when it comes to SSH I'm used to the FingerPrint IDs being in either SHA256 or MD5. So I'm not sure this FingerPrint is valid (as I don't know how to compare the two).

Looking to see if anyone can confirm if this is in fact what I'm looking for. If it is, I'll just save the byte array as is and load it back, as I don't need to convert it to SHA256/MD5, b/c if the server fingerprint is different then it'll fail with the connection.

If no one knows, I'll have to set up a VM for some testing later this week and will leave the information for anyone else that runs into this question.

Thanks

**Comment by TechLoom** [comment]
After running a few tests I was able to confirm and double check how the fingerprint works with Ubuntu.

This cli works on Ubuntu 16.04 LTS and 18.04 LTS (didn't work on 14.04 LTS).

`ssh-keygen -E md5 -l -f /etc/ssh/ssh_host_rsa_key.pub | awk '{print $2}' | sed -e 's/MD5://g' | tr -d ':'`

Running the command you'll get output like `6383a56507cb6ea6622fd09f1339bb8c`

Then in SSH.NET to get the fingerprint to compare with.

```C#
using (var client = new SftpClient(_host, _port, _userName, _password))
{
    client.HostKeyReceived += delegate (object sender, HostKeyEventArgs e)
    {
        var fingerPrint = new StringBuilder(e.FingerPrint.Length * 2);
        foreach (var b in e.FingerPrint)
        {
            fingerPrint.AppendFormat("{0:x2}", b);
        }

        Console.WriteLine($"FingerPrint: {fingerPrint.ToString()}");
    };

    client.Connect();
    if (client.IsConnected)
    {
        logger.Information($"Connected to client at {_host}");
    }
}
```

Now fingerPrint var will have the fingerprint that will match the command line output.

**Comment by timmi4sa** [comment]
Actually, the library seems to fail to provide a correct fingerprint (assuming it's MD5) for `e.HostKeyName` that equals to "ssh-ed25519". The HostKeyEventArgs (e.Fingerprint) contains 16 bytes that absolutely **not** match OS X ssh (nor Windows 10 built-in ssh command output.) I even made sure to execute the command like below to ensure I am requesting the "ssh-ed25519" (to match what's reported by e.HostKeyName). 

The ssh command: `ssh admin@host-address -o HostKeyAlgorithms=ssh-ed25519 -o FingerprintHash=md5`

Please help! The library works correctly with `e.HostKeyName` of "ssh-rsa", but "ssh.net" doesn't pick "rsa" when connecting to AWS Ubuntu hosts in 2021.
