### ISSUE TITLE
Connection timeout using public test server (connects in FileZilla)

### ISSUE THREAD

**Issue by robcam73** [sshnet/SSH.NET#539]
When connecting with this code

using (var sftp = new SftpClient("test.rebex.net", 990, "demo", "password"))

sftp.Connect() error is

Renci.SshNet.Common.SshOperationTimeoutException: 'Socket read operation has timed out after 30000 milliseconds.'

If I connect with FileZilla all works correctly

This mode is failing
FTP/SSL (implicit mode)

sftp and ftp work, but I need to support all 3 methods.

**Comment by Deantwo** [comment]
So SFTP works?
What is your issue then?

I don't think this library support FTP/S? Since it is SSL and not SSH.

**Comment by robcam73** [comment]
Yes, don't remember what I was thinking when I wrote this. Using libcurl for the ftp/s part now. This library is working as described
