### ISSUE TITLE
SFTP connection issue in D365 Finance and operation local one box environment

### ISSUE THREAD

**Issue by MadhanRamachandran** [sshnet/SSH.NET#542]
Hi,

I am getting the below error in SFTP connection code in my local D365 FO one box environment. But the same code and same configuration working fine in azure deployed environment.

Please advice on the same.

Microsoft.Dynamics.Ax.Xpp.ClrErrorException: SshOperationTimeoutException ---> Renci.SshNet.Common.SshOperationTimeoutException: Socket read operation has timed out after 30000 milliseconds. at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout) at Renci.SshNet.Session.SocketReadLine(TimeSpan timeout) at Renci.SshNet.Session.Connect()

**Comment by darkoperator** [comment]
Logs on server should give an idea. Do you have access to those?

**Comment by MadhanRamachandran** [comment]
Hi Carlos,

Thanks for the replay.

I have check in my local one box event log no logs found. Also checked in sftp server log there also no log found.

Please suggest.

**Comment by darkoperator** [comment]
I meant O365 the target

**Comment by MadhanRamachandran** [comment]
Yes, D365 FO is the target .

**Comment by darkoperator** [comment]
Only other option is to look at a PCAP and see if the server send something back that lib does not know how to handle

**Comment by drieseng** [comment]
No feedback.
