### ISSUE TITLE
Exception if both Password and PrivateKey authentication are tried

### ISSUE THREAD

**Issue by laindir** [sshnet/SSH.NET#55]
Any situation that causes both Password and PrivateKey authentication to be attempted (server requires both, password tried first but is wrong, private keys) will throw `CreateMessageTypeAlreadyEnabledForOtherMessageException` for message number 60.

The [ssh auth spec](https://www.ietf.org/rfc/rfc4252.txt) indicates that `SSH_MSG_USERAUTH_PK_OK` and `SSH_MSG_USERAUTH_PASSWD_CHANGEREQ` are method specific, so it is ok that they share message number 60. But `SshMessageFactory` treats message numbers globally.

**Comment by drieseng** [comment]
Thanks for reporting this.
I'll look into it tomorrow, and make sure it's fixed before the stable **2016.0.0** is release

**Comment by drieseng** [comment]
This is fixed in c5d51b9d9d1bfc2ddefe606654f2d9a9d1f94f87.

**Comment by laindir** [comment]
Looks good in my tests. Thanks for the quick response, and for writing such an awesome library.
