### ISSUE TITLE
Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib

### ISSUE THREAD

**Issue by jorgecachoh** [sshnet/SSH.NET#551]
I'm trying to use this library in a .NET Framework 4.6.1 but is raising this error:

```
2019-06-07T19:36:00.028 [Error] Executed 'SftpReadContactFiles' (Failed, Id=7937f4cb-063b-4624-a4fb-fe63a7e5b0ae)
Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

This was working in a previous version of the project using .NET Core

Thanks in advance

**Comment by piperun** [comment]
It's due to SSH.NET being still targeted towards the old 4.0 Framework which is not compatible with Core.

I would recommend in the meantime to look into using libssh / libssh2 directly or via some embedded language like Python.
