### ISSUE TITLE
Turning off Verbose mode

### ISSUE THREAD

**Issue by imays76** [sshnet/SSH.NET#553]
While using SshNet, a log of 

```
SshNet.Logging Verbose: 5: .......
SshNet.Logging Verbose: 1: .......
```
lines are printed in Debug Output Window.

How can I disable the verbose mode?
[This document](https://github.com/sshnet/SSH.NET/wiki/Troubleshooting-SSH.NET) explains how to make it more verbose (I guess), but I cannot figure out how to turn off verbose mode with that document.

**Comment by drieseng** [comment]
If I recall correctly, it is only enabled by you build **SSH.NET** in **debug** configuration.

**Comment by imays76** [comment]
Thank you for your answer.
Even if I am using Debug Configuration, how can I turn off the verbose mode?

**Comment by Deantwo** [comment]
@imays76, you can probably just disable it here: https://github.com/sshnet/SSH.NET/blob/13bef36d3811a3811b587c20b33c4ff512dabe93/src/Renci.SshNet/Abstractions/DiagnosticAbstraction.cs

**Comment by imays76** [comment]
Thank you!
