### ISSUE TITLE
Exception of type 'System.OutOfMemoryException' was thrown.

### ISSUE THREAD

**Issue by Bob200387** [sshnet/SSH.NET#563]
I'm trying to download a large file (1.2 GB) with azure function but after a few minutes return the message "Exception of type 'System.OutOfMemoryException' was thrown."
Here below the code:
using (var sftp = new SftpClient(ftpServer, ftpPort, ftpUserName, ftpPassword))
{
	sftp.Connect();
	foreach (string fileName in fileList)
	{
		Stream stream = new MemoryStream();
        sftp.DownloadFile(pathPdfDefinitivi + fileName, stream);
	}
	sftp.Disconnect();
}

Version=2016.1.0.0
.NET Framework 4.6.1

**Comment by darinkes** [comment]
> Stream stream = new MemoryStream();

MemoryStream is in your Memory and you dont have enough apparently.
So, whats the question? :)
