### ISSUE TITLE
Error when installing ssh.net

### ISSUE THREAD

**Issue by renperez** [sshnet/SSH.NET#569]
Install-Package SSH.NET -Version 2016.1.0
PS C:\Users\Administrator> Install-Package SSH.NET -Version 2016.1.0
Install-Package : A parameter cannot be found that matches parameter name 'Version'.
At line:1 char:25
+ Install-Package SSH.NET -Version 2016.1.0
+                         ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by IgorMilavec** [comment]
Please see https://docs.microsoft.com/en-us/powershell/module/packagemanagement/install-package?view=powershell-7.2
