### ISSUE TITLE
Key 'OPENSSH' is not supported.

### ISSUE THREAD

**Issue by alexeyluchkin** [sshnet/SSH.NET#570]
Unable to connect to an SFTP server. Error: Key 'OPENSSH' is not supported. Windows 8.1 pro.
  On Windows 10 - it works.

**Comment by BorisAmelyan** [comment]
is this project still valid?  I haven't seen new version come out in over 3 years

**Comment by drieseng** [comment]
Personally, I haven't had time to work on SSH.NET.
Does that mean I've given up on it? No.
Right now, I'm spending most of my time on another OSS project and my family.
I'd be happy if there's anyone else (preferrable more than one dev) that is willing to take the lead until I have more time.

**Comment by BorisAmelyan** [comment]
it would be good to release version which at least supports OPENSSH
with increased security SSH.NET is becoming outdated/obsolete
i am forced to move on to other product

**Comment by darinkes** [comment]
@BorisAmelyan I think it would help if more people test/review my Merge Requests for this features
- https://github.com/sshnet/SSH.NET/pull/496

Follow up change on the elliptic curves MR is in this git branch:
- https://github.com/darinkes/SSH.NET-1/tree/openssh_format_rsa

**Comment by drieseng** [comment]
@darinkes's changes have now landed in the *develop* branch, and will be part of the next release.
