### ISSUE TITLE
Question on CIPHERS

### ISSUE THREAD

**Issue by Manjuittangur** [sshnet/SSH.NET#575]
Hi,
We are using SH.NET version 2016.0.0 to connect to thirdparty SFTP, They have notified saying some of the insecure CIPHERS will not be supported and suggested to use latest ones, looked thru code and seems like the latest ones are in the list on ConnectionInfo along with insecure ones, my question is during establishing connection will it use any of the one from list which server accepts, meaning there will be negotiation on what CIPHERS server accepts from the list correct? so eventhough the insecure ones exists in list, it will work using the latest CIPHERS

INSECURE SFTP CIPHERS
	KEX : diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
	Ciphers: aes256-cbc,aes192-cbc,aes128-cbc,blowfish-ctr,blowfish-cbc,cast128-cbc,arcfour256,arcfour128,3des-cbc
	MAC : umac-64@openssh.com
The list of SECURE SFTP CIPHERS that clients should begin using immediately/moving forward are below.

SECURE SFTP CIPHERS
	KEX: diffie-hellman-group-exchange-sha256
	Ciphers: aes256-ctr aes192-ctr aes128-ctr
	MAC: hmac-sha2-512 hmac-sha2-256 hmac-ripemd160 hmac-sha1

Thanks,
Manju

**Comment by drieseng** [comment]
There will indeed be a negotiation between client and server. If the server only supports - what you refer to as - "latest" ciphers and the client supports these as well, then one of those "latest" ciphers will indeed be used.
