### ISSUE TITLE
No suitable authentication method found to complete authentication

### ISSUE THREAD

**Issue by adamatnac** [sshnet/SSH.NET#579]

**Comment by adamatnac** [comment]
We have a c# console task which uses ssh.net to send files by sftp. Its worked fine for years, but last Thursday it started generating an error message  "No suitable authentication method found to complete authentication" despite the fact that files were successfully transmitted to the target sftp server!

The code has not changed. No changes were made to the config files or anything related to the console task. We can log in to the target sftp server with filezilla using identical authentication keys to what the console task uses. 

The job runs fine in our testing environment. The only thing that has happened is that our production (winsvr 2012 r2) server was rebooted a few hours before the job started "pseudo" failing.

Exact error message: "No suitable authentication method found to complete authentication (keyboard-interactive,publickey)"

Any ideas?

Thanks.

**Comment by drieseng** [comment]
@adamatnac If you didn't change anything on the client, then something surely changed on the server. What authentication methods do you supply on the client?

**Comment by adamatnac** [comment]
@drieseng No, our sys admin inisists that nothing changed on the server. We are using a key file and not a password. The server reboot may be a red herring. A csv file had been incorrectly dropped into the source folder. Currently speculating that the target sftp server responded with a misleading error message while trying and failing to process this file. Will post a conclusion when I have one.

**Comment by adamatnac** [comment]
It looks as though the csv file caused this problem. Once removed from the source directory, the error messages stopped. I have no idea why a rogue csv file would cause this particular error message.
