### ISSUE TITLE
Socket read operation has timed out exception

### ISSUE THREAD

**Issue by PingPongSet** [sshnet/SSH.NET#583]
I got the exception below when the client tries to connect to ftp server:

> Socket read operation has timed out after 30000 milliseconds.     
>  
> Source = "Renci.SshNet" 
> 
> at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
> at Renci.SshNet.Session.SocketReadLine(TimeSpan timeout)
> at Renci.SshNet.Session.Connect()
> at Renci.SshNet.BaseClient.Connect()
> at SftpClient.ReadAllBytesAsync() in C:\SftpClient\SftpClient.cs:line 42

Code below:

```
using (Renci.SshNet.SftpClient sftp = new Renci.SshNet.SftpClient(server,
                                                    21,
                                                    Username,
                                                    Password))                      
                    sftp.Connect();  //exception here
                    content = sftp.ReadAllBytes(FilePath);    
                    sftp.Disconnect();                      
			}
```

SSH.NET version: 2016.1.0

Hoever, it connects via telnet like below via command prompt:
```

  telnet server_ip_address 21
   220 (SFTPPlus_3.15.0) Welcome to the FTP/FTPS Service.
```

A staff on server side sends me public certificates, which I installed on my Windows 10. 

Any idea?

**Comment by biocoder-frodo** [comment]
Answered in cross-post on SO:
https://stackoverflow.com/questions/57859497/socket-read-operation-has-timed-out-exception-with-ssh-net-when-connecting-to

**Comment by darkoperator** [comment]
SFTP is not the same as FTP over SSL but via SSH. Based on the mention of port 21

**Comment by biocoder-frodo** [comment]
I know, @PingPongSet knows after posting on SO, and now @drieseng knows he can safely skip this one ;)
