### ISSUE TITLE
SSH.NET ShellStream Question

### ISSUE THREAD

**Issue by asanchezayra01** [sshnet/SSH.NET#585]
Hello,

     I have been using SSH.NET in one of my projects and I have to run commands using sudo. One of the commands I have to run involves using sudo and then getting result of the sudo call. When running sudo I am aware that I have to use the ShellStream Object in order to execute the sudo command and then input a password but now I am stuck in the part of retrieving the output (from the entered sudo command) from the ShellStream. Do you think you can help me with an understanding of how I would be able to do this. Thank you for taking the time to read this message and I hope to hear from you soon.

P.S: This is the code that I am trying to execute:

 using (var client = new SshClient(host.HostIp, UserNameTextBoxID.Text, PasswordTextBox.Text))
            {
                client.Connect();

                var sh = client.CreateShellStream("", 80, 40, 80, 40, 1024);

                sh.WriteLine("sudo -S find -name " + host.HostPort);

                sh.WriteLine(PasswordTextBox.Text);

                var output = sh.Read();
            }

**Comment by biocoder-frodo** [comment]
https://github.com/search?q=client.CreateShellStream&type=Code
?

**Comment by asanchezayra01** [comment]
Thank you for showing me the ways of github. I am new to using this site, I guess I should have done more research!
