### ISSUE TITLE
Wrong error message "Server string is null or empty"

### ISSUE THREAD

**Issue by ygoe** [sshnet/SSH.NET#593]
I have the error message "Server string is null or empty" which does not apply. The actual issue is that the target machine has not enough memory to fork the bash process (or whatever process it uses for SFTP). This should be corrected because the wrong error message leads the user in a completely wrong direction.

**Comment by biocoder-frodo** [comment]
Does the error throw from 'CrystalBall.cs' or somewhere else? If you want this edge case fixed, please provide more info? Is it clear from the source code that the target server was misbehaving??

**Comment by ygoe** [comment]
I don't have a stack trace available. The remote machine was restarted afterwards so I'm not sure I get this error condition back again for testing.

It was totally unclear that it was an error on the remote side since the exception clearly said there was a configuration error locally, which is not correct.

**Comment by drieseng** [comment]
Please open a new issue if you still run into this issue, and have extra information to share.
