### ISSUE TITLE
Reboot command not working..

### ISSUE THREAD

**Issue by Kangyongkyu** [sshnet/SSH.NET#594]
I am trying to remotely reboot Linux using ssh.net. But I can't figure out why my code doesn't work. Can someone help me?

Below is my code

     using (var client = new SshClient("host", "username", "password"))
                {
                    client.Connect();
                    client.RunCommand("reboot");
                    client.Disconnect();
                }

**Comment by gelbartm** [comment]
You can try 
client.RunCommand($”echo {password} | sudo -S reboot”);

Where password is your linux user password. If you are root user use.

client.RunCommand($”sudo reboot”);

Or use CreateShellStream instead of using RunCommand

**Comment by Kangyongkyu** [comment]
Thank you for the answer.
This is not the way to tell you, but I solved it with the code below. Thank you.

sshClient.RunCommand("echo -e 'password\n' | sudo -S reboot");

**Comment by Kangyongkyu** [comment]
> 이것은 당신에게 말하는 방법이 아니지만 아래 코드로 해결했습니다. 감사합니다.
> 
> sshClient.RunCommand ( "echo -e 'dydrb! 001 \ n'| sudo

**Comment by dave-watts** [comment]
if you do a reboot then the client.Disconnect(); will throw an exception since the client is disconnected. 
Also, if you are using a using block an exception will be thrown by ssh.net.
I have no idea if ssh.net cleans itself up properly when a client breaks a ssh connection, it seems the best you can do is

```
var client = new SshClient("host", "username", "password");
client.Connect();
client.RunCommand($"sudo reboot");
```
