### ISSUE TITLE
OperationTimeout not working on SFTPClient Class

### ISSUE THREAD

**Issue by mukundmalladi** [sshnet/SSH.NET#597]
Hello,
I'm using latest Renci.SshNet version in my code and when I set 

> OperationTimeout  

to a period of **10 secs** and trying  to upload file which takes ~1min to SFTP,  code is not timing out. The operation completes without any exception. 

- All I'm doing up newing up the sftpclient class, setting connection info and setting OperationTimeout  to 10 sec. I even set the connection info's timeout property to 10sec but I guess that is  for trying to connect to sftp server.

`var sftpClient = new StpClient(new connectionInfo(){...)};
sftpClient.OperationTimeOut = Timespan.FromSeconds(10);
sftpClient.Upload(file path)
`
I'm using .net framework.

Is there something I'm missing. I need an exception to be thrown after 10sec.

Any help is appreciated. Thank you in advance!

**Comment by IanTaylorGMSL** [comment]
I had a similar question, looking at the code it looks like the operation timeout is triggered when the operation is idle for for the timeout duration.
So no matter how long the operation actually takes it will not timeout unless it has gone idle.

**Comment by mukundmalladi** [comment]
Closing this issue since I could not get a concrete answer.
