### ISSUE TITLE
Add support for SecureString

### ISSUE THREAD

**Issue by wldevries** [sshnet/SSH.NET#6]
It would be nice if SSH.NET used [SecureString](https://msdn.microsoft.com/en-us/library/system.security.securestring%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) for the password in PasswordConnectionInfo for instance.

**Comment by 0x333333** [comment]
Hi @wldevries,

I'd like to know why SecureString is not supported in SSH.NET? Why did you close it the second day after you created the issue?

Thanks in advance,
Zhipeng

**Comment by wldevries** [comment]
You are probably right. I closed it because I thought it was an unreasonable request and not often used in the .net platform.

However I just found out that for instance both [SqlCredential](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcredential%28v=vs.110%29.aspx) and [NetworkCredentials](https://msdn.microsoft.com/en-us/library/system.net.networkcredential%28v=vs.110%29.aspx) use SecureString.

**Comment by 0x333333** [comment]
Thanks! Would like to see another custructor **ScpSecureClient** or something alike :)

**Comment by IgorMilavec** [comment]
https://github.com/dotnet/platform-compat/blob/master/docs/DE0001.md

**Comment by jscarle** [comment]
@WojciechNagorski This issue can be closed as per @IgorMilavec 's comment.
