### ISSUE TITLE
Updated Nuget ?

### ISSUE THREAD

**Issue by karimjouini** [sshnet/SSH.NET#600]
Hi,

Great job implementing this client! Really !

I noticed the SSH.NET Nuget is older than the code here, do you have any plans on updating the nuget ?

https://www.nuget.org/packages/SSH.NET/

Thanks,
Karim Jouini - Expensya.com

**Comment by kirk-quinbar** [comment]
i was gonna ask something similar. one of the checkin comments indicated that a .netstandard 2.0 build was made but the nuget feed still only shows .netstandard 1.3 build. it would be nice to get a later revision and also the async version if any of that is ready to go.

**Comment by drieseng** [comment]
We've released [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) a few weeks ago.
Note that the corresponding NuGet package is marked pre-release.
