### ISSUE TITLE
Stay connected question

### ISSUE THREAD

**Issue by Miroslav-S** [sshnet/SSH.NET#608]
Hi I am new to SSH.NET and C# too. I have question about use of SshClient.
I am using Visual studio 2017 community.
I am connecting from win 10 pc to Raspberry pi 4B - Buster. Everything works fine.
But do I always have to connect client like:

` private void GON_Click(object sender, EventArgs e)
        {
            using (var client = new SshClient("101.100.100.100", "pi", "Rpi4"))
            {
              client.Connect();
              client.RunCommand("gpio mode 7 out");
              client.Disonnect();
            }
           }`

Can I just somewhere initialize  

`var client= new SshClient("101.100.100.100", "pi", "Rpi4")
client.Connect();`

And then use it in other classes - for example in the buttons click?
` private void BUTOPEN_Click(object sender, EventArgs e)
{client.RunCommand("gpio write 7 1")}`
Thanks in advance for your reply.

**Comment by drieseng** [comment]
@Miroslav-S Yes, of course this is possible. Another way of dealing with this, is using a pool of connections. However, in your case it may be enough to have a factory that returns a singleton instance and which only (disposes the current and) creates a new connection when the singleton instance is "broken".
