### ISSUE TITLE
SSH session is terminated unexpectedly (nonexistent channel)

### ISSUE THREAD

**Issue by pangapp** [sshnet/SSH.NET#609]
Hi,

We use SSH.NET to establish a tunnel with [node-http-proxy](https://github.com/http-party/node-http-proxy).

It works perfectly by using shell SSH client.
With SSH.NET, the connection will drop unexpectedly with the error: ProtocolError data packet referred to nonexistent channel 3.

This will happen easily if multiple channels are open and closed rapidly, then the whole session will be dropped unexpectedly.

Any idea?

**Comment by drieseng** [comment]
Please provide a complete (and yet minimal) repro for this.

**Comment by drieseng** [comment]
Please reopen this issue if you have more information.

**Comment by ck-levin** [comment]
Hi @drieseng , 

Here is the sample project [SshSample.zip](https://github.com/sshnet/SSH.NET/files/4986785/SshSample.zip) and hope it helps to reproduce the issue.

You may want to change the following variables:
`static string ProxyHost = "XXX"; // proxy host`
`static string ProxyUsername = "XXX"; //  proxy host username`
`static string ProxyPassword = "XXX"; // proxy host password`
`static int ProxyRemotePort = 8080; // remote port`
`static string LocalHostIP = "127.0.0.1"; // localhost IP`
`static int LocalHostPort = 80; // localhost port`
