### ISSUE TITLE
Unable to connect to FileZilla

### ISSUE THREAD

**Issue by mjanulaitis** [sshnet/SSH.NET#616]
I have a FileZilla server which I can connect using the FileZilla client.  When connecting with the FileZilla Client I get the following messages.  I have tried port 21 and 990.  Port 22 does not connect.

Status:	Connecting to x.x.x.x:990...
Status:	Connection established, initializing TLS...
Status:	Verifying certificate...
Status:	TLS connection established, waiting for welcome message...
Status:	Logged in
Status:	Retrieving directory listing...
Status:	Directory listing of "/" successful
Status:	Connection closed by server

When using this client library I with the following format:

                var client = new SftpClient(hostname, 990, username, password);
                client.Connect();

I see the connection on my server and it responds however the client throws the following exception:

Socket read operation has timed out after 30000 milliseconds

With a stack trace of:

   at Renci.SshNet.Abstractions.SocketAbstraction.Read(Socket socket, Byte[] buffer, Int32 offset, Int32 size, TimeSpan timeout)
   at Renci.SshNet.Session.SocketReadLine(TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

I have tried connecting with port 21, 22 and 990.

**Comment by darinkes** [comment]
Port 21 and 990 are not the correct Ports for SFTP. This requires SSH-Server on Port 22.
Maybe you want to use an FTPS-Library?

Port 21 => FTP
Port 22 => SSH (SFTP is part of SSH)
Port 990 => FTPS

This library is for SSH and therefore just SFTP is supported.

**Comment by mjanulaitis** [comment]
@darinkes I understand but as you can see I listed port 22 as well.  I have FTPS working on my own now.  I thought the FileZilla client was connecting with SFTP but apparently it's FTPS.  So my mistake.

**Comment by darinkes** [comment]
Is there maybe an option to enable SFTP in Filezilla?
Your stacktrace reads like there was no answer from the server.
Can't test it right now, but maybe later.

**Comment by mjanulaitis** [comment]
I do now know if this is an option.  I believe I need to setup an SSH server instead of using Filezilla.  My mistake.
