### ISSUE TITLE
.Net Framework app is unable to connect.

### ISSUE THREAD

**Issue by mjanulaitis** [sshnet/SSH.NET#618]
I have a .Net Framework 4.7.2 application running version Renci.SshNet 2016.1.0.0.  When I attempt to connect I get the following error:

'An attempt was made to access a socket in a way forbidden by its access permissions'

Both Putty and Windows SSH Client are able to connect without issue.

Both the client and server are running on my dev machine therefore I did not open my firewall.

**Comment by darkoperator** [comment]
Have you looked at the different answers here? https://stackoverflow.com/questions/10461257/an-attempt-was-made-to-access-a-socket-in-a-way-forbbiden-by-its-access-permissi Does not seem to be a library issue but more of an OS socket error

**Comment by mjanulaitis** [comment]
I looked however both Putty and Windows SSH Client work so I'm not following how it's a socket issue.

**Comment by mjanulaitis** [comment]
However, I just tried with my IP address instead of my hostname and bam I was able to move forward to the next error. Access Denied.  So I guess this is closed.  For some reason the socket code is not able to connect with the hostname.
