### ISSUE TITLE
How can I generate an OpenSSH key pair?

### ISSUE THREAD

**Issue by SuperJMN** [sshnet/SSH.NET#626]
Can SSH.NET be used to generate keys? If it can not, is there a good way using .NET and C# to do it?

Thanks!

**Comment by natopedroso** [comment]
I want to know it too

**Comment by OgreTransporter** [comment]
Maybe this one?

https://github.com/ShawInnes/SshKeyGenerator

**Comment by IgorMilavec** [comment]
@SuperJMN was the question answered, can you please close the issue or provide feedback?
