### ISSUE TITLE
Running more than one command

### ISSUE THREAD

**Issue by madsholme** [sshnet/SSH.NET#627]
If i run one command, it works fine, but if i try and run a few it causes an exception, so how do i run more than one command?

i tried:

```
                using (var client = new SshClient(hostip, YYYYYYY, XXXXXXXX))
                {
                    

                    try
                    {
                        client.Connect();
                        var sshcommand = client.CreateCommand("configure terminal");
                        var sshcommand2 = client.CreateCommand("nint " + port);
                        var output = client.RunCommand(sshcommand.CommandText).Result;
                        MessageBox.Show(output.ToString());      
                        var output2 = client.RunCommand(sshcommand2.CommandText).Result;
                        MessageBox.Show(output2.ToString());               
                        client.Disconnect();
                    }
                    catch (Exception ex)
                    {

                        MessageBox.Show(ex.ToString());
                    }
                }
```

this just causes an exception
Exception thrown: 'Renci.SshNet.Common.SshConnectionException' in Renci.SshNet.dll that says "Renci.SshNet.Common.SshConnectionException: Client not connected."

so i guess i have to use CreateShellStream when running more than one command, but i am having a hardtime finding any examples on how to do this?

**Comment by darkoperator** [comment]
There is no state with RunCommand since it is not a full terminal, similar to using plink. You will have to look at sing shell streams in the cae of gear like Cisco.

**Comment by madsholme** [comment]
thanks, do you have any examples on how to use shellstream? im having a hard time finding any examples on it?

**Comment by madsholme** [comment]
seems i managed to figure it out, so here is the answer for anyone else in the same situation

`                 using (var sshclient = new SshClient(ip, user, pass))
                 {
                    int milliseconds = 5000;
                    sshclient.Connect();

                    var sshStream = sshclient.CreateShellStream("", 80, 40, 80, 40, 1024);
                    sshStream.Write("configure terminal\n");
                    System.Threading.Thread.Sleep(milliseconds);
                    sshStream.Write("int Gi0/9\n");
                    System.Threading.Thread.Sleep(milliseconds);
                    sshStream.Write("shutdown\n");
                    System.Threading.Thread.Sleep(milliseconds);
                    sshStream.Write("no shut\n");


                    sshclient.Disconnect();
                }`
