### ISSUE TITLE
An established connection was aborted by the software in your host machine.

### ISSUE THREAD

**Issue by HantsTerrier** [sshnet/SSH.NET#628]
I am trying to connect to an FTP site but getting the following error message "An established connection was aborted by the software in your host machine."

The code is used to connect to multiple other sites and works successfully, the site getting this error worked until last week.

we are using Renci.SSH.Net v2013.4.7

This is the code snippet falling over on the sftp.Connect();

            using (var sftp1 = new Renci.SshNet.SftpClient(connectionInfo))
            {
                try
                {
                    sftp1.Connect();

the connectionInfo variable is created by the code below and the parameters are all populated correctly.

var connectionInfo = new PasswordConnectionInfo(HostName, Port, UserName, Password);

Does anybody have any ideas?

Thanks

**Comment by darkoperator** [comment]
You mention FTP and not SSH, there is a difference between FTP over SSL (FTPS) and the SFTP extension of the SSH protocol. They are not the same, just want to make sure you  are not using the lib with the wrong service. 

Sent from my iPhone

**Comment by HantsTerrier** [comment]
Hi DarkOperator,

Thanks for your response. 

I've been rumbled in that I have no real idea what I'm doing in this area, it is SSH protocol we're using.  as I said, it has worked until last week.

**Comment by drieseng** [comment]
@HantsTerrier Were you able to resolve this issue? If not, do you have any extra information you can share?

**Comment by IgorMilavec** [comment]
Closed due to inactivity
