### ISSUE TITLE
Exception Creating either ConnectionInfo or SftpClient  Could not load type 'System.Security.Cryptography.HMACRIPEMD160

### ISSUE THREAD

**Issue by pfly9000** [sshnet/SSH.NET#635]
Exception creating a client in F# Visual Studio 2019 SSH.NET.2016.1.0
SSH.net was installed in VS with NuGet.

System.TypeLoadException
  HResult=0x80131522
  Message=Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  Source=Renci.SshNet
  StackTrace:
   at Renci.SshNet.ConnectionInfo..ctor(String host, Int32 port, String username, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword, AuthenticationMethod[] authenticationMethods)
   at Renci.SshNet.ConnectionInfo..ctor(String host, String username, AuthenticationMethod[] authenticationMethods)
   at cat1.catSftp.sftpExample@33.Invoke(Unit unitVar) in C:\Users\pflynn\source\repos\CATWeb1\CATWeb1\sftper.fs:line 35
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 398
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in E:\A\_work\130\s\src\fsharp\FSharp.Core\async.fs:line 109

**Comment by drieseng** [comment]
Please provide a minimal repro.

**Comment by pfly9000** [comment]
Sorry for not including this originally.  I was able to get this error just copying the F# snippet from here: http://fssnip.net/7U7/title/SFTP-with-SSHNet 
and calling it from a unit test in my project where I was having and issue loading the dll.
I have added all of the System.Security.Cryptography packages as dependencies to no avail.

my target .NET framework is 4.7.2

It dies when I try to create the new SFTPClient.

namespace cat1
module catSftp = 
    open Renci.SshNet
    

    /// FSharp Async wrapper for SSH.NET SFTP
    type SftpClient with
        member x.ListDirectoryAsync path =
            Async.FromBeginEnd((fun(iar,state) ->
                x.BeginListDirectory(path, iar, state)), x.EndListDirectory)

        member x.DownloadFileAsync path output =
            Async.FromBeginEnd((fun(iar,state) ->
                x.BeginDownloadFile(path, output, iar, state)), x.EndDownloadFile)

        member x.UploadFileAsync input path =
            Async.FromBeginEnd((fun(iar,state) ->
                x.BeginUploadFile(input, path, iar, state)), x.EndUploadFile)
            |> Async.Catch

        member x.SynchronizeDirectoriesAsync sourcePath destinationPath searchPattern =
            Async.FromBeginEnd((fun(iar,state) ->
                x.BeginSynchronizeDirectories(
                    sourcePath, destinationPath, searchPattern, iar, state)),
                x.EndSynchronizeDirectories)
            |> Async.Catch

    let downloadDir = @"c:\temp"
    let uploadfile = @"c:\temp\file.txt"

    let sftpExample host port username (password:string) =
        async {
            let workDir = "workingDir"

           

           
            use client = new SftpClient(host, port, username, password)
            client.Connect()
            printfn "Connected to %s" host

            // Change directory:
            client.ChangeDirectory workDir

            // List files in directory:
            let! listDirectory = client.ListDirectoryAsync workDir
            listDirectory |> Seq.iter(fun file ->
                if file.IsDirectory then printfn "/%s" file.Name
                else printfn "%s" file.Name)

            // Download a file:
            (*let fileName = "manual_en.pdf"
            use fileStream = File.OpenWrite(Path.Combine(downloadDir, fileName))
            printfn "Downloading %s..." fileName
            do! client.DownloadFileAsync ("./download/"+fileName) fileStream
            printfn "Downloaded %s (%i bytes)" fileName fileStream.Length*)

            // Upload a file:
            (*client.ChangeDirectory "upload"
            use fileStream = new FileStream(uploadfile, FileMode.Open)
            printfn "Uploading %s (%i bytes)" uploadfile fileStream.Length
            client.BufferSize <- 4096u // bypass Payload error large files
            let! r = client.UploadFileAsync fileStream (Path.GetFileName uploadfile)
            match r with
            | Choice1Of2 _ -> printfn "Uploaded %s" uploadfile
            | Choice2Of2 err -> printf "Error uploading %s: %O" uploadfile err*)

        } |> Async.StartAsTask

    let test =
       sftpExample "SFTPURL" 22 "username" "password"


Thanks!

P

**Comment by Rob-Hague** [comment]
This would have been fixed somewhere between 2023.0.0 and 2024.0.0
