### ISSUE TITLE
nuget packages are far too outdated

### ISSUE THREAD

**Issue by michalkurz** [sshnet/SSH.NET#636]
Current nuget packages do not reflect important fixes. I would appreciate new nuget package and I do not care much if it is just a beta. 
If you make one, please include solution of #516 as it is kind of a show stopper for me and no workaround is good enough.

**Comment by mvalerio71** [comment]
CONSIDER also using Source Link to add source control metadata to your assemblies and NuGet packages.

https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/sourcelink

**Comment by mmillican** [comment]
Curious if there's any progress on publishing updated packages?

**Comment by drieseng** [comment]
@mmillican I'm getting there...

**Comment by drieseng** [comment]
@mvalerio71 Please submit an issue (or even better, a PR) for this.

**Comment by zeadgif** [comment]
Is there any update on this?

**Comment by drieseng** [comment]
I'm getting close, but the good weather here is a setback :p

**Comment by babin93** [comment]
Hi, 

What is your current workflow for deploying nuget packages ? Would there be a way to make it easier ? If so, I would be interested in helping.

**Comment by mmillican** [comment]
It's not a great solution by any means, but I ended up cloning the repo, building it locally and changing my reference to that instead of the Nuget version.

**Comment by zeadgif** [comment]
I tought so too, cloning locally and building it. But sadly the project im working on doesnt allow me to do that. And the packages are indeed too far outdated, im even working arround known bugs atm... Maybe we could as @babin93 sugested put in place a system to generate nugets automatically. 
This is by far the best ssh for .net, so im patiently waiting for the package to release..... :P

**Comment by babin93** [comment]
@zeadgif I am investigating to use this library for an enterprise project. I don't want to configure my CI to build this code and reference it. Another option would be to fork and generate a nuget from the fork that I would put on a private feed. But i would rather use the official Nuget source instead.

**Comment by drieseng** [comment]
@babin93 Building a release is an ordeal since target a myriad of legacy target frameworks. I have a Windows 8.1 VM that I use to build those, and combine that manually with the "modern" artifacts.

I was hoping to fix #355 in the next beta, but the workaround that was mentioned in this issue does not work in a multithreaded application. The underlying issue in .NET Core has been fixed in .NET 5.0, but with some quirks. I'm still in doubt on how to proceed.

**Comment by darkoperator** [comment]
I would say release the beta and in the notes mention the bug as one of the known ones being worked on and the scenarios. Also mention the deprecation of older frameworks like 3.5, phone ..etc

**Comment by drieseng** [comment]
@darkoperator Wanna help by creating an issue for this, and prepare a section to include in the release notes in which the plans are outlined (proposal is welcome) and where we sollicit for feedback.

**Comment by darkoperator** [comment]
Sure, will create one right after I finish sone … urrrggg ….  VBA code for work

**Comment by drieseng** [comment]
My condolences :p

**Comment by mcrossley** [comment]
Any progress on this? I'm eagerly awaiting a updated nuget package!

**Comment by drieseng** [comment]
We released [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) a few weeks ago.
