### ISSUE TITLE
Basic issue: compiling library

### ISSUE THREAD

**Issue by manthrax-9** [sshnet/SSH.NET#645]
Hi all, 

I'm trying to use library in VS2017 project with Framework 4.5.2.

When I open Renci.SshNet.VS2017 project and try to build Renci.Sshnet it returns theattached errors.

What's the solution? Sorry for this really really basic topic!
![Cattura](https://user-images.githubusercontent.com/62698064/77638686-d6837a00-6f57-11ea-8a03-47c8003c92cb.JPG)

**Comment by babin93** [comment]
I think you should either install dotnet core or edit the project file to remove entries mentionning .Net core or Standard

**Comment by drieseng** [comment]
@manthrax-9 Try installing the latest update for VS 2017. You're [not alone](https://github.com/dotnet/sdk/issues/8980) having this issue with VS 2017.
