### ISSUE TITLE
Socket read operation has timed out after 30000 milliseconds. Is it possible to increase the timeout settings?

### ISSUE THREAD

**Issue by kristoledo** [sshnet/SSH.NET#649]
Hi,

I am having the read operation timed out error while downloading a number of files. It will just cut out in the middle. But running it again will download the remaining few files. Would it be possible to increase the timeout setting?

**Comment by drieseng** [comment]
You can control the timeout using **ConnectionInfo.Timeout**:

```cs
var connectionInfo = new ConnectionInfo("host", "user", new PasswordAuthenticationMethod("user", "pwd"));
connectionInfo.Timeout = TimeSpan.FromSeconds(60);

using (var client = new SftpClient(connectionInfo))
{
    ...
}
```
