### ISSUE TITLE
KEX negotiation failed using curve25519-sha256

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#653]
With the **develop** branch, I've already ran a few times into a KEX failure:

> Renci.SshNet.Common.SshConnectionException: Key exchange negotiation failed.
>    at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
>    at Renci.SshNet.Session.Connect()
>    at Renci.SshNet.BaseClient.CreateAndConnectSession()
>    at Renci.SshNet.BaseClient.Connect()

I'm testing again OpenSSH 8.0p1 (Ubuntu 19.10 Desktop).

The following simple code fragment should allow you to reproduce this issue:

```cs
using Renci.SshNet;
using System;
using System.Linq;
using System.Threading.Tasks;

class ConnectDisconnect
{
    private static void Main(string[] args)
    {
        if (args.Length != 3)
        {
            Console.Error.WriteLine("Please specify the host name, user name and password.");
            return;
        }

        var hostName = args[0];
        var userName = args[1];
        var password = args[2];

        var tasks = Enumerable.Range(1, 10).Select(y =>
            {
                return Task.Factory.StartNew(() =>
                    {
                        for (var i = 0; i < 500; i++)
                        {
                            using (SftpClient client = new SftpClient(args[0], userName, password))
                            {
                                client.Connect();
                                Console.Write(".");
                            }
                        }
                    });
            }).ToArray();

        Task.WaitAll(tasks);
    }
}
```
**Note:**
It could take a while for this issue to reproduce.

**Comment by drieseng** [comment]
@darinkes Can you investigate this issue ? Without a fix for this issue, I'll need to disable at least **curve25519-sha256**. I'll see if can find time to thouroughly test the other new key exchange methods as well.

**Comment by darinkes** [comment]
@drieseng I tried to reproduce it, but 10.000 connects were successful in my setup.
*Maybe* I oversaw one area needing ToBigInteger2. Since the issue happens random(?) and I guess it depends on the generated KEX-Data.

I went back to my commit, you made some changes meanwhile, and let it run over the day.
Then we can narrow it down, I think.

`git checkout -b elliptic 546e2b9ece47f1982811a0bcdafa93fec7c5d0e3`

I was able to reproduce with current origin/develop Commit 2c1a4d95961b174fe9950ee1a5995bd73a20173a, not yet with elliptic checkout 546e2b9ece47f1982811a0bcdafa93fec7c5d0e3.

Hot candidate is commit c0da2c14fb133637245ed30cb029c1d2f95a0c4a.

**Comment by drieseng** [comment]
Thanks for looking into this, and pinpointing the culprit (me!).
I'll have to review those changes again :(

**Comment by darinkes** [comment]
Oh, thats not how i meant it!
Was just suprised, cause I was sure I had it running for days.
Feel free to ping me for testing any changes!

**Comment by darinkes** [comment]
FWIW, thats my test: https://gist.github.com/darinkes/7e2cc25580b6dc247b8def92f1067ef7
Not fast but sshd in debug and tests all variations.

**Comment by drieseng** [comment]
@darinkes No problem, I can admit my mistakes. Like I always say: "I've made many mistakes, but I'm not married". My gf doesn't always appreciate this. Not sure why.

**Comment by drieseng** [comment]
I've fixed my changes, and up to now I've not been able to reproduce this issue again.
I'll commit the fix tomorrow.
