### ISSUE TITLE
Nugget Release for Beta

### ISSUE THREAD

**Issue by darkoperator** [sshnet/SSH.NET#655]
Issue to track changes that will be in the next NuGet beta release.

New: 

- Supports for Key Exchange algorithms: curve25519-sha256, curve25519-sha256@libssh.org, ecdh-sha2-nistp256, ecdh-sha2-nistp384 and ecdh-sha2-nistp521.

- Support for host key algorithms: ssh-ed25519, ecdsa-sha2-nistp256, ecdsa-sha2-nistp384 and ecdsa-sha2-nistp521

- ED25519 in OpenSSH key format

- key exchange more efficient with the use of byte[] in internal structures.

Fixes:

- SCP filename error on upload. 
- Socks 5 connection port written to wire correction. 
- SftpClient and NetConfClient can re-establish connection using a existing client instance object.
- Support for .Net Standard 2.0

**Comment by darkoperator** [comment]
this is the main points for the next nugget release I found in the issues @drieseng

**Comment by drieseng** [comment]
Let me know if something is missing from the [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) release notes.
