### ISSUE TITLE
Please add code documentation

### ISSUE THREAD

**Issue by mubed** [sshnet/SSH.NET#657]
At least a list of available methods.

**Comment by mmoo9154** [comment]
@mubed, are you suggesting to add an examples section to the CHM help file that is generated?  If not, where are you thinking the exaples should go.

Also, if there is a specific example you are looking for, it would be interesting to know.

**Comment by mubed** [comment]
@mmoo9154 
Well, CHM is great, but you cannot google for a method in it or link a class description file in StackOverflow like you can do it for the .Net framework itself.

I remember there was a code doc output that would generate HTML hierarchical pages. The best would be in my opinion to generate such a doc and put it on the Wiki section of GitHub.

**Comment by Rob-Hague** [comment]
https://sshnet.github.io/SSH.NET/
