### ISSUE TITLE
Support of .net core 3.1

### ISSUE THREAD

**Issue by GeorgScholz** [sshnet/SSH.NET#663]
Is there a branch which supports .net core 3.1?  Ideally it should be possible to use the library in azure webservices for accessing sftp servers.

**Comment by doug62** [comment]
+1

**Comment by GeorgScholz** [comment]
Interestingly, I was able to install the 2016.1.0 release of ssh.net into a new .net core 3.1 project. 
So far, connecting and downloading files from an sftp server works fine!

**Comment by doug62** [comment]
I was able to get it to build by having it ignore the NU1605 error, and it does run with 3.1

**Comment by zhouandke** [comment]
Please update to support .Net standard 2.0
When I use command "dotnet.exe publish", error NU1605 stop the build action

**Comment by drieseng** [comment]
The next (beta) release will support .NET Standard 2.0.
