### ISSUE TITLE
Multi host connection vb.net

### ISSUE THREAD

**Issue by fokenhelpmy** [sshnet/SSH.NET#664]
Hi Guys.
Just starting out in the world of Software development(If you guys will call visual basic that).
I decided to pick up a small project that will fit my needs.
As with everything there is a learning curve.

So here is where im stuck

I would like to reboot about 10 machines at once using my app
i am trying to figure out how to specify multiple server addresses
ie Dim connInfo As New Renci.SshNet.PasswordConnectionInfo("192.168.1.9,192.168.1.10,192.168.1.11", "username", "Password")

Thanks a mill
Rob

**Comment by tawaraja** [comment]
Hi,

Must it be rebooted at the same time? Else, you could just do a for loop to reboot the server.
If it must be done at the same time, then I would consider creating 10 , connInfo_0 to connInfo_9 to pull the trigger exactly at the same time.

Regards,
Raja

**Comment by fokenhelpmy** [comment]
maybe not 100% at the same time, but send reboot command to 1 then 2 then 3 etc will work ass-well
