### ISSUE TITLE
Wait till command is completely executed

### ISSUE THREAD

**Issue by jufelka** [sshnet/SSH.NET#666]
I want to execute command completely before the next command line is taken. Each command should complete the processing and then move to next command. Can't find how to do this. So now I use pauses after each command, like this:
```
var cmd = client.CreateCommand("apt-get update -y");
cmd.Execute();
Thread.Sleep(20000);	
cmd = client.CreateCommand("apt-get install git -y");
cmd.Execute();
Thread.Sleep(40000);
....
```

**Comment by drieseng** [comment]
This is indeed something we should add in the form of:
* `WaitForExit()` and `WaitForExit(TimeSpan timeout)` overloads
* An `Exited` event

It is in a way linked to #650.

**Comment by Rob-Hague** [comment]
`Execute` should wait for a command to complete, at least in 2024.1.0 and above
