### ISSUE TITLE
Close of channel should not dispose ShellStream

### ISSUE THREAD

**Issue by drieseng** [sshnet/SSH.NET#672]
We currently dispose the **ShellStream** when the underlying channel is closed.
This can lead to a **NullReferenceException** in, for example, `ShellStream.Expect(TimeSpan timeout, params ExpectAction[] expectActions)`.

In case of `ReadLine(TimeSpan timeout)`, we should return **null** when the channel has been closed.

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
