### ISSUE TITLE
Interactive Authentication with Private Key + Password?

### ISSUE THREAD

**Issue by chipmunkofdoom2** [sshnet/SSH.NET#677]
I'm trying to connect to a server that requires private key and password authentication. I would like to use a `KeyboardInteractiveAuthenticationMethod` to get the users' passwords. The reason I don't want to use `PasswordAuthenticationMethod` is because I want to be able to enforce password policy. I want to `expire` user passwords and have them interactively create a new one from within my C# application. 

However, when I try to use both `PrivateKeyAuthenticationMethod` and `KeyboardInteractiveAuthenticationMethod`, I get an error message:

    SshAuthenticationException: 'No suitable authentication method found to complete authentication (password).'

When I give the `SshClient` a `PasswordAuthenticationMethod`, it works just fine, but I want the login to be interactive for the reasons I mentioned above. Is there any way to do what I am attempting with Ssh.Net?

Code:

    void ConnectToSsh()
    {
    	var AuthenticationMethods = new List<AuthenticationMethod>();
    	AuthenticationMethods.Add(new PrivateKeyAuthenticationMethod(UserName, new PrivateKeyFile(KeyFilePath)));
    	//Without the line below, this code generates the error specified above.
    	AuthenticationMethods.Add(new PasswordAuthenticationMethod(UserName, Password));
    	var Interactive = new KeyboardInteractiveAuthenticationMethod(UserName);
    	Interactive.AuthenticationPrompt += Interactive_AuthenticationPrompt;
    	AuthenticationMethods.Add(Interactive);
    	var info = new ConnectionInfo(Server, Port, UserName, AuthenticationMethods.ToArray());
    	using (var client = new SshClient(info))
    		client.Connect();
    }

    void `Interactive_AuthenticationPrompt(object` sender, AuthenticationPromptEventArgs e)
    {
    	foreach (var prompt in e.Prompts)
    	{
    		Console.WriteLine(prompt.Request);
    		prompt.Response = Console.ReadLine();
    	}
    }

**Comment by biocoder-frodo** [comment]
No, since you do not control the server?

**Comment by chipmunkofdoom2** [comment]
What? I own the target server and have root privileges.

**Comment by biocoder-frodo** [comment]
This is not an issue of SSH.NET.
If the server is configured to allow/require private key and password authentication only, it is pointless to let the client offer the KeyboardInteractiveAuthenticationMethod to the server. It will just ignore you.

You can implement client-side password policy enforcement by using the PasswordAuthenticationMethod (not in one line of code) but that would be pointless for anyone *not* using your client.

If you want to use KeyboardInteractiveAuthenticationMethod to enforce a passwordpolicy, you should find or write an SSH server that implements such policy via the Keyboard Interactive protocol.
