### ISSUE TITLE
sshCmd returns nothing when wildcard is used

### ISSUE THREAD

**Issue by Traxxel** [sshnet/SSH.NET#678]
This command returns an empty string:
`sshCmd = sshClient.RunCommand("ls -1 *TEST*")`
even if file like myTEST12 or TESTfile exists

**Comment by darinkes** [comment]
I'm using wildcards all the time and works for me.

Are you sure the directories are correct? RunCommand runs in the default directory, usually /home/$USER

**Comment by Traxxel** [comment]
`if me == idiot { apologize } ;`
Sorry, of course I forgot that...
Now I am using 
`cd /dir1/dir2 && ls- 1 *TEST*`
That works, but can I make some kind of "cd /dir1/dir2" and all then following commands are running in that dir?

**Comment by darinkes** [comment]
You can if you use the ShellStream.
SSH-RunCommand runs in a new context everytime.
