### ISSUE TITLE
SOCKS version 67 is not supported

### ISSUE THREAD

**Issue by reang** [sshnet/SSH.NET#68]
`.........

Exception thrown: 'System.NotSupportedException' in Renci.SshNet.dll
System.NotSupportedException: SOCKS version 67 is not supported.
..........`

How to fix these?
NB:
VS2015
Win10

**Comment by drieseng** [comment]
What version of **SSH.NET** are you using ?
Also please provide the full stacktrace.

**Comment by reang** [comment]
I use the latest from Nuget

`Exception thrown: 'System.NotSupportedException' in Renci.SshNet.dll
System.NotSupportedException: SOCKS version 67 is not supported.
   at Renci.SshNet.ForwardedPortDynamic.HandleSocks(IChannelDirectTcpip channel, Socket clientSocket, TimeSpan timeout)
   at Renci.SshNet.ForwardedPortDynamic.ProcessAccept(Socket clientSocket)
`

**Comment by drieseng** [comment]
What SOCKS client are you using ?

**Comment by reang** [comment]
Solved with "socks4://127.0.0.1:1081"
thanks
