### ISSUE TITLE
Sponsor option for sshnet organisation?

### ISSUE THREAD

**Issue by webprofusion-chrisc** [sshnet/SSH.NET#681]
Hi, I would like to sponsor (via github) the development of ssh.net because I depend on it for my project. Please can you enable the sponsor option for your github organisation or project.

Thanks!

**Comment by drieseng** [comment]
I'm currently setting up sponsorship for my account. Setting it up for an organization (even if there's only one active member), seems complicated.

Are you ok with me just enabling sponsorship for my account?

What price tier(s) were you thinking abount? I have no idea what is common.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes that's fine. Once enabled you should promote it directly in the readme for your projects.  

It's nice if the sponsoring person/org can show up against the project it's using (as a sponsor) but it's not essential. I'm currently sponsoring a few other devs/projects as well. It's easier to consolidate to github and pay through a business than have several opencollective/patreon etc bills.

It's good to offer both casual and serious tiers - I've been put off sponsoring some projects because they're asking for more than I'm looking to give. $5 per month upwards ($10,$15,$25,$50 etc) - I don't know how many options you get. Worst case nobody sponsors you but if a project is active, like maybe updating published nugets (or publishing replacement ones), it's much more likely to get sponsors (especially companies who need your library).

Thanks for continuing to work on your library, I know a lot of people use it and many of those will be businesses willing to sponsor if you ask.

**Comment by drieseng** [comment]
@webprofusion-chrisc, I've now enabled the sponsor option for SSH.NET:
https://github.com/sponsors/sshnet

It's a little light on content, so keep the feedback coming.

**Comment by webprofusion-chrisc** [comment]
Cool! I've sponsored via @certifytheweb
It would be nice if the github 'sponsor' button showed up on the ssh.net repo to attract other sponsors, I think maybe that's a per repo setting.

**Comment by drieseng** [comment]
You should now see the sponsor button on the **SSH.NET** repo.
Thanks for supporting us!
