### ISSUE TITLE
.Disconnect hangs the thread on MacOS

### ISSUE THREAD

**Issue by delebru** [sshnet/SSH.NET#686]
```
var ssh = new SshClient(hostName, username, password);
ssh.Connect();
var command = ssh.RunCommand("whoami");
Console.WriteLine($"Command result: {command.Result}");
ssh.Disconnect();
ssh.Dispose();
```

The above code runs fine on Windows but hangs on MacOS. It will connect and run the remote command just fine, but it never gets past the .Disconnect. If there is no .Disconnect, it will hang on .Dispose.

Tested with .NET Core 2.2 and 3.1 and v2016.1.0.

Downgrading to v2013.4.7 fixes the issue.

**Comment by marcelcandidoferreira** [comment]
Same issue here

**Comment by scottpidzarko** [comment]
See #355 

Does the issue occur on the latest build on develop?

**Comment by delebru** [comment]
@scottpidzarko thanks for the reference! Didn't find an existing issue on my terrible search... I'd be happy to test it, where can I grab the latest develop build? I'm not being able to compile from source.

**Comment by drieseng** [comment]
@delebru Please try [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1), and let me know it that fixed the issue for you.

**Comment by delebru** [comment]
@drieseng works fine on 2020.0.0-beta1

**Comment by drieseng** [comment]
@delebru Thanks for the feedback!
