### ISSUE TITLE
Server response does not contain SSH protocol identification.

### ISSUE THREAD

**Issue by PierreVanvolsem** [sshnet/SSH.NET#690]
Hi,

I can't connect to my ssh server. I am suspecting "StrictHostKeyChecking" is causing a problem. The error that I'm having when trying to connect is the following: Renci.SshNet.Common.SshConnectionException: 'Server response does not contain SSH protocol identification.'

Thank you for your help !

**Comment by drieseng** [comment]
@PierreVanvolsem Can you share why you closed this issue? Thanks! (or should I say "Bedankt!"?)

**Comment by PierreVanvolsem** [comment]
Hi,
I fixed it by installing this package: PM> Install-Package SSH.NET.Fork -Version 2018.8.25.2

**Comment by drieseng** [comment]
@PierreVanvolsem [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1) is now available. Can you confirm that this release fixes this issue? Thx!

**Comment by PierreVanvolsem** [comment]
@drieseng I can confirm that the release fixes this issue. Thank you for fixing this issue !

**Comment by Vandersteen** [comment]
Unfortunately, we are still encountering this issue sporadically with 2020.0.0-beta1

**Comment by avadesh** [comment]
This is still an issue in the release : 2020.0.0-beta1
We are using BrickFTP server.

trace :

at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()
