### ISSUE TITLE
MS WINDOWS .NET CORE WPF APP | Port forwarding with SSH.NET does not work!

### ISSUE THREAD

**Issue by sm-a** [sshnet/SSH.NET#695]
I have now a .net core WPF app (previous a MS WINDOWS UWP APP - https://github.com/sshnet/SSH.NET/issues/630) and it is the same failure. The UWP APP is no longer being developed but this WPF APP is under development.

If I use the following code and then call the forwarded port 8443 it loads endlessly in the browser and nothing happens. When I use the "ssh centos@serverip -L 8443:localhost:443" command then it works but not with SSH.NET.

I use for test a AWS lightsail CentOS 7 VPS.

Has nobody any idea to fix this?
I use the following version: 2020.0.0-beta1

Here my actual code:

```
ConnectionInfo conInfo;
var pk = new PrivateKeyFile(smaRSAKey);
var keyFiles = new[] { pk };

var methods = new List<AuthenticationMethod>();
methods.Add(new PrivateKeyAuthenticationMethod(smaUserName, keyFiles));

conInfo = new ConnectionInfo(smaHost, 22, smaUserName, methods.ToArray());

using (var client = new SshClient(conInfo))
{

    client.KeepAliveInterval = new TimeSpan(0, 0, 30);
    client.ConnectionInfo.Timeout = new TimeSpan(0, 0, 20);
    client.Connect();

    var port = new ForwardedPortLocal("localhost", 8443, smaHost, 443);
    client.AddForwardedPort(port);

    port.Start();

    MessageBox.Show("If finish then click OK!");

    port.Stop();
    client.Disconnect();

}
```

**Comment by darinkes** [comment]
>     var port = new ForwardedPortLocal("localhost", 8443, smaHost, 443);

This is not the same you do with your ssh-command "ssh centos@serverip -L 8443:localhost:443".
To do the same it should look like this:

` var port = new ForwardedPortLocal("127.0.0.1", 8443, "127.0.0.1", 443);`

Note: I avoid using "localhost" since I dont want to rely on working DNS.

**Comment by sm-a** [comment]
@darinkes Perfect. Now it works. Thank you very much.
