### ISSUE TITLE
Heap Inspection - Use SecureString to store password

### ISSUE THREAD

**Issue by rhyswynn** [sshnet/SSH.NET#697]
Hi there, any chance to modify ConnectionInfo.cs to set the password variable as SecureString instead of String, to improve the security of this library?  I'm not a developer, I could probably manage, but I don't want to maintain my own version and it would probably take me half a day to sort it out properly.
Thank you

**Comment by drieseng** [comment]
I'm inclined not to do this. There's some serious talk to [obsolete](https://github.com/dotnet/runtime/issues/30612) SecureString
