### ISSUE TITLE
SSH Operation Consuming Large Amounts of CPU While Waiting

### ISSUE THREAD

**Issue by weberms** [sshnet/SSH.NET#702]
After connecting to remote host using SshClient and executing a long running command asynchronously using SshCommand.BeginExecute() the process takes a large amount of CPU (25-35%+) waiting on the command to complete.

                    `using (SshCommand command = client.CreateCommand(commands))
                    {
                        IAsyncResult result = command.BeginExecute();

                        StreamReader standardOutput = new StreamReader(command.OutputStream);
                        StreamReader errorOutput = new StreamReader(command.ExtendedOutputStream);

                        // Output stdout and stderr as data is received
                        Task stdOutTask = ReadStandardOutAsync(standardOutput, result);
                        Task stdErrTask = ReadStandardErrorAsync(errorOutput, result);

                        // Wait until the command finishes
                        command.EndExecute(result);

                        // Ensure all output has been received
                        stdOutTask.Wait();

                        // Ensure all error output has been received
                        stdErrTask.Wait();

                        executeResult.ExitCode = command.ExitStatus;
                        executeResult.ErrorsReceived = _errorReceived;
                    }`

**Comment by xforever1313** [comment]
I've run into this too.  To workaround, I had to add a sleep in between each read operation from streams from the SshCommand class.  I went from 50%+ CPU usage down to under 1%.

An example of doing this is here:

https://github.com/xforever1313/SshRunAs/blob/1.3.0/SshRunAs/SshRunner.cs#L86

**Comment by Rob-Hague** [comment]
should be fixed with 2024.1.0
