### ISSUE TITLE
ScpClient (Upload)

### ISSUE THREAD

**Issue by AndriiMor** [sshnet/SSH.NET#708]
I tried to load file into remote  directory scpClient.Upload(info,"/tmp/basic_rpc"); where info is FileInfo but i get 
Exception has occurred: CLR/Renci.SshNet.Common.ScpException
An unhandled exception of type 'Renci.SshNet.Common.ScpException' occurred in Renci.SshNet.dll: 'scp: error: unexpected filename: '
   at Renci.SshNet.ScpClient.CheckReturnCode(Stream input)
   at Renci.SshNet.ScpClient.UploadFileModeAndName(IChannelSession channel, Stream input, Int64 fileSize, String serverFileName)
   at Renci.SshNet.ScpClient.Upload(FileInfo fileInfo, String path)
but for download command scpClient.Download("/tmp/basic_rpc/rpc.xml",info); it works fine, so I don't really understand why it's so

**Comment by rzk3** [comment]
This issue also applies when using DirectoryInfo, instead of FileInfo.

**Comment by drieseng** [comment]
@AndriiMor, @rzk3:
What version of SSH.NET are you using? This should be fixed in [2020.0.0-beta1](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0-beta1).
Please reopen this issue if you can still reproduce it with that version.
