### ISSUE TITLE
Failed to negotiate key exchange algorithm

### ISSUE THREAD

**Issue by csoumita2000** [sshnet/SSH.NET#717]
I am trying to connect to a SFTP server programmatically using C#. I am facing this issue when I try to call the connect() method.
The error is "Failed to negotiate key exchange algorithm". However, when I try to connect it using WinSCP Client, I am able to connect successfully. Could you please help?
Below is my code:

            using (SftpClient sftp = new SftpClient(host, 22, username, password))
            {
                sftp.Connect();

                using (var file = File.OpenWrite(ConfigurationManager.AppSettings["sourcePath"]))
                {
                    //do something....
                }

                sftp.Disconnect();
            }

**Comment by gavin1970** [comment]
Some of these might help.
[https://csharp.hotexamples.com/examples/Renci.SshNet/SftpClient/-/php-sftpclient-class-examples.html](url)

**Comment by csoumita2000** [comment]
Hi @gavin1970 ,

Thank you. I looked at the examples provided in the link you shared, but could not find anything which would help resolve the issue.
I am getting an error while connecting to the SFTP Server on this line : 

        using (SftpClient sftp = new SftpClient(host, 22, username, password))
        {
               sftp.Connect();<--this line gives error (Failed to negotiate key exchange algorithm.)
        }

Please find below the complete stack trace. 

Failed to negotiate key exchange algorithm.
at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()

I am able to connect to the SFTP Server using WinSCP client though.

Any help would be really appreciated.

**Comment by darkoperator** [comment]
Which version are you using? Support for multiple algorithms where added in the beta.

**Comment by csoumita2000** [comment]
@darkoperator Version 2016.1.0

**Comment by darkoperator** [comment]
Compile and use the beta, that version is limited in algorithms given the defaults of most systems now

**Comment by soumita-chowdhury** [comment]
Yes, I used the beta version and it started working fine. Thanks @darkoperator .
