### ISSUE TITLE
While connecting to Mac OS, throws - No suitable authentication method found to complete authentication (publickey,keyboard-interactive).

### ISSUE THREAD

**Issue by bogomal** [sshnet/SSH.NET#72]
I am not able to connect remotely to a Mac System (OS X 10.10.5) using Renci.SshNet library in a .NET application. The code I am using allows me to connect to any other linux OS systems such as RHL, Ubuntu etc. **I am able to connect to this Mac System thru putty.** But when I try to connect from my .NET application it gives me the following error -

> No suitable authentication method found to complete authentication (publickey,keyboard-interactive). Source - Renci.SshNet

This is my code. Please help

`public SshClient sshClient;
sshClient = new SshClient(ipAddress, port, username, password);
sshClient.KeepAliveInterval = TimeSpan.FromSeconds(60);
sshClient.Connect();`

**Comment by drieseng** [comment]
As the exception message states, you'll either need to use a **PrivateKeyAuthenticationMethod** or a **KeyboardInteractiveAuthenticationMethod**.

Your SSH server is not setup to accept "_regular_" password authentication.

Let me know if you need more help.

**Comment by drieseng** [comment]
Here's a code fragment that shows you how to use both private key and keyboard-interactive authentication:

``` cs
const string userName = "user XXX";

var keyboardInteractiveAuth = new KeyboardInteractiveAuthenticationMethod(userName);
keyboardInteractiveAuth.AuthenticationPrompt += (sender, args) =>
    {
        foreach (var authenticationPrompt in args.Prompts)
            authenticationPrompt.Response = "password XXX";
    };

var privateKeyAuth = new PrivateKeyAuthenticationMethod(userName,
                                                        new PrivateKeyFile("private key file name"));

var connectionInfo = new ConnectionInfo("HOST", 22, userName, privateKeyAuth, keyboardInteractiveAuth);

using (var client = new SshClient(connectionInfo))
{
    client.Connect();

    // perform your actions here
}
```
