### ISSUE TITLE
The connection was closed by the server:  (ByApplication)

### ISSUE THREAD

**Issue by anujtripathi04** [sshnet/SSH.NET#725]
Hi there,

Somehow I get an exception after I try to access an SFTP server running on an Windows 10 machine.

When I try to access the same server via WinSCP it works fine, however using the same configuration from RenciSSH throws the error "The connection was closed by the server:  (ByApplication)".

On the SFTP server logs I can notice that the connection is made but it gets terminated immediately.

Do you know if such issue is already known?

Thanks

**Comment by wickdninja** [comment]
I am having the same issue. Did you find a resolution?

**Comment by anujtripathi04** [comment]
Just upgrading it to the latest beta version and it was solved for me.
