### ISSUE TITLE
ShellStream doesn't write to shell

### ISSUE THREAD

**Issue by gexpult** [sshnet/SSH.NET#729]
I can successfully connect to the remote computer. However, ShellStream.WriteLine does not work properly:

```
            ShellStream sh = client.CreateShellStream("xterm", 0, 0, 0, 0, 16 * 1024);
            sh.WriteLine("echo > /tmp/something\n");
            sh.Flush();
            sh.Close();
```

This command never completes and the file is not created. If I set a breakpoint at WriteLine and delay the program, then it works. Likewise, using `System.Threading.Thread.Sleep(250);` is enough of a delay to allow the command to execute.

**Comment by gavin1970** [comment]
Try looking at this code, might help.
https://github.com/gavin1970/Linux-Commander/blob/master/Linux-Commander/common/Ssh.cs

I not sure what your trying to do with that WriteLine, but not sure it would do anything directly in a console.   Try
sh.WriteLine("echo gexpult > /tmp/something.txt");

**Comment by IgorMilavec** [comment]
@gexpult was the question answered? If so, please close the issue.
