### ISSUE TITLE
unwanted UTF-8 BOM sequence even when using ASCII encoding

### ISSUE THREAD

**Issue by TimHaydnJones** [sshnet/SSH.NET#73]
I am getting a UTF-8 BOM sequence in my output file even though I have changed my encoding to ASCII - what am I doing wrong? (or is it a bug)?

Dim methods = New List(Of AuthenticationMethod)()
methods.Add(New PasswordAuthenticationMethod(username, password)) 
Dim conn = New ConnectionInfo(servername, serverport, username, methods.ToArray())
conn.Encoding = System.Text.Encoding.GetEncoding("ASCII")
Using sftp As New SftpClient(conn)
    Try
          sftp.Connect()
          connected = True
     Catch ex As Exception
         connected = False
    End Try
    If connected Then
         sftp.WriteAllText(targetfilename, datastring)
    end if
End Using

**Comment by drieseng** [comment]
You should use the WriteAllText overload that allows you to specify the encoding: `WriteAllText(string path, string contents, Encoding encoding)`.

The encoding that you specify on the ConnectionInfo does not have any effect here.
Note that I'm aware that it's currently not clear what exactly `ConnectionInfo.Encoding` applies to.

**Comment by TimHaydnJones** [comment]
Brill - thanks ever so much for a quick response.
