### ISSUE TITLE
Single des encryption

### ISSUE THREAD

**Issue by jcassity** [sshnet/SSH.NET#731]
The single des encryption file exists, but we are unable to connect to a server using single des.

A current project I am on required this so I made a single line edit to allow it.
I am creating this issue before making a pull request since I assume there is a reason single des was not included as a supported encryption.

Can someone let me know if single des was indeed excluded purposefully?

**Comment by gavin1970** [comment]
Single DES has a 56-bit key and vulnerable.  Developers try to stay away from it.

**Comment by darinkes** [comment]
If you do this, please don't claim you use SSH for security reasons.

**Comment by jcassity** [comment]
Agreed that it's not secure, but sometimes due to the constraints of a project you have to use ugly methods. It seems odd to not be able to use the default library without making a one line change if you're in that situation.

**Comment by darinkes** [comment]
Using DES is not ugly, its irresponsible and unsupported for good reasons.

**Comment by gavin1970** [comment]
Just a suggestion, but a quick google search for AES will help you in a lot less grief later.

**Comment by jcassity** [comment]
Agreed that des is insecure and aes is better. It is not that I chose to implement des, it was that I needed to connect to a server only supporting des encryption with no option or ability for me to change this. For cases like this I wondered if it would be worth making the addition to the code.

**Comment by darkoperator** [comment]
You can fork it and keep the forked version for you app
