### ISSUE TITLE
Tests DLLs tagged as ransomware

### ISSUE THREAD

**Issue by v999dka** [sshnet/SSH.NET#737]
Hello everyone!

I'm a bit worried, I was scanning my pc as always when this happens

![imagen](https://user-images.githubusercontent.com/19328340/96719663-fa058a80-13a9-11eb-8a84-508debf50375.png)

It basically says that the Renci.SshNet.Tests.dlls are indeed infected.
Surely this is a bug with some encryption method that is involve with the ssh, but I want to get a clarification because it seems so fishy

Greetings!

**Comment by darkoperator** [comment]
Its a false positive, more than likely triggering on the encryption calls that probably are used also by malware.

**Comment by v999dka** [comment]
Just what I thought

I'll erase it and compile it by myself, if It keeps happening is surely a false positive

Sorry for bothering!

Yep, when seems like a false positive it happens again

**Comment by IgorMilavec** [comment]
Fixed by #867
