### ISSUE TITLE
Can't reboot command

### ISSUE THREAD

**Issue by gabogth** [sshnet/SSH.NET#74]
I can not restart. I used the library, all commands work less "reboot", I use it in C #, WIN2012 installed on a server, all clients use Ubuntu MATE. When sending "sudo reboot" does not ask password and restarted.

_string host = "192.168.1.20";
            string user = "global";
            string pass = "123456";
            SshClient client = new SshClient(host, user, pass);
            try
            {
                client.Connect();
                SshCommand command = client.CreateCommand("sudo reboot");
                string text1 = command.Execute();
                richTextBox1.BeginInvoke(new Action(() => richTextBox1.Text += text1));
            }
            catch (Exception ex)
            {
                richTextBox1.BeginInvoke(new Action(() => richTextBox1.Text += ex.Message));
            }
            finally
            {
                client.Disconnect();
                client.Dispose();
            }_

**Comment by akranjec** [comment]
+1

**Comment by darkoperator** [comment]
You have to use a sshstream since sudo expects a terminal and execute() does not create one

**Comment by akranjec** [comment]
Thank you @darkoperator , that works for me.
