### ISSUE TITLE
Scp error unexpected filename, again?

### ISSUE THREAD

**Issue by yanivka** [sshnet/SSH.NET#744]
ScpClient (2016.1.0) is falling when calling Upload with the exception "scp: error: unexpected filename: "

The function is called with:
`scp.Upload(new FileInfo(@"C:\chunks\f671a706-d92e-4538-bc4a-037c8341149d.tar.gz"), "/root/f671a706-d92e-4538-bc4a-037c8341149d.tar.gz");`

Notes - My application is running **as admin** on the local computer and the **file exist**, the application connects to the target host using **root** credentials.

I saw some familiar problems #516 , #515 . it says that this problem is already solved .... but I am still getting the same exception

**Comment by drieseng** [comment]
This is fixed in version 2020.0.0-beta1. Is that the version you're using?

**Comment by yanivka** [comment]
Oops ... sorry I was using the older version. 

I just installed it using the NuGet Package manager Gui, only the 2016.1.0 version is showing because I didn't checked the Prerelease filter.

Thank you very much

**Comment by yi452873250** [comment]
Hi,I use scp.upload, but it tell me "scp: error: unexpected filename: "  I used the newest version 2020.0.1 How can I do it ? please!,
![QQ图片20210507134132](https://user-images.githubusercontent.com/20902016/117402915-dff05b80-af39-11eb-8b87-2f285e97de23.png)
