### ISSUE TITLE
Windows Defender flags test assembly as ransomware

### ISSUE THREAD

**Issue by sfreed141** [sshnet/SSH.NET#747]
Cloning (commit cefdc203d98cd890815e029bc759bc43ec5a9643) and building with no changes results in Renci.SshNet.Tests.dll being flagged as ransomware (Ransom:MSIL/Hasadcrypt.A). Does anyone have an idea what portion of the code could be suspect?

System info: Windows 10 Enterprise version 10.0.19042 Build 19042

**Comment by darkoperator** [comment]
Could be any of the encryption library or that many of them are loaded at once. I would report it to MS

**Comment by sfreed141** [comment]
Reported to MS. Btw the file that is causing the issue is https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet.Tests/Classes/PrivateKeyFileTest.cs. If I remove it from the build I can build and run tests fine.

**Comment by bad-samaritan** [comment]
Unfortunately it's still the case.
Today my Defender flagged _Renci.SshNet.Tests.dll_ as _MSIL/Hasadcrypt.A_ for all targets (.NET Framework and NET Core).
On the other hand this does not seem like a Microsoft Defender only issue - on VirusTotal 16/69 engines flags it as Malicious.

**Comment by zybexXL** [comment]
Still the same today for me, just for target NET4.0 in Debug profile.

**Comment by zybexXL** [comment]
Fixed with PR #867

**Comment by IgorMilavec** [comment]
Duplicate of #737
