### ISSUE TITLE
ShellStream.ReadLine only recognises CrLf as a line ending

### ISSUE THREAD

**Issue by martingbrown** [sshnet/SSH.NET#748]
I am connecting to a server that ends its lines with a single Cr. Because ShellStream.ReadLine is looking for CrLf it is not finding the end of the line.

I propose that this method be changed to look for CrLf or Cr or Lf that should cover most cases.

**Comment by IgorMilavec** [comment]
I have created a discussion #926 for all ShellStream related issues.

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
