### ISSUE TITLE
SshOperationTimeoutException and SshConnectionException continue to appear randomly. 

### ISSUE THREAD

**Issue by cgwg1993** [sshnet/SSH.NET#75]
Hello, I am currently working on a project that must download, edit and then upload a file from an sftp server. To achieve this, I am using this library. As well as this, the file on the sftp is renamed before it is edited and uploaded, then renamed back to its original name once completed. 

 My issue is 50% of the time, an exception will appear. This exception can be either a SshOperationTimeoutException (timeout set to 10 seconds) or a SshConnectionException, but will always occur on the 'SftpClient.Connect()' function. The other 50% of the time, the program works as expected. What could be causing these issues and what can I do to minimize or solve them. I will put the code I use to upload, rename and download below.

**Download File**
`public bool downloadFile(String ftpPath, String localPath)
  {        
    retrieveFile:
      try
      {
           using (SftpClient request = CreateFtpWebRequest())
           {
               request.Connect();
               using (var file = File.OpenWrite(localPath))
               {
                   request.DownloadFile(ftpPath, file);
               }
               request.Disconnect();
            }
            return true;
        }
        catch (Exception e)
        {
            //Exception rules
            return false;
        }
    }`

**Upload File**
                `try
                {      
                    using (SftpClient request = CreateFtpWebRequest())
                    {
                            request.Connect();
                            FileInfo f = new FileInfo(localPath);
                            String uploadedfile = f.FullName;
                            var fileStream = new FileStream(uploadedfile, FileMode.Open);
                            request.UploadFile(fileStream, newPath, null);
                            request.Disconnect();
                            fileStream.Dispose();
                    }
                    this.alterations.Clear();
                }
                catch (Exception e)
                {
                    //Exception rules
                 }`

**Rename File**
`using (SftpClient ftp = CreateFtpWebRequest())
            {
                ftp.Connect();
                if (ftp.Exists(newFilePath))
                    ftp.DeleteFile(newFilePath);
                ftp.RenameFile(ftpPath, newFilePath);
                ftp.Disconnect();
            }`

**Comment by drieseng** [comment]
What version of SSH.NET are you using, and using which CLR (.NET 4.0, .NET Core, ...)?
What SSH server, and what version?

**Comment by drieseng** [comment]
@cgwg1993: Ping!

**Comment by cgwg1993** [comment]
Sorry it's taken so long to. The issue was with the sftp server itself and not with the library. One quick call to the host and everything sorted itself out.
