### ISSUE TITLE
Check the plan to release the official version of 2020

### ISSUE THREAD

**Issue by yew** [sshnet/SSH.NET#750]
Hi @drieseng , I really appreciate your contributions on this repro, and it helped me a lot.

I want to inquire about the plan to release the official 2020 version.
My product is waiting to be upgraded as the new version have more cipher support and many bug fixes.

Or, if I can do something to speed up the progress, I'm willing to help : )

Many thanks!

**Comment by mohdwaseem** [comment]
I am also waiting for the official release

**Comment by drieseng** [comment]
@yew I've continued working on **SSH.NET**, and hope to land a new release soon.
There are some issues that only/mostly reproduce on Mac, so an iMac or MacBook would be nice :p

**Comment by drieseng** [comment]
@yew @mohdwaseem The (official) [2020.0.0](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0) release is available now. The release notes include information on how you can show us your appreciation :)

**Comment by mohdwaseem** [comment]
> @yew @mohdwaseem The (official) [2020.0.0](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0) release is available now. The release notes include information on how you can show us your appreciation :)

Thanks for your efforts and very much appreciated.

**Comment by yew** [comment]
> @yew @mohdwaseem The (official) [2020.0.0](https://github.com/sshnet/SSH.NET/releases/tag/2020.0.0) release is available now. The release notes include information on how you can show us your appreciation :)

Truly appreciate you effort.
