### ISSUE TITLE
Inconsistant timeout issue with (some) Cisco devices

### ISSUE THREAD

**Issue by Patrick92x** [sshnet/SSH.NET#752]
It seems that some changes were made between version "2016.1.0-beta2" and "2016.1.0" that negatively impact connectivity to (some) Cisco devices. When using the beta version, every connection succeeds. When using the stable version only 50% of the connections succeed, the others end up in a timeout.

I've made packet capture, in both scenario's traffic is generated. However, when it fails you can see that the "Key exchange Init" is never started (thus the timeout). Unfortunately the debug on the Cisco device only shows the following:
`cisco Session disconnected - error 0x00`

Since the issue never occurs when using "2016.1.0-beta2", and my lack of programming skills, i hope someone can help me find what causes this issue.

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
