### ISSUE TITLE
Renci.SshNet.Common.SshException: read from 13 for 32755 from 32772 not supported.

### ISSUE THREAD

**Issue by jamessdixon** [sshnet/SSH.NET#754]
I am running this code

```
            using (SftpClient client = new SftpClient(_ftpServerIP, _ftpUserID, _ftpPassword))
            {
                client.Connect();
                var fileStream = client.Open(filePath,FileMode.Open);
                var memoryStream = new MemoryStream();
                fileStream.CopyTo(memoryStream);
                return memoryStream;
            }

```
and I am getting this exception

> Renci.SshNet.Common.SshException
>   HResult=0x80131500
>   Message=read from 13 for 32755 from 32772 not supported.
>   Source=Renci.SshNet

This looks like an error in the underlying codebase the stream is not being buffered correctly.  Has anyone else seen this before?

**Comment by darkoperator** [comment]
Uhmm seen this when people tried connecting to FTP over TLS/SSL and not against SSH SFTP subsystem

**Comment by jamessdixon** [comment]
It was my mistake - it is .OpenRead and not .Open
Then set the MemoryStream position to 0
