### ISSUE TITLE
IIS crashes due to null ref error with Renci.SshNet.SFTP (occurs rarely)

### ISSUE THREAD

**Issue by mukundmalladi** [sshnet/SSH.NET#76]
I cannot reproduce locally though but here is the stack strace I received:

Local System:
OS: windows -10

Source Code:
Application: w3wp.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
Stack:
   at Renci.SshNet.Sftp.SubsystemSession.Dispose(Boolean)
   at Renci.SshNet.Sftp.SftpSession.Dispose(Boolean)
   at Renci.SshNet.Sftp.SubsystemSession.Finalize()
Is it something with objects not getting disposed correctly?
I can transfer files to my local ftp server via SFTP.

**Comment by drieseng** [comment]
What version of **SSH.NET** are you using ?
Would it possible for you to use a debug build (which contains more tracing) ?

Note:
Right now, this requires me to provide you a debug version of **SSH.NET**, or you could build **SSH.NET** from source yourself. This will be changed as part of issue #45.

**Comment by mukundmalladi** [comment]
I'm using SSH.NET.2014.4.6  version. I'll try from source code.

Editing this: I took the latest version of dll and was able to debug, however I could not find any exceptions.

**Comment by drieseng** [comment]
Try upgrading to 2016.0.0, and see if that fixes the problem for you.
Please provide feedback.

**Comment by drieseng** [comment]
@mukundmalladi: Ping

**Comment by mukundmalladi** [comment]
Hey, yes we tried upgrading to 2016 but I guess we could not do it right now since we in the process of converting from VS-2013 to 2015. So I guess this issue can be closed for now. I personally tried debugging the source code(2016 version) and  could not find any issue.

**Comment by drieseng** [comment]
There's nothing in **2016.0.0** that would block you from upgrading to **VS 2015**.
Don't hesitate to reopen this issue if you ever encounter this issue again in **2016.0.0** or higher.
