### ISSUE TITLE
Azure Function with sshnet dll : Could not load type Error

### ISSUE THREAD

**Issue by gtrennert** [sshnet/SSH.NET#762]
Hello

I try to create an Azure Function to get the files on FTP Server

I'm using Renci.SshNet dll, version 2020.0.0.0

I think I referenced correctly the dll by doing adding : #r "..\bin\Renci.SshNet.dll" at the top

(the dll was uploaded on kudu)

I get the following error :

2021-01-07T11:47:52.038 [Error] Executed 'Functions.RenciTst1' (Failed, Id=b0fe9ed8-434d-4ae1-aef1-56fd7f6c58ba, Duration=45ms)Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

I'm new to azure functions, could somebody help me to understand the problem ?

Thanks

**Comment by drieseng** [comment]
What target framework flavor of **SSH.NET** are you referencing?
Depending on the Azure Functions runtime version you'll either need to use the .NET Framework 4.0 or the .NET Standard 2.0 flavor.

More information is available [here](https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions).

I have zero experience with Azure Functions, so I may be way off here.

**Comment by Rob-Hague** [comment]
I have not tested it, but I am confident that this is fixed in 2023.0.0 (by virtue of updated target framework support).
