### ISSUE TITLE
"Channel was closed" / logging / specifying cipher

### ISSUE THREAD

**Issue by iainb123** [sshnet/SSH.NET#763]
I've found the library very reliable and I'm using it day-to-day, but I've hit an odd problem.  I'm trying to connect to an SFTP site where if I'm connecting from MacOS on the command line I need to specify the cipher ("e.g. sftp -c aes256-cbc ...").  While the SftpClient.Connect() does not throw an error the SftpClient.Create() method throws an exception:

```
Renci.SshNet.Common.SshException: Channel was closed.
   at Renci.SshNet.SubsystemSession.WaitOnHandle(WaitHandle waitHandle, Int32 millisecondsTimeout)
   at Renci.SshNet.Sftp.SftpSession.RequestOpen(String path, Flags flags, Boolean nullOnError)
   at Renci.SshNet.Sftp.SftpFileStream..ctor(ISftpSession session, String path, FileMode mode, FileAccess access, Int32 bufferSize)
   at Renci.SshNet.SftpClient.Create(String path)
```

Is there a way to enable any debugging output so I can dig into why this happens?  Also, do I need to do the equivalent of the cipher specification with the library, or will it be automatic - I see it in the list of supported ciphers?

**Comment by drieseng** [comment]
This should not be a KEX / cipher issue as the SSH session was successfully established.
You can try to subscribe to *ErrorOccurred* events on *SftpClient*, but it's likely that you won't get much wiser from that.
An SSH server does not provide a reason when closing a channel.
You'll probably get more lucky looking at the logs of the SSH server.

**Comment by iainb123** [comment]
The ErrorOccurred doesn't seem to trigger, so it seems to look OK from the client side.  I found the OpenWrite() method worked fine, but Create() doesn't.

Looking at the code there seem to be different flags requested, but I'm not sure why the server would drop the connection on Create().

OpenWrite:
return new SftpFileStream(_sftpSession, path, FileMode.OpenOrCreate, FileAccess.Write, (int) _bufferSize);

Create:
return new SftpFileStream(_sftpSession, path, FileMode.Create, FileAccess.ReadWrite, (int) _bufferSize);

This resolves my issue, but happy to try other things on this server if it helps.  It may just be a strangely configured server though.
