### ISSUE TITLE
Is There Difference between SFTPClient and SCPClient?

### ISSUE THREAD

**Issue by gdosu** [sshnet/SSH.NET#764]
Hello, I'm totally new on SSH.NET and Ubuntu, so my question could be ambiguous.
Is there difference between SFTPClient class and SCPClient class?
Any answer or doc link would be appreciated, many thanks for reading

**Comment by drieseng** [comment]
SftpClient = SFTP
ScpClient = SCP

Google is your friend.

**Comment by gdosu** [comment]
@drieseng 
yeah, but I was confused because of this.
![1](https://user-images.githubusercontent.com/70877629/105268219-22816880-5bd5-11eb-9b05-581fe3c87c10.png)

thx for answer anyway
