### ISSUE TITLE
Random Connection Issue with Cisco Kit

### ISSUE THREAD

**Issue by darkoperator** [sshnet/SSH.NET#778]
Since version 2020 the powershell module I wrote has been having issues with Cisco kit, it seems to get stuck in the kinit part as it selects the encryption to use https://github.com/darkoperator/Posh-SSH/issues/376

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
