### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by bkfichter** [sshnet/SSH.NET#786]
Just curious if anyone has attempted to to build to ARM? I am trying but am not too experienced with doing it. I did notice the sshnet/Cryptography will need to be rebuild for ARM also. Just thought I would ask before venturing down the path further.

**Comment by darinkes** [comment]
There no need to build for ARM. SSH.NET is AnyCPU. Use the netstandard-Libraries and they work.

**Comment by bkfichter** [comment]
Also explains why it will build, deploy, and run with no issues as a uwp app on the ARM device but not Unity.
