### ISSUE TITLE
Support non-standard protocol version identification

### ISSUE THREAD

**Issue by yew** [sshnet/SSH.NET#787]
![image](https://user-images.githubusercontent.com/12381485/108960684-41ca5480-76b1-11eb-9bde-b4494f56d2af.png)

Non-standard protocol version identification will cause connect to fail with error message "Socket read operation has timed out after 30000 milliseconds."
I have checked the code, this is caused by such identification not matching the server version regex.
https://github.com/sshnet/SSH.NET/blob/6e1f839ca1d32cdf510a548945d38b0bcfbf273f/src/Renci.SshNet/Connection/ProtocolVersionExchange.cs#L71-L77

Is softwareversion a required property in subsequent data transfer? If not, we can support that kind of servers.
And WinSCP and FileZilla support this identification.

**Comment by Rob-Hague** [comment]
Fixed by #1441
