### ISSUE TITLE
Does SSH.NET work with .NET core and .NET 5?

### ISSUE THREAD

**Issue by nikhilramabhadra** [sshnet/SSH.NET#789]
Does SSH.NET work with .NET core and .NET 5 on Windows and Linux?

**Comment by IgorMilavec** [comment]
SSH.NET targets .NET Standard 2.0 so yes, it will work with .NET Core 2 and newer.
In regard to running on Linux: I see no dependencies on specific platform in the sources, so it should run. You can always build a simple test project and run it on Linux.

**Comment by mmacagno** [comment]
It actually does not, a specific target flavor for dot net core due to .NET virtual methods resolution issues.
See https://github.com/sshnet/SSH.NET/issues/776.

**Comment by Rob-Hague** [comment]
#776 is fixed in 2023.0.0 (by virtue of updated target framework support). So the answer to this question is "Yes"... aside from any bugs :-)
