### ISSUE TITLE
Exception: "An attempt was made to access a socket in a way forbidden by its access permissions"

### ISSUE THREAD

**Issue by tekgiant** [sshnet/SSH.NET#79]
Exception: "An attempt was made to access a socket in a way forbidden by its access permissions"

This happens when attempting to connect to a device in a UWP app with SShClient, but using the same method in a WPF app, it works fine.

Working Solution (WPF):
SSH.NET version: 2016.0.0-beta2
CLR: .NET 4.5
OS: Windows 10 (Anniversary Update)

Non-Working Solution (UAP 10):
SSH.NET version: 2016.0.0
CLR: .NET 4.5
OS: Windows 10 (Anniversary Update)
StackTrace:
   at Renci.SshNet.Abstractions.SocketAbstraction.Connect(IPEndPoint remoteEndpoint, TimeSpan connectTimeout)
   at Renci.SshNet.Session.SocketConnect(String host, Int32 port)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.Connect()
   at **********************.MyConnectMethod(String ipAddress)

**Comment by drieseng** [comment]
Please provide the following information (and any additional info you have):
- Version of SSH.NET
- CLR & version
- OS & version
- Full stacktrace

**Comment by tekgiant** [comment]
I did also try to update the UWP app to the beta release one as well, and it still has the same problem. Just FYI

**Comment by drieseng** [comment]
I cannot reproduce this issue.
Please attach the smallest app (sources + VS project file!) possible that allows me to reproduce this issue.

**Comment by tekgiant** [comment]
K, let me work on that today.

**Comment by tekgiant** [comment]
Here's an example app with the reproducible issue.
[SSHTest.zip](https://github.com/sshnet/SSH.NET/files/466281/SSHTest.zip)

**Comment by drieseng** [comment]
Works fine. I only had to modify the manifest to enable the **Private Networks (Client & Server)** capability.

**Comment by tatulea** [comment]
Hi! I have the same problem. I enabled the Private Networks, but it is still not working.
