### ISSUE TITLE
Default constructor not found for type Renci.SshNet.Security.KeyExchangeECCurve25519

### ISSUE THREAD

**Issue by bkfichter** [sshnet/SSH.NET#796]
Builds to ARM
Application starts
Fails on client.connect();

"System.MissingMethodException: Default constructor not found for type Renci.SshNet.Security.KeyExchangeECCurve25519\r\n  at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Activator.CreateInstance (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Common.Extensions.CreateInstance[T] (System.Type type) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.ServiceFactory.CreateKeyExchange (System.Collections.Generic.IDictionary`2[TKey,TValue] clientAlgorithms, System.String[] serverAlgorithms) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Session.OnKeyExchangeInitReceived (Renci.SshNet.Messages.Transport.KeyExchangeInitMessage message) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Messages.Transport.KeyExchangeInitMessage.Process (Renci.SshNet.Session session) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Session.MessageListener () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Session.<Connect>b__169_0 () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at Renci.SshNet.Abstractions.ThreadAbstraction+<>c__DisplayClass2_0.<ExecuteThread>b__0 (System.Object o) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context (System.Object state) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00000] in <00000000000000000000000000000000>:0 \r\n  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <00000000000000000000000000000000>:0 "

**Comment by darinkes** [comment]
Mono is not supported, see https://github.com/sshnet/SSH.NET#framework-support

But if you manage to make it work, I'm sure a PR is welcome.

**Comment by bkfichter** [comment]
So I am using Unity 3D and it does use Mono. However it is up to date with .net 4.6. So a .net 4.5 dll should work. Unless there is something in the code set that is using above this framework level. The code does compile. Just gets that particular error when running.

**Comment by darinkes** [comment]
Found this online with same Error Message: https://www.opsive.com/forum/index.php?threads/missingmethodexception-when-using-il2cpp-in-unity-19-3-3.3039/

Looks like Mono is stripping some code.

https://docs.unity3d.com/Manual/ManagedCodeStripping.html

Maybe worth a try.

**Comment by bkfichter** [comment]
You, my friend, are a FREAKING HERO! That was exactly the issue. If I am ever rich enough to own a bridge, I am naming it in your honor.

**Comment by drieseng** [comment]
@darinkes: thanks!
