### ISSUE TITLE
Connect hangs forever

### ISSUE THREAD

**Issue by drwtsn32x** [sshnet/SSH.NET#798]
Sometimes the `Connect()` method will hang forever. I notice this happens when I reboot the SSH server. (My program that uses this library will automatically try to reconnect after a disconnection, and it's at this point when it hangs forever.)

Adjusting `ConnectionInfo.Timeout` has no effect on this problem.

Any ideas?

**Comment by jgarciadelanoceda** [comment]
Same happens to me.
I updated from version 2016.1.0 to 2020.0.1 and with some machines Connection hang forever in new version whereas with old version connection was a successfull one.

This is the method I use for connecting:
`@params.sshClient = new Renci.SshNet.SshClient(@params.connectionAsEvent.connection.Ip.Trim(), @params.GetPort() ?? 22, @params.GetUser(), @params.GetPassword());
							@params.sshClient.Connect();
							@params.shellStream = @params.sshClient.CreateShellStream("xterm", 80, 600, 0, 0, 32 * 1024);`


And this is the exception it gave:
`Error Renci.SshNet.Common.SshOperationTimeoutException: Session operation has timed out
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()`

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1

**Comment by kazykenov** [comment]
This experiencing this issue with the latest version of the library (2023.0.1)
In my case it freezes on file open.

It happens once in 1-2 days. I'm connecting to the files served by this docker container https://github.com/atmoz/sftp on Azure VM


```
innermostType
Renci.SshNet.Common.SshOperationTimeoutException
innermostMessage
Operation has timed out.
innermostAssembly
Renci.SshNet, Version=2023.0.1.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106
innermostMethod
Renci.SshNet.SubsystemSession.WaitOnHandle
```

```
{"assembly":"Renci.SshNet, Version=2023.0.1.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106","method":"Renci.SshNet.SubsystemSession.WaitOnHandle","level":0,"line":0}
1
{"assembly":"Renci.SshNet, Version=2023.0.1.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106","method":"Renci.SshNet.Sftp.SftpSession.RequestOpen","level":1,"line":0}
2
{"assembly":"Renci.SshNet, Version=2023.0.1.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106","method":"Renci.SshNet.Sftp.SftpFileStream..ctor","level":2,"line":0}
3
{"assembly":"Renci.SshNet, Version=2023.0.1.0, Culture=neutral, PublicKeyToken=1cee9f8bde3db106","method":"Renci.SshNet.SftpClient.OpenRead","level":3,"line":0}
```
