### ISSUE TITLE
Can we use SSH.NET with TLS 1.2 & 1.3 ?

### ISSUE THREAD

**Issue by lordgovinda** [sshnet/SSH.NET#801]
Hi 
Shall we use SSH.NET  for TLS 1.2 & 1.3  we already using this for SFTP for file transfer which is working well . There is a plan to migrate it to either TLS 1.2 /1.3 will SSH.NET work with them(FTPS)?

**Comment by UlyssesAlves** [comment]
@lordgovinda how did you get to make SSH.NET work with SFTP? Could you share a sample code please?

**Comment by IgorMilavec** [comment]
FTPS is a completely different protocol and is not supported by SSH..NET.
