### ISSUE TITLE
Compression algorithm not found

### ISSUE THREAD

**Issue by cristogomez** [sshnet/SSH.NET#815]
Hi,

I'm using SftpClient class on C# project to connect to an SFTP Server. The code was working fine, but suddenly started throwing the following error:

"Compression algorithm not found".  Please check the attached image

<img width="816" alt="SftpClient Error" src="https://user-images.githubusercontent.com/25061184/115915039-5cfadb80-a438-11eb-8ab8-9de46d802416.png">

Any help will be appreciated

**Comment by IgorMilavec** [comment]
Based on the description I think that the server requires compression. Unfortunately SSH.NET does not support compression at this time.

**Comment by Rob-Hague** [comment]
Most likely fixed by #1326 and/or #1453
