### ISSUE TITLE
Permission denied (password)

### ISSUE THREAD

**Issue by kevinYnag** [sshnet/SSH.NET#817]
I'm getting Permission denied (password) when i try to connect. I know the username and password are correct because I can log in via a web transfer client. Any idea as to what is doing wrong? Is it maybe a setting that isn't set correctly?

Using ftp = New Renci.SshNet.SftpClient("host", "username", "password")
ftp.Connect()
End Using

**Comment by kiddailey** [comment]
Not sure if it will help, but I had a similar issue and it turned out that the user had to officially log in on the server before I could use the account with my SSH.NET client.  And I also had to make sure the user was allowed for remote logins.
