### ISSUE TITLE
Can't install on Visual Studio 2012

### ISSUE THREAD

**Issue by Papa-Tori** [sshnet/SSH.NET#82]
No matter which framework version I use. I always get a message which says 'SSH.NET' already has a defined dependency on 'SshNet.Security.Cryptography'. But if I try to install 'SshNet.Security.Cryptography', I get another message which says it already has a defined dependency for 'System.IO'.

I've tried through the nuget packet manager and the nuget command line as well.

Any clue on what's happening?
Regards

**Comment by drieseng** [comment]
This is because of NuGet/Home#3131.
I've added a workaround as one the comments to that issue.

If this issue cannot or will not resolved in **NuGet**, then I'll probably have to re-introduce using separate .zip files for each supported target framework :(

**Comment by Papa-Tori** [comment]
You're the man!!! I tried yesterday, but I think I clicked (by mistake) at the "how-to" link, instead of download. My bad!!! It was right there! 

Thank you :)
