### ISSUE TITLE
Exception thrown when the server SSH identification is missing its"softwareversion" part

### ISSUE THREAD

**Issue by chsoft-ag** [sshnet/SSH.NET#822]
We have actually run into a server in the wild which only provides an identification string of "SSH-2.0-" and omits the "softwareversion" part required by the standard. This leads to SSH.NET throwing an exception

`Renci.SshNet.Common.SshConnectionException: The server response contains a null character at position 0x0000000B:

  00000000  53 53 48 2D 32 2E 30 2D 0D 0A 00                 SSH-2.0-...

A server must not send a null character before the Protocol Version Exchange is complete.`

I've seen that there had been some discussion about less strict parsing in #749, with a suggestion of a potential strict/lenient property to allow for non-conforming servers that do not provide the software version part. Any thoughts on actually going forward with such a leniency option?

We've contacted the server operator about their non-conformance, but no idea if they have any interest in fixing this as apparently other clients are more forgiving about a missing software version. FileZilla for example connects without issues.

**Comment by toxis** [comment]
@chsoft-ag: I have the same issue with an external SFTP provider. Do you find a solution or a workaround?

**Comment by chsoft-ag** [comment]
@toxis: In our case, the server was using proprietary software of the server owner and they changed their side to correctly provide the software version. Since that was the only occurrence so far, we had no reason to further look for a fix or workaround.

**Comment by doerig** [comment]
I came across the same issue, forked the repo and changed the regex for parsing the version string to Version 2 mentioned in #749, looks good now and hope that this tolerant parsing will be incorporated as it is sometimes hard, slow or impossible to make someone change the server configuration.

**Comment by Rob-Hague** [comment]
Consider raising a PR?

**Comment by doerig** [comment]
created a PR, reverted back to only a minimal change of the regex, as there where some tests failing with the expression from #749
