### ISSUE TITLE
Scp on cisco device not working

### ISSUE THREAD

**Issue by chenditc** [sshnet/SSH.NET#829]
I tested on Cisco switch
SKU: Cisco-4351
Version: 17.3.2

When calling Upload from scp client: https://github.com/sshnet/SSH.NET/blob/develop/src/Renci.SshNet/ScpClient.cs#L209
The exec command "scp -t -d <directory>" will have two problem:
1. -d is not supported on cisco router, which gives an "-p -d options not supported" error.
2. cisco switch will throw back a "write failed" error.

In order to work with cisco router, the exec command needs to be: "scp -t <full path>".

Is there anyway to configure this behavior in current code? I don't see anyway to do that. 

I would like to make a PR and add an option to overwrite the exec behavior, have the user pass in the exact exec command, something like:

```C#
public void Upload(Stream source, string path, string handshakeExecCommand)
```

Any comments?

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
