### ISSUE TITLE
"Bad Message" received when attempting call SftpClient.Open with FileMode.Append

### ISSUE THREAD

**Issue by braydie** [sshnet/SSH.NET#83]
Hey, I'm having some problems trying to append to a file on my SFTP server. [I've posted on StackOverflow](http://stackoverflow.com/questions/39395340/error-bad-message-when-accessing-a-file-on-windows-openssh-sftp-server/39407761) and in order to cover all bases I'm wondering if this is an issue with SSH.NET. 

The code I'm using is as follows:

``` csharp
const string DESTINATION_PATH = "/D:/sftp/test.xml";
var Client = new SftpClient("host", 22, "username", "password");

Client.Connect();   

if(!Client.Exists(DESTINATION_PATH ))
{                       
    var s = Client.Create(DESTINATION_PATH, 1024 * 4);
    s.Dispose();        
}   

var Data = File.ReadAllBytes(@"D:\Temp\TestFile.xml");  
using(var w = Client.Open(DESTINATION_PATH, FileMode.Append, FileAccess.ReadWrite)) // this line throws an exception
{
    w.Write(Data, 0, Data.Length);
}

Client.Disconnect();
```

I get an SshException thrown when I call `Client.Open(..)` with the message "Bad Message".

**Comment by drieseng** [comment]
To improve compatibility with **System.IO.FileStream**, I've modified our SftpFileStream to only support write-only mode when combined with **Append**.
