### ISSUE TITLE
Error under .net core

### ISSUE THREAD

**Issue by tabdurman** [sshnet/SSH.NET#831]
v 2020.0.1.0

Could not load type 'System.Security.Cryptography.HMACRIPEMD160' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

using (SftpClient sftp = new SftpClient(_host, _username, _password))
            {
                sftp.Connect();

                var files = sftp.ListDirectory(_remoteDirectory);
 .....

"ExceptionId": 14,
"StackTrace": "   at Renci.SshNet.ConnectionInfo..ctor(String host, Int32 port, String username, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword, AuthenticationMethod[] authenticationMethods)\r\n   at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, Byte[] password, ProxyTypes proxyType, String proxyHost, Int32 proxyPort, String proxyUsername, String proxyPassword)\r\n   at Renci.SshNet.PasswordConnectionInfo..ctor(String host, Int32 port, String username, String password)\r\n   at Renci.SshNet.SftpClient..ctor(String host, Int32 port, String username, String password)\r\n   at Renci.SshNet.SftpClient..ctor(String host, String username, String password)\r\n

**Comment by Rob-Hague** [comment]
I have not tested it, but I am confident that this is fixed in 2023.0.0 (by virtue of updated target framework support).
