### ISSUE TITLE
Return matched group in ShellStream.Expect

### ISSUE THREAD

**Issue by NN---** [sshnet/SSH.NET#833]
Currently it returns the strings which requires me to call Regex.Match second time.

**Comment by IgorMilavec** [comment]
I have created a discussion #926 for all ShellStream related issues.

**Comment by IgorMilavec** [comment]
@NN I'm trying to better understand usage patterns related to Expect API. Can you please explain how you use it and if possible provide a proto code for it?

**Comment by NN---** [comment]
The API reads the data and tries to
match it with the given pattern.
Once it is matched the method returns.
The problem here is that I want the matched groups what API doesn't give.

If you talk generally about the API, it would be better to have a Stream abstraction over SSH, then such code could be implemented for any stream.

**Comment by IgorMilavec** [comment]
Yes, I know what the Expect API is supposed to do. :)
What I'm asking is how you are using it? I agree that having such functionality for any Stream would be beneficial, but to design it properly, we first need to understand how it is used in the client code. So if you could describe why and how you are using it would help me very much.

**Comment by NN---** [comment]
One of usages is to wait for password prompt when `sudo` is called and put a password.

**Comment by IgorMilavec** [comment]
So in this case you would be Expecting ```$".*\[sudo\] password for {RegexEscape(username)}: "```?

**Comment by NN---** [comment]
Yes, this is the idea.
It is one of the possible usages of Expect of course.

**Comment by NN---** [comment]
In general any command requiring input needs to wait for the prompt and only then put the text.

**Comment by jscarle** [comment]
@IgorMilavec @WojciechNagorski Although the conversation is unclear, I believe this was also fixed by #1207 and #1319.
