### ISSUE TITLE
Permission denied (publickey) connecting to windows server 2019 through key authentication

### ISSUE THREAD

**Issue by Bazatron** [sshnet/SSH.NET#845]
Hi,
I am working on a project that has renci.sshnet implemented to transferring files between servers using key based authentication.
I generated the keys using the documentation i have found on the internet for OpenSSH and windows as i required RSA keys for the renci.sshnet implementation we have in our project.
I managed to get a working version between my main computer (running windows 10) and my hyper V VM (Windows server 2012) this was using the same type of keys (i used the same process when generating keys in both environments).
I'm getting the above error (permission denied (publickey) when trying to connect to a windows server 2019 using the key based authentication.

The code i am using to connect to the sftpclient is shown below:

     var authMethod = new AuthenticationMethod [] { new PrivateKeyAuthenticationMethod(username, new PrivateKeyFile[]{
                  new PrivateKeyFile(PrivateKeyFile, passPhrase)}) };

     var SftpClient = new SftpClient(new ConnectionInfo(host, username, authMethod));

      try
      {
          SftpClient.Connect();
      }
      catch (Exception ex)
      {
          throw new Exception("Error connecting to the sftp client");
      }

When i checked the eventviewer in the environment i am only getting two entries per attempt to connect to the client, these are:
sshd: Connection closed by authenticating user sftpuser (with a 
sshd: Authentication refused.

I am able to use the key using PuTTY and i can access the environment using the username and password i have setup for the key
i have tried to generate different keys multiple times but still no luck.
I have knocked up a dummy application to limit the code this runs through.
Are there any prerequisite's that are required in a new server? 
Are there much differences that could affect the connection when doing this on a windows 2019 server?
I am trying to increase the debugging info level to output more info which i have change in the sshd_config file but i am not getting any additional info.
I have created a user account called sftpuser that i am storing the keys in C:\Users\sftpuser\.ssh\ - have created an authorized_keys file that is a copy of the public key
I have been researching online but there is not much information out there
Any advice on this issue would be greatly appreciated?
I can upload a copy of my sshd_config file if this is required

**Comment by Bazatron** [comment]
My sshd_config is as follows:

# This is the sshd server system-wide configuration file.  See
# sshd_config(5) for more information.

# The strategy used for options in the default sshd_config shipped with
# OpenSSH is to specify options with their default value where
# possible, but leave them commented.  Uncommented options override the
# default value.

#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

#HostKey __PROGRAMDATA__/ssh/ssh_host_rsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_dsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ecdsa_key
#HostKey __PROGRAMDATA__/ssh/ssh_host_ed25519_key

# Ciphers and keying
#RekeyLimit default none

# Logging
#SyslogFacility AUTH
LogLevel DEBUG3

# Authentication:

#LoginGraceTime 2m
#PermitRootLogin prohibit-password
#StrictModes yes
#MaxAuthTries 6
#MaxSessions 10

#PubkeyAuthentication yes

# The default is to check both .ssh/authorized_keys and .ssh/authorized_keys2
# but this is overridden so installations will only check .ssh/authorized_keys
AuthorizedKeysFile	.ssh/authorized_keys

#AuthorizedPrincipalsFile none

# For this to work you will also need host keys in %programData%/ssh/ssh_known_hosts
#HostbasedAuthentication no
# Change to yes if you don't trust ~/.ssh/known_hosts for
# HostbasedAuthentication
#IgnoreUserKnownHosts no
# Don't read the user's ~/.rhosts and ~/.shosts files
#IgnoreRhosts yes

# To disable tunneled clear text passwords, change to no here!
#PasswordAuthentication yes
#PermitEmptyPasswords no

# GSSAPI options
#GSSAPIAuthentication no

AllowAgentForwarding no
AllowTcpForwarding no
#GatewayPorts no
PermitTTY no
PrintMotd yes
#PrintLastLog yes
#TCPKeepAlive yes
#UseLogin no
#PermitUserEnvironment no
#ClientAliveInterval 0
#ClientAliveCountMax 3
#UseDNS no
#PidFile /var/run/sshd.pid
#MaxStartups 10:30:100
PermitTunnel no
ChrootDirectory C:/inetpub/sftproot/
#VersionAddendum none

# no default banner path
#Banner "C:\ProgramData\ssh\motd.txt"

# override default of no subsystems
Subsystem	sftp	sftp-server.exe -d C:\inetpub\sftproot\

# Example of overriding settings on a per-user basis
#Match User anoncvs
#	AllowTcpForwarding no
#	PermitTTY no
ForceCommand internal-sftp

#Match Group administrators
#       AuthorizedKeysFile __PROGRAMDATA__/ssh/administrators_authorized_keys

**Comment by WojciechNagorski** [comment]
Fixed by #1177 and #1180

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
