### ISSUE TITLE
Support writing to stdin when executing a remote command

### ISSUE THREAD

**Issue by hifi** [sshnet/SSH.NET#85]
SSH.NET currently does not support executing a command (without shell) with an option to directly write to the stdin of the executed program. A writable stream is needed for that.

This is a critical feature when you need to pipe large amounts of data from SSH.NET to remote commands.

**Comment by hifi** [comment]
So it was rather easy to implement but here's the minimum amount of changes required to get writing working:

https://gist.github.com/hifi/d7c4e3689e28df13893fc0c4fd813706

Ideally it should use something like `PipeStream` to expose a `InputStream` for writing instead of raw byte arrays. Also it's worth noting that `SendEof` _must_ be called to close stdin. Failing to do that, a program you are executing could end up waiting input forever. Closing this `InputStream` should do this implicitly so you can signal the program on the other send that you are finished.

**Comment by Livius90** [comment]
Is this feature available now? I would like to send diskimage datas from C# to a stdin pipe of dd over SSH, like in [this example](https://www.thegeekdiary.com/how-to-clone-linux-disk-partition-over-network-using-dd/).


Is that pipe data sending Linux style is available to use in SSH.NET?
```console
# dd bs=16M if=/dev/sda | ssh root@serverB "dd bs=16M of=/dev/sda"
```

**Comment by Rob-Hague** [comment]
This was added in version 2024.0.0 in #1293
