### ISSUE TITLE
PrivateKeyFile

### ISSUE THREAD

**Issue by terryholland** [sshnet/SSH.NET#851]
Im trying to create a PrivateKeyFile using the code below.
I get an "Invalid private key file" exception when I try to construct the PrivateKeyFile object.
Im using a file and password combination that I know to be valid (I use it on a daily basis and can verify using FileZilla)

```
private static void TestUVUATUsingUsernameAndPPK()
{
    string ppkFilename = Path.Combine(Directory.GetCurrentDirectory(), "MyPrivateKeyFile.ppk");
    string ppkPassword = @"MyPPKPassword";

    PrivateKeyFile keyFile = new PrivateKeyFile(ppkFilename, ppkPassword);
  
}
```
![image](https://user-images.githubusercontent.com/10390177/126963395-d49423f0-1040-4b36-9b7d-36c4efda352c.png)

Header of ppk file
![image](https://user-images.githubusercontent.com/10390177/126965016-3027eccd-58f7-4e01-b2fe-90ea333c700a.png)

**Comment by DavePlater** [comment]
I was only able to use key files that were RSA type.

> -----BEGIN RSA PRIVATE KEY-----

I do not think I got it to work with

> -----BEGIN OPENSSH PRIVATE KEY-----

**Comment by FabkomInc** [comment]
I’ll convert and re-upload.

 

 

Regards,

 

Alex Dorokhin

Fabkom, Inc.

917-439-0712

**Comment by FabkomInc** [comment]
Here it is

**Comment by terryholland** [comment]
The ppkFilename parameter I was using in the line
`PrivateKeyFile keyFile = new PrivateKeyFile(ppkFilename, ppkPassword);`
was the path to my public/private ppk file generated by putty.  When I changed the path to point to my private key the code works.

This is different to the way I use my current ftp client software (FileZilla and SecureBlackBox)

SHould I be able to use my PPK file or should I always have to use just the private key?

**Comment by terryholland** [comment]
@FabkomInc

Does this imply an update will be available?  I don't see any recent updates in repo

**Comment by FabkomInc** [comment]
Sorry for the confusion. Was sending a public key to a customer and sent it to the list by mistake.

 

 

Regards,

 

Alex Dorokhin

Fabkom, Inc.

917-439-0712

**Comment by FabkomInc** [comment]
Sorry for the confusion, 

Was sending a public key to a customer and sent it to the list by mistake.

 

 

From: ***@***.*** ***@***.***>  ***@***.*** ***@***.***> > 
Sent: Monday, 26 July, 2021 4:46 PM
To: 'sshnet/SSH.NET' ***@***.*** ***@***.***> >
Cc: ***@***.***' ***@***.*** ***@***.***> >
Subject: RE: [sshnet/SSH.NET] PrivateKeyFile (#851)

 

Here it is

**Comment by Rob-Hague** [comment]
For future readers, PuTTY files are supported by an extension https://github.com/darinkes/SshNet.PuttyKeyFile
