### ISSUE TITLE
SecureString for SSH password

### ISSUE THREAD

**Issue by ineedalife222** [sshnet/SSH.NET#853]
Is it possible to allow a SecureString to be used for the ssh password?
I am fairly new to this any help would be appreciated.
Thank you

**Comment by drieseng** [comment]
I don't think we should go down that road:
https://github.com/dotnet/designs/blob/18ef6a5b3f561b9ce6cbdcb4a67b4f41116281bc/accepted/2020/better-obsoletion/securestring-obsoletion.md
