### ISSUE TITLE
SSH.NET assumes SFTP serrver will always operate with a "\" directory separator?

### ISSUE THREAD

**Issue by kikaragyozov** [sshnet/SSH.NET#854]
After looking at the code, there is a check that sees if the path ends with a "\", and if it does not, appends that character to the path.

In the event we have an SFTP server that uses another path separator, this will prove to be a terrible thing.

What is the motivation behind assuming this? Are there any outlined SFTP RFC's that set a standard path separators moving forward?

**Comment by DavePlater** [comment]
From what I am seeing, SFTP should always be using the "/" separator.
[https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13)

**Comment by kikaragyozov** [comment]
Thank you for clarifying!
