### ISSUE TITLE
Can this be compiled targeting .net core 6 and 5?

### ISSUE THREAD

**Issue by tplecko** [sshnet/SSH.NET#862]
I don't have much knowledge in this matter. 
I have added the .net-6 framework, but there is an error I don't know how to resolve
CS0116	A namespace cannot directly contain members such as fields or methods	Renci.SshNet (net6.0-windows)
Error is in the auto generated file, and removing the 'global' keyword (which removes the error) isn't persistent, as the file is generated before the build starts.

Content of the file:
// <autogenerated />
global using global::System;
global using global::System.Collections.Generic;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;

thanks

**Comment by tplecko** [comment]
I have managed to build the solution but now i get an error:
System.IO.FileNotFoundException: 'Could not load file or assembly 'SshNet.Security.Cryptography, Version=1.3.0.0, Culture=neutral, PublicKeyToken=2fa9220ff3eadda4'. The system cannot find the file specified.'
on line:
            : base(host, port, username, proxyType, proxyHost, proxyPort, proxyUsername, proxyPassword, new PasswordAuthenticationMethod(username, password))
in file:
PasswordConnectionInfo.cs

**Comment by IgorMilavec** [comment]
You should be able to reference the SSH.NET NuGet package from your net50 or net60 projects, because the package already includes netstandard20 target. You do not need to compile SSH.NET specifically for net50 or net60 unless you plan to add new features to the SSH.NET that are dependent on net50 or net60.

**Comment by tplecko** [comment]
Thanks.
Since we are on the subject of NuGet - can you, please, point me in a direction where i can find out more about it? I have been avoiding using it. I don't know what impact it does on the portability of my workspace (i prefer to have all the libraries locally, and updated when I choose)

**Comment by IgorMilavec** [comment]
NuGet is a repository of precompiled packages you can reference from your projects. You can have a look at the NuGet packages for SSH.NET at https://www.nuget.org/packages/SSH.NET/. As you can see, the packages are versioned. By referencing a specific version of NuGet package you are in control of the dependency you take from the external repository.
A walkthrough on how to use reference NuGet packages in Visual Studio is available at https://docs.microsoft.com/en-us/nuget/quickstart/install-and-use-a-package-in-visual-studio.
That being said, please check your organization's policy on using external code repositories before using NuGet packages.

**Comment by tplecko** [comment]
Thank you.
