### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by jcs090218** [sshnet/SSH.NET#872]
I think there are multiple bug fix. Maybe is good to tag a new release? 😕

**Comment by Isitar** [comment]
push

**Comment by var1ap-WA** [comment]
![image](https://user-images.githubusercontent.com/63446336/153759732-324cb626-cca1-454a-b686-fa9f93439c36.png)

**Comment by fossbrandon** [comment]
Is there an update on when we might get a new release? The projects I'm using this with require features that are not released yet so I have to bring the project into my own project and reference it that way.

**Comment by IgorMilavec** [comment]
@drieseng  could you publish a preview NuGet package? This way users will be able to access the latest features and bug fixes from the development branch and we would gain feedback if the code is stable enough.

**Comment by drieseng** [comment]
@IgorMilavec I'll try to find time in the next days. Releasing a new version is a pain (until we remove support for legacy target frameworks).

**Comment by IgorMilavec** [comment]
I know, that's why I'm trying to push towards vNext so we can release the final legacy version and then remove legacy frameworks. :)

**Comment by chrcar01** [comment]
Any chance of getting a new release of what's currently in the develop branch?

**Comment by Shadow-of-N7** [comment]
![821w4n](https://github.com/sshnet/SSH.NET/assets/23334061/e21a0069-d810-4f38-acbd-15e2d52b5ff2)

**Comment by WojciechNagorski** [comment]
@Shadow-of-N7 @var1ap-WA @chrcar01 https://twitter.com/WojtekNagorski/status/1711675545061110039

**Comment by Rob-Hague** [comment]
Completed by #1201

**Comment by mhm-iteris** [comment]
Is it just possible to make another repo with .NET core 6 and push out a nuget package? Isolating .NET and .NET framework from one another is probably best.

**Comment by Rob-Hague** [comment]
> Is it just possible to make another repo with .NET core 6 and push out a nuget package? Isolating .NET and .NET framework from one another is probably best.

In what way? I see no reason to do that.

**Comment by mhm-iteris** [comment]
> > Is it just possible to make another repo with .NET core 6 and push out a nuget package? Isolating .NET and .NET framework from one another is probably best.
> 
> In what way? I see no reason to do that.

Ah... Let me explain a little more clearly. .NET Framework and .NET core are vastly different frameworks with different lifecycle support policies by Microsoft. Microsoft is phasing out support for .NET framework, but will continue to support 4.7.2- 4.8.1 under their OS support policies. They have agreed to stop developing features for .NET framework. Details in below links:

https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-framework
https://learn.microsoft.com/en-us/lifecycle/faq/dotnet-framework



From a high level perspective the team would have to support 2 different versions of this package anyway. Where .NET Core will be more frequently updated. My suggestion would be to have 2 separate repos, one for .NET Core  (updated frequently) and .NET framework (updated only for security issues). Splitting the codebase will result in less work to develop .NET core codebase as Nuget packages, less work to regression test, and faster deployments for .NET core (majority of users will switch over to).

**Comment by Rob-Hague** [comment]
Thanks. I understand the difference between Framework and Core, but 99% of the code base for this project is shared between the targets, so in reality it would be twice as much work to maintain two repos. It is very common (and well supported) for a library project to target both.

Long term, I expect the project to simply drop Framework and Standard targets. But there is plenty of modernizing and bug-fixing to be done with the current targets before that point.

**Comment by WojciechNagorski** [comment]
I agree with @Rob-Hague.
