### ISSUE TITLE
Can release/add a new algorithm

### ISSUE THREAD

**Issue by AliceTJ** [sshnet/SSH.NET#875]
Hi Team,

The latest library does not implement the hmac-sha2-256-etm@openssh.com or hmac-sha2-512-etm@openssh.com algorithms.

Can someone advice how to add or use? Thanks!!

**Comment by Ph43n0m** [comment]
Hi,
I also need it.
After an Security Audit we can't connect to any server in our company anymore....

**Comment by IgorMilavec** [comment]
Would you be willing add it and make a PR?

**Comment by WojciechNagorski** [comment]
This issue has been fixed in the 2024.0.0 version.
