### ISSUE TITLE
How to coding like ssh "ssh -R 8888:127.0.0.1:43022 user@xxx.xxx.xxx.xxx"

### ISSUE THREAD

**Issue by un4ckn0wl3z** [sshnet/SSH.NET#878]
How to implement Ssh.net like this raw ssh command

"ssh -R 8888:127.0.0.1:43022 user@xxx.xxx.xxx.xxx"

help me.

Thanks

**Comment by un4ckn0wl3z** [comment]
OK I done this job.

closed.

**Comment by mridah** [comment]
@un4ckn0wl3z can you please share your code of how you managed to implement this?

**Comment by un4ckn0wl3z** [comment]
@mridah 
Yes bro!!

`SshClient sshclient;
ForwardedPortRemote port;

string remoteIp = "199.199.199.199";
string remotePassword = "xxxxxxx";
string username = "root";
int remotePort = 80;
int localPort = 3000;

ConnectionInfo ConnNfo = new ConnectionInfo(remoteIp, 22, username, new AuthenticationMethod[]{new PasswordAuthenticationMethod(username,remotePassword)});

sshclient = new SshClient(ConnNfo);
sshclient.KeepAliveInterval = new TimeSpan(0, 0, 30);
sshclient.ConnectionInfo.Timeout = new TimeSpan(0, 0, 20);
sshclient.Connect();

port = new ForwardedPortRemote((uint)remotePort, "127.0.0.1", (uint)localPort);

// start tunnel
if (sshclient.IsConnected)
{
    sshclient.AddForwardedPort(port);
    port.Start();
}


// stop tunnel
sshclient.Disconnect();
port.Stop();
`

I coded like this for start sshtunnel for create something like ngrok.
