### ISSUE TITLE
SFTP/SCP Permission Denied for system directories 

### ISSUE THREAD

**Issue by mgamache** [sshnet/SSH.NET#882]
How do I upload into directories that require 'sudo' permissions? I can work with user folders just fine, but I don't see a way to access directories that require root/su permissions. Getting 'permission denied' errors. Any help would be welcome. 

Note: I am working with ubuntu on AWS with private key authentication (ubuntu as username).

**Comment by IgorMilavec** [comment]
Do you have ssh access? Then you could first sftp files to some temp folder and then run ssh to copy the files to final destination with sudo.

**Comment by IgorMilavec** [comment]
Closing due to author's inactivity.
