### ISSUE TITLE
Is it possible to connect anonymously with this client to a FTP server?

### ISSUE THREAD

**Issue by UlyssesAlves** [sshnet/SSH.NET#884]
I'm trying to connect SftpClient anonymously to a portable FTP server which I've setup with [FubarDevelopment/FtpServer](https://github.com/FubarDevelopment/FtpServer), but I couldn't find a way to do so yet.

Maybe this question does not even make sense, since SSH.NET is expected to be a secure FTP client, for what I could understand so far. But in case this is not the case, could someone please tell me if this is possible, and how to accomplish this task of connecting SftpClients anonymously to a FTP server?

**Comment by zybexXL** [comment]
No, just use using System.Net.FtpClient.

**Comment by UlyssesAlves** [comment]
@zybexXL The project I'm working on has a dependency on SSH.NET, and a restriction that it cannot stop using it. We've just decided to drop the option of using an insecure FTP server. Thanks for sharing your thoughts.
