### ISSUE TITLE
The requested address is not valid in its context.

### ISSUE THREAD

**Issue by UlyssesAlves** [sshnet/SSH.NET#885]
### Error Description

I'm trying to connect with normal authentication (user and password) to a [Portable FTP Server](https://github.com/FubarDevelopment/FtpServer) hosted in a console application with [FubarDevelopment/FtpServer](https://github.com/FubarDevelopment/FtpServer) running on the local machine, but the Renci.SshNet client throws error _"The requested address is not valid in its context."_ while trying to connect to the server.

### Valiadations and Test Scenarios

I can successfully connect to this same local server with [FileZilla ftp client](https://filezilla-project.org/) with same authentication parameters, port and host adddress, so it looks like the problem is on the Renci.SshNet client side, and not on the Portable FTP Server, which again works with no issues when connecting to it via FileZilla. 

I can upload, download and list files, and I can also create directories on this server with FileZilla, so the Portable FTP Server really looks like to be in a good healthy shape. But something is wrong with either my setting up of the Renci.SshNet client application, or there's something else happening somewhere which is preventing my code from successfully connecting Renci.SshNet client to the Portable FTP Server.

I'm sharing here a [sample solution which simulates the problem](https://github.com/sshnet/SSH.NET/files/7261756/RequestAddressNotValidInThisContext.zip), so that it will be easier to look at the error hands on, in case someone is available to give me some help, which I would highly appreciate. I'm also sharing some prints and the steps necessary to simulate the problem with Renci.SshNet client and to verify that the error does not occur with other FTP clients like FileZilla, which was used in this test case.

### Sample Solution to Simulate the Error
[The sample solution, which is attached to this issue](https://github.com/sshnet/SSH.NET/files/7261756/RequestAddressNotValidInThisContext.zip), contains two projects:

- **PortableFtpServer**: a console app which hosts the Portable FTP Server instance.
- **SftpClientConsumerApp**: also a console app, which tries to connect to the Portable FTP Server, but unfortunately fails with the error on this issue title ("The requested address is not valid in its context.").

### Steps To Reproduce The Error

1. [Download and run or debug the sample solution](https://github.com/sshnet/SSH.NET/files/7261756/RequestAddressNotValidInThisContext.zip) with F5 in Visual Studio. The solution is configured with multiple projects execution, so the projects are already setup to be run in the correct dependent order, which means there's no need to run them one by one.
2. Application "SftpClientConsumerApp" will print the error in red to its console screen.
3. While the PortableFtpServer is still open and running, try now to connect to the Portable FTP Server with another FTP Client tool, like FileZilla for example, with the same connection parameters used by the SftpClient application. That is: host=127.0.0.1, user=tester, password=testing, and logon type=normal.
4. FileZilla will successfully connect to the Portable FTP Server and you can work with FTP operations as you please.

### Expected Behaviour
SftpClient should be able to properly connect to the Portable FTP Server, rather than echoing the error _"The requested address is not valid in its context."_ when trying to connect to it.

### Print Screens

![image](https://user-images.githubusercontent.com/2872102/135513937-baecf3d2-1922-493c-8a31-28eb410cb674.png)
![image](https://user-images.githubusercontent.com/2872102/135513985-bc86b1d6-92d6-42b3-935f-7cf93f5436b9.png)
![image](https://user-images.githubusercontent.com/2872102/135514129-62861bc2-aec4-4731-8498-2c2d904d500f.png)
![image](https://user-images.githubusercontent.com/2872102/135514316-1e44eab9-18d4-4e7e-892a-d9493b1417c6.png)

[RequestAddressNotValidInThisContext.zip](https://github.com/sshnet/SSH.NET/files/7261756/RequestAddressNotValidInThisContext.zip)

**Comment by Vinayakkulkarni11** [comment]
I am getting the same error, have you got the resolution?

**Comment by darkoperator** [comment]
That is FTP over TLS, this library is for SFTP the sub component of SSH, same acronym different technologies

**Comment by UlyssesAlves** [comment]
> I am getting the same error, have you got the resolution?

Not really, @Vinayakkulkarni11 . For what I understood, it's not possible to use normal authentication (username + password) with SSH.NET if the server itself is not secure. In other words, it looks like SSH.NET works only with secure SFTP servers, and the error _"The requested address is not valid in its context."_ is thrown when this requirement is not properly met, that is, when SSH.NET tries to connect to a non SFTP server.

**Comment by Vinayakkulkarni11** [comment]
Mine is resolved, Port number was not passed to connect method if SFTP client, it was passing as zero and caused this issue. Port 22 resolved this.

**Comment by darinkes** [comment]
> > I am getting the same error, have you got the resolution?
> 
> Not really, @Vinayakkulkarni11 . For what I understood, it's not possible to use normal authentication (username + password) with SSH.NET if the server itself is not secure. In other words, it looks like SSH.NET works only with secure SFTP servers, and the error _"The requested address is not valid in its context."_ is thrown when this requirement is not properly met, that is, when SSH.NET tries to connect to a non SFTP server.

This doesnt make any sense.

Your Screenshot shows FTPS and Port 21. Thats not SSH or SFTP.
And even your FileZilla complains about missing TLS and goes back to plain FTP.

You are looking for an FTP(S)-Library. Wrong neighborhood here then ;)

**Comment by UlyssesAlves** [comment]
> You are looking for an FTP(S)-Library. Wrong neighborhood here then ;)

Yes. My tech lead only explained me their needs for SSH after I had already done this research for FTP(S).
