### ISSUE TITLE
SSH.NET : Export Control Classification Number (ECCN)

### ISSUE THREAD

**Issue by suriktairina** [sshnet/SSH.NET#89]
Hi,

I want to use this package in order to connect with a SFTP server in an enterpriese application.
1) What is the ECCN number for this library? I know that in order to use this API, you will need the  ECCN number. The ECCN number is needed because this library provides crypthography.

2) Can you confirm that the license for this package is MIT? In the previous site (codeplex), the license was BSD.

Thank you!

**Comment by drieseng** [comment]
> 1) What is the ECCN number for this library? I know that in order to use this API, you will need the ECCN number. The ECCN number is needed because this library provides crypthography.

We do not have an ECCN number, and quite honestly I never even looked into this.

> 2) Can you confirm that the license for this package is MIT? In the previous site (codeplex), the license was BSD.

Yes, we relicensed the code under the MIT license.

**Comment by drieseng** [comment]
If you - or anyone else - want to assist us in getting an ECCN number, then please reopen this issue.
