### ISSUE TITLE
Add methods from BaseClient to ISftpClient

### ISSUE THREAD

**Issue by benjaminoerskov** [sshnet/SSH.NET#890]
Im still having a hard time mocking some of the methods in the SftpClient.
I came across the method Connect() which does not exist in the Interface, but comes from the BaseClient.
Would it be possible to add such methods to the ISftpClient interface? Or how would you mock them?

**Comment by DavidErben** [comment]
I am having the same issue! How are we supposed to do unit tests if we cannot mock essential methods like Connect() or Disconnect()? Since these methods are not virtual, I do not know any solution on how to mock them. If there is any, I would appreciate any help!

**Comment by benjaminoerskov** [comment]
@DavidErben I ended up writing my own wrapper. Quite simple: 
![image](https://user-images.githubusercontent.com/11537543/139807693-2d65ad82-896a-4e13-b637-49e3b5b55c5d.png)

**Comment by DavidErben** [comment]
> 
> 
> @DavidErben I ended up writing my own wrapper.

This is probably the only solution, but I tried to avoid it since I do not want to have stuff inside my code base which is only needed for testing. :smile:

**Comment by polly-utopi** [comment]
> > @DavidErben I ended up writing my own wrapper.
> 
> This is probably the only solution, but I tried to avoid it since I do not want to have stuff inside my code base which is only needed for testing. 😄

Also trying to avoid this 😅 Is there a reason it hasn't already been implemented?

**Comment by CasperWSchmidt** [comment]
@utopi-polly I guess lack of time from the maintainer(s)

**Comment by drieseng** [comment]
I'm sure guys, but I've spending way to much time working for my paid job lately.
Not adding that method was a serious oversight. We'll have to check if other methods or properties are M.I.A., but I'm sure there are (such as `ConnectAsync()`, `Disconnect()`).

**Comment by karpikpl** [comment]
Hey @benjaminoerskov ,
Shouldn't your wrapper implement `IDisposable` and  Dispose underlying client?

**Comment by benjaminoerskov** [comment]
Thank you @karpikpl, I have updated my wrapper now :)

**Comment by CasperWSchmidt** [comment]
@drieseng Any news on this? Do you want a hand with it?

**Comment by CasperWSchmidt** [comment]
I just went through the `BaseClient` code and noticed the below public properties, events and methods that would need to be part of an interface. I suggest having a new interface `IBaseClient` (or similar) that inherits from IDisposable and allows ISftpClient etc. to inherit from it:
```
public interface IBaseClient : IDisposable
{
    bool IsConnected { get; }
    TimeSpan KeepAliveInterval { get; set; }
    ConnectionInfo ConnectionInfo { get; }
    event EventHandler<ExceptionEventArgs> ErrorOccurred;
    event EventHandler<HostKeyEventArgs> HostKeyReceived;
    void Connect();
    void Disconnect();
}
```
So `ISftpClient` interface is changed to: `public interface ISftpClient: IBaseClient` to make sure all public members of current `BaseClient` implementation gets accessible via the interfaces for each client (like `SftpClient`) extending it.

For now I'm making my own interface `ISftpService` that extends `ISftpClient` with the missing methods that I need (`Connect`, `Disconnect` and `IsConnected`) and an implementation wrapping the actual `SftpClient` like @benjaminoerskov and myself has suggested earlier.

**Comment by CasperWSchmidt** [comment]
On another note, the methods returning `SftpFile` (like `ListDirectory` and `Get`) should be modified to return `ISftpFile` instead to allow unit testing

**Comment by Owen-Krueger** [comment]
Thanks for the great suggestion on the IBaseClient, @CasperWSchmidt!

This issue should theoretically be fixed in #975.

**Comment by benjaminoerskov** [comment]
@Owen-Krueger Any idea when this will be released? I can see the last release was on May 29, 2022. I would like to start using this asap.

**Comment by Owen-Krueger** [comment]
That would be up to the owner of this solution, and I'm sure they are extremely busy. If there's anything I can do to help get this released, I can sure do that. I appreciate that you're excited for it, though 😄

**Comment by drieseng** [comment]
Fixed by @Owen-Krueger in https://github.com/sshnet/SSH.NET/pull/975.
Thanks!
