### ISSUE TITLE
New to this. How to install

### ISSUE THREAD

**Issue by netaware-NJ** [sshnet/SSH.NET#895]
Hello, i want to use SSH via PowerShell but dont know how to install this.
Can you please help?

**Comment by EHelgeland** [comment]
You should probably check out [Posh-SSH](https://github.com/darkoperator/Posh-SSH)

**Comment by IgorMilavec** [comment]
@netaware-NJ was your question answered, can we close the issue?

**Comment by IgorMilavec** [comment]
Seems to be answered. If not, please reopen the issue.
