### ISSUE TITLE
cipher name aes256-ctr for openssh key file is not supported

### ISSUE THREAD

**Issue by AndreMarschalek** [sshnet/SSH.NET#898]
also mentioned @ https://github.com/sshnet/SSH.NET/issues/742 but still existing with 2020.0.1

Renci.SshNet.PrivateKeyFile.ParseOpenSshV1Key(byte[] keyFileData, string passPhrase)
Renci.SshNet.PrivateKeyFile.Open(Stream privateKey, string passPhrase)
Renci.SshNet.PrivateKeyFile..ctor(string fileName, string passPhrase)

**Comment by IgorMilavec** [comment]
Am I correct to understand this is a duplicate of #742? If yes, can you please close this issue?
