### ISSUE TITLE
SFTP download is slow on high bandwidth high latency connections

### ISSUE THREAD

**Issue by Ravenbs** [sshnet/SSH.NET#899]
I use a 1GB/s connection with 16ms of ping time. This is very common in my region, because the providers offer internet connection over G-PON and DS-Lite, which drive the latency high.

sftp is a very latency critical protocol. With high latency the throughput falls to very small numbers. To overcome throughput issues, there were a series of patches in openSSH  called “HPN-SSH”. With those patches in place, you can reach full speed in sftp transfers also with high latency lines. Those patches are active in most linux distribution out of the box. The patches need to be active on the file recipient side (its a buffer of incoming packets) to speed up the transfer. 

With tools using openSSH and this extension (winSCP) upload and download reach about 450 Mbit/s on my line per connection.
With SSH.NET the upload reach 400 Mbit/s per connection, but the download only get 35 Mbit/s.

**So my Questions and Request is:**
- Is it possible to enable something like this HPN buffer also in ssh.net?

**Background:**
SSH.NET is the backend for Duplicati backup software. In this Software, the Backup is very fast, but the restore is painful slow out of this reason.

**Related links:**
HPN FaQ: https://www.psc.edu/hpn-ssh-home/hpn-ssh-faq/

**Comment by Ravenbs** [comment]
Compiled it with this fix: https://github.com/sshnet/SSH.NET/pull/866
Works great for me - speedup by factor of 10!
Please include it and scedule a new official release of this library 👍

**Comment by zybexXL** [comment]
Thanks @Ravenbs, good to have confirmation! I wish the PR would get merged, but things move glacially on this project.
@drieseng , any chance of taking at look at #866 and #865  for merging? Thanks!
