### ISSUE TITLE
Changing prompt during connection

### ISSUE THREAD

**Issue by maxmontgmx** [sshnet/SSH.NET#903]
Hi all,
I'm developing an app which communicate with a SSH server.
I execute a command which starts a process remotely. The process change the prompt in Putty Console.
If I just execute a command with code "cmd.Execute()". The function never returns because I guess that the prompt has changed.

So how can I change the expected prompt during a SSH connection?
Do I have to use a ShellStream? Does it exist another easier solution?
Thanks for your help

**Comment by IgorMilavec** [comment]
I don't see how changing the prompt would affect ```SshCommand```, I think it must be something else. Can you make a simple repro for this problem?

**Comment by glorialearnscoding** [comment]
Hi @IgorMilavec , I'm interested in how the library deal with the prompt if when the prompt changes. Can you point me the code? I'm seeing some issue on a certain devices. However, I can not do a live debug to understand how the library gives us the command result. (I think the prompt exists in the output stream, so how does the library extract the output and discard the prompt?) Thanks!
