### ISSUE TITLE
New SSH.NET NuGet package release for OpenSSH 8.8 support

### ISSUE THREAD

**Issue by xuewentianxia** [sshnet/SSH.NET#908]
Please upload new NuGet package release for OpenSSH 8.8 support, current NuGet package is too old for us, thanks.

**Comment by magnusjjj** [comment]
This. I managed to compile the ssh library just fine, but..

1. The current error message is not exactly.. helpful.
2. For me, I ran into the issue when running someone else's code. And I don't think that person will accept a bunch of binaries getting accepted for someone random ;)

**Comment by xuewentianxia** [comment]
If these issues are fixed well, please release new one, thanks.
