### ISSUE TITLE
.net5 web api... System.IO.FileLoadException

### ISSUE THREAD

**Issue by laventnc** [sshnet/SSH.NET#911]
I'm porting over some working code from a .net5 console app, and have the SSH.NET (2020.0.1) package installed in a .net5 class library project.

This project is being referenced by a web api application (within a Hangfire job). When the method that uses an SftpClient is called, I get the following error: "Could not load file or assembly Renci.SshNet... Access is denied".

I looked around online and didn't see anything, is there something about using the project within a web api application that doesn't work? The dll is in the app's bin/Debug/net5.0 directory as usual,

Update: I narrowed down the issue, and it's because I'm wrapping the call in a WindowsIdentity.RunImpersonated() call... See [here](https://github.com/dotnet/runtime/issues/21524) for more info.

**Comment by IgorMilavec** [comment]
Does the impersonated user have read access to your web app's bin folder?
You can also try instantiating SftpClient outside impersonated call. This way the assembly will be loaded in memory.

**Comment by laventnc** [comment]
I ended up having to change the logon_type parameter to get it to work locally... When that failed in production for reasons I cannot explain (manually set the permissions for the impersonated user & everything), I decided that opening a [network connection](https://docs.microsoft.com/en-us/windows/win32/api/winnetwk/nf-winnetwk-wnetaddconnection2a?redirectedfrom=MSDN) to the shared drive probably better than manually pre-loading assemblies.
