### ISSUE TITLE
shellstream Flush() does not clear receive queue data which causes big memory leak

### ISSUE THREAD

**Issue by beachmiles** [sshnet/SSH.NET#912]
Using the DataReceived callback to get new data doesn't require the shellstream Read command since the data already exists in the ShellDataEventArgs.Data passed to the DataReceived callback.

I was trying to do a sshStream.Flush() and other manual garbage collections with no luck to stop the memory leak. 
Only after I did a "dummy" sshStream.Read();   did it clear the the read buffer queue. 

I tried using async methods for the callback to do the EndRead but I was getting occasional glitches in the received data or data lines  coming slightly out of order.

Please clear the receive queue when running the Flush() command or maybe make another method to clear this queue instead of having to manually do a shellstream Read after already getting the new data from the DataReceived callback via the ShellDataEventArgs.Data

**Comment by IgorMilavec** [comment]
Flush() has a predetermined semantics in dotnet and is supposed to operate on outbound/send buffers. Modifying ShellStream.Flush() as you propose would break that semantics.

**Comment by beachmiles** [comment]
> Flush() has a predetermined semantics in dotnet and is supposed to operate on outbound/send buffers. Modifying ShellStream.Flush() as you propose would break that semantics.

Perhaps you could add a helper function inside your library to clear the input buffer without having to actually do a dummy run of the Read() function to a clear the buffer. Something like this?
sshStream.FlushInputData()
