### ISSUE TITLE
System.InvalidOperationException: Renci.SshNet.Abstractions.SocketExtensions+_ConnectAsync_d__1.MoveNext

### ISSUE THREAD

**Issue by paulmaybee** [sshnet/SSH.NET#913]
We are seeing crashes when an async connect operation is canceled. Analyses of the crash leads me to believe that SocketAsyncEventArgsAwaitable.SetCompleted is being called twice: once during the handling of the cancel and once when the IOCompletion fires. However the code that runs the continuationAction does not handle this condition appropriately and runs the continuationAction twice, causing the InvalidOperationException.  Changing this line in SetCompleted:
```
var continuation = continuationAction ?? Interlocked.CompareExchange(ref continuationAction, SENTINEL, null);
```
to:
```
var continuation = Interlocked.Exchange(ref continuationAction, SENTINEL);
```
seems to fix the problem.

**Comment by IgorMilavec** [comment]
Can you please provide the exception call stack?

**Comment by paulmaybee** [comment]
Call stack for the failure:
mscorlib.ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, mscorlib]].SetException
VS.Renci.SshNet!Renci.SshNet.Abstractions.SocketExtensions
mscorlib.ni!System.Threading.ExecutionContext.RunInternal
mscorlib.ni!System.Threading.ExecutionContext.Run
mscorlib.ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore
VS.Renci.SshNet!Renci.SshNet.Abstractions.SocketExtensions
System.ni!System.Net.Sockets.SocketAsyncEventArgs.OnCompleted
mscorlib.ni!System.Threading.ExecutionContext.RunInternal
mscorlib.ni!System.Threading.ExecutionContext.Run
mscorlib.ni!System.Threading.ExecutionContext.Run
System.ni!System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure
System.ni!System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback
mscorlib.ni!System.Threading._IOCompletionCallback.PerformIOCompletionCallback

**Comment by IgorMilavec** [comment]
Hm, not very readable... I'll try to do a repro...

**Comment by paulmaybee** [comment]
A little more detail might help to reproduce it. The failure would occur after canceling a dialog box that was waiting for a connection to complete. The connection was being made to an address that was not responding so normally would have timed out after 15 seconds.

The InvalidOperationException had text to the effect that an attempt was made to Complete a task that was already marked as Completed.

**Comment by IgorMilavec** [comment]
I am unable to reproduce this error; I tried a console app on net472 and netcoreapp3.1. It could be that the error is due to ```SynchronizationContext``` flow in UI application.
Can you create a simplified repro based on your code?

**Comment by paulmaybee** [comment]
I was able to repro with the attached program.
[SshCrashFWTest.zip](https://github.com/sshnet/SSH.NET/files/8051765/SshCrashFWTest.zip)

Start the program then hit the OK button on the dialog box when it pops up.

**Comment by IgorMilavec** [comment]
At first I thought the problem was caused by sync/async used in the repro, but when I added a button to the form with this handler:
```csharp
        private async void Button_Click(object sender, RoutedEventArgs e)
        {
            await AddConnectionAsync();
        }
```
the problem persists.
My build environment is occupied at this time so I cannot look into the root cause for this immediatelly, but I will do it ASAP.

**Comment by IgorMilavec** [comment]
@paulmaybee can you please test the fix if it solves the problem in your real application?

**Comment by paulmaybee** [comment]
@IgorMilavec This fix seems to work. Thanks.

**Comment by IgorMilavec** [comment]
Great, thanks for feedback. Let me do some more tests in real life and then I'll "un-draft" the PR.
