### ISSUE TITLE
entering password to use local ssh key

### ISSUE THREAD

**Issue by tofutim** [sshnet/SSH.NET#92]
Hi, I would like to use sshclient to ssh into one of my servers and run 'git clone' or 'git pull'. The target machine contains an rsa key which has a passphrase. For the life of me I cannot figure out how to enter the passphrase when I enter git clone. Is there anything like 'expect' for the sshclient?

http://unix.stackexchange.com/questions/90853/how-can-i-run-ssh-add-automatically-without-password-prompt

has some interesting tips. Not sure how I can get tty with sshclient but that might be another possibility.

or maybe this

https://ifireball.wordpress.com/2015/01/12/automatic-loading-of-ssh-keys-from-scripts/

**Comment by tofutim** [comment]
I was able in osx to use security unlock-keychain

**Comment by drieseng** [comment]
The **ShellStream** class offers the 'expect' capabilities you were looking for.
For example:

``` cs
using (var sshClient = new SshClient("host", "user", "pwd"))
{
    var shellStream = sshClient.CreateShellStream("xterm", 80, 24, 800, 600, 1024);
    shellStream.WriteLine("sudo ls");
    shellStream.Expect("^[\\S\\s] *?\\[sudo\\] password for [A - Za - z].*:\\s$");
    shellStream.WriteLine("pwd");
}
```

**Comment by tofutim** [comment]
Thanks. Actually, in testing shellStream it seems like sometimes all my
commands do not complete. But I will test more.

**Comment by tofutim** [comment]
I ended up going back to Execute with &&'s because it was hard to tell when
the shell commands were complete.
