### ISSUE TITLE
Task based async support?

### ISSUE THREAD

**Issue by kendallb** [sshnet/SSH.NET#932]
There is some async support in the library, but it would be nice if it supported task based async out of the box. There is a wrapper library that supports this:

https://github.com/JohnTheGr8/Renci.SshNet.Async

But it modified some internal code so it's not really a clean solution as it could break in the future if the code that was cloned is changed. 

Any chance this functionality could be included into the main SSH.net libraries?

**Comment by IgorMilavec** [comment]
Equivalent functionality has been implemented directly in SSH.NET, but the updated NuGet package has not been released yet.
If I understand #931 you are interested mainly in SSH connections? If so, can you please close this issue and we can continue discussion in #931?

**Comment by kendallb** [comment]
Sure, we can close this. I am mostly interested in SSH, but we also do SFTP via Renci also. But the code I am using at the moment that needs Async is SSH and port forwarding.
