### ISSUE TITLE
Enable Github Pages

### ISSUE THREAD

**Issue by lupaulus** [sshnet/SSH.NET#943]
Hi,

I find this library necessary in a C# to made SSH calls and (S)FTP transfer.
As for me, this project needs to enable Github Pages to create a static web based documentation.

There are too many pieces of code that was published on Stack or HotExamples
that's uses bad practices in C#. This need to be improve by creating a documentation with samples of codes.

Wait to see ;)
I will be helping to build the documentation, if you enable it !

**Comment by codelovercc** [comment]
can't agree more.

**Comment by Rob-Hague** [comment]
https://sshnet.github.io/SSH.NET/ (still needs more examples)

**Comment by lupaulus** [comment]
@Rob-Hague I will look after, need to go back to my source from 2 years ;)

**Comment by Rob-Hague** [comment]
2 years is practically brand new around here :-)

**Comment by lupaulus** [comment]
@Rob-Hague Please enforce HTTPS in settings of the repository to facilitate indexing from search engines [How-To](https://github.com/orgs/community/discussions/21125)

**Comment by Rob-Hague** [comment]
Thanks, I don't see that option. Do you see it @WojciechNagorski?

![image](https://github.com/sshnet/SSH.NET/assets/5132141/a1f6566c-5622-40d0-be52-f7de3f696900)
