### ISSUE TITLE
The connection was closed by the server: idle connection timeout expired (ProtocolError)

### ISSUE THREAD

**Issue by Shafqat-Ali** [sshnet/SSH.NET#952]
Hi, @IgorMilavec @drieseng 
I'm using ssh.net library for CISCO SG-350 switch configuration from C# web application and facing this error for only CISCO SG-350 model.
All the commands are working fine for CISCO SG-300 and HP switch but I'm unable to make connection only for CISCO SG-350 model.
If anyone facing and solved the same issue, please help me.

**Error:** The connection was closed by the server: idle connection timeout expired (ProtocolError).
**StackTrace:**    
at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle, TimeSpan timeout)
   at Renci.SshNet.Session.WaitOnHandle(WaitHandle waitHandle)
   at Renci.SshNet.Session.Connect()
   at Renci.SshNet.BaseClient.CreateAndConnectSession()
   at Renci.SshNet.BaseClient.Connect()

**Comment by IgorMilavec** [comment]
At first glance it seems that SG-350 is not responding. Are you able to connect using telnet? Did you try to capture network traffic (you can use Wireshark) and see what is happening?

**Comment by Shafqat-Ali** [comment]
> 

@IgorMilavec From same PC using Putty I can run all the commands, but from ssh.net library I'm getting this error "The connection was closed by the server: idle connection timeout expired (ProtocolError)."

**Comment by IgorMilavec** [comment]
Can you capture network traffic in both cases and check for differences?

**Comment by Shafqat-Ali** [comment]
> Can you capture network traffic in both cases and check for differences?

Sure, I'll capture network traffic and share results here.
Thank you for your prompt response.

**Comment by Shafqat-Ali** [comment]
> Can you capture network traffic in both cases and check for differences?

**Comment by Shafqat-Ali** [comment]
> Can you capture network traffic in both cases and check for differences?

[NetworkTraffic.zip](https://github.com/sshnet/SSH.NET/files/8552782/NetworkTraffic.zip)

I attached files of traffic monitoring with Wireshark. Please use this filter: "**(ip.src == 10.1.7.26 && ip.dst == 172.17.21.254) || (ip.src == 172.17.21.254 && ip.dst == 10.1.7.26)**"

**Traffic monitored for Putty (file name):** PuttySession.pcapng
**Traffic monitored for C# application traffic (file name):** ApplicationSession.pcapng

I'm not network expert to analyze the traffic. Please take a look into files. @IgorMilavec Please support.

**Comment by Shafqat-Ali** [comment]
@IgorMilavec @darinkes @hifi @drieseng 
Need your support for CISCO SG-350 switch connection using SSH.NET.
Please help me with this issue.

**Comment by KrisMie** [comment]
@Shafqat-Ali @IgorMilavec @drieseng
Not an expert here but by comparing those two Wireshark captures with recommended filters, it looks like the problem is that for some reason SSH.NET doesn't initiate Key Exchange process with the server.

Then - as expected - sends [FIN, ACK] disconnection signal after 30s timeout due to inactivity.

Why would the SSH/Net not start the Key Exchange Init?

**Comment by Shafqat-Ali** [comment]
@KrisMie Thank you for comparing Wireshark captured results and identification of issue.

@IgorMilavec @darinkes @hifi @drieseng Please support for above mentioned issue by @KrisMie.
I'm stuck at this point, Need support.

**Comment by geoffstewart** [comment]
I have created a PR to resolve a similar issue I encountered: #972

**Comment by WojciechNagorski** [comment]
It's done in https://github.com/sshnet/SSH.NET/pull/1274

**Comment by WojciechNagorski** [comment]
The 2023.0.1 version has been released to Nuget: https://www.nuget.org/packages/SSH.NET/2023.0.1
