### ISSUE TITLE
Usage of ServiceFactory/Binding client to specific interface

### ISSUE THREAD

**Issue by GeorgRottensteiner** [sshnet/SSH.NET#953]
I need to bind the client address to a specific TCP interface. However there seems to be no direct way to do that.

I see a ServiceFactory, holding a SocketFactory, which might be a way for me to create the socket with the required settings. However these look to be purely internal, I can't see how to set them from outside.

There is a constructor of SftpClient, that would allow for a ServiceFactory to be passed in, unfortunately it's internal:

internal SftpClient(ConnectionInfo connectionInfo, bool ownsConnectionInfo, IServiceFactory serviceFactory)

Is there a way to pass my custom Socket/ServiceFactory? Or to bind a client interface?

**Comment by WojciechNagorski** [comment]
I am closing the issue due to lack of time and other priorities for the near future. If you care about time, I encourage you to prepare a PR.
