### ISSUE TITLE
Getting "Key type 'if-modn{sign{rsa-pkcs1-sha1},encrypt{rsa-pkcs1-none}}' is not supported" error

### ISSUE THREAD

**Issue by Padmapriya89** [sshnet/SSH.NET#960]
### Discussed in https://github.com/sshnet/SSH.NET/discussions/959

<div type='discussions-op-text'>

<sup>Originally posted by **Padmapriya89** May 13, 2022</sup>
Using SSH .net with private key for SFTP and getting below error
Key type 'if-modn{sign{rsa-pkcs1-sha1},encrypt{rsa-pkcs1-none}}' is not supported</div>

We are using SSH2 encrypted private key

**Comment by linyus** [comment]
I have the same issue when I use SSH2 in SSH.NET.
Do you have any update about the issue?
Thanks!
