### ISSUE TITLE
Permission denied when SshClient.RunCommand() using renci.sshnet

### ISSUE THREAD

**Issue by ajmetoo** [sshnet/SSH.NET#965]
After establishing an SSH connection, when trying to SCP some files from one remote server to another using Renci.SshNet library. The command is working perfectly when directly given to the terminal, but not through .NET

used this in terminal and it works perfectly
`~$ scp -i /private/key/file  /source/file user@connecting.com:/destination/file`

used this in .NET
`SshClient.RunCommand("scp -i /private/key/file  /source/file user@connecting.com:/destination/file");`

but this one throwing an error

_Permission denied, please try again.
Permission denied, please try again.
user@connecting.com: Permission denied (publickey,password).
lost connection_

I used ssh-add to authenticate the keypair automatically and it works fine through the terminal. But I couldn't figure out why it is not working with .NET (used Visual Studio 17.2.1).

**Comment by gregolsky** [comment]
#956 sounds similar.

**Comment by WojciechNagorski** [comment]
Version 2023.0.0 has been published https://www.nuget.org/packages/SSH.NET/2023.0.0
