### ISSUE TITLE
PrivateKeyAuthenticationMethod is it needed?

### ISSUE THREAD

**Issue by Iron-Nail** [sshnet/SSH.NET#97]
Hi All,

In the internet I found this example, and it works fine

```
var keyFile = new PrivateKeyFile(@"C:\Projects\SshProject\OpenSsh-RSA-key.ppk");
var keyFiles = new[] {keyFile};

var methods = new List<AuthenticationMethod>();
methods.Add(new PasswordAuthenticationMethod("username", "password"));
methods.Add(new PrivateKeyAuthenticationMethod("username", keyFiles));

var con = new ConnectionInfo("example.host.com", 22, "username", methods.ToArray());
```

However, if I do not create PrivateKeyAuthenticationMethod it still works fine. This behavior confused me, what happens if I did not set a private key:
1) It works without any key? (like simple FTP server)
2) It uses some default private key?
3) It generates its own private key? (everytime new)
4) Something else?

**Comment by drieseng** [comment]
This depends on the SSH server that you're establishing a connection to.
For example, the SSH server may support either password or public key authentication, or require both.
For more information, search for "_OpenSSH authentication methods_".
