### ISSUE TITLE
SOCKS5: Support domain name address type

### ISSUE THREAD

**Issue by reang** [sshnet/SSH.NET#98]
Hi, anyone can resolve this error?
![Error](http://i.imgur.com/PDnjsU0.png)

**Comment by drieseng** [comment]
I'm working on this.

Not sure if we should just pass the domain name to the SSH server, or if we should also have an option to resolve the host name locally. We could just say that this is an option the SOCKS client should offer, and not the SOCKS proxy (meaning SSH.NET).
