### ISSUE TITLE
Ctrl C in ShellStream

### ISSUE THREAD

**Issue by liamnguyen109** [sshnet/SSH.NET#980]
Hi, 

I'm able to connect successfully ssh and create shellstream. However, I can't find any way to stop a running command on terminal. For example, if you type `ping xxx.xxx.xxx.xxx` on the PUTTY or prompt, they terminal will keep print out the result until we hit Ctrl C but in this case, the console windows is closed after I hit ctrl C. Are there any way I can assign ctrl C in shellstream

`
  

        SshClient sshClient = new SshClient("ip", 22, "username", "password");        
        sshClient.ConnectionInfo.Timeout = TimeSpan.FromSeconds(120);
        sshClient.Connect();

        ShellStream shellStreamSSH = sshClient.CreateShellStream("vt-100", 80, 50, 1024, 1024, 1024);

        Thread thread = new Thread(() => recvSSHData(shellStreamSSH));

        thread.Start();

        while (true)
        {
            string command = Console.ReadLine();

            shellStreamSSH.Write(command + "\n");
            shellStreamSSH.Flush();
        }
    }

    public static void recvSSHData(ShellStream shellStreamSSH)
    {
        while (true)
        {
            try
            {
                if (shellStreamSSH != null && shellStreamSSH.DataAvailable)
                {
                    string strData = shellStreamSSH.Read();

                    Console.WriteLine(strData);
                }
            }
            catch
            {

            }

            System.Threading.Thread.Sleep(200);
        }
    }
`

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
If the problem still persists, please feel free to open it, but please note that we need more information e.g. about the server.
