### ISSUE TITLE
ShellStream.Expect with Windows 2019 OpenSSH

### ISSUE THREAD

**Issue by mt34** [sshnet/SSH.NET#982]
We are having an issue apparently identical to one posted with the Win32-OpenSSH team (see below) where we are using ShellStream.Expect quite happily on other Unix and Windows 2016 machines - but on Windows 2019 the same code and configuration results in an interactive session and ultimately breaks our expect-based automations.

https://github.com/PowerShell/Win32-OpenSSH/issues/1633

Using ssh -t or rebex sshclient (trial!) works as expected.

We can't see anything obviously wrong with our sshnet code or any options that might control this. We have tried various TERM and/or dimensions - though admittedly no TerminalModes.

Has anybody seen this before or any suggestions as to what it could be?

.NET Framework: 4
Renci.SSHNET version: 2020.0.2.0

Thank you.

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
