### ISSUE TITLE
Renci.SshNet.Common.SshException - "Cannot remove file"

### ISSUE THREAD

**Issue by hbzhxying** [sshnet/SSH.NET#985]
Recently we hit an error when trying to delete the files in SFTP server. We hit an error "Cannot remove file". But if we use the same credentials in SFTP client, we can successfully delete files. Does anyone know what happens?

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
If the problem still persists, please feel free to open it, but please note that we need more information.
