### ISSUE TITLE
SshAuthenticationException - Permission Denied (Password) 

### ISSUE THREAD

**Issue by hbzhxying** [sshnet/SSH.NET#986]
After we upgrade the SDK from 2016 to 2020, we started to hit the error "Permission Denied (Password)". We didn't change the credential and SFTP configuration.

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
If the problem still persists, please feel free to open it, but please note that we need more information.
