### ISSUE TITLE
Nuget package is much elder than repository

### ISSUE THREAD

**Issue by jay94ks** [sshnet/SSH.NET#987]
May I request a Nuget package update?
When I reference this package when I build a docker image, it always gets the old version; 2020.0.2.

Ref: [https://www.nuget.org/packages/SSH.NET/2020.0.2/](https://www.nuget.org/packages/SSH.NET/2020.0.2/)

**Comment by aberbegall** [comment]
What version were you expecting in Nuget? 
I can see latest version in Nuget matches latest released version

**Comment by Retidurc** [comment]
2020.0.2 is not a package from the year 2020. It is in fact the lastest available package in the release page here on github.

I think that's where the confusion came from. I got the same at first.

**Comment by ciarancolgan** [comment]
Hi @drieseng - thanks for a superb library (I have made a small sponsorship donation as a thank you). Would you mind publishing a Nuget package update of the latest develop branch? I'd really love to get the ISftpFile change merged in commit: https://github.com/sshnet/SSH.NET/commit/583a9cea6a2cacdc63bb353ed2f5867613f24271. The most recent release doesn't have this: https://github.com/sshnet/SSH.NET/compare/2020.0.2...develop
Cheers!

**Comment by spottedmahn** [comment]
>2020.0.2 is not a package from the year 2020

really?  it seems like it:

![image](https://user-images.githubusercontent.com/14079228/197095452-2155b614-5ca3-4e59-96cb-37b0a7c8d264.png)

(Yes, I see it was published in 2021 but I'm guessing it was just a minor release to 2020)

@Retidurc 

---

> I'd really love to get the ISftpFile change merged in commit

ditto! (reference #812)

**Comment by WojciechNagorski** [comment]
Does the problem still occur? If so don't hesitate to reopen an issue.

**Comment by Rob-Hague** [comment]
Completed by #1201
