### ISSUE TITLE
Error occured while executing activity- SSH Run command activity inside -UiPath SSH connector activities package

### ISSUE THREAD

**Issue by ShahneelZia** [sshnet/SSH.NET#989]
Error occurred decode() argument 1 must be string, not None

The above does not appear while executing the commands manually through putty but through SSH Run command activity. It does not generate output but the above error.

Please suggest.

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
If the problem still persists, please don't hesitate to open an issue.
