### ISSUE TITLE
Specify which encryption to use

### ISSUE THREAD

**Issue by stefanoromanello** [sshnet/SSH.NET#991]
I'm trying to connect to multiple cisco switches but for some of them I get a "connection timeout" error. I thought that maybe ssh.net is not able to detect the correct encryption and I would like to force it to use a specified one from the supported ones. Can someone give me a snippet of code that does this?
Note: my code is in C# and this is my current login flow:
```
 ConnectionInfo connNfo = new ConnectionInfo(switchObj.ip, 22, username,
                    new AuthenticationMethod[]{
                        // Pasword based Authentication
                        new PasswordAuthenticationMethod(username,password),
                    });

                    //switchObj.sshConnection = new SshClient(connNfo); 
                    switchObj.sshConnection = new SshClient(switchObj.ip, username, password);
                    switchObj.sshConnection.Connect();
```

**Comment by WojciechNagorski** [comment]
I'm closing the issue, the report does not contain enough information to reproduce the bug.
If the problem still persists, please don't hesitate to open an issue.
