### ISSUE TITLE
Connecting to SFTP in Azure Storage started failing username format

### ISSUE THREAD

**Issue by bbeasley-e78** [sshnet/SSH.NET#992]
Up until Saturday, we were able to successfully connect and upload to Azure Storage.  We are using the following standard connection 
ConnectionInfo ftpConn = new ConnectionInfo(this.host, "sftp", new PasswordAuthenticationMethod(username, password));
It seems to be widespread.  We have multiple locations to multiple Azure storage accounts all with same failure.
Error is:
Renci.SshNet.Common.SshConnectionException: 'The connection was closed by the server: The SSH username format is invalid. (IllegalUserName).'
I confirmed SSH.NET is 2020.0.2.0

**Comment by darkoperator** [comment]
If it was working before and changed across the board more than likely it was a change on the azure side. I would check if they changed ciphers

**Comment by jimmiebergmann** [comment]
The exact same thing happend to me, using the same ssh.net verison, configuration and Azure Storage. Production environment completely bricked yesterday(But not test for some reason) with the same error message!

I solved this issue by replacing "sftp" with username(still passing it to PasswordAuthenticationMethod):
``` ConnectionInfo ftpConn = new ConnectionInfo(this.host, username, new PasswordAuthenticationMethod(username, password)); ```

**Comment by bbeasley-e78** [comment]
That is what I did also.  That code was working for so long I didn't bother going through constructors in detail because they worked.  But clearly the second parameter states username.  But all works now with that change like you said.  And also noted that our non-production continued to work.

**Comment by al-dass-spc** [comment]
In the [Microsoft documentation for Azure Storage/SFTP](https://learn.microsoft.com/en-us/azure/storage/blobs/secure-file-transfer-protocol-support-how-to?tabs=azure-portal#connect-an-sftp-client) there is a note with something to the effect of:

> The SFTP username is **`storage_account_name`.`username`** where `storage_account_name` is the name of the Azure Storage Account (with SFTP enabled) and `username` is the local user identity.

**Comment by hpsanampudi** [comment]
I do have same Issue. 

**For example:** If the azure storage sftp connection string is 
"*<storage_account_name.username>*@*<storage_account_name>*.blob.core.windows.net"

**Solution:**
- The **host** value which we pass to Renci.SshNet client instance should not contain "*<storage_account_name.username>@*"
- The **username** value should be "*<storage_account_name.username>*"

**Code Sample:**

    var host = "<storage_account_name>.blob.core.windows.net";
    var username = "<storage_account_name.username>";
    var password = "<password>";
    
    var client = new SftpClient(host, username, password);
    
    client.Connect();

**Comment by dheerajawale-svg** [comment]
> I do have same Issue.
> 
> **For example:** If the azure storage sftp connection string is "_<storage_account_name.username>_@_<storage_account_name>_.blob.core.windows.net"
> 
> **Solution:**
> 
> * The **host** value which we pass to Renci.SshNet client instance should not contain "_<storage_account_name.username>@_"
> * The **username** value should be "_<storage_account_name.username>_"
> 
> **Code Sample:**
> 
> ```
> var host = "<storage_account_name>.blob.core.windows.net";
> var username = "<storage_account_name.username>";
> var password = "<password>";
> 
> var client = new SftpClient(host, username, password);
> 
> client.Connect();
> ```

Thank you very much. I couldn't find this info either on google or on chatGpt.
