### ISSUE TITLE
Shellstream missing incoming requests

### ISSUE THREAD

**Issue by salamander194** [sshnet/SSH.NET#998]
I have built a client application that processes incoming requests from a push data feed. The requests are JSON strings, terminated by a NewLine sequence. The issue is that the client app does not receive all of these requests. I happen to know that there is no throttling on the server side, so at times requests can arrive at a rate of 10k per hour or more. Some of my code:

//create stream, note the buffer size
_stream = _client.CreateShellStream("session", 512, 1024, 1024, 2048, 2097152);

//create event handler
 _stream.DataReceived += HandleChannelDataReceived;

//event handler
private static void HandleChannelDataReceived(object sender, ShellDataEventArgs e)
{
    string result = System.Text.Encoding.UTF8.GetString(e.Data, 0, e.Data.Length);
    //do some stuff with result
}

Any ideas? It is essential that all incoming requests are processed.

**Comment by WojciechNagorski** [comment]
SSH.NET version 2024.0.0 has changed a lot. I'm closing the ticket, but if the problem still persists, please feel free to reopen or open a new ticket.
